<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/151010/red-01.jpg ",96,230);
$z[1][4]['ddimg']="/upload/allimg/151010/red-01-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="495";
$z[1][4]['height']="320";
$z[2]=Array("img"," /upload/allimg/151010/red-02.jpg ",232,366);
$z[2][4]['ddimg']="/upload/allimg/151010/red-02-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="495";
$z[2][4]['height']="320";

?>