<li class="clear"> 
                     <div class="img">
                          <img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="703" height="335" />
                     </div>
                     <div class="con">  
                        <div class="middle">   
                             <div class="inner">
                                <h2><i></i>[field:title/]</h2>
                                [field:body/]
                             </div>    
                        </div>     
                     </div>                 
                </li>