{gemel:field name='keywords'}站长之家, 新iPhone, iPhone{/gemel:field}
{gemel:field name='description'}新iPhone首周销量再破纪录：中国市场和5c立功 苹果全新iOS7装机数量超过2亿台，这也成为了历史上更新最快的软件。{/gemel:field}
{gemel:field name='title'}新iPhone首周销量再破纪录：中国市场和5c立功{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130925/13P0S0A54640-45064.jpg" border="0" /></p>
<p><strong>腾讯科技 王冠 9月25日报道</strong></p>
<p>尽管对于iPhone5s和5c存在很多质疑，但在9月20日上市后，首发市场对于新品的购买热情依然不减。本周，苹果公布了iPhone5s和iPhone 5c的首周销量，在三天时间里，两部手机共卖出了900万部，创下历代iPhone首周销量的新高。</p>
<p>同时，苹果还公布了全新iOS 7系统的装机数量&mdash;&mdash;超过2亿台，这也成为了历史上更新最快的软件。</p>
<p><strong>屡创神话的iPhone首周战绩</strong></p>
<p>从2007年iPhone诞生起，每一年的新品都能够打破上一年保持的首周销售记录。由于苹果喜欢把iPhone上市定在周五（7年里只有iPhone 4例外，定在了周四），所以，这里提到的首周销量，其实仅为周五到周日三天的统计数字。</p>
<p>2007年，苹果公布了第一代iPhone首周前两天的销量（未公布第三天数据），为27万台；</p>
<p>2008年，iPhone 3G首周销量突破100万；</p>
<p>2009年，iPhone 3GS首周销量100多万；</p>
<p>2010年，iPhone 4首周销量170万；</p>
<p>2011年，iPhone 4s首周销量400万；</p>
<p>2012年，iPhone 5首周销量500万；</p>
<p>到2013年，iPhone5s和5c将这一数字暴增至900万。</p>
<p>在过去七年里，iPhone销量不断增长的秘密隐藏在那些苹果最看重的元素里。这可能包括：创新、体验、应用数量和质量、开发者生态圈、零售店、运营商合作、不断扩大的市场和品牌影响力。</p>
<p><strong>iPhone爆发定律：首发扩军</strong></p>
<p>纵观苹果历代iPhone手机的首周销量增长情况，有两次表现非常突出：iPhone 4s的400万相对于上一代的170万，以及新一代5s和5c的900万相对于上一代的500万，均实现了一倍左右的增幅。</p>
<p>2011年，苹果在选择iPhone 4s首批发售地区时，新增加了澳大利亚和加拿大市场。此外，iPhone 4s还首次将CDMA与WCDMA两种网络制式手机同时首发，并提出了&ldquo;World Phone&rdquo;口号。这两大因素对iPhone 4s首周销量暴增贡献了很大力量。</p>
<p>5s和5c也沿用了这一套路。在首发市场中，新一代iPhone加入了中国大陆地区。现在虽然还没有数据显示中国市场对5s和5c首周销量贡献多大，但作为全球最大的智能手机市场，中国市场显然贡献了很大一部分销量。</p>
<p>运营商市场也是如此。拥有6000万用户的NTT是日本最大的运营商，苹果将其纳入到iPhone 5s和5c的首发合作伙伴中。这对日本市场销量提升相信会有很大帮助。而在中国，虽然由于4G牌照等原因，中移动版iPhone没有赶上首发，但苹果的目的已经达到了&mdash;&mdash;与当地最大运营商建立合作，提升iPhone的市场份额。</p>
<p>当然，最终还是要靠产品说话。iPhone 5s推出64位处理器，增加指纹识别功能，以及替换了全新iOS 7系统，和今年同期的其他旗舰手机相比，这些创新和领先会对消费者的购买行为产生影响。</p>
<p><strong>苹果产品组合拳玩法初战告捷</strong></p>
<p>当然，苹果并非全靠自己的努力就实现了新一代iPhone首周销量的大幅增加。</p>
<p>根据IDC的报告，2013年第二季度全球智能手机出货总量较上年同期增长51.3%，Android手机同比增长高达73.5%。赶上了智能手机浪潮的一个高峰，新一代iPhone首周增量达到80%，虽然令人惊讶，但也在情理之中。</p>
<p>同时，另一个隐藏的事实也需要关注。这一代iPhone推出了两款产品，尽管5c的市场反应明显不如5s，但在官方数据给出之前，我们依然无法预估两部手机各自的比例。从配置等方面看，iPhone 5c更像是一个换了背壳和颜色的iPhone 5，而在发布之前，苹果已经宣布了上一代的iPhone 5停产。因此，苹果首周销量，相当于是两代iPhone之和。而之前历代iPhone首周销量统计里，是不会计算更早一代在那三天中的销售数字的。</p>
<p>至于定价高的iPhone 5s销量反而好过iPhone 5c的原因可能主要有两个。相相较于iPhone 5s，iPhone 5c的创新并不多，除了颜色，基本和上一代产品一致；定价方面，iPhone 5c也没有如外界期待的一样成为廉价产品，两者差价很小，对于愿意花钱买苹果的人来说，这个差价很难形成太大的用户区分。</p>
<p>所以说，iPhone 5c是一个很神奇的产品。一方面，它让上一代产品的库存备件能以更好和更高的价格处理掉，另一方面，iPhone 5c和iPhone 5s之间模糊的定位和差价，某种程度上也刺激了后者的销量。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130925/13P0S0A54640-45064_lit.jpg{/gemel:field}
