{gemel:field name='keywords'}站长之家, 小米3, 小米电视{/gemel:field}
{gemel:field name='description'}小米发布会看点：或推电视 前谷歌高管亮相。小米此次发布会或将发布会两款新品，一款是小米3手机，另一款可能是小米Pad或小米电视。{/gemel:field}
{gemel:field name='title'}小米发布会看点：或推电视 前谷歌高管亮相{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130905/13N35424F4K0-39195.jpg" border="0" /></p>
<p>备受期待的小米发布会明日在国家会议中心召开。发布会前，小米已广发&ldquo;英雄帖&rdquo;，印有&ldquo;倚天、屠龙&rdquo;文案。据知情人士爆料，小米此次发布会将发布会两款新品。其中一款是小米3手机，另一款可能是小米Pad或小米电视。</p>
<p><strong>小米3手机</strong></p>
<p>此次发布会备受关注的是小米3手机。知情人士透露，小米3外形酷似诺基亚lumia，很可能采用高通骁龙800处理器或Tegra4处理器，2GB的RAM，16GB以上存储空间，还会搭载1300万像素摄像头，屏幕则为5吋上下全高清1920&times;1080级别。</p>
<p><strong>小米电视</strong></p>
<p>可能推出的新品是小米电视。此前，小米电视谍照多次传出，从包装箱照片来看，曝光的小米电视型号为L47M1-AA，尺寸为47英寸，分辨率达到1080P级别，支持杜比音效、dts数字化影院系统并且内建Wi-Fi同时内置米联等应用。</p>
<p>此前，腾讯科技已获悉，小米型号为L47M1-AA的47寸电视于6月27日通过3C认证。认证信息显示，小米电视制造商为&ldquo;北京小米通讯技术有限公司&rdquo;，生产商为&ldquo;纬创资通(中山)有限公司临海分公司&rdquo;。</p>
<p>不过，如果小米电视发布，当前必然会面临强劲挑战。爱奇艺和TCL已抢&ldquo;头彩&rdquo;，于9月3日发布48英寸智能电视&ldquo;TV+&rdquo;。爱奇艺的&ldquo;TV+&rdquo;这一项目备受百度和TCL重视。</p>
<p>昨日发布会上，百度CEO李彦宏和TCL董事长李东生均出席发布会，尤其是李彦宏，是首次参加爱奇艺发布会。TV+聚合爱奇艺和PPS视频资源，用户无需另外付费，其中，尊爵版TV+配备48英寸屏幕，定价为4567元。经典版TV+定价2999元，在价格上颇具冲击力。</p>
<p><strong>小米平板</strong></p>
<p>另一个可能发布的产品是小米Pad。此前，据台湾媒体报道，小米平板电脑已通过富士康测试，主打千元低价策略。小米Pad采用联发科的MT8125四核处理器。</p>
<p>另有消息称，小米Pad售价有两个版本，3G版1299元，WiFi版999元。不过，小米Pad可能不会在本次发布会发布，更可能在9月底或10月初发布。</p>
<p><strong>前谷歌高层将亮相</strong></p>
<p>此次小米发布会也应该是小米手机发布以来最抢眼的一次发布会。前任谷歌全球副总裁，Android团队产品副总裁雨果&bull;巴拉(Hugo Barra)已到北京，确认参加这场发布会。据知情人士透露，此次发布会上小米海外化战略将进一步清晰。</p>
<p>此次小米发布会&ldquo;倚天、屠龙&rdquo;的口号非常响亮。有分析人士指出，&ldquo;武林至尊，宝刀屠龙&rdquo;，意味着小米决心进入新领域，挑战新霸主；&ldquo;号令天下，莫敢不从&rdquo;则指巴拉加盟小米后，可带领小米领头Android深度定制业界。不过，一切还得明天发布会才能明朗。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130905/13N35424F4K0-39195_lit.jpg{/gemel:field}
