<li>
                                 <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="238" height="216" /></a>
                                 <p><a href="[field:arcurl/]">[field:shorttitle/]</a></p>
                            </li>
                            {/gemel:arclist }                       
                        </ul>
                </div>
            </li>
            <li>
                About Us</li>
            <li>
                Products Video</li>    
        </ul>
   </div>  
</div>    
<!-- home_content end -->

<!-- footer  begin -->
{gemel:include filename="footer.htm"