<tr>    
                    <td>[field:title/]</td>
                    <td>[field:supplier/]</td>
                    <td>[field:number/]</td>  
                    <td>[field:format/]</td>
                    <td>[field:price/]</td>
                    <td><a href="[field:png/]">点击阅读</a></td>
                    <td class="pro_num"><span>-</span><input type="text" /><span>+</span></td>
                    <td class="inquiry"><span>订购</span>|<span>询价</span></td>     
                </tr>