<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/140526/1-1405260UR7.jpg ",96,242);
$z[1][4]['ddimg']="/upload/allimg/140526/1-1405260UR7-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="732";
$z[1][4]['height']="321";
$z[2]=Array("img"," /upload/allimg/140526/1-1405260UR8.jpg ",244,390);
$z[2][4]['ddimg']="/upload/allimg/140526/1-1405260UR8-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="732";
$z[2][4]['height']="321";
$z[3]=Array("img"," /upload/allimg/140526/1-1405260UR9.jpg ",392,538);
$z[3][4]['ddimg']="/upload/allimg/140526/1-1405260UR9-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="732";
$z[3][4]['height']="321";
$z[4]=Array("img"," /upload/allimg/140526/1-1405260US0.jpg ",540,686);
$z[4][4]['ddimg']="/upload/allimg/140526/1-1405260US0-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="732";
$z[4][4]['height']="321";

?>