{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140526/1-1405260UR7-lp.jpg' text='' width='732' height='321'} /upload/allimg/140526/1-1405260UR7.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140526/1-1405260UR8-lp.jpg' text='' width='732' height='321'} /upload/allimg/140526/1-1405260UR8.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140526/1-1405260UR9-lp.jpg' text='' width='732' height='321'} /upload/allimg/140526/1-1405260UR9.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140526/1-1405260US0-lp.jpg' text='' width='732' height='321'} /upload/allimg/140526/1-1405260US0.jpg {/gemel:img}
