<div class="shownews">
                <img src="/templets/style/images/news_09.jpg" />
                <div class="indexnews02_profile">
                    <a href="[field:arcurl/]"><b>[field:title/]</b></a>
                    <p>[field:description function='cn_substrR(html2text(@me),200)'/] <a href="[field:arcurl/]" style="color:#ff9900;">[详情]</a></p>
                </div>    
            </div>
            <div class="clear"></div>