{gemel:field name='keywords'}站长之家, 米聊, 陌陌, 约{/gemel:field}
{gemel:field name='description'}9月23日消息，米聊今日面向4000万米聊用户发布公告，对在平台内发布违禁信息的用户，一经发现进行封号处理。此举的严肃作风一改平日的和蔼，也揭示了米聊作为公众IM平台，{/gemel:field}
{gemel:field name='title'}米聊公告誓不做“约炮工具”暗讽陌陌{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p>9月23日消息，米聊今日面向4000万米聊用户发布公告，对在平台内发布违禁信息的用户，一经发现进行封号处理。此举的严肃作风一改平日的和蔼，也揭示了米聊作为公众IM平台，对淫秽色情信息的&ldquo;零容忍&rdquo;。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130925/13P0S05E5110-35063.jpg" border="0" width="350" alt="暗讽陌陌，米聊发公告誓不做&ldquo;约炮工具&rdquo;" /></p>
<p>据悉，此公告一经发出，引发了部分米聊用户对封号行为的不满。对此米聊的内容运营总监李岚第一时间在新浪微博进行回应：&ldquo;感谢大家的支持和善意的提醒！对于垃圾广告用户的治理也已在实施中，我们将努力给米聊用户一个更纯粹的环境。米聊的目标，绝不是&ldquo;约炮神器。&rdquo;</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130925/13P0S05Ha10-412K.jpg" border="0" width="499" alt="暗讽陌陌，米聊发公告誓不做&ldquo;约炮工具&rdquo;" /></p>
<p>如今，互联网违禁信息的治理，一直是各家老生常谈的问题，非但治理力度缺良莠不齐，甚至还有被业界冠名&ldquo;约炮神器&rdquo;，此次米聊发布公开声明，内容暗讽陌陌的运营方式，或将引起再次行业IM话题之争。</p>
<p>自今年8月份5.0版本的微信发布，小米联合创始人、米聊负责人黄江吉公开接受媒体采访，坦言米聊改变了传统IM定位，主推&ldquo;发烧友聚集地&rdquo;，兴趣群的发展思路成为了米聊的最大看点。现如今拥有群总量26万的米聊，整顿军纪也可谓是意料之中。纵观如今的微信、易信、陌陌，每家都发展着各自专注的领域，或平台化、或通信化、或交友化。米聊的公告也再一次印证了米聊不断专注在聊天、群的体验之上，这或许才是发烧友用户真正需要的米聊。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130925/13P0S05E5110-35063_lit.jpg{/gemel:field}
