<?php
$z[0]=Array("top","\r\n  <m:item name='一键更新网站' link='makehtml_all.php' rank='sys_MakeHtml' target='main' class='yjgxwz' />\r\n  <m:item name='更新系统缓存' link='sys_cache_up.php' rank='sys_ArcBatch' target='main' class='gxxthc' />\r\n",51,389);
$z[0][4]['item']="1_";
$z[0][4]['name']="自动任务";
$z[0][4]['notshowall']="1";
$z[0][4]['display']="block";
$z[0][4]['rank']="sys_MakeHtml";
$z[0][4]['class']="zdrw";
$z[1]=Array("top","\r\n  <m:item name='更新主页HTML' link='makehtml_homepage.php' rank='sys_MakeHtml' target='main' class='gxzyhtml' />\r\n  <m:item name='更新栏目HTML' link='makehtml_list.php' rank='sys_MakeHtml' target='main' class='gxlmhtml' />\r\n  <m:item name='更新文档HTML' link='makehtml_archives.php' rank='sys_MakeHtml' target='main' class='gxwdhtml' />\r\n",391,851);
$z[1][4]['item']="1_";
$z[1][4]['name']="HTML更新";
$z[1][4]['notshowall']="1";
$z[1][4]['display']="none";
$z[1][4]['rank']="sys_MakeHtml";
$z[1][4]['class']="htmlgx";

?>