
-----------------------------------------------
<m:top item='1_' name='自动任务' notshowall='1'  display='block' rank='sys_MakeHtml' class='zdrw'>
  <m:item name='一键更新网站' link='makehtml_all.php' rank='sys_MakeHtml' target='main' class='yjgxwz' />
  <m:item name='更新系统缓存' link='sys_cache_up.php' rank='sys_ArcBatch' target='main' class='gxxthc' />
</m:top>
<m:top item='1_' name='HTML更新' notshowall='1' display='none' rank='sys_MakeHtml' class='htmlgx'>
  <m:item name='更新主页HTML' link='makehtml_homepage.php' rank='sys_MakeHtml' target='main' class='gxzyhtml' />
  <m:item name='更新栏目HTML' link='makehtml_list.php' rank='sys_MakeHtml' target='main' class='gxlmhtml' />
  <m:item name='更新文档HTML' link='makehtml_archives.php' rank='sys_MakeHtml' target='main' class='gxwdhtml' />
</m:top>
-----------------------------------------------
