<a href="[field:typeurl/]">[field:typename/]</a>{/gemel}|
            {gemel:type typeid="21" }<a href="[field:typeurl/]">[field:typename/]</a>{/gemel}|
            {gemel:type typeid="21" }<a href="[field:typeurl/]">[field:typename/]</a>{/gemel}|
            {gemel:type typeid="21" }<a href="[field:typeurl/]">[field:typename/]</a>{/gemel}|
            {gemel:type typeid="21" }<a href="[field:typeurl/]">[field:typename/]</a>{/gemel}    
        </div>
        <div class="footer_left">{gemel:global.cfg_powerby