<li>
                        <div class="img">
                            <a href="{gemel:field.typeurl/}"><img src="{gemel:field.typepic2/}" title="{gemel:field.typename/}" alt="{gemel:field.typename/}" width="252" height="187"/></a>
                        </div>
                        <div class="text">
                            <h3><a href="{gemel:field.typeurl/}">{gemel:field.typename/}</a></h3>
                            <a href="{gemel:field.typeurl/}" title="{gemel:field.typename/}">view more</a>
                        </div>
                    </li>