{gemel:field name='keywords'}站长之家, iphone丢了怎么定{/gemel:field}
{gemel:field name='description'}前些时候，国外一名女性用户Danielle Bruckman无意中丢了自己的iPhone，通过手机的iCloud服务，她在网上看到了捡到自己手机的男子的自拍照。如果事情发生在国内，那么后续{/gemel:field}
{gemel:field name='title'}iPhone丢了以后：“自拍狂”遇上“偷窥狂”{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>前些时候，国外一名女性用户Danielle Bruckman无意中丢了自己的iPhone，通过手机的iCloud服务，她在网上看到了捡到自己手机的男子的自拍照。如果事情发生在国内，那么后续剧情就是失主报警、男子被勒令返还手机了。 不过，这事情发生在国外，就大不同了。</p>
<p>这位美女失主看到这位&ldquo;自拍狂&rdquo;男子的照片后，居然觉得很有趣，偷窥欲瞬间被激发。于是乎，Danielle不仅每天坐等更新，还忍不住对这名男子的自拍照进行了各种模仿。</p>
<p>Danielle表示，在iCloud上查看更新，窥探该男子的日常生活已经成为很期待的一件事情。</p>
<p style="text-align: center;"><img src="/upload/allimg/c140103/13XG5Uc4150-2O46.jpg" border="0" width="500" alt="iPhone丢了以后：&ldquo;自拍狂&rdquo;遇上&ldquo;偷窥狂&rdquo;" height="259" /></p>
<p style="text-align: center;"><img src="/upload/allimg/c140103/13XG5V036420-3M21.jpg" border="0" width="500" alt="" height="259" /></p>
<p style="text-align: center;"><img src="http://upload.chinaz.com/2014/0102/1388653943164.jpg_w600.jpg" border="0" width="600" alt="iPhone丢了以后：&ldquo;自拍狂&rdquo;遇上&ldquo;偷窥狂&rdquo;" height="294" /></p>
<p style="text-align: center;"><img src="http://upload.chinaz.com/2014/0102/1388653943918.jpg_w600.jpg" border="0" width="600" alt="" height="296" /></p>
<p style="text-align: center;"><img src="http://upload.chinaz.com/2014/0102/1388653943458.jpg_w600.jpg" border="0" width="600" alt="" height="296" /></p>
<p style="text-align: center;"><img src="http://upload.chinaz.com/2014/0102/1388653943677.jpg_w600.jpg" border="0" width="600" alt="" height="293" /></p>
<p style="text-align: center;"><img src="http://upload.chinaz.com/2014/0102/1388653943902.jpg_w600.jpg" border="0" width="600" alt="" height="298" /></p>
<p style="text-align: center;"><img src="http://upload.chinaz.com/2014/0102/1388653943808.jpg_w600.jpg" border="0" width="600" alt="" height="296" /></p>
<p style="text-align: center;"><img src="http://upload.chinaz.com/2014/0102/1388653943421.jpg_w600.jpg" border="0" width="600" alt="" height="296" /></p>
<p style="text-align: center;"><img src="http://upload.chinaz.com/2014/0102/1388653943333.jpg_w600.jpg" border="0" width="600" alt="" height="296" /></p>
<p><img src="http://upload.chinaz.com/2014/0102/1388653943200.jpg_w600.jpg" border="0" width="600" alt="" height="294" style="display: block; margin-left: auto; margin-right: auto;" /></p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c140103/13XG5Uc4150-2O46_lit.jpg{/gemel:field}
