<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/140620/1-1406201H159.jpg ",96,246);
$z[1][4]['ddimg']="/upload/allimg/140620/1-1406201H159-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="2048";
$z[1][4]['height']="1536";
$z[2]=Array("img"," /upload/allimg/140620/1-1406201H241.jpg ",248,398);
$z[2][4]['ddimg']="/upload/allimg/140620/1-1406201H241-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="2048";
$z[2][4]['height']="1536";
$z[3]=Array("img"," /upload/allimg/140620/1-1406201H244.jpg ",400,548);
$z[3][4]['ddimg']="/upload/allimg/140620/1-1406201H244-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="800";
$z[3][4]['height']="600";
$z[4]=Array("img"," /upload/allimg/140620/1-1406201H248.jpg ",550,698);
$z[4][4]['ddimg']="/upload/allimg/140620/1-1406201H248-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="800";
$z[4][4]['height']="600";

?>