{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140620/1-1406201IA4-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201IA4.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201IA7-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201IA7.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201IF0-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201IF0.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201IF3-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201IF3.jpg {/gemel:img}
