
  <m:item name='所有档案列表' link='content_list.php' rank='a_List,a_AccList' target='main' class='sydalb' />
  <m:item name='内容回收站' link='recycling.php' ischannel='1' addalt='清空回收站' addico='images/gtk-del.png' linkadd='archives_do.php?dopost=clear&aid=no' rank='a_List,a_AccList,a_MyList' target='main' class='nrhsz' />  
  <m:item name='友情链接' link='friendlink_main.php' target='main' class='yqlj' />
  <m:item name='广告管理' link='rpad_main.php' target='main' class='gggl' />
  
