<li class="clear">
                              <div class="img">
                                   <a href="[field:arcurl/]"><img src="[field:footer_img/]" title="[field:title/]" alt="[field:title/]" width="160" height="95" /></a>
                              </div>
                              <div class="text">
                                    <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
                                    <p>SHOW: [field:add_time/]</p>
                                    <a href="[field:arcurl/]">READ MORE</a>    
                              </div>   
                           </li>