<li>
                    <div class="video">
                          <iframe width="626" height="420" src="[field:litpic/]" frameborder="0" allowfullscreen></iframe> 
                    </div>
                    <div class="video-title">
                          <div class="middle">
                                <div class="linner">
                                      <h3>[field:title/]</h3>
                                </div>
                          </div>
                    </div>
               </li>