{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/160601/dr-f-01-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-f-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160601/dr-f-02-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-f-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160601/dr-f-03-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-f-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160601/dr-f-04-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-f-04.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160601/dr-f-05-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-f-05.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160601/dr-f-06-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-f-06.jpg {/gemel:img}
