<li>
                    <a href="[field:typelink/]"><img src="/images/home-pro-04.jpg" title="Battery charger" alt="Battery charger" width="278" height="270" /></a>
                    <div class="title">
                          <div class="left">
                                <h2><a href="[field:typelink/]">Battery charger</a></h2>
                          </div>
                          <a href="[field:typelink/]"><em></em></a>
                    </div>
               </li>