<?php
$z[0]=Array("field","",40,62);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",74,97);
$z[1][4]['name']="typepic2";
$z[2]=Array("field","",106,129);
$z[2][4]['name']="typename";
$z[3]=Array("field","",136,159);
$z[3][4]['name']="typename";
$z[4]=Array("field","",232,254);
$z[4][4]['name']="typeurl";
$z[5]=Array("field","",256,279);
$z[5][4]['name']="typename";
$z[6]=Array("field","",330,352);
$z[6][4]['name']="typeurl";

?>