<li>
                        <a href="[field:arcurl/]" class="activities_list_img"><img src="[field:litpic/]" /></a>
                        <div class="activities_list_right">
                            <a href="[field:arcurl/]" class="activities_list_tit">[field:title/]</a>
                            <p class="activities_list_time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</p>
                            <p class="activities_list_profile">[field:description function='cn_substrR(html2text(@me),280)'/]</p>
                            <p><a class="activities_more" href="[field:arcurl/]">查看详情</a></p>
                        </div>
                        <div class="clear"></div>
                    </li>