<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/151029/b2214-02.png ",96,234);
$z[1][4]['ddimg']="/upload/allimg/151029/b2214-02-lp.png";
$z[1][4]['text']="";
$z[1][4]['width']="870";
$z[1][4]['height']="555";
$z[2]=Array("img"," /upload/allimg/151029/b2214-03.png ",236,374);
$z[2][4]['ddimg']="/upload/allimg/151029/b2214-03-lp.png";
$z[2][4]['text']="";
$z[2][4]['width']="870";
$z[2][4]['height']="555";
$z[3]=Array("img"," /upload/allimg/151029/b2214-04.png ",376,514);
$z[3][4]['ddimg']="/upload/allimg/151029/b2214-04-lp.png";
$z[3][4]['text']="";
$z[3][4]['width']="870";
$z[3][4]['height']="555";

?>