<li>
                    <a href="[field:typelink/]"><img src="/images/home-pro-03.jpg" title="Battery pack" alt="Battery pack" width="278" height="270" /></a>
                    <div class="title">
                          <div class="left">
                                <h2><a href="[field:typelink/]">Battery pack</a></h2>
                          </div>
                          <a href="[field:typelink/]"><em></em></a>
                    </div>
               </li>