{gemel:field name='keywords'}站长之家, 1号店, 销售额{/gemel:field}
{gemel:field name='description'}11月11日凌晨开门仅1个小时，1号店全站销售额周同比增长11倍，1号商城销售额周同比增长25倍；截止11日晨10点战报，团购销售额较去年同比增长50倍。{/gemel:field}
{gemel:field name='title'}1号店双11仅1小时销售疯长11倍{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>11月11日凌晨开门仅1个小时，1号店全站销售额周同比增长11倍，1号商城销售额周同比增长25倍；截止11日晨10点战报，团购销售额较去年同比增长50倍。</p>
<p>1号店副总裁黄晓强透露，&ldquo;昨天很多同事都通宵加班，一起见证销量疯狂攀升，截止到11日上午10点，1号店手机数码品类周同比增长11倍，母婴品类周同比增长10倍，美护品类周同比增长8倍，生活电器周同比增长13倍。而且，这些数字还在不断被刷新中。&rdquo;</p>
<p>据1号店副总裁黄志雄介绍，截止到11日上午10点，1号店进口和国产食品饮料都双双达到周同比增长7倍；营养保健周同比增长5倍，较去年同比增长17倍。</p>
<p>据了解，1号店双11促销第二波&ldquo;5折狂欢&rdquo;，正式于11日凌晨拉开帷幕。&ldquo;5折狂欢&rdquo;涵盖了食品饮料、进口食品、美容护理、厨卫清洁、生活电器、手机等热门品类的热销商品。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
