<?php
$z[0]=Array("field","",80,102);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",104,127);
$z[1][4]['name']="typename";
$z[2]=Array("field","",246,268);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",280,302);
$z[3][4]['name']="typepic";
$z[4]=Array("field","",336,359);
$z[4][4]['name']="typename";
$z[5]=Array("field","",366,389);
$z[5][4]['name']="typename";
$z[6]=Array("arclist","\r\n                    <li>\r\n                        <a href=\"[field:arcurl/]\">\r\n                            <img src=\"[field:blist_img/]\" width=\"182\" height=\"130\" title=\"[field:title/]\" alt=\"[field:title/]\"/>\r\n                        </a>\r\n                    </li>\r\n                    ",516,909);
$z[6][4]['orderby']="weight";
$z[6][4]['titlelen']="40";
$z[6][4]['row']="6";
$z[6][4]['addfields']="blist_img";
$z[6][4]['channelid']="2";
$z[7]=Array("field","",965,987);
$z[7][4]['name']="typeurl";

?>