<li>
                    <a href="[field:typelink/]"><img src="/images/home-pro-04.jpg" title="" alt="" width="" height="" /></a>
                    <div class="title">
                          <div class="left">
                                <h2><a href="[field:typelink/]">PCM PROTECTION BOARD</a></h2>
                          </div>
                          <a href="[field:typelink/]"><em></em></a>
                    </div>
               </li>