<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:pro_certificate itemname="Certificate" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="UL,VDE,CCC"  maxlength="250" page="">
</field:pro_certificate>

<field:pro_material itemname="Material" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="PVC,Silicone,Rubber,Teflon"  maxlength="250" page="">
</field:pro_material>

<field:pro_temperature itemname="Temperature" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="80℃,105℃,180℃,200℃"  maxlength="250" page="">
</field:pro_temperature>

<field:pro_voltage itemname="Voltage" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="300V,500V,600V "  maxlength="250" page="">
</field:pro_voltage>

<field:certificate_icon itemname="认证图标" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:certificate_icon>
