<li>
                            <div class="news_img"><a href="[field:arcurl/]"><img src="[field:litpic/]" width="58" height="58" alt="[field:title/]" title="[field:title/]"/></a></div>
                            <div class="news_text"><a href="[field:arcurl/]">[field:title/] ...</a><br/><span style="padding-top:10px;"><a href="[field:arcurl/]">Read More...</a></span></div>
                            <div class="clear"></div>
                        </li>