<li>
                        <a href="[field:arcurl/]" class="testimonials_list_tit">[field:title/]</a>
                        <p class="testimonials_list_time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</p>
                        <p class="news_list_profile">[field:description function='cn_substrR(html2text(@me),280)'/]</p>
                        <a class="news_more" href="[field:arcurl/]"></a>
                    </li>