{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/170621/wet-drawing-machine-2-01-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/wet-drawing-machine-2-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/wet-drawing-machine-2-02-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/wet-drawing-machine-2-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/wet-drawing-machine-2-03-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/wet-drawing-machine-2-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/wet-drawing-machine-2-04-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/wet-drawing-machine-2-04.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/wet-drawing-machine-2-05-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/wet-drawing-machine-2-05.jpg {/gemel:img}
