<li class="clear">
                       <div class="news_img">
                           <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="164" height="120" /></a>
                       </div>
                       <div class="news_text">
                            <h2><a href="[field:arcurl/]">[field:title/]</a></h2>
                            <p>[field:description function='cn_substrR(html2text(@me),200)'/].... </p>
                            <span><a href="[field:arcurl/]">More</a></span>
                       </div>                         
                  </li>