<?php
$z[0]=Array("brand","	\n",4,150);
$z[0][4]['itemname']="品牌";
$z[0][4]['autofield']="1";
$z[0][4]['notsend']="0";
$z[0][4]['type']="text";
$z[0][4]['isnull']="true";
$z[0][4]['islist']="1";
$z[0][4]['default']="";
$z[0][4]['maxlength']="250";
$z[0][4]['page']="";
$z[1]=Array("uptime","	\n",154,312);
$z[1][4]['itemname']="上架时间";
$z[1][4]['autofield']="1";
$z[1][4]['notsend']="0";
$z[1][4]['type']="datetime";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="0";
$z[1][4]['default']="";
$z[1][4]['maxlength']="250";
$z[1][4]['page']="";
$z[2]=Array("body","	\n",314,470);
$z[2][4]['itemname']="详细介绍";
$z[2][4]['autofield']="1";
$z[2][4]['notsend']="0";
$z[2][4]['type']="htmltext";
$z[2][4]['isnull']="true";
$z[2][4]['islist']="0";
$z[2][4]['default']="";
$z[2][4]['maxlength']="";
$z[2][4]['page']="split";

?>