{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140714/90018-b-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90018-b.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90018-c-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90018-c.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90033-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90033-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90046-b--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90046-b-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90060-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90060-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90082-b--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90082-b-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96017-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96017-a.jpg {/gemel:img}
