{gemel:field name='keywords'}站长之家, 小米手机3, 小米{/gemel:field}
{gemel:field name='description'}今日中午12点，被称作“倚天屠龙”双神器的小米手机3与小米电视正式开始售卖。在此次的首批开放购买中，小米公司总共备货了10万台小米手机3与3000台小米电视，不出意料的是{/gemel:field}
{gemel:field name='title'}倚天屠龙今试刀锋小米手机3与小米电视闪电售罄{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>10月15日消息，今日中午12点，被称作&ldquo;倚天屠龙&rdquo;双神器的小米手机3与小米电视正式开始售卖。在此次的首批开放购买中，小米公司总共备货了10万台小米手机3与3000台小米电视，不出意料的是，两款神器产品都闪电般迅速售罄。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131015/13QR15045E20-5Z95.jpg" border="0" /></p>
<p>记者从小米公司处获得了最新数据，数据显示，10万台小米手机3在1分26秒的时间内售罄，而3000台小米电视也在1分58秒内被抢购一空。同时，小米内部人士表示：小米一直以来不断提升售后服务体系，能够在最快的时间内保证发货，让抢购成功的用户在最短时间内收到快递。</p>
<p>与此前小米手机的统一硬件平台不同，小米手机3提供两种处理器版本，本次开放购买的小米手机3为采用NVIDIA Tegra 4的中国移动TD版本，而中国联通/中国电信版小米3采用高通骁龙800(8974AB)尚未量产，所以本次开放购买并未涉及。</p>
<p>小米手机3配备了索尼1300万像素F2.2大光圈堆栈式后置摄像头、飞利浦双LED闪光灯、与200万像素背照式前置摄像头。在屏幕方面，采用夏普\LG 5英寸全高清IPS视网膜屏幕，屏幕更大确更加细腻，并且还配备全球最高标准的2GB LPDDR3内存与全球最高标准的16GEMMC4.5闪存，以及3000毫安大容量锂离子聚合物电池。</p>
<p>记者拿到了多款专业测试软件的跑分测试数据，搭载Tegra4处理器的小米手机3安兔兔跑分36582、Quadrant跑分18702、Geekbench2跑分4106。高通骁龙800 (8974AB)小米3安兔兔跑分36026、Quadrant跑分19175、Geekbench2 4139，被业界公认为迄今为止运行速度最快的智能手机。</p>
<p>小米电视采用了47寸LG\三星1080p顶级高清屏，配备高通8064四核1.5G处理芯片以及2G内存，堪称电视机+小米盒子+安卓游戏机的完美组合，定价2999元。其时尚的工艺设计与高超的性价比，受到了诸多年轻人群的热捧。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131015/13QR15045E20-5Z95_lit.jpg{/gemel:field}
