<div class="list-text">
              <h2><a href="{gemel:field.typeurl/}">{gemel:field.typename/}</a></h2>
              <div class="list">
                   <ul class="clear">
                        {gemel:arclist orderby='weight' titlelen='40' row='40' addfields='blist_img' channelid='2'}                   
                        <li>
                             <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="298" height="450" /></a>
                             <div class="product-specifications">
                                   <p>• Speaker horn:  4inch (4Ω 10W)*2 + 3inch（Bass）*1</p>       
                                   <p>• Battery: 3000mAh</p>
                                   <p>• 4PCS/CTN</p>
                                   <p>• Product Size: 20(L)*13(W)*55(H)cm</p>
                                   <p>• Carton Box size:47.5*33.5*59cm</p>
                                   <p>• N.W: 14.5KG  G.W: 15.5KG"</p>
                             </div>
                             <h3><a href="[field:arcurl/]">KBQ-165</a></h3>
                        </li>
                        {/gemel:arclist}
                   </ul>
              </div>
        </div>