<?php
$z[0]=Array("field","",52,74);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",76,99);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","                   \r\n                        <li>\r\n                             <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"298\" height=\"450\" /></a>\r\n                             <div class=\"product-specifications\">\r\n                                   <p>• Speaker horn:  4inch (4Ω 10W)*2 + 3inch（Bass）*1</p>       \r\n                                   <p>• Battery: 3000mAh</p>\r\n                                   <p>• 4PCS/CTN</p>\r\n                                   <p>• Product Size: 20(L)*13(W)*55(H)cm</p>\r\n                                   <p>• Carton Box size:47.5*33.5*59cm</p>\r\n                                   <p>• N.W: 14.5KG  G.W: 15.5KG\"</p>\r\n                             </div>\r\n                             <h3><a href=\"[field:arcurl/]\">KBQ-165</a></h3>\r\n                        </li>\r\n                        ",207,1219);
$z[2][4]['orderby']="weight";
$z[2][4]['titlelen']="40";
$z[2][4]['row']="40";
$z[2][4]['addfields']="blist_img";
$z[2][4]['channelid']="2";

?>