{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140620/1-1406201GH4-lp.jpg' text='' width='600' height='528'} /upload/allimg/140620/1-1406201GH4.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201GI2-lp.jpg' text='' width='700' height='616'} /upload/allimg/140620/1-1406201GI2.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201GI9-lp.jpg' text='' width='700' height='525'} /upload/allimg/140620/1-1406201GI9.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201GJ4-lp.jpg' text='' width='700' height='525'} /upload/allimg/140620/1-1406201GJ4.jpg {/gemel:img}
