<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/140620/1-1406201GH4.jpg ",96,242);
$z[1][4]['ddimg']="/upload/allimg/140620/1-1406201GH4-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="600";
$z[1][4]['height']="528";
$z[2]=Array("img"," /upload/allimg/140620/1-1406201GI2.jpg ",244,390);
$z[2][4]['ddimg']="/upload/allimg/140620/1-1406201GI2-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="700";
$z[2][4]['height']="616";
$z[3]=Array("img"," /upload/allimg/140620/1-1406201GI9.jpg ",392,538);
$z[3][4]['ddimg']="/upload/allimg/140620/1-1406201GI9-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="700";
$z[3][4]['height']="525";
$z[4]=Array("img"," /upload/allimg/140620/1-1406201GJ4.jpg ",540,686);
$z[4][4]['ddimg']="/upload/allimg/140620/1-1406201GJ4-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="700";
$z[4][4]['height']="525";

?>