{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140528/1-14052P95G9-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P95G9.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052P95H1-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P95H1.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052P95H2-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P95H2.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052P95H3-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P95H3.jpg {/gemel:img}
