<li>
            <a href="[field:arcurl/]" class="content-main"><img src="[field:litpic/]" width="290" height="219" alt="[field:title/]" title="[field:title/]" >
                <span>[field:title/]</span>
            </a>
            <div class="pro-layer">
            <a href="[field:arcurl/]">
                     [field.pro_info/]
                <div class="layer-btn">
                     <a href="" class="pro-email"><i>&nbsp;</i></a>
                <a href="" class="pro-shou"><i>&nbsp;</i></a>
                </div>
            </a>
              
                
            </div>
           
            </li>