<li>
                       <div class="img">
                           <a href="[field:arcurl/]"><img src="[field:related_img/]" title="[field:title/] - [field:typename/]" alt="[field:title/] - [field:typename/]" width="237" height="237" /></a>
                       </div>
                       <h3><a href="[field:arcurl/]" title="[field:title/] - [field:typename/]">[field:title/]</a></h3>
                  </li>