<?php
$z[0]=Array("arclist","\r\n                <li><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"270\" height=\"270\" alt=\"[field:typename/] - [field:title/]\" title=\"[field:typename/] - [field:title/]\">\r\n                    <span>[field:title/]</span>\r\n                </a></li>\r\n                ",36,385);
$z[0][4]['orderby']="weight";
$z[0][4]['titlelen']="100";
$z[0][4]['row']="8";

?>