		
	  <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='图片集' ischannel='1' link='content_i_list.php?channelid=2' linkadd='album_add.php?channelid=2' channelid='2' rank='' target='main' />
  <m:item name='图片集PCM' ischannel='1' link='content_i_list.php?channelid=15' linkadd='album_add.php?channelid=15' channelid='15' rank='' target='main' />
  <m:item name='图片集UPS' ischannel='1' link='content_i_list.php?channelid=16' linkadd='album_add.php?channelid=16' channelid='16' rank='' target='main' />
  <m:item name='图片集battery_pack' ischannel='1' link='content_i_list.php?channelid=17' linkadd='album_add.php?channelid=17' channelid='17' rank='' target='main' />
  <m:item name='图片集pack_charger' ischannel='1' link='content_i_list.php?channelid=18' linkadd='album_add.php?channelid=18' channelid='18' rank='' target='main' />
		
