<?php
$z[0]=Array("sppage","",4,75);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.chinaz.com/news/2012/1024/279602.shtml",77,159);
$z[2]=Array("keywordtrim","",161,196);
$z[3]=Array("descriptiontrim","",198,241);
$z[4]=Array("item","\r\n   {gemel:match}<title>[内容] - 站长之家</title>{/gemel:match}\r\n   \r\n   {gemel:function}{/gemel:function}\r\n",243,414);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {gemel:match}{/gemel:match}\r\n   \r\n   {gemel:function}{/gemel:function}\r\n",416,550);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {gemel:match}{/gemel:match}\r\n   \r\n   {gemel:function}{/gemel:function}\r\n",552,686);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {gemel:match}{/gemel:match}\r\n   \r\n   {gemel:function}@me=GetMkTime(@me);{/gemel:function}\r\n",688,842);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {gemel:match}<div class=\"content cont-detail fs-small\" id=\"ctrlfscont\">[内容]<div class=\"share-mod clearfix\">{/gemel:match}\r\n   {gemel:trim replace=\"\"}<a([^>]*)>(.*)</a>{/gemel:trim}\r\n{gemel:trim replace=\"\"}<script([^>]*)>(.*)</script>{/gemel:trim}\r\n{gemel:trim replace=\"\"}<div([^.]*)>{/gemel:trim}\r\n{gemel:trim replace=\"\"}</div>{/gemel:trim}\r\n   {gemel:function}{/gemel:function}\r\n",844,1274);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>