
-----------------------------------------------
<m:top item='1_' name='常用操作' display='block' class='cycc'>
  <m:item name='所有档案列表' link='content_list.php' rank='a_List,a_AccList' target='main' class='sydalb' />
  <m:item name='内容回收站' link='recycling.php' ischannel='1' addalt='清空回收站' addico='images/gtk-del.png' linkadd='archives_do.php?dopost=clear&aid=no' rank='a_List,a_AccList,a_MyList' target='main' class='nrhsz' />  
  <m:item name='友情链接' link='friendlink_main.php' target='main' class='yqlj' />
  <m:item name='广告管理' link='rpad_main.php' target='main' class='gggl' />
  
</m:top>
<m:top item='1_' name='内容管理' display='block' class='cycc'>		
	  <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='产品中心' ischannel='1' link='content_list.php?channelid=3' linkadd='archives_add.php?channelid=3' channelid='3' rank='' target='main' />
  <m:item name='品牌介绍' ischannel='1' link='content_list.php?channelid=14' linkadd='archives_add.php?channelid=14' channelid='14' rank='' target='main' />
  <m:item name='下载中心' ischannel='1' link='content_list.php?channelid=15' linkadd='archives_add.php?channelid=15' channelid='15' rank='' target='main' />
  <m:item name='会员中心' ischannel='1' link='content_list.php?channelid=16' linkadd='archives_add.php?channelid=16' channelid='16' rank='' target='main' />
		
</m:top>
<m:top item='1_' name='附件管理' display='block' rank='sys_Upload,sys_MyUpload,plus_文件管理器' class='fjgl'>
  <m:item name='上传新文件' link='media_add.php' rank='' target='main' class='scxwj' />
  <m:item name='附件数据管理' link='media_main.php' rank='sys_Upload,sys_MyUpload' target='main' class='fjsjgl' />
  <m:item name='文件式管理器' link='media_main.php?dopost=filemanager' rank='plus_文件管理器' target='main' class='wjsglq' />
</m:top>
-----------------------------------------------
