{gemel:field name='keywords'}站长之家, im2.0, WPP集团,{/gemel:field}
{gemel:field name='description'}传WPP集团收购中国数字营销公司im2.0互动营销 im2.0是专注与Web 2.0的互动营销公司，目前拥有230名员工，资产约为人民币2亿元。{/gemel:field}
{gemel:field name='title'}传WPP集团收购中国数字营销公司im2.0互动营销{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p><img src="/upload/allimg/c131015/13QR149492510-323c.jpg" border="0" /></p>
<p><strong>腾讯科技 明轩 10月15日消息</strong></p>
<p>消息人士周一透露，作为全球最大的广告公司WPP集团在中国市场扩张战略的一部分，这家公司已经收购了中国数字营销公司im2.0互动营销。</p>
<p>据悉，WPP集团通过旗下的自营公司VML完成了此次收购，VML隶属于扬&middot;罗比凯广告公司（Young &amp; Rubicam）。收购im2.0互动营销的交易目前已提交给监管部门等待审批。</p>
<p>中国市场目前是WPP集团的第三大市场，仅次于美国和英国市场。包括关联公司在内，WPP集团在中国拥有约1.4万名员工，年营收达到14亿美元。为应对欧洲和北美增长放缓，在新兴经济体捕捉到新业务，WPP集团今年已投入4亿英镑（约合6.4亿美元）在土耳其、巴西、印度和越南等快速增长的市场收购数字广告资产和公司。</p>
<p>im2.0互动营销是专注与Web 2.0的互动营销公司，公司的客户包括了戴尔、阿迪达斯、蒙大利兹、以及青岛海尔等。消息人士透露，im2.0互动营销目前拥有230名员工，资产约为人民币2亿元（约合3300万美元）。</p>
<p>截至目前，im2.0互动营销及WPP集团发言人均对此报道未置可否。</p>
<p><strong>新兴市场扩张</strong></p>
<p>WPP集团股价周一在伦敦证券交易所上涨0.3%，报收于1242便士。今年以来，这家公司的累计涨幅已达到40%。</p>
<p>中国政府此前将今年的经济增长速度定为7.5%，这一增长率在第二季度已经实现。国家统计局将会在本周发布第三季度经济增长数据。彭博社的调查结果显示，市场分析师当前预计中国第三季度经济增长速度将达到7.8%。</p>
<p>在收购im2.0互动营销之后，WPP集团今年已收购了五家中国公司，其中包括市场调研公司秒针系统（Miaozhen Systems）和新华信国际信息咨询（北京）有限公司（sinotrust international information &amp; consulting (beijing) co.）。WPP集团在今年已完成超过40笔并购交易，其中70%位于阿根廷、缅甸、泰国和肯尼亚等新兴市场。</p>
<p>阳狮集团（Publicis）与宏盟集团（Omnicom）在今年7月份披露了价值350亿美元的合并计划，此举将重塑全球广告行业，影响全球各大品牌--从电视网络到谷歌(微博)与Facebook--的巨额广告支出。按营收及股权价值计，新成立的阳狮宏盟集团（Publicis Omnicom Group）将成为全球最大的广告集团。新公司采用荷兰控股企业架构，将分别在巴黎和纽约保留总部，在纽约主要上市，同时在巴黎泛欧交易所上市。</p>
<p>WPP集团在今年8月份预计，公司今年的营收增幅将超过3%。该公司首席执行官苏铭天（Sir Martin Sorrell）当时曾表示，未来五年时间里，公司来自快速增长市场和数字业务的营收将占到总营收的40%至45%，高于此前预计的35%至40%。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131015/13QR149492510-323c_lit.jpg{/gemel:field}
