{gemel:field name='keywords'}站长之家, 微信, 第一视频{/gemel:field}
{gemel:field name='description'}新浪科技讯9月24日下午消息，第一视频集团旗下子公司邻讯互动今日发布了类微信应用“邻讯VIC”(注：VIC指语音、即时通讯和社区)。“邻讯VIC”主打私密社交、安全通讯的特点{/gemel:field}
{gemel:field name='title'}第一视频再战移动互联：发布类微信应用{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p>新浪科技讯 9月24日下午消息，第一视频集团旗下子公司邻讯互动今日发布了类微信应用&ldquo;邻讯VIC&rdquo;(注：VIC指语音、即时通讯和社区)。&ldquo;邻讯VIC&rdquo;主打私密社交、安全通讯的特点，设置密友功能，同时对用户发送的图文、语音等信息进行加密。</p>
<p>这也是继2010年的LBS社交应用&ldquo;邻讯&rdquo;之后，第一视频在移动互联网上的又一次主动进攻。邻讯互动成立于2009年，由第一视频集团投资控股，定位于互联网及移动互联网媒体。目前的邻讯互动团队规模在30人左右。</p>
<p>2010年，邻讯互动发布了LBS移动社区应用&ldquo;邻讯&rdquo;。三年过后，&ldquo;邻讯&rdquo;这款应用在街旁、新浪微博、陌陌等诸多竞品的竞争中销声匿迹。</p>
<p>今日，邻讯互动发布了类微信应用&ldquo;邻讯VIC&rdquo;。&ldquo;邻讯VIC&rdquo;集合了网络语音电话、即时通讯和社交功能，与微信的区别在于强调自身私密、安全的特点。&ldquo;邻讯VIC&rdquo;设置了密友圈功能，用户可将私密信息分享给特定的朋友。此外，该款产品通过技术手段对用户发送的语音、图文消息进行加密，同时对手机和服务器链接进行加密，以确保用户隐私的安全性。</p>
<p>&ldquo;邻讯VIC"强调隐私的特点与阿里巴巴今日高调推广的IM&ldquo;来往&rdquo;不谋而合。</p>
<p>据悉，&ldquo;邻讯VIC&rdquo;将在10月15日正式上线。据邻讯互动总裁王海拉透露，&ldquo;邻讯VIC&rdquo;的商业模式包括社区广告、O2O、电商分成和实际线下商店分成。此外，&ldquo;邻讯VIC&rdquo;还将推出VIP版本和企业版。</p>
<p>邻讯互动今年将有两款IM社交结合的产品上线运营。王海拉表示，另外一款应用定位于社交互动营销平台，是和其他公司合作开发的产品，具体情况还不能对外披露。(李云)</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
