<?php
$z[0]=Array("type","\r\n    	<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"98%\">\r\n    		<tr>\r\n    		<td width='10%'><img src='[field:global name='cfg_templeturl'/]/img/channellist.gif' width='14' height='16'></td>\r\n    	 <td width='60%'>\r\n    	<a href=\"[field:typelink /]\">[field:typename /]</a>\r\n        </td>\r\n      <td width='30%' align='right'>\r\n      <a href=\"[field:typelink /]\">更多...</a>\r\n      </td>\r\n    </tr>\r\n   </table>\r\n   ",123,577);
$z[1]=Array("arclist","\r\n	·<a href=\"[field:arcurl /]\">[field:title /]</a><br>\r\n  ",661,751);

?>