<table width="99%" border="0" cellpadding="3" cellspacing="1" bgcolor="#BFCFA9">
  <tr>
    <td bgcolor="#E6F2CC">
    	{gemel:type}
    	<table border="0" cellpadding="0" cellspacing="0" width="98%">
    		<tr>
    		<td width='10%'><img src='[field:global name='cfg_templeturl'/]/img/channellist.gif' width='14' height='16'></td>
    	 <td width='60%'>
    	<a href="[field:typelink /]">[field:typename /]</a>
        </td>
      <td width='30%' align='right'>
      <a href="[field:typelink /]">更多...</a>
      </td>
    </tr>
   </table>
   {/gemel:type}
   </td>
  </tr>
  <tr>
    <td height="100" valign="top" bgcolor="#FFFFFF">
	{gemel:arclist}
	·<a href="[field:arcurl /]">[field:title /]</a><br>
  {/gemel:arclist}
	</td>
  </tr>
</table>
<div style='font-size:2px'>&nbsp;</div>
