{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/151028/b3001-01-lp.png' text='' width='870' height='555'} /upload/allimg/151028/b3001-01.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151028/b3001-02-lp.png' text='' width='870' height='555'} /upload/allimg/151028/b3001-02.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151028/b3001-03-lp.png' text='' width='870' height='555'} /upload/allimg/151028/b3001-03.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151028/b3001-04-lp.png' text='' width='870' height='555'} /upload/allimg/151028/b3001-04.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151028/b3001-05-lp.png' text='' width='870' height='555'} /upload/allimg/151028/b3001-05.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151028/b3001-06-lp.png' text='' width='870' height='555'} /upload/allimg/151028/b3001-06.png {/gemel:img}
