{gemel:field name='keywords'}站长之家, 360, 安全联盟{/gemel:field}
{gemel:field name='description'}“现实生活中的安全都保障不了，居然号称保护网民安全？”安全联盟徽官方发博文责问360。昨日，由360主办的“2013中国互联网安全大会”在北京会议中心举行，早晨10点左右，{/gemel:field}
{gemel:field name='title'}安全大会现闹剧：安全联盟谴责360打压对手{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p><strong>站长之家（Chinaz.com）9月24日讯：</strong>&ldquo;现实生活中的安全都保障不了，居然号称保护网民安全？&rdquo;安全联盟徽官方发博文责问360。昨日，由360主办的&ldquo;2013中国互联网安全大会&rdquo;在北京会议中心举行，早晨10点左右，360与安全联盟成员起冲突，上演一出闹剧。</p>
<p style="text-align: center;"><img src="/upload/allimg/c130925/13P0S05J2110-521C.jpg" border="0" alt="安全联盟与360冲突疑似现场" /></p>
<p style="text-align: center; font-size: 12px; text-indent: 0;">安全联盟与360冲突的疑似现场</p>
<p>&ldquo;2013中国互联网安全大会，安全联盟受360邀约前往参加，在参展期间安全联盟展台受到360官方工作人员围堵，阻挠参会人员与展台工作人员正常沟通，360官方工作人员不仅派保安收缴安全联盟宣传资料，摔掉工作人员手机，还限制安全联盟工作人员走动，并要挟安全联盟撤出互联网安全大会。&rdquo;安全联盟徽撰文称。</p>
<p>安全联盟不仅指责360在互联网安全大会期间对其不公，更把战火烧向此前热议的&ldquo;360&lsquo;封杀'搜狗浏览器&rdquo;事件上。</p>
<p>&ldquo;对于360如此行为，安全联盟表示强烈不满，并强烈谴责360以不正当行为打压竞争对手。近期360无视自己浏览器产品漏洞问题，反而混淆视听，通过360手机卫士无端恶意指责腾讯手机qq浏览器，暗杀搜狗浏览器，毫无道德底线，严重伤害用户利益。&rdquo;安全联盟气愤填膺的表示。</p>
<p>安全联盟不仅发博文语气严厉的进行责问，同时在微博上也多次声讨360的行为。目前，360方面并没有做出回应。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130925/13P0S05J2110-521C_lit.jpg{/gemel:field}
