<li>
                        <div class="img">
                            <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:typename/] - [field:title/]" alt="[field:typename/] - [field:title/]" width="245" height="190"/></a>
                        </div>
                        <h3><a href="[field:arcurl/]" title="[field:typename/] - [field:title/]">[field:title/]</a></h3>
                    </li>