{gemel:field name='keywords'}站长之家, 市场, 份额{/gemel:field}
{gemel:field name='description'}据国外媒体报道，随着Windows 8.1的推出，微软浏览器IE11面世后在去年12月份经历了第二个满月，12月份Firefox 26发布，并且也是Chrome 31发布后所经历的第一个满月。来自市{/gemel:field}
{gemel:field name='title'}IE市场份额降至57.91% Chrome升至16.22%{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>网易科技讯 1月2日消息，据国外媒体报道，随着Windows 8.1的推出，微软浏览器IE11面世后在去年12月份经历了第二个满月，12月份Firefox 26发布，并且也是Chrome 31发布后所经历的第一个满月。来自市场研究机构Net Applications最新研究数字显示，2013年12月份在浏览器市场份额竞争中唯一的胜者是Chrome。</p>
<p>与11月份相比，IE市场份额减少了0.45个百分点，从58.36%下降至57.91%；Firefox市场份额减少了0.19个百分点，从18.54%下降至18.35%；Chrome市场份额上升了0.78个百分点，从15.44%增长至16.22%；Safari市场份额减少了0.08个百分点，降至5.82%；Opera市场份额减少了0.06个百分点，降至1.33%。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c140103/13XG5U20110-EX2.png" border="0" /></p>
<p>到2013年末，微软IE市场份额为57.91%，而11月份末这个数字为58.36%，为去年全年最高峰水平。去年1月份，该浏览器市场份额曾为55%，之后全年一直在靠近60%大关附近。</p>
<p>12月份值得一提的是IE11的增长，其市场份额上升了7.15个百分点，从3.27%增长至10.42%。这主要是建立在IE10市场份额降低基础之上，12月份IE10市场份额减少了6.45个百分点，降至11.05%；与此同时，IE9市场份额减少了0.29个百分点，降至8.96%。</p>
<p>12月份，IE8市场份额减少了1.10个百分点，但该浏览器仍然是全球使用人数最多的浏览器，其市场份额高达20.64%。不幸的是，由于Windows XP用户无法升级IE8，IE11市场份额的增长主要是抢夺了IE10和IE9的市场份额。12月份，IE7的市场份额也获得了提升达到2.14%，净增加0.80个百分点；而IE6市场份额减少了0.49个百分点，降至4.43%。三个月前，IE6市场份额终于降至5%以下，并且一直没有能够有所恢复。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c140103/13XG5U2A5P-KL9.png" border="0" /></p>
<p>12月份，Firefox的市场份额为18.35%。该浏览器市场份额一段时间以来一直处于徘徊状态，过去6个月一直保持在18%水平。Firefox 26市场份额为6.60%，这个数字如果能够保持将是一个不错的成绩。其它版本市场份额都在下滑，其中Firefox 25市场份额减少了2.95个百分点，Firefox 24则减少了3.20个百分点，Firefox 22减少了0.05个百分点。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c140103/13XG5U303120-Q929.png" border="0" /></p>
<p>12月份，Chrome夺回了部分失地，其市场份额达到16.22%。Chrome 31市场份额上升了6.11个百分点，该浏览器推出已经有一个整月；Chrome 30市场份额减少了5.49个百分点，而Chrome 29、Chrome 28和Chrome 27几乎未变化。</p>
<p>Net Applications的上述数字，来自对4万家网站的月独立访问量约1.60亿用户的监视。而另一家受欢迎的监视市场份额变动的研究机构StatCounter，通过监视访问者页面浏览量进行研究认为，去年12月份Chrome市场份额为43.92%，位列第一；IE以23.24%，位列浏览器市场份额排名第二；Firefox市场份额为18.95%，排名第三；Safari市场份额为9.14%，排名第四；Opera为1.31%，排名第五。不过，两家研究机构研究结果都显示，Safari和Opera均不在12月份浏览器市场份额排名前三位次。（天门山）</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c140103/13XG5U20110-EX2_lit.png{/gemel:field}
