<field:job_targets itemname="招聘对象" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_targets>

<field:job_vacancies itemname="招聘人数" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_vacancies>

<field:job_add itemname="工作地点" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_add>


<field:job_money itemname="工资待遇" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_money>

<field:job_published itemname="发布时间" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_published>

<field:job_expiration itemname="有效期限" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_expiration>

<field:job_requirements itemname="招聘要求" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_requirements>