{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/170413/st250-01-lp.jpg' text='' width='550' height='500'} /upload/allimg/170413/st250-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170413/st250-02-lp.jpg' text='' width='550' height='500'} /upload/allimg/170413/st250-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170413/st250-03-lp.jpg' text='' width='550' height='500'} /upload/allimg/170413/st250-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170413/st250-04-lp.jpg' text='' width='550' height='500'} /upload/allimg/170413/st250-04.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170413/st250-05-lp.jpg' text='' width='550' height='500'} /upload/allimg/170413/st250-05.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170413/st250-06-lp.jpg' text='' width='550' height='500'} /upload/allimg/170413/st250-06.jpg {/gemel:img}
