 
             <li>
                <a href="[field:typelink/]">[field:typename/]</a>
                   <ul class="sub_menu">
                       [field:sonchannel0]
                       <li><a href='[field:typeurl/]'><img src="[field:typepic/]" alt="[field:typename/]" title="[field:typename/]" width="53" height="53" /><span>[field:typename/]</span></a></li>
                       [/field:sonchannel0]
                   </ul>
             </li>
            