{gemel:field name='keywords'}站长之家, 小米手机, 小米{/gemel:field}
{gemel:field name='description'}国产手机第二大“神器”—小米3手机，将在今天下午2点，国家会议中心正式发布。小米手机和魅族手机，一直以来都是国产手机中最受关注的两款明星机器，也是唯一两款拥有大量{/gemel:field}
{gemel:field name='title'}小米将召开最抢眼发布会 三大亮点值得关注{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}
                                                            <p><strong>站长之家（Chinaz.com）9月5日讯：</strong>国产手机第二大&ldquo;神器&rdquo;&mdash;小米3手机，将在今天下午2点，国家会议中心正式发布。</p>
<p>小米手机和魅族手机，一直以来都是国产手机中最受关注的两款明星机器，也是唯一两款拥有大量粉丝群体的手机。最近魅族发布了最新的MX3手机，时隔两日，最新的小米3手机也要发布了。</p>
<p style="text-align: center;"><img src="/upload/allimg/c130905/13N35424412610-2Y03.jpg" border="0" alt="小米3手机今日发布" /></p>
<p style="text-align: center; font-size: 12px; text-indent: 0;">小米3手机今日发布</p>
<p>本次小米发布会，被称为&ldquo;有史以来最抢眼的一次发布会&rdquo;，现场看点颇多。</p>
<p>首先，最受关注的当然是小米3手机。据网上曝光的资料来看，最新的小米3手机的外观类似于诺基亚的lumia系列手机，采用比较中正的长方形造型，据称会有多种色彩外壳。</p>
<p>按配置来分，小米3可能会有两种版本。第一种，采用主频1.8GHz的英伟达Tegra4处理器、支持移动的TD-SCDMA网络版本，第二种，采用高通骁龙800处理器，支持电信CDM2000、联通WCDMA网的版本，目前高通处理器版本的主频还没有消息透露。</p>
<p>小米3两个版本配备的都是，夏普与JDI的5寸（甚至会更大）in-cell屏幕，分辨率为1920*1080。据悉，该机还会内置3GB&nbsp;RAM的大容量内存和3600mAh超大容量电池，前置摄像头200万，后置摄像头1300万，并支持NFC、米Hi-Fi等功能。</p>
<p>其次，还有一个备受关注的点，是小米电视和紫米平板。据消息人士透露，和小米3同时发布的小米电视，将配备47寸、1080p分辨率的屏幕。据称，小米L47M1-AA的47寸电视已经通过了3C认证。另外一个重磅新品，传说已久的紫米平板，采用1280*768的分辨率的7寸屏、配备4000毫安超大容量电池。这两款终端产品，同样以高性价比作为杀手锏，有消息表示，小米电视定价2999元，紫米平板定价999元，从价格和配置来看，杀伤力巨大。</p>
<p>另外，此前刚加盟小米的谷歌副总裁Hugo&nbsp;Barra，将出席这次发布会，也引发了广泛的关注，届时雷军还会公布进军国际市场的计划。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130905/13N35424412610-2Y03_lit.jpg{/gemel:field}
