<?php
$z[0]=Array("arcurl","",86,101);
$z[1]=Array("litpic","",113,128);
$z[2]=Array("typename","",137,154);
$z[3]=Array("title","",157,171);
$z[4]=Array("typename","",178,195);
$z[5]=Array("title","",198,212);
$z[6]=Array("arcurl","",362,377);
$z[7]=Array("typename","",386,403);
$z[8]=Array("title","",406,420);
$z[9]=Array("title","",422,436);
$z[10]=Array("arcurl","",484,499);
$z[11]=Array("typename","",508,525);
$z[12]=Array("title","",528,542);

?>