<li>
                      <img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="366" height="366"/>
                      <h2>[field:title/]</h2>
                      <div class="readmore">
                           <h3>[field:title/]</h3>
                           <a href="[field:arcurl/]" target="_blank">Read more</a>
                      </div>
                  </li>