{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/151029/b2138-01-lp.png' text='' width='870' height='555'} /upload/allimg/151029/b2138-01.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151029/b2138-02-lp.png' text='' width='870' height='555'} /upload/allimg/151029/b2138-02.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151029/b2138-03-lp.png' text='' width='870' height='555'} /upload/allimg/151029/b2138-03.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151029/b2138-04-lp.png' text='' width='870' height='555'} /upload/allimg/151029/b2138-04.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151029/b2138-05-lp.png' text='' width='870' height='555'} /upload/allimg/151029/b2138-05.png {/gemel:img}
