<?php
$z[0]=Array("field","",94,116);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",128,151);
$z[1][4]['name']="typepic2";
$z[2]=Array("field","",160,183);
$z[2][4]['name']="typename";
$z[3]=Array("field","",190,213);
$z[3][4]['name']="typename";
$z[4]=Array("field","",322,344);
$z[4][4]['name']="typeurl";
$z[5]=Array("field","",346,369);
$z[5][4]['name']="typename";
$z[6]=Array("arclist","\r\n                                <p><a href=\"[field:arcurl/]\">[field:shorttitle/]</a></p>\r\n                                ",460,655);
$z[6][4]['orderby']="weight";
$z[6][4]['titlelen']="40";
$z[6][4]['row']="14";

?>