<li>
                            <div class="img">
                                <a href="{gemel:field.typeurl/}"><img src="{gemel:field.typepic2/}" title="{gemel:field.typename/}" alt="{gemel:field.typename/}" width="79" height="62"/></a>
                            </div>
                            <h2><a href="{gemel:field.typeurl/}">{gemel:field.typename/}</a></h2>
                            <div class="list">
                                {gemel:arclist orderby='weight' titlelen='40' row='14'}
                                <p><a href="[field:arcurl/]">[field:shorttitle/]</a></p>
                                {/gemel:arclist}
                            </div>
                        </li>