{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140528/1-14052P92P7-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P92P7.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052P92P8-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P92P8.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052P92Q0-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P92Q0.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052P93530-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P93530.jpg {/gemel:img}
