<li>
              <a href="[field:arcurl/]" class="img"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="320" height="239" /></a>
              <!--<a href="[field:arcurl/]" class="img"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="384" height="287" /></a>-->
              <p><a href="[field:arcurl/]">[field:title/]</a></p>
         </li>