<?php
$z[0]=Array("top","\r\n	<m:item name='网站栏目管理' link='catalog_main.php' target='main' class='wzlmgl' />\r\n	<m:item name='添加栏目' link='catalog_add.php?listtype=all' target='main' class='tjlm' />\r\n",51,315);
$z[0][4]['item']="1_";
$z[0][4]['name']="栏目管理";
$z[0][4]['display']="block";
$z[0][4]['class']="lmgl";
$z[1]=Array("top","\r\n  <m:item name='更新系统缓存' link='sys_cache_up.php' rank='sys_ArcBatch' target='main' class='gxxthc' />\r\n  <m:item name='文档批量维护' link='content_batch_up.php' rank='sys_ArcBatch' target='main' class='wdplwh' />\r\n  <m:item name='搜索关键词维护' link='search_keywords_main.php' rank='sys_Keyword' target='main' class='ssgjcwh' />\r\n  <m:item name='文档关键词维护' link='article_keywords_main.php' rank='sys_Keyword' target='main' class='wdgjcwh' />\r\n  <m:item name='重复文档检测' link='article_test_same.php' rank='sys_ArcBatch' target='main' class='cfwdjc' />\r\n  <m:item name='自动摘要|分页' link='article_description_main.php' rank='sys_Keyword' target='main' class='zdzy' />\r\n  <m:item name='数据库内容替换' link='sys_data_replace.php' rank='sys_ArcBatch' target='main' class='sjknrth' />\r\n",317,1234);
$z[1][4]['item']="1_";
$z[1][4]['name']="批量维护";
$z[1][4]['display']="block";
$z[1][4]['class']="plwh";

?>