<li>
                        <div class="img">
                            <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:typename/] - [field:title/]" alt="[field:typename/] - [field:title/]" width="252" height="187"/></a>
                        </div>
                        <div class="text">
                            <h3><a href="[field:arcurl/]" title="[field:typename/] - [field:title/]">[field:title/]</a></h3>
                        </div>                  
                    </li>