<?php
$z[0]=Array("arcurl","",61,76);
$z[1]=Array("home_img","",88,105);
$z[2]=Array("shorttitle","",114,133);
$z[3]=Array("typename","",136,153);
$z[4]=Array("shorttitle","",160,179);
$z[5]=Array("typename","",182,199);
$z[6]=Array("arcurl","",280,295);
$z[7]=Array("shorttitle","",304,323);
$z[8]=Array("typename","",326,343);
$z[9]=Array("shorttitle","",345,364);
$z[10]=Array("arcurl","",397,412);

?>