<li>
            	<div class="img">
            		<a href="[field:arcurl/]"><img src="[field:home_img/]" title="[field:shorttitle/] - [field:typename/]" alt="[field:shorttitle/] - [field:typename/]" width="202" height="176"/></a>
            	</div>
            	<h3><a href="[field:arcurl/]" title="[field:shorttitle/] - [field:typename/]">[field:shorttitle/]</a></h3>
            	<a href="[field:arcurl/]">view more</a>
            </li>