{gemel:field name='keywords'}站长之家, 谷歌眼镜, 谷歌{/gemel:field}
{gemel:field name='description'}北京时间9月5日消息，Suntrust Robinson Humphrey金融分析师罗伯特-S-佩克（Robert S. Peck）在报告中指出，2017年，Google眼镜将成为年规模32.7亿美元的业务。{/gemel:field}
{gemel:field name='title'}谷歌眼镜2017年营收将达33亿美元{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}
                                                            <p>【搜狐IT消息】北京时间9月5日消息，Suntrust Robinson Humphrey金融分析师罗伯特-S-佩克（Robert S. Peck）在报告中指出，2017年，Google眼镜将成为年规模32.7亿美元的业务。</p>
<p>就算硬件没有利润，Google仍然可以通过眼镜中的搜索、数据来赚钱，还可以通过APP销售分成获得收入。佩克认为，到2017年，Google眼镜装机量将达6.45万，新品定价将达349美元。</p>
<p>2017年，眼镜的显示屏可以为Google带来非硬件收入32.7亿美元，约占2017年公司总估计营收864亿美元的3.7%。</p>
<p>收入主要来自眼镜中的搜索。佩克称，在作出估计时，考虑的是用户每天搜索量比现有搜索活动多2次以上，眼镜的广告会更有效率，也更贵。</p>
<p>听起来，佩克的估计并不夸张（除非眼镜完全失败），毕竟到目前为止，1万名测试者已经花1500美元购买设备，他们会不会每天都佩戴这又是另一个问题了。</p>
<p>佩克估计，如果2014年年中时Google眼镜开始销售，2014年带来的总营收将达2.71784亿美元，2015年总营收10.15324亿美元，2016年达20.05358亿美元，到2017年增至32.67亿美元。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
