{gemel:field name='keywords'}站长之家, 淘宝, 导购类网{/gemel:field}
{gemel:field name='description'}不允许在商品标题、商品详情、店铺、旺旺等中使用导购、团购、促销类网站的名称、LOGO等信息，如前述构成不当使用他人权利的，则根据《淘宝规则》的规定进行处理。{/gemel:field}
{gemel:field name='title'}淘宝再出新规：清除导购类网站信息{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p>据悉，《淘宝规则》将调整对于滥发信息的管理与处理措施，规则中新增了一条：</p>
<p>不允许在商品标题、商品详情、店铺、旺旺等中使用导购、团购、促销类网站的名称、LOGO等信息，如前述构成不当使用他人权利的，则根据《淘宝规则》的规定进行处理。</p>
<p></p>
<p>据了解，2013年9月18日&mdash;9月29日为整改期，淘宝网要求卖家结合宝贝体检中心提醒与自我排查，及时修改自己的商品信息。9月29日规则将正式开始执行。</p>
<p>在淘宝网公布的《滥发信息实施细则》中，还发现，将成交的结果指向本店铺以外的店铺或外部网站，包括以二维码、超链接等形式出现的淘宝客、外部购物平台、外部社交网站等信息，也不允许出现在商品详情、店铺信息等处。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
