<li>
                <div class="exhibition_left">
                      <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="398" height="275" /></a>
                </div>
                <div class="exhibition_right">
                      <h2>[field:title/]</h2>
                      <p>[field:description function='cn_substrR(html2text(@me),150)'/]...</p>
                      <a href="[field:arcurl/]">Read More</a>
                </div>
          </li>