{gemel:field name='keywords'}站长之家, 谷歌眼镜, 苹果{/gemel:field}
{gemel:field name='description'}传苹果06年开始研发iGlasses 类似谷歌眼镜 可惜由于iPod和iPhone等产品的人气过旺，iGlasses项目最终被搁置下来。{/gemel:field}
{gemel:field name='title'}传苹果06年开始研发iGlasses 类似谷歌眼镜{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130925/13P0S0A22F-3B33.jpg" border="0" /></p>
<p style="text-align: center;">传苹果06年开始研发iGlasses（腾讯科技配图）</p>
<p><strong>腾讯科技 悦潼 9月25日编译</strong></p>
<p>苹果公司iPod业务前负责人托尼&middot;法戴尔（Tony Fadell）近日宣称，该公司早在2006年就开始研发一项类似于谷歌(微博)眼镜的产品，即&ldquo;iGlasses&rdquo;。不过，托尼称，由于iPod和iPhone等产品的人气过旺，iGlasses项目最终被搁置下来。</p>
<p>托尼声称，iGlasses是他在苹果公司从事的&ldquo;最为疯狂的&rdquo;项目。他还称，早在谷歌今年初向市场展示谷歌眼镜之前很久，苹果就已经制作了一些iGlasses原型。</p>
<p>托尼的上述言论正值最近几个季度苹果公司一直遭受业界批评之际。业界批评苹果公司自从史蒂夫&middot;乔布斯辞世后就一直缺乏创新，而苹果的竞争对手却不断推出诸如智能手表和智能眼镜等新产品。</p>
<p>托尼最近在接受商业杂志《快公司》的采访时确认，自从2006年初以来的较长一段时期，苹果一直在研发一个像放大的耳机那样的产品，也类似于&ldquo;谷歌眼镜&rdquo;。据托尼称，苹果iGlasses的理念旨在打造一种内置显示屏的产品，该产品可以为用户带来一种全新的娱乐体验，让用户感觉到&ldquo;就像是坐在电影院&rdquo;一样。</p>
<p>不过，托尼透露，随着iPhone在2007年成功推出，苹果也因此放弃了iGlasses项目，与此同时，市场对新版iPod的需求也成为了苹果公司工作的重点。对此，托尼称：&ldquo;我们已经从事的一些工作取得了巨大成功，因而我们没有时间做其它的事务。&rdquo;</p>
<p>事实上，去年就有消息称，苹果很久前就开始研究所谓的iGlasses产品，托尼近日的言论似乎也证明了这些传闻。不过，目前来看，托尼的上述消息可能表明苹果版的智能眼镜将以打造新一代的娱乐体验为重点，这可能也是谷歌眼镜的巨大不同之处，因为谷歌眼镜似乎更关注商业市场，而且特别提供了接收电子邮件和拍照等功能。</p>
<p>对于上述传闻，苹果目前还未置评。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130925/13P0S0A22F-3B33_lit.jpg{/gemel:field}
