<li>
                        <div class="img">
                            <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:typename/] - [field:title/]" alt="[field:typename/] - [field:title/]" width="245" height="190"/></a>
                        </div>
                        <div class="text">
                            <h2><a href="" title="">[field:title/]</a></h2>
                            <a href="" title="">view more</a>
                        </div>
                    </li>