{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/150129/double-color-with-high-glossy-edge-banding-m-01-lp.jpg' text='' width='990' height='454'} /upload/allimg/150129/double-color-with-high-glossy-edge-banding-m-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150129/double-color-with-high-glossy-edge-banding-m-02-lp.jpg' text='' width='990' height='454'} /upload/allimg/150129/double-color-with-high-glossy-edge-banding-m-02.jpg {/gemel:img}
