{gemel:field name='keywords'}站长之家, 搜狐, 刘春离职{/gemel:field}
{gemel:field name='description'}2013年10月15日，搜狐公司宣布，搜狐副总裁兼搜狐网总编辑、搜狐视频总裁刘春先生，因为个人原因将于近期离职。{/gemel:field}
{gemel:field name='title'}搜狐公司关于副总裁刘春先生离职的公告{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>2013年10月15日，搜狐公司宣布，搜狐副总裁兼搜狐网总编辑、搜狐视频总裁刘春先生，因为个人原因将于近期离职。</p>
<p>刘春先生2011年7月加盟搜狐，担任搜狐公司副总裁、搜狐视频COO和搜狐网站总编辑，后出任搜狐视频总裁。</p>
<p>搜狐公司董事局主席兼首席执行官张朝阳表示：&ldquo;感谢刘春先生在搜狐就职期间的努力和付出，过去两年多的时间里，搜狐媒体业务在刘春先生的带领下成绩显著，进一步加强了领先优势。我们对刘春先生的选择表示理解和尊重。&rdquo;</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
