<?php
$z[0]=Array("field","",69,98);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",100,130);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                <li>\r\n                <a href=\"[field:app_img/]\" rel=\"prettyPhoto[]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" title=\"[field:title/]\"/></a>\r\n                <span>[field:title/]</span>\r\n                </li>\r\n                ",197,566);
$z[2][4]['titlelen']="38";
$z[2][4]['row']="4";
$z[2][4]['flag']="c";
$z[2][4]['addfields']="app_img";
$z[2][4]['channelid']="16";

?>