<tr>
                           <td><a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="150" height="104" /></a></td>
                           <td>[field:shorttitle/]</td>
                           <td>[field:voltage_p/]</td>
                           <td>[field:capacity_p/]</td>
                           <td>[field:size_p/]</td>
                           <td>[field:cell_model_p/]</td>  
                      </tr>