<?php
$z[0]=Array("channel2","\r\n\r\n                         <li><a href='{gemel:field name='typeurl'",28,137);
$z[0][4]['type']="son";
$z[0][4]['typeid']="1";
$z[1]=Array("field","",146,173);
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",185,214);
$z[2][4]['name']="typepic";
$z[3]=Array("field","",221,251);
$z[3][4]['name']="typename";
$z[4]=Array("field","",260,290);
$z[4][4]['name']="typename";
$z[5]=Array("field","",323,353);
$z[5][4]['name']="typename";
$z[6]=Array("field","",532,561);
$z[6][4]['name']="typeurl";
$z[7]=Array("field","",573,602);
$z[7][4]['name']="typepic";
$z[8]=Array("field","",609,639);
$z[8][4]['name']="typename";
$z[9]=Array("field","",648,678);
$z[9][4]['name']="typename";
$z[10]=Array("field","",711,741);
$z[10][4]['name']="typename";
$z[11]=Array("type","<a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",904,1206);
$z[11][4]['typeid']="12";
$z[12]=Array("type","<a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",1256,1558);
$z[12][4]['typeid']="13";
$z[13]=Array("type","<a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",1608,1910);
$z[13][4]['typeid']="14";
$z[14]=Array("type","<a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",1960,2262);
$z[14][4]['typeid']="15";
$z[15]=Array("type","<a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",2312,2614);
$z[15][4]['typeid']="16";
$z[16]=Array("type","<a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",2664,2966);
$z[16][4]['typeid']="17";

?>