{gemel:field name='keywords'}站长之家, DNS劫持, 百度站{/gemel:field}
{gemel:field name='description'}近来，百度安全团队检测到一大批网站被黑客非法入侵，嵌入恶意代码导致用户dns被蓄意篡改，且影响范围呈上升趋势。目前已检测出有12332个网站受到该木马的侵害。{/gemel:field}
{gemel:field name='title'}百度：DNS劫持漏洞呈上升趋势，请站长关注{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p><strong>站长之家（Chianz.com）11月6日消息</strong>&nbsp; 今日，百度站长平台发布文章《DNS劫持漏洞呈上升趋势，请站长关注》。文中表示已检测到一大批网站被黑客非法入侵，嵌入恶意代码导致用户dns被蓄意篡改，且影响范围呈上升趋势。目前已检测出有12332个网站受到该木马的侵害。</p>
<p><strong>以下为文中全文：</strong></p>
<p>亲爱的网站管理员，</p>
<p>百度安全团队检测到一大批网站被黑客非法入侵，嵌入恶意代码导致用户dns被蓄意篡改，从而对用户的安全造成了严重的影响。知名安全网站乌云也曾进行过公布（http://paper.wooyun.org/bugs/wooyun-2010-037425），我们发现近期受该漏洞影响的网站呈现快速上升的趋势。</p>
<p>据悉，DNS劫持漏洞的具体表现及危害为：当网友访问存在此漏洞的网站时，网站会正常打开，但在后台，网站会自动分析用户所使用的路由器用户名和密码。针对密码较弱的用户，网站会自动破解登录，登录成功后篡改用户的DNS设置，然后在用户毫不知情的情况下，跟踪用户上网行为，盗取个人信息。被劫持的用户很容易受到黑客操纵，在浑然不觉的情况下，被带入钓鱼网站，这样，当用户进行网上金融交易等敏感操作时，极易造成重大的财产损失。</p>
<p>目前我们已检测出有12332个网站受到该木马的侵害。对于受到污染的网站，百度搜索系统会暂时将其放入黑名单中，对其进行保护性拦截，同时我们已经将相应情况通过站长平台消息提醒工具通知了相关站长。</p>
<p>我们建议您及时进行清理并修补漏洞，当百度确认该站点已进行清理完成后，会将其从黑名单中移除，以最大程度地保证网站和用户利益不受损害。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
