{gemel:field name='keywords'}站长之家, 雷军微博, 小米{/gemel:field}
{gemel:field name='description'}如果在2014年小米真能实现4000万的供货量，那么这将妥妥达到全球前十的水平，只是不知道，2014年，小米手机能否做到“马上有货”呢？{/gemel:field}
{gemel:field name='title'}14年销量4000万部？雷军微博引网友吐槽{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>转眼间，承载着我们梦想和努力的2013即将过去，假若要在岁末盘点一下本年度的风云人物，那么小米科技的总裁雷军则绝对名列前茅，这位业界大佬在今年凭借小米3手机等多款新品，制造了一波又一波的抢购高潮，到了年末也总是出席于业内外各大活动和颁奖典礼，大有进军娱乐圈的趋势。</p>
<p><img src="/upload/allimg/c140103/13XG5TY04P-134V.jpg" border="0" width="500" alt="14年销量4000万部？雷军微博引网友吐槽第1张图" height="310" style="display: block; margin-left: auto; margin-right: auto;" /></p>
<p style="text-align: center;">小米总裁－－雷军</p>
<p>2013年12月31日，雷军发表微博称，希望大家用一个词来总结小米的2013，结果此条微博一出，便遭到了广大网友的热烈吐槽，在评论中&ldquo;期货&rdquo;、&ldquo;售罄&rdquo;&ldquo;坑爹&rdquo;等成为出现最多的字眼，米粉们纷纷借此机会表达了对小米&ldquo;玩期货&rdquo;的不满。面对大家的吐槽，雷军随后表示，在2014年将保证供货4000万部手机。</p>
<p style="text-align: center;"><img src="/upload/allimg/c140103/13XG5T9360F-2I41.jpg" border="0" width="500" alt="14年销量4000万部？雷军微博引网友吐槽第2张图" height="272" /></p>
<p style="text-align: center;">雷军微博截图</p>
<p><img src="/upload/allimg/c140103/13XG5TcY40-3M46.jpg" border="0" width="500" alt="14年销量4000万部？雷军微博引网友吐槽第3张图" height="260" style="display: block; margin-left: auto; margin-right: auto;" /></p>
<p style="text-align: center;">雷军微博截图</p>
<p>其实总的来看，小米手机在国内还是比较成功的，只是在营销手段上频遭质疑和吐槽。如果在2014年小米真能实现4000万的供货量，那么这将妥妥达到全球前十的水平，只是不知道，2014年，小米手机能否做到&ldquo;马上有货&rdquo;呢？</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c140103/13XG5TY04P-134V_lit.jpg{/gemel:field}
