<li>
                                   
                                    <a href="[field:arcurl/]"><img src="[field:pro_related/]" alt="[field:typename/] - [field:title/]" title="[field:typename/] - [field:title/]" width="377" height="293" />
                                        <h3>[field:title/]</h3>
                                        <div class="pro_info">
                                            [field:pro_info/]
                                        </div>
                                        
                                    </a>
                                    <div class="pro-more">
                                        <a class="bt rect-btn noajax" href="[field:arcurl/]">
                                            <svg>
                                                <defs>
                                                    <linearGradient id="home-about" x1="0%" y1="0%" x2="100%" y2="0%">
                                                        <stop offset="0%" stop-color="#FFF">
                                                            <animate attributeName="stop-color" values="#FFF;#F5F5F5;#FFF;#FFF" dur="2s" repeatCount="indefinite"></animate>
                                                        </stop>
                                                        <stop offset="33%" stop-color="#FFF">
                                                            <animate attributeName="stop-color" values="#F5F5F5;#FFF;#FFF;#FFF" dur="2s" repeatCount="indefinite"></animate>
                                                        </stop>
                                                        <stop offset="66%" stop-color="#F5F5F5">
                                                            <animate attributeName="stop-color" values="#FFF;#F5F5F5;#FFF;#FFF;" dur="2s" repeatCount="indefinite"></animate>
                                                        </stop>
                                                    </linearGradient>
                                                </defs>
                                                <rect x="0" y="0" fill="none" width="100%" height="100%" stroke="url(#home-about)"></rect>
                                            </svg>
                                            <p data-txt="Showroom">VIEW MORE</p>
                                        </a>
                                    </div>
                                </li>