<li>
                            <a href="[field:arcurl/]" class="redeem_list_img"><img src="[field:litpic/]" /></a>
                            <a href="[field:arcurl/]">[field:title/]</a><br />
                            <span class="price">市场价：￥[field:price/]</span><br />
                            <span class="credits">积分价：[field:credits/]</span>
                            <div class="cboth"></div>
                        </li>