
-----------------------------------------------
<m:top item='1_' name='模板管理' display='none' rank='temp_One,temp_Other,temp_MyTag,temp_test,temp_All' class='mbgl'>
  <m:item name='默认模板管理' link='templets_main.php' rank='temp_All' target='main' class='mrmbgl'/> 
  <m:item name='自定义宏标记' link='mytag_main.php' rank='temp_MyTag' target='main' class='zdyhbj'/>
  <m:item name='全局标记测试' link='tag_test.php' rank='temp_Test' target='main' class='qjbjcs'/>
</m:top>
-----------------------------------------------
