<?php
$z[0]=Array("top","\r\n  <m:item name='默认模板管理' link='templets_main.php' rank='temp_All' target='main' class='mrmbgl'/> \r\n  <m:item name='自定义宏标记' link='mytag_main.php' rank='temp_MyTag' target='main' class='zdyhbj'/>\r\n  <m:item name='全局标记测试' link='tag_test.php' rank='temp_Test' target='main' class='qjbjcs'/>\r\n",51,506);
$z[0][4]['item']="1_";
$z[0][4]['name']="模板管理";
$z[0][4]['display']="none";
$z[0][4]['rank']="temp_One,temp_Other,temp_MyTag,temp_test,temp_All";
$z[0][4]['class']="mbgl";

?>