{gemel:field name='keywords'}站长之家, 小米路由器, 极{/gemel:field}
{gemel:field name='description'}小米路由器正式版目前还没有具体何时上市的消息，而关于这款产品的售价则是有不同的猜测。不过目前的一张快递单据显示，小米路由器的售价极可能为1499元。{/gemel:field}
{gemel:field name='title'}快递单显示小米智能路由器售价或高达1499元{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>小米路由器正式版目前还没有具体何时上市的消息，而关于这款产品的售价则是有不同的猜测。不过目前的一张快递单据显示，小米路由器的售价极可能为1499元。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c140103/13XG5V2925Z-146192.jpg" border="0" /></p>
<p>根据快递单显示，寄出公司为小米科技，寄出产品为小米路由器，而选择保价的声明价值为1499元。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c140103/13XG5V333330-152S3.jpg" border="0" /></p>
<p>小米路由器依旧延续了为发烧友创造的理念，目前送测的工程机测试版本需要用户自己组装而成，而在硬件方面则支持双核1GHz处理器，支持802.11ac双频段，并内置1TB SATA硬盘（该硬盘售价为400元以上）。</p>
<p>同时，小米路由器还与迅雷达成合作，在设置中完成迅雷会员的登陆便可获得一年的白金会员资格。</p>
<p>这样一款设备的售价，自然不会太低廉，而目前送测的应该是工程测试版本，所以该售价仅能做一个参考。不过很据小米产品一向的定价，相信还是会为大家带来足够的惊喜，1499元不一定是最终售价。（完）</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c140103/13XG5V2925Z-146192_lit.jpg{/gemel:field}
