{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/170621/sdt2-01-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/sdt2-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/sdt2-01.jpg-50' text='' width='135' height='119'} /upload/allimg/170621/sdt2-01.jpg-50 {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/sdt2-02-lp.png' text='' width='566' height='429'} /upload/allimg/170621/sdt2-02.png {/gemel:img}
