<li>
                           <div class="img">
                               <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/] - [field:typename/]" alt="[field:title/] - [field:typename/]" width="160" height="160" /></a>
                           </div>
                           <h3><a href="[field:arcurl/]" title="[field:title/] - [field:typename/]">[field:title/]</a></h3>
                       </li>