{gemel:field name='keywords'}站长之家, 天天跑酷, 节奏{/gemel:field}
{gemel:field name='description'}《天天酷跑》是9月15日登陆iOS平台，到今天刚好一个月，有媒体报道称《天天酷跑》月流水过亿，个人判断这个消息还是靠谱的，证据有三：{/gemel:field}
{gemel:field name='title'}《天天酷跑》月入过亿确实靠谱{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p><img class="flag_bigP" src="/upload/allimg/c131015/13QR14V12960-25501.jpg" border="0" alt="" align="middle" style="border: 0px; margin: 0px auto; padding: 0px; font-size: 0px; color: transparent; display: block;" /></p>
<p>《天天酷跑》是9月15日登陆iOS平台，到今天刚好一个月，有媒体报道称《天天酷跑》月流水过亿，个人判断这个消息还是靠谱的，证据有三：</p>
<p>1.在iOS平台，《天天酷跑》压制《我叫MT》大半个月。10.1归来这几天，《天天酷跑》再度在iOS收入排行榜超越《我叫MT》，《我叫MT》号称在iOS平台月流水3000万，能够压制《我叫MT》，在iOS平台月流水至少3000万。</p>
<p>另据业内人士估计，仅在9月下半月，《天天酷跑》月流水就突破3500万。考虑到微信、手Q游戏通过社交关系链缓慢传递特点，《天天酷跑》即使不过亿，也与亿元这个数字相去不远。</p>
<p>2.腾讯在Q4是收获季。我此前听到的说法是，腾讯移动游戏平台（包括手Q、微信等）今年总KPI为20亿，这意味腾讯移动游戏平台的Q4是收获季，像《天天酷跑》这样计费点颇多的游戏如拿不出过亿收入，很难想象这个KPI如何完成。</p>
<p>3.《天天酷跑》确实很牛。（这个是我个人感受，不喜勿喷）10.1回家，我坐的火车，火车上玩游戏的人群最多是玩《天天酷跑》，其次是《节奏大师》，我玩酷跑时还有不少学生党围观。个人直观感受是微信、手Q到达率确实很牛，以这两条社交链做基础，即使存在作弊、刷分、拒绝付费党等，《天天酷跑》做到过亿收入仍然So easy。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131015/13QR14V12960-25501_lit.jpg{/gemel:field}
