{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/131009/1-131009140S9-lp.jpg' text='' width='518' height='359'} /upload/allimg/131009/1-131009140S9.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/131009/1-131009140T1-lp.jpg' text='' width='379' height='244'} /upload/allimg/131009/1-131009140T1.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/131009/1-131009140T3-lp.jpg' text='' width='376' height='304'} /upload/allimg/131009/1-131009140T3.jpg {/gemel:img}
