{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140620/1-1406201KF4-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201KF4.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201KG7-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201KG7.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201KH2-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201KH2.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201KH7-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201KH7.jpg {/gemel:img}
