<li>
                            <a href="[field:arcurl/]"><img src="[field:pro_related/]" alt="[field:typename/] - [field:title/]" title="[field:typename/] - [field:title/]" width="260" height="260" />
                                                             <span>[field:title/]</span>
                                
                            </a>
                           
                        </li>