<li>
                    <a href="[field:arcurl/]" class="news_con_img"><img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" /></a>
                    <div class="news_con_right">
                        <p class="news_con_tit"><a href="[field:arcurl/]">[field:title/]([field:pubdate function="MyDate('Y-m-d',@me)"/])</a></p>
                        <p class="news_con_profile">为切实贯彻公司战略升级工作方针要求，2013年6月18日，锂电事业部组织全体一线并要求沿着行业领袖企业、全球畅销20年的富士达品牌建设路线，不断让部门员工分享企业发展所带至的荣誉感和幸福感从而提升员工自信快乐工</p>
                        <a class="news_more" href="[field:arcurl/]"></a>
                    </div>
                </li>