<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/170413/tt187-01.jpg-50 ",96,237);
$z[1][4]['ddimg']="/upload/allimg/170413/tt187-01.jpg-50";
$z[1][4]['text']="";
$z[1][4]['width']="550";
$z[1][4]['height']="500";
$z[2]=Array("img"," /upload/allimg/170413/tt187-02.jpg-50 ",239,380);
$z[2][4]['ddimg']="/upload/allimg/170413/tt187-02.jpg-50";
$z[2][4]['text']="";
$z[2][4]['width']="550";
$z[2][4]['height']="500";
$z[3]=Array("img"," /upload/allimg/170413/tt187-03.jpg-50 ",382,523);
$z[3][4]['ddimg']="/upload/allimg/170413/tt187-03.jpg-50";
$z[3][4]['text']="";
$z[3][4]['width']="550";
$z[3][4]['height']="500";
$z[4]=Array("img"," /upload/allimg/170413/tt187-04.jpg-50 ",525,666);
$z[4][4]['ddimg']="/upload/allimg/170413/tt187-04.jpg-50";
$z[4][4]['text']="";
$z[4][4]['width']="550";
$z[4][4]['height']="500";

?>