<?php
$z[0]=Array("noteinfo","",2,161);
$z[0][4]['notename']="文章测试";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {gemel:addurls}http://www.chinaz.com/news/roll/{/gemel:addurls}\r\n    {gemel:batchrule}{/gemel:batchrule}\r\n    {gemel:regxrule}{/gemel:regxrule}\r\n    {gemel:areastart}<div class=\"news_list\">{/gemel:areastart}\r\n    {gemel:areaend}<ul class=\"pageul\">{/gemel:areaend}\r\n",165,596);
$z[1][4]['sourcetype']="hand";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://";
$z[1][4]['startid']="1";
$z[1][4]['endid']="";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="shtml";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>