<li>
                             <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="298" height="450" /></a>
                             <div class="product-specifications">
                                   
                             </div>
                             <h3><a href="[field:arcurl/]">[field:shorttitle/]</a></h3>
                             <em></em>
                        </li>