<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/140620/1-1406201G438.jpg ",96,244);
$z[1][4]['ddimg']="/upload/allimg/140620/1-1406201G438-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="734";
$z[1][4]['height']="321";
$z[2]=Array("img"," /upload/allimg/140620/1-1406201G445.jpg ",246,394);
$z[2][4]['ddimg']="/upload/allimg/140620/1-1406201G445-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="734";
$z[2][4]['height']="321";
$z[3]=Array("img"," /upload/allimg/140620/1-1406201G448.jpg ",396,544);
$z[3][4]['ddimg']="/upload/allimg/140620/1-1406201G448-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="734";
$z[3][4]['height']="321";
$z[4]=Array("img"," /upload/allimg/140620/1-1406201G452.jpg ",546,694);
$z[4][4]['ddimg']="/upload/allimg/140620/1-1406201G452-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="734";
$z[4][4]['height']="321";

?>