<li>
                  <div class="box_left">
                       <a href="[field:typelink/]"><img src="/images/home-product-01.jpg" title="[field:typename/]" alt="[field:typename/]" width="243" height="164" /></a>
                  </div>
                  <div class="box_right">
                       <h3><a href="[field:typelink/]">[field:typename/]</a></h3>
                       <p>[field:description function='cn_substrR(html2text(@me),40)'/]....</p> 
                       <span><a href="[field:typelink/]">View more</a></span>  
                  </div>                        
             </li>