<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:pro_info itemname="简介参数" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pro_info>
<field:pro_application itemname="应用领域" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pro_application>
<field:pro_detail itemname="详细参数" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:pro_detail>
