<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>

<field:wire_download itemname="PDF地址" autofield="1" notsend="0" type="addon" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wire_download>

<field:wire_pin_img itemname="Pin contact(Img)" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wire_pin_img>

<field:wire_pin_text itemname="Pin contact(Text）" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wire_pin_text>


<field:wire_socket_img itemname="Socket contact(Img)" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wire_socket_img>


<field:wire_socket_text itemname="Socket contact(Text)" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wire_socket_text>


<field:wire_receptacle_img itemname="Receptacle housing（Img）" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wire_receptacle_img>

<field:wire_receptacle_text itemname="Receptacle housing(Text)" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wire_receptacle_text>

<field:wire_plug_img itemname="Plug housing(Img)" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wire_plug_img>

<field:wire_plug_text itemname="Plug housing(Text)" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wire_plug_text>
