<?php
$z[0]=Array("field","",69,98);
$z[0][4]['name']="typepic";
$z[1]=Array("field","",105,135);
$z[1][4]['name']="typename";
$z[2]=Array("field","",144,174);
$z[2][4]['name']="typename";
$z[3]=Array("field","",235,265);
$z[3][4]['name']="typename";
$z[4]=Array("field","",310,339);
$z[4][4]['name']="content";
$z[5]=Array("global","@me=2",375,437);
$z[5][4]['name']="itemindex";
$z[5][4]['runphp']="no";

?>