<li>
                    <a href="[field:typelink/]"><img src="/images/home-pro-02.jpg" title="Portable UPS power supply" alt="Portable UPS power supply" width="278" height="270" /></a>
                    <div class="title">
                          <div class="left">
                                <h2><a href="[field:typelink/]">Portable <br/>UPS power supply</a></h2>
                          </div>
                          <a href="[field:typelink/]"><em></em></a>
                    </div>
               </li>