<?php
$z[0]=Array("$key++","\r\n						<div class=\"pro_list\">\r\n							<img src=\"{gemel:field name='typepic'",0,92);
$z[1]=Array("field","",99,129);
$z[1][4]['name']="typename";
$z[2]=Array("field","",138,168);
$z[2][4]['name']="typename";
$z[3]=Array("field","",229,259);
$z[3][4]['name']="typename";
$z[4]=Array("field","",304,333);
$z[4][4]['name']="content";
$z[5]=Array("global","",369,427);
$z[5][4]['name']="itemindex";
$z[5][4]['runphp']="yes";

?>