<li>
                    <div class="video">
                          <iframe width="626" height="420" src="https://www.youtube.com/embed/mhMyK6GIenc" frameborder="0" allowfullscreen></iframe> 
                    </div>
                    <div class="video-title">
                          <div class="middle">
                                <div class="linner">
                                      <h3>How to add hot fix rhinestone to a t-shirt with aplicator</h3>
                                </div>
                          </div>
                    </div>
               </li>