<?php
$z[0]=Array("arcurl","",86,101);
$z[1]=Array("litpic","",113,128);
$z[2]=Array("typename","",137,154);
$z[3]=Array("title","",157,171);
$z[4]=Array("typename","",178,195);
$z[5]=Array("title","",198,212);
$z[6]=Array("arcurl","",363,378);
$z[7]=Array("shorttitle","",380,399);
$z[8]=Array("arcurl","",451,466);
$z[9]=Array("typename","",475,492);
$z[10]=Array("title","",495,509);
$z[11]=Array("title","",511,525);
$z[12]=Array("arcurl","",573,588);
$z[13]=Array("typename","",597,614);
$z[14]=Array("title","",617,631);

?>