<li>
                  <div class="box_left">
                       <a href=""><img src="/images/home-product-04.jpg" title="[field:typename/]" alt="[field:typename/]" width="243" height="164" /></a>
                  </div>
                  <div class="box_right">
                       <h3><a href="[field:typelink/]">[field:typename/]</a></h3>
                       <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh </p> 
                       <span><a href="[field:typelink/]">View more</a></span>  
                  </div>                        
             </li>