{gemel:field name='keywords'}站长之家, 马云, 王健林{/gemel:field}
{gemel:field name='description'}今日晚间，阿里巴巴集团董事局主席马云、阿里巴巴集团CEO陆兆禧到天猫双11发布会现场与媒体进行沟通。{/gemel:field}
{gemel:field name='title'}马云：如果王健林赢了 等于这个社会输了{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131112/13T22151A04Z-24950.jpg" border="0" /></p>
<p><strong>腾讯科技讯</strong>（王可心）11月11日消息，今日晚间，阿里巴巴集团董事局主席马云、阿里巴巴集团CEO陆兆禧到天猫双11发布会现场与媒体进行沟通。</p>
<p>马云在现场谈到和万达集团董事长王健林1亿元对赌时称：&ldquo;如果王健林赢了，那么是整个社会输了，是这一代年轻人输了。&rdquo;</p>
<p>在2012年初的CCTV经济年度人物颁奖盛典上，马云和王健林等就&ldquo;10年后电商在中国零售市场份额能否过半&rdquo;设下1亿元赌局。</p>
<p>马云今日称，如果十年后房地产仍占半壁江山，说明这一代人的努力不如上一代人。</p>
<p>&ldquo;今年双11数字，不管是300亿还是350亿，一定会对商业地产的老板有震撼。现在很多商场里的服务员比顾客多。企业家很聪明，当产业升级、网购起来后，不会把商业区作为重要投资，边上的居民区成本也会降下来，让中国物价通过市场手法调节。&rdquo;</p>
<p>对于今年双11可能达成的交易额目标，马云表示300亿不是悬念，未来1000亿也不是做不到。&ldquo;即使有一年双11做到1000亿，也希望是自然健康的结果，而不是追求的目标。健康更重要，而不是冲多少数字。&rdquo;马云说。</p>
<p>马云还表示，双11会继续做下去，现在已经是中国消费者的节日，不会轻易成&ldquo;绝唱&rdquo;。</p>
<p>对于阿里巴巴集团在哪里IPO的问题，马云称：&ldquo;IPO不是今天讨论的问题。我们自己也不知道。&rdquo;</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131112/13T22151A04Z-24950_lit.jpg{/gemel:field}
