<li>
            <a href="{gemel:field.typeurl/}">{gemel:field.typename/}
            <em>&nbsp;</em></a>
            <div class="pro-list-son">
                <ul>
                {gemel:arclist orderby='weight' titlelen='40' row='6' channelid='2'}
                    <li><a href="[field:arcurl/]">[field:title/]</a></li>
                    {/gemel:arclist}
                </ul>
            </div>

            </li>