<tr>
                        <td width="460"><a href="[field:arcurl/]">[field:title/]</a></td>
                        <td align="center" width="200">[field:pubdate function="MyDate('Y-m-d',@me)"/]</td>
                        <td align="center" width="70">：<span id="vvclick">载入中...</span><span style="display:none" id="span_vvclick">{gemel:field name='click'/}</span></td>
                        
                    </tr>