{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140528/1-14052PZ600-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PZ600.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PZ601-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PZ601.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PZ602-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PZ602.jpg {/gemel:img}
