{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/151221/kbq-603-1-lp.png' text='' width='540' height='670'} /upload/allimg/151221/kbq-603-1.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151221/kbq-603-2-lp.png' text='' width='540' height='670'} /upload/allimg/151221/kbq-603-2.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151221/kbq-603-3-lp.png' text='' width='540' height='670'} /upload/allimg/151221/kbq-603-3.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151221/kbq-603-4-lp.png' text='' width='540' height='670'} /upload/allimg/151221/kbq-603-4.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151221/kbq-603-5-lp.png' text='' width='540' height='670'} /upload/allimg/151221/kbq-603-5.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151221/kbq-603-6-lp.png' text='' width='540' height='670'} /upload/allimg/151221/kbq-603-6.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151221/kbq-603-7-lp.png' text='' width='540' height='670'} /upload/allimg/151221/kbq-603-7.png {/gemel:img}
