{gemel:field name='keywords'}站长之家, 双十一, 爆仓{/gemel:field}
{gemel:field name='description'}“双十一”网购热潮带来的数以万计的快件陆续投放至广州市圆通、中通、申通、汇通和韵达等多家快递公司的快件分拣站，快递业全员上阵迎战送货高峰。国家邮政局预计，该次购{/gemel:field}
{gemel:field name='title'}“双十一”快递迎高峰 包裹预超3.23亿件{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
