<?php
$z[0]=Array("field","站长之家, 双十一, 爆仓",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","“双十一”网购热潮带来的数以万计的快件陆续投放至广州市圆通、中通、申通、汇通和韵达等多家快递公司的快件分拣站，快递业全员上阵迎战送货高峰。国家邮政局预计，该次购",72,354);
$z[1][4]['name']="description";
$z[2]=Array("field","“双十一”快递迎高峰 包裹预超3.23亿件",356,445);
$z[2][4]['name']="title";
$z[3]=Array("field","",447,484);
$z[3][4]['name']="writer";
$z[4]=Array("field","",486,523);
$z[4][4]['name']="source";
$z[5]=Array("field","",525,560);
$z[5][4]['name']="body";
$z[6]=Array("field","",562,600);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",602,639);
$z[7][4]['name']="litpic";

?>