{gemel:field name='keywords'}站长之家, 短视频, Line新版{/gemel:field}
{gemel:field name='description'}通讯应用Line新版今日上线，新增“视频通话”、短视频分享“微片”、好友可共同管理的“相册”等功能。{/gemel:field}
{gemel:field name='title'}Line新版上线 添加短视频分享“微片”功能{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130925/13P0S05b5440-36230.jpg" border="0" width="531" alt="Line新版上线 添加短视频分享&ldquo;微片&rdquo;功能" height="464" /></p>
<p style="text-align: center;">Line新版添加视频通话功能</p>
<p>腾讯科技讯（王鑫）9月24日消息，通讯应用Line新版今日上线，新增&ldquo;视频通话&rdquo;、短视频分享&ldquo;微片&rdquo;、好友可共同管理的&ldquo;相册&rdquo;等功能。</p>
<p>Line此前功能中已拥有语音通话功能，新上线的视频通话则在语音之外，进一步满足了用户之间的视频交流需求。目前iOS、Android和PC版用户之间，都可以进行&ldquo;面对面&rdquo;的通话。</p>
<p>新版本中的&ldquo;微片&rdquo;功能意味着Line也正式加入了短视频分享战场。用户在聊天和动态消息中选择&ldquo;微片&rdquo;后，可拍摄4秒至10秒内的短视频进行分享。该功能比较有趣的地方在于，Line提供了9种类型的视频背景音乐供用户选择，用户可以选择其一添加到视频中，以降低视频的单调感。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130925/13P0S06011940-4L57.jpg" border="0" width="550" alt="Line新版上线 添加短视频分享&ldquo;微片&rdquo;功能" height="482" /></p>
<p style="text-align: center;">新版本中的&ldquo;微片&rdquo;功能，可添加背景音乐</p>
<p>在今年8月份召开的Line企业年会上，该公司曾宣布，在下半年推出的新产品中，除了视频通话服务外，还包括数字音乐服务Line Music和电商服务Line Mall。这两大产品将成为Line下一步值得关注的动向。</p>
<p>据8月公布的数据，Line全球用户数已达到2.3亿，其中，日本用户占20%，海外用户占比80%。公司第二季度财报显示，Line应用平台贡献的收入为1.01亿美元，占比达到76%。其中，Line平台的收入中，游戏收入占到53%，付费贴纸收入占27%，而企业赞助类的收入达到20%。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130925/13P0S05b5440-36230_lit.jpg{/gemel:field}
