<li>
                     <a href="[field:arcurl/]"><img src="[field:new_home/]" title="[field:title/]" alt="[field:title/]" width="120" height="120" /></a>
                     <div class="content">
                           <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
                           <p>[field:description function='cn_substrR(html2text(@me),50)'/]..</p>
                           <span><a href="[field:arcurl/]">View More</a></span>
                     </div>
                </li>