<tr>
                           <td><a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="150" height="104" /></a></td>
                           <td>[field:shorttitle/]</td>
                           <td>[field:ac_ups/]</td>
                           <td>[field:dc_ups/]</td>
                           <td>[field:battery_ups/]</td>
                           <td>[field:solar_panel_ups/]</td>                         
                      </tr>