<?php
$z[0]=Array("typelink","",58,75);
$z[1]=Array("typename","",77,94);
$z[2]=Array("sonchannel1","\r\n                                    <li class=\"c2\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                        [field:sonchannel2]\r\n                                        <li class=\"c3\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                            [field:sonchannel3]\r\n                                            <li class=\"c4\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                            [/field:sonchannel3]\r\n                                        [/field:sonchannel2]\r\n                                    ",141,805);

?>