<?php
$z[0]=Array("field","",58,80);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",82,105);
$z[1][4]['name']="typename";
$z[2]=Array("field","",182,204);
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",216,238);
$z[3][4]['name']="typepic";
$z[4]=Array("field","",247,270);
$z[4][4]['name']="typename";
$z[5]=Array("field","",277,300);
$z[5][4]['name']="typename";
$z[6]=Array("arclist","                   \r\n                        <li>\r\n                             <a href=\"[field:arcurl/]\"><img src=\"/images/01.jpg\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"178\" height=\"172\" /></a>\r\n                             <p><a href=\"[field:arcurl/]\"> [field:shorttitle/]</a></p>\r\n                        </li>\r\n                        ",454,869);
$z[6][4]['orderby']="weight";
$z[6][4]['titlelen']="100";
$z[7]=Array("field","",943,965);
$z[7][4]['name']="typeurl";

?>