{gemel:field name='keywords'}站长之家, 阿里旺旺, 京东{/gemel:field}
{gemel:field name='description'}京东今日对外发布其针对个人用户的免费IM通讯工具——京东咚咚，用户在京东购物时可使用这款软件实现即时沟通。{/gemel:field}
{gemel:field name='title'}京东正式发布IM工具咚咚 定位类似于阿里旺旺{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p><strong>腾讯科技讯</strong>（乐天）1月2日消息，京东今日对外发布其针对个人用户的免费IM通讯工具&mdash;&mdash;京东咚咚，用户在京东购物时可使用这款软件实现即时沟通。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c140103/13XG5U03W60-4F93.jpg" border="0" /></p>
<p>京东人士指出，京东咚咚客户端增加了加好友、群聊、截图、发送文件等功能。视觉方面，采用扁平化风格，表情和头像根据京东特色而设计，并支持用户设置个性昵称和设置特色头像。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c140103/13XG5U10P60-59240.png" border="0" /></p>
<p style="text-align: center;">聊天窗口展示品牌畅销商品信息</p>
<p>在操作上，点击&ldquo;添加&rdquo;按钮，可加入自己的朋友进行私聊或群聊；在购物交易中，有任何疑问需要联系客服时，点击商家页面的在线客服，客服MM可与用户沟通。在聊天同时可以查看店铺信息、咨询的商品信息、品牌畅销商品信息，并可以将咨询的商品加入购物车。</p>
<p>阿里数年前将原来的淘宝旺旺与阿里巴巴贸易通整合，推出即时通信产品阿里旺旺，曾试图挑战QQ即时通信地位。如今阿里旺旺主要服务于阿里巴巴B2B、淘宝、天猫上的买家和买家。</p>
<p>京东咚咚延续阿里旺旺这一定位，据内部人士透露，京东已从综合电商变成产业链整合者，随着京东开放平台做大，京东为方便卖家沟通，推出京东咚咚是顺势之举。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c140103/13XG5U03W60-4F93_lit.jpg{/gemel:field}
