<li class="clear">

            <a href="[field:arcurl/]" class="news-img">
                <img src="[field:litpic/]" width="380" height="240" alt="[field:title/]" title="[field:title/]">
            </a>
                <div class="news-info">
                    <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
                    <p>[field:description function='cn_substrR(html2text(@me),100)'/]..</p>
                    <a href="[field:arcurl/]" class="more">VIEW MORE</a>
                </div>
            </li>