<tr>
                           <td><a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="150" height="104" /></a></td>
                           <td>[field:shorttitle/]</td>
                           <td>[field:working_current_c/]</td>
                           <td>[field:size_c/]</td>
                           <td>[field:application_c/]</td>
                           <td>[field:certification_c/]</td>
                      </tr>