<?php
$z[0]=Array("pagestyle","",0,92);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/131009/1-131009140P6.jpg ",94,238);
$z[1][4]['ddimg']="/upload/allimg/131009/1-131009140P6-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="379";
$z[1][4]['height']="244";
$z[2]=Array("img"," /upload/allimg/131009/1-131009140P8.jpg ",240,384);
$z[2][4]['ddimg']="/upload/allimg/131009/1-131009140P8-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="376";
$z[2][4]['height']="304";
$z[3]=Array("img"," /upload/allimg/131009/1-131009140Q0.jpg ",386,530);
$z[3][4]['ddimg']="/upload/allimg/131009/1-131009140Q0-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="518";
$z[3][4]['height']="359";

?>