
                        <li>
                            <a href="[field:link/]">
                                <img src="[field:pic/]" width="1600" height="670" alt="[field:text/]" title="[field:text/]">
                                 <div class="banner-text">
                                    <p>WHAT WE CAN DO?</p>
                                    <h2>SPRING WIRE</h2>
                                </div>
                            </a>
                        </li>
                        