<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/170607/globe-ball-lamp-for-ceiling-lights-c3-02.jpg ",96,298);
$z[1][4]['ddimg']="/upload/allimg/170607/globe-ball-lamp-for-ceiling-lights-c3-02-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="480";
$z[1][4]['height']="450";

?>