<?php
$z[0]=Array("arclist","\r\n                    <div class=\"indexpro_img\">\r\n                        <a href=\"jacascrit:viod(0);\">\r\n                        <img src=\"[field:litpic/]\" width=\"217\" height=\"120\" title=\"[field:title/]\" alt=\"[field:title/]\"/>\r\n                        </a>\r\n                    </div>\r\n                    ",26,394);
$z[0][4]['titlelen']="38";
$z[0][4]['row']="1";
$z[0][4]['flag']="c";
$z[1]=Array("field","",425,454);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",478,508);
$z[2][4]['name']="typename";

?>