<li>
                    {gemel:arclist titlelen='38' row='1' flag='c'}
                    <div class="indexpro_img">
                        <a href="jacascrit:viod(0);">
                        <img src="[field:litpic/]" width="217" height="120" title="[field:title/]" alt="[field:title/]"/>
                        </a>
                    </div>
                    {/gemel:arclist}
                    <a href="{gemel:field name='typeurl'/}" class="indexpro_text">{gemel:field name='typename'/}</a>
                </li>