{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140620/1-1406201QH3-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201QH3.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201QH7-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201QH7.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201QH9-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201QH9.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201QI2-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201QI2.jpg {/gemel:img}
