<?php
$z[0]=Array("pagestyle","",0,92);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/131008/1-13100Q41316.jpg ",94,238);
$z[1][4]['ddimg']="/upload/allimg/131008/1-13100Q41316-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="205";
$z[1][4]['height']="150";
$z[2]=Array("img"," /upload/allimg/131008/1-13100Q41319.jpg ",240,384);
$z[2][4]['ddimg']="/upload/allimg/131008/1-13100Q41319-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="205";
$z[2][4]['height']="150";
$z[3]=Array("img"," /upload/allimg/131008/1-13100Q41330.jpg ",386,530);
$z[3][4]['ddimg']="/upload/allimg/131008/1-13100Q41330-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="205";
$z[3][4]['height']="150";
$z[4]=Array("img"," /upload/allimg/131008/1-13100Q41337.jpg ",532,676);
$z[4][4]['ddimg']="/upload/allimg/131008/1-13100Q41337-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="205";
$z[4][4]['height']="150";

?>