{gemel:field name='keywords'}站长之家, 网络违法, 无资{/gemel:field}
{gemel:field name='description'}为大力整治网络秩序，切实维护广大群众切身利益，营造安全文明的网络环境，安徽省公安机关自今年6月以来，开展集中打击整治网络违法犯罪专项行动，严厉打击网络诈骗、黑客{/gemel:field}
{gemel:field name='title'}安徽清理513家无资质网站{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p>本报合肥9月22日电&nbsp;&nbsp;（记者叶琦）为大力整治网络秩序，切实维护广大群众切身利益，营造安全文明的网络环境，安徽省公安机关自今年6月以来，开展集中打击整治网络违法犯罪专项行动，严厉打击网络诈骗、黑客攻击破坏、侵害公民个人信息、涉枪涉爆、网络赌博等违法犯罪活动，专项行动目前取得显著成效。</p>
<p>据统计，安徽省截至目前累计已查破涉网刑事案件381起，打掉犯罪团伙29个；清理缺乏开办资质的网站513家；依据网络管理有关行政法规警告处罚网站19家，责令限期整改97家，停机整顿2家，停业7家，违法信息数量7、8月份同比分别下降36%和48%。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
