{gemel:field name='keywords'}站长之家, 淘宝理财, 国华{/gemel:field}
{gemel:field name='description'}天猫1111购物狂欢节24点整宣告结束，全天成交量为350亿元。首次加入双十一的淘宝理财，也交出一份漂亮的答卷，总成交金额为9.08亿元。{/gemel:field}
{gemel:field name='title'}淘宝理财交答卷: 成交超9亿元 3家理财店铺过亿{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p><img class="flag_bigP" src="/upload/allimg/c131112/13T22151SLZ-13J7.jpg" border="0" alt="" align="middle" style="border: 0px; margin: 0px auto; padding: 0px; font-size: 0px; color: transparent; display: block;" /></p>
<p>【搜狐IT消息】（张睿）天猫1111购物狂欢节24点整宣告结束，全天成交量为350亿元。首次加入双十一的淘宝理财，也交出一份漂亮的答卷，总成交金额为9.08亿元。</p>
<p>今年天猫双十一总计9家店铺销售额过亿，远超去年的3家。尤其值得一提的是，9家店铺中包含3家理财店铺，分别是国华人寿、易方达基金和生命人寿。</p>
<p>截至11日24时，国华人寿官方旗舰店成交额为5.31亿元，易方达基金官方旗舰店为2.11亿元，生命人寿官方旗舰店为1.01亿元。</p>
<p>其他排名靠前的理财店铺有：华夏人寿旗舰店3000万元；珠江人寿旗舰店2000万元；阳光人寿旗舰店1000万元。</p>
<p>从单款产品销售额上看，国华人寿华瑞2号拔得头筹，销售额达到4.6亿元，易方达聚盈A排名第二为2.1亿元。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131112/13T22151SLZ-13J7_lit.jpg{/gemel:field}
