<?php
$z[0]=Array("field","站长之家, 淘宝理财, 国华",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","天猫1111购物狂欢节24点整宣告结束，全天成交量为350亿元。首次加入双十一的淘宝理财，也交出一份漂亮的答卷，总成交金额为9.08亿元。",75,298);
$z[1][4]['name']="description";
$z[2]=Array("field","淘宝理财交答卷: 成交超9亿元 3家理财店铺过亿",300,398);
$z[2][4]['name']="title";
$z[3]=Array("field","",400,437);
$z[3][4]['name']="writer";
$z[4]=Array("field","",439,476);
$z[4][4]['name']="source";
$z[5]=Array("field","<p style=\"text-align:center;\">          </p>\n                                                            <p><img class=\"flag_bigP\" src=\"/upload/allimg/c131112/13T22151SLZ-13J7.jpg\" border=\"0\" alt=\"\" align=\"middle\" style=\"border: 0px; margin: 0px auto; padding: 0px; font-size: 0px; color: transparent; display: block;\" /></p>\n<p>【搜狐IT消息】（张睿）天猫1111购物狂欢节24点整宣告结束，全天成交量为350亿元。首次加入双十一的淘宝理财，也交出一份漂亮的答卷，总成交金额为9.08亿元。</p>\n<p>今年天猫双十一总计9家店铺销售额过亿，远超去年的3家。尤其值得一提的是，9家店铺中包含3家理财店铺，分别是国华人寿、易方达基金和生命人寿。</p>\n<p>截至11日24时，国华人寿官方旗舰店成交额为5.31亿元，易方达基金官方旗舰店为2.11亿元，生命人寿官方旗舰店为1.01亿元。</p>\n<p>其他排名靠前的理财店铺有：华夏人寿旗舰店3000万元；珠江人寿旗舰店2000万元；阳光人寿旗舰店1000万元。</p>\n<p>从单款产品销售额上看，国华人寿华瑞2号拔得头筹，销售额达到4.6亿元，易方达聚盈A排名第二为2.1亿元。</p>",478,1731);
$z[5][4]['name']="body";
$z[6]=Array("field","",1733,1771);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/upload/allimg/c131112/13T22151SLZ-13J7_lit.jpg",1773,1857);
$z[7][4]['name']="litpic";

?>