<li>
            <p class="case_list_img"><a href="[field:arcurl/]"><img src="[field:litpic/]" onload="zoomimg(209,152,this)" /></a></p>
            <a href="[field:arcurl/]" class="case_list_text">[field:title/]</a>
            <p class="case_list_des">[field:description function='cn_substrR(html2text(@me),80)'/]</p>
            <a href="[field:arcurl/]" class="case_list_more">详细 >>></a>
            </li>