<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/150724/mall-cosmetic-showcase-01.jpg ",96,269);
$z[1][4]['ddimg']="/upload/allimg/150724/mall-cosmetic-showcase-01-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1040";
$z[1][4]['height']="498";
$z[2]=Array("img"," /upload/allimg/150724/mall-cosmetic-showcase-02.jpg ",271,444);
$z[2][4]['ddimg']="/upload/allimg/150724/mall-cosmetic-showcase-02-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1040";
$z[2][4]['height']="498";

?>