<li>
                       <a href="[field:arcurl /]"><img src="[field:hot_img /]" title="[field:title /]" alt="[field:title /]" width="336" height="314" /></a>
                       <div class="con">
                             <em class="up">&nbsp;</em>
                             <h2><a href="[field:arcurl /]">[field:title /]</a></h2>
                             <h3><a href="[field:arcurl /]">[field:shorttitle /]</a></h3>
                             <em class="cn">&nbsp;</em>
                             <span><a href="[field:arcurl /]">Read more</a></span>
                       </div>
                  </li>