<?php
$z[0]=Array("field","",37,60);
$z[0][4]['name']="typename";
$z[1]=Array("field","",82,104);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",106,129);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","                                      \r\n                 <li>\r\n                     <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"384\" height=\"287\" /></a>\r\n                     <p><a href=\"[field:arcurl/]\">[field:shorttitle/]</a></p>\r\n                 </li>\r\n                 ",194,599);
$z[3][4]['orderby']="weight";
$z[3][4]['titlelen']="40";
$z[3][4]['row']="10";

?>