{gemel:field name='keywords'}站长之家, 高考题库, 猿题{/gemel:field}
{gemel:field name='description'}在线教育领域有个共识，就是职业教育容易做，中小学教育难做，但实情可能是大家都错了。一个月前，猿题库宣布推出高考产品，该题库是针对高三学生的高考题库产品，定价为每{/gemel:field}
{gemel:field name='title'}猿题库免费策略 要切下10%的高考市场{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center;"><img src="/upload/allimg/c131106/13SI0U220220-1WD.jpg" border="0" /></p>
<p>文/王聪佶</p>
<p>在线教育领域有个共识，就是职业教育容易做，中小学教育难做，但实情可能是大家都错了。一个月前，猿题库宣布推出高考产品，该题库是针对高三学生的高考题库产品，定价为每月18元，拥有网页版和移动设备应用。在40天内，猿题库用户到了3万人，覆盖了28个省市自治区的6623所中学的高考考生。</p>
<p>初期成绩不错，让猿题库对高考市场有了新的理解，那么，未来猿题库将进行哪些策略调整？以下是笔者采访猿题库创始人李勇获得的信息：</p>
<p><strong style="border: 0px; margin: 0px; padding: 0px; font-size: 14px; font-weight: bold;">1.高考市场这么大，猿题库还是免费好了。</strong>猿题库创始人李勇表示，我们都低估了高中生市场，这样巨大的市场，收入并不重要，我们还是免费好了。</p>
<p>猿题库宣布，自11月6日起，高考题库全部免费，并将为所有已付费用户办理全额退费。</p>
<p><strong style="border: 0px; margin: 0px; padding: 0px; font-size: 14px; font-weight: bold;">2.猿题库是试水产品，因为低估了移动互联网对高中生影响。</strong>根据猿题库获得信息，猿题库产品上线40天，已经覆盖6623所学生，用户数量达到3万人。移动端用户比重为93.9%，其中Android用户为75%，iPhone用户为15.1%，iPad用户占比为2.9%。在个别地方，比如广东，猿题库覆盖了全省863所高中的834所。</p>
<p>猿题库自己做了一个粗略的估算，最终结果很有趣：目前60%的高三学生拥有智能手机。李勇表示猿题库高考其实是他们试水的一个产品，并不确定做中小学产品是否成熟，但是产品推出后结果超出预期。</p>
<p><strong style="border: 0px; margin: 0px; padding: 0px; font-size: 14px; font-weight: bold;">3.猿题库明年目标用户是100万人。</strong>李勇估算，在付费的情况下，一个月内用户能达到3万人，免费之后，每个月成长10万用户应该没问题。所以猿题库明年的目标用户数为100万人，周活跃用户为50万人。可以参考对比的是今年高考人数为907万，李勇表示，如能达成目标，明年猿题库将覆盖明年至少10%的高考学生。</p>
<p>另外，猿题库还将在明年推出针对高一高二学生的题库，同样采用免费策略。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131106/13SI0U220220-1WD_lit.jpg{/gemel:field}
