{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140528/1-14052PZJ9-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PZJ9.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PZK0-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PZK0.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PZK2-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PZK2.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PZK3-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PZK3.jpg {/gemel:img}
