
                    <div class="moudle_about">
                        <div class="moudle_img"><img src="[field:typepic/]" /></div>
                        <a class="moudle_url" href="[field:typeurl/]">
                            <span class="moudle_tit">[field:typename/]</span><br />
                            <span class="moudle_seo">[field:seotitle/]</span>
                        </a>
                        <div class="moudle_des">[field:description function='cn_substrR(html2text(@me),120)'/]...</div>
                    </div>
                    