{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/170714/hollow-fiber-filter-01-lp.jpg' text='' width='530' height='450'} /upload/allimg/170714/hollow-fiber-filter-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170714/hollow-fiber-filter-02-lp.jpg' text='' width='530' height='450'} /upload/allimg/170714/hollow-fiber-filter-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170714/hollow-fiber-filter-03-lp.jpg' text='' width='530' height='450'} /upload/allimg/170714/hollow-fiber-filter-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170714/hollow-fiber-filter-04-lp.jpg' text='' width='530' height='450'} /upload/allimg/170714/hollow-fiber-filter-04.jpg {/gemel:img}
