{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/151030/b2197-01-lp.png' text='' width='870' height='555'} /upload/allimg/151030/b2197-01.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151030/b2197-02-lp.png' text='' width='870' height='555'} /upload/allimg/151030/b2197-02.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151030/b2197-03-lp.png' text='' width='870' height='555'} /upload/allimg/151030/b2197-03.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151030/b2197-04-lp.png' text='' width='870' height='555'} /upload/allimg/151030/b2197-04.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151030/b2197-05-lp.png' text='' width='870' height='555'} /upload/allimg/151030/b2197-05.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151030/b2197-06-lp.png' text='' width='870' height='555'} /upload/allimg/151030/b2197-06.png {/gemel:img}
