<li>
            <h4>
              <span>.</span>
              <a href='{gemel:field.typeurl/}'>{gemel:field.typename/}</a>
              <em>&nbsp;</em>
            </h4>
            <div class="three-sort">
              {gemel:channel type='onlyson'}
              <p>
                <a href="[field:typeurl/]">[field:typename/]</a>
              </p>
              {/gemel:channel}
            </div>
        </li>