{/gemel:}
					<li>
						<div class="pro_list">
							<img src="/upload/team/team-pic-01.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation1</h1>
								<p>box-product</p>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-02.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation2</h1>
								<p>box-product</p>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-03.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation3</h1>
								<p>box-product</p>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-01.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation4</h1>
								<p>box-product</p>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-02.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation5</h1>
								<p>box-product</p>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-03.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation6</h1>
								<p>box-product</p>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-01.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation7</h1>
								<p>box-product</p>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-02.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation8</h1>
								<p>box-product</p>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-03.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation9</h1>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
					</li>
					<li>
						<div class="pro_list">
							<img src="/upload/team/team-pic-01.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation10</h1>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-02.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation11</h1>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-03.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation12</h1>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-01.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation13</h1>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-02.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation14</h1>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-03.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation15</h1>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-01.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation16</h1>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-02.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation17</h1>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
						<div class="pro_list">
							<img src="/upload/team/team-pic-03.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">Youdao translation</a>
							<div class="pro_info">
								<h1>Youdao translation18</h1>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>
					</li>
				</ul>
			</div>
		</div>
		<ul class="list_nav"></ul>
	</div>
	<div class="box_bg3">
		<div class="contact_main main_width clearfix">
			<div class="contact_left">
				<h1>CONTACT</h1>
				<p>Address: Bldg, B, Cha Bridge Park, BaoLong 6th Road., BaoLong Ind. Zone, LongGang, ShenZhen, P.R.China.</p>
				<p>Shanghai Branch Address: RM.1108A, NO.1759, North Zhongshan RD., Shanghai, China</p>
			</div>
			<div class="contact_right">
				<ul>
					<li><span>TEL: </span>0755-29176570</li>
					<li><span>Fax: </span>0755-29176570</li>
					<li class="contact_icon1"><span>Email: </span><a href="mailto:sales@yingxiaoli.com" title="Send email">sales@yingxiaoli.com</a></li>
					<li class="contact_icon2"><span>MSN: </span>Mr.Chen@yingxiaoli.com</li>
					<li class="contact_icon3"><span>Skype: </span>Mr.Chen</li>
					<li><span>Contact Person: </span>MR.Chen(General Manager)</li>
				</ul>
			</div>
		</div>
	</div>

	<!-- 弹出内容框 -->
	<div class="box_shade"></div>
	<div class="box_main">
		<div class="box_left">
			<div class="pro_bd">
				<div class="tempWrap">
					<ul>
						<li><img src="/upload/products/box-product-01.jpg" width="865" height="600" /></li>
						<li><img src="/upload/products/box-product-01.jpg" width="865" height="600" /></li>
						<li><img src="/upload/products/box-product-01.jpg" width="865" height="600" /></li>
						<li><img src="/upload/products/box-product-01.jpg" width="865" height="600" /></li>
						<li><img src="/upload/products/box-product-01.jpg" width="865" height="600" /></li>
					</ul>
				</div>
			</div>
			<div class="hd pro_s">
				<ul class="clearfix">
					<li><img src="/upload/products/box-product-s-01.jpg" width="83" height="83" /></li>
					<li><img src="/upload/products/box-product-s-01.jpg" width="83" height="83" /></li>
					<li><img src="/upload/products/box-product-s-01.jpg" width="83" height="83" /></li>
					<li><img src="/upload/products/box-product-s-01.jpg" width="83" height="83" /></li>
					<li><img src="/upload/products/box-product-s-01.jpg" width="83" height="83" /></li>
				</ul>
			</div>
		</div>
		<div class="box_right">
			<h1></h1>
			<ul></ul>
			<p>
				<img src="/upload/products/pro-icon-01.png" alt="pro-icon" title="pro-icon" />
				<img src="/upload/products/pro-icon-02.png" alt="pro-icon" title="pro-icon" />
				<img src="/upload/products/pro-icon-03.png" alt="pro-icon" title="pro-icon" />
			</p>
		</div>
		<div class="box_btn box_btn_l"></div>
		<div class="box_btn box_btn_r"></div>
		<div class="box_btn box_btn_c"></div>
	</div>

	{gemel:include filename="footer.htm"