{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140714/90257-b-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90257-b.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90267-a--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90267-a-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90267-d--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90267-d-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/91000-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/91000-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96017-a.jpg-50' text='' width='270' height='290'} /upload/allimg/140714/96017-a.jpg-50 {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96017-b-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96017-b.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96017-c-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96017-c.jpg {/gemel:img}
