<channel:id>16</channel:id>
<channel:nid>job</channel:nid>
<channel:typename>人才招聘</channel:typename>
<channel:maintable>#@__archives</channel:maintable>
<channel:addtable>#@__addon15</channel:addtable>
<channel:addcon>archives_add.php</channel:addcon>
<channel:mancon>content_list.php</channel:mancon>
<channel:editcon>archives_edit.php</channel:editcon>
<channel:useraddcon></channel:useraddcon>
<channel:usermancon></channel:usermancon>
<channel:usereditcon></channel:usereditcon>
<channel:fieldset>

<field:job_targets itemname="招聘对象" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_targets>

<field:job_vacancies itemname="招聘人数" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_vacancies>

<field:job_add itemname="工作地点" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_add>


<field:job_money itemname="工资待遇" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_money>

<field:job_published itemname="发布时间" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_published>

<field:job_expiration itemname="有效期限" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_expiration>

<field:job_requirements itemname="招聘要求" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_requirements>

</channel:fieldset>
<channel:listfields></channel:listfields>
<channel:allfields></channel:allfields>
<channel:issystem>0</channel:issystem>
<channel:isshow>1</channel:isshow>
<channel:issend>0</channel:issend>
<channel:arcsta>-1</channel:arcsta>
<channel:usertype></channel:usertype>
<channel:sendrank>0</channel:sendrank>
<channel:isdefault>0</channel:isdefault>
<channel:needdes>0</channel:needdes>
<channel:needpic>0</channel:needpic>
<channel:titlename>标题</channel:titlename>
<channel:onlyone>0</channel:onlyone>
<channel:dfcid>0</channel:dfcid>
