<a href="[filed:typeurl/]" class="index_news_more">更多新闻>></a>{/gemeltype}
	<div class="notice_tit"></div>
    <div class="notice_sc">
        <a class="notice_sc_right" href="javascript:viod(0);"></a>
        <a class="notice_sc_left" href="javascript:viod(0);"></a>
    </div>
	<div class="notice_con">
		<ul>
		{gemel:arclist typeid='13' orderby='weight' row='5' titlelen='50' flag='c'}
        <li><a href="[field:arcurl/]">[field:title/]</a></li>
        {/gemel:arclist}
		</ul> 
	</div>
	<div class="clear"></div>
</div>

<div class="main">
    <div class="gg_img">
        {gemel:rpad name='index_gg1'/}
        {gemel:rpad name='index_gg2'/}
    </div>
    <div class="index_tv"><embed src="http://player.youku.com/player.php/sid/XNjEyOTE4NTEy/v.swf" allowFullScreen="true" quality="high" width="284" height="207" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash"></embed></div>
    <div class="clear"></div>
</div>

<div class="index_pro">
	<div class="index_pro_tit">{gemel:type typeid='8'}<a href="[field:typeurl/]">MORE >></a><span>[field:typename/]</span>