{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140524/1-1405241KK1-lp.jpg' text='' width='734' height='321'} /upload/allimg/140524/1-1405241KK1.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140524/1-1405241KK2-lp.jpg' text='' width='734' height='321'} /upload/allimg/140524/1-1405241KK2.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140524/1-1405241KK3-lp.jpg' text='' width='734' height='321'} /upload/allimg/140524/1-1405241KK3.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140524/1-1405241KK4-lp.jpg' text='' width='734' height='321'} /upload/allimg/140524/1-1405241KK4.jpg {/gemel:img}
