
                    <li><a href="[field:typelink/]">[field:typename/]</a></li>
                        [field:sonchannel0]
                        <li class="c1"><a href="[field:typelink/]">[field:typename/]</a></li>
                            [field:sonchannel1]
                            <li class="c2"><a href="[field:typelink/]">[field:typename/]</a></li>
                                [field:sonchannel2]
                                <li class="c3"><a href="[field:typelink/]">[field:typename/]</a></li>
                                    [field:sonchannel3]
                                    <li class="c4"><a href="[field:typelink/]">[field:typename/]</a></li>
                                    [/field:sonchannel3]
                                [/field:sonchannel2]
                            [/field:sonchannel1]
                        [/field:sonchannel0]
                    