{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140714/90060-a.jpg-50' text='' width='240' height='180'} /upload/allimg/140714/90060-a.jpg-50 {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90062-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90062-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96164-b-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96164-b.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96164-c-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96164-c.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96164-e-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96164-e.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96273-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96273-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96273-b-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96273-b.jpg {/gemel:img}
