<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/170621/rhc-01.jpg ",96,230);
$z[1][4]['ddimg']="/upload/allimg/170621/rhc-01-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="566";
$z[1][4]['height']="429";
$z[2]=Array("img"," /upload/allimg/170621/rhc-02.jpg ",232,366);
$z[2][4]['ddimg']="/upload/allimg/170621/rhc-02-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="566";
$z[2][4]['height']="429";
$z[3]=Array("img"," /upload/allimg/170621/rhc-03.jpg ",368,502);
$z[3][4]['ddimg']="/upload/allimg/170621/rhc-03-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="566";
$z[3][4]['height']="429";
$z[4]=Array("img"," /upload/allimg/170621/rhc-04.jpg ",504,638);
$z[4][4]['ddimg']="/upload/allimg/170621/rhc-04-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="566";
$z[4][4]['height']="429";
$z[5]=Array("img"," /upload/allimg/170621/rhc-05.jpg ",640,774);
$z[5][4]['ddimg']="/upload/allimg/170621/rhc-05-lp.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="566";
$z[5][4]['height']="429";

?>