{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140524/1-1405241F542-lp.jpg' text='' width='734' height='321'} /upload/allimg/140524/1-1405241F542.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140524/1-1405241FQ2-lp.jpg' text='' width='734' height='321'} /upload/allimg/140524/1-1405241FQ2.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140524/1-1405241FR2-lp.jpg' text='' width='734' height='321'} /upload/allimg/140524/1-1405241FR2.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140524/1-1405241FS1-lp.jpg' text='' width='734' height='321'} /upload/allimg/140524/1-1405241FS1.jpg {/gemel:img}
