<li>
                    <div class="img">
                        <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:typename/] - [field:title/]" alt="[field:typename/] - [field:title/]" width="240" height="184"/></a>
                    </div>
                    <div class="text">
                        <div class="icon">
                            <a href="[field:arcurl/]"><img src="/images/hot-icon.png" title="[field:typename/] - [field:title/]" alt="[field:typename/] - [field:title/]" width="100" height="93"/></a> 
                        </div>
                        <h3><a href="[field:arcurl/]">[field:typename/]</a></h3>
                        <p><a href="[field:arcurl/]">[field:title/]</a></p>
                        <em></em>
                    </div>
                </li>