<?php
$z[0]=Array("arcurl","",78,93);
$z[1]=Array("litpic","",105,120);
$z[2]=Array("typename","",129,146);
$z[3]=Array("title","",149,163);
$z[4]=Array("typename","",170,187);
$z[5]=Array("title","",190,204);
$z[6]=Array("arcurl","",387,402);
$z[7]=Array("typename","",443,460);
$z[8]=Array("title","",463,477);
$z[9]=Array("typename","",484,501);
$z[10]=Array("title","",504,518);
$z[11]=Array("arcurl","",621,636);
$z[12]=Array("typename","",638,655);
$z[13]=Array("arcurl","",702,717);
$z[14]=Array("title","",719,733);

?>