<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/160614/db7824-011.jpg ",96,239);
$z[1][4]['ddimg']="/upload/allimg/160614/db7824-011-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1158";
$z[1][4]['height']="520";
$z[2]=Array("img"," /upload/allimg/160614/db7824-021.jpg ",241,384);
$z[2][4]['ddimg']="/upload/allimg/160614/db7824-021-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1158";
$z[2][4]['height']="520";
$z[3]=Array("img"," /upload/allimg/160614/db7824-031.jpg ",386,529);
$z[3][4]['ddimg']="/upload/allimg/160614/db7824-031-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1158";
$z[3][4]['height']="520";
$z[4]=Array("img"," /upload/allimg/160614/db7824-041.jpg ",531,674);
$z[4][4]['ddimg']="/upload/allimg/160614/db7824-041-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1158";
$z[4][4]['height']="520";

?>