{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/160614/db7824-011-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/db7824-011.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/db7824-021-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/db7824-021.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/db7824-031-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/db7824-031.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/db7824-041-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/db7824-041.jpg {/gemel:img}
