<div class="pro_list">
							<img src="{gemel:field name='typepic'/}" alt="{gemel:field name='typename'/}" title="{gemel:field name='typename'/}" width="354" height="257" />
							<a href="javascript:;">{gemel:field name='typename'/}</a>
							<div class="pro_info">
								{gemel:field name="content"/}
							</div>
						</div>
					{gemel:name runphp='yes'}$j=0;$str = "</li><li>";@me = $str;{/gemel:name}