<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/140714/90239-a.jpg ",96,232);
$z[1][4]['ddimg']="/upload/allimg/140714/90239-a-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="270";
$z[1][4]['height']="290";
$z[2]=Array("img"," /upload/allimg/140714/90239-b.jpg ",234,370);
$z[2][4]['ddimg']="/upload/allimg/140714/90239-b-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="270";
$z[2][4]['height']="290";
$z[3]=Array("img"," /upload/allimg/140714/90242-a.jpg ",372,508);
$z[3][4]['ddimg']="/upload/allimg/140714/90242-a-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="270";
$z[3][4]['height']="290";
$z[4]=Array("img"," /upload/allimg/140714/90243-a.jpg ",510,646);
$z[4][4]['ddimg']="/upload/allimg/140714/90243-a-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="270";
$z[4][4]['height']="290";
$z[5]=Array("img"," /upload/allimg/140714/96305-b-.jpg-50 ",648,789);
$z[5][4]['ddimg']="/upload/allimg/140714/96305-b-.jpg-50";
$z[5][4]['text']="";
$z[5][4]['width']="270";
$z[5][4]['height']="290";

?>