<?php
$z[0]=Array("litpic","",82,97);
$z[1]=Array("title","",106,120);
$z[2]=Array("typename","",123,140);
$z[3]=Array("title","",147,161);
$z[4]=Array("typename","",164,181);
$z[5]=Array("title","",288,302);
$z[6]=Array("typename","",305,322);
$z[7]=Array("title","",329,343);
$z[8]=Array("typename","",346,363);
$z[9]=Array("arcurl","",461,476);
$z[10]=Array("title","",478,492);
$z[11]=Array("arcurl","",537,552);
$z[12]=Array("typename","",554,571);
$z[13]=Array("arcurl","",612,627);

?>