<li>
                     <div class="img">
                          <img src="[field:litpic/]" title="[field:title/] - [field:typename/]" alt="[field:title/] - [field:typename/]" width="260" height="208"/>
                          <a href=""><img src="/images/home-more.png" title="[field:title/] - [field:typename/]" alt="[field:title/] - [field:typename/]" width="260" height="208" /></a>
                     </div>
                     <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
                     <h3><a href="[field:arcurl/]">[field:typename/]</a></h3>
                     <a href="[field:arcurl/]">READ MORE</a>
                </li>