<li>
				<div class="img-box">
				   <img src="/images/home-pro-01.jpg" title="" alt="" width="323" height="242" class="on"/>
				   <img src="/images/home-pro-02.jpg" title="" alt="" width="323" height="242"/>
				   <img src="/images/home-pro-03.jpg" title="" alt="" width="323" height="242"/>
				   <a href="{gemel:field.typeurl/}"></a>
				</div>
				<h3><a href="{gemel:field.typeurl/}">{gemel:field.typename/}</a></h3>
			</li>