<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/170714/gallon-bucket-water-bottling-machine-01.jpg ",96,296);
$z[1][4]['ddimg']="/upload/allimg/170714/gallon-bucket-water-bottling-machine-01-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="530";
$z[1][4]['height']="450";
$z[2]=Array("img"," /upload/allimg/170714/gallon-bucket-water-bottling-machine-02.jpg ",298,498);
$z[2][4]['ddimg']="/upload/allimg/170714/gallon-bucket-water-bottling-machine-02-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="530";
$z[2][4]['height']="450";
$z[3]=Array("img"," /upload/allimg/170714/gallon-bucket-water-bottling-machine-03.jpg ",500,700);
$z[3][4]['ddimg']="/upload/allimg/170714/gallon-bucket-water-bottling-machine-03-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="530";
$z[3][4]['height']="450";
$z[4]=Array("img"," /upload/allimg/170714/gallon-bucket-water-bottling-machine-04.jpg ",702,902);
$z[4][4]['ddimg']="/upload/allimg/170714/gallon-bucket-water-bottling-machine-04-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="530";
$z[4][4]['height']="450";

?>