{gemel:field name='keywords'}站长之家, 联想集团, 杨元{/gemel:field}
{gemel:field name='description'}据经济之声《天下公司》报道，联想9月将启动裁员，比例将达到10%-15%。据悉，经济之声记者曾就裁员问题咨询联想员工。联想员工表示：“有传闻是这样，从这个月开始，但是具{/gemel:field}
{gemel:field name='title'}联想登顶PC市场王位 计划9月份将裁员15%{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}
                                                            <p><strong>站长之家（Chinaz.com）9月4日讯：</strong>据经济之声《天下公司》报道，联想9月将启动裁员，比例将达到10%-15%。</p>
<p>据悉，经济之声记者曾就裁员问题咨询联想员工。联想员工表示：&ldquo;有传闻是这样，从这个月开始，但是具体的话还没有听说身边人有被裁，但是应该是人力资源那边会有这样的决策，比例出来了。&rdquo;</p>
<p style="text-align: center;"><img src="/upload/allimg/c130905/13N3541c0I10-4I12.jpg" border="0" alt="联想集团大裁员" /></p>
<p style="text-align: center; font-size: 12px; text-indent: 0;">联想集团大裁员</p>
<p>如果消息属实，以目前联想集团4.2万的员工（包括国外员工7000人）的总数来算，将有4000名左右的员工裁掉。这将是联想历史上第五次大裁员，也是最大规模的一次裁员。</p>
<p>相关资料显示，联想此前的四次大裁员分别是：</p>
<p>2004年，并购IBM个人电脑前夕，联想宣布裁员600人。占到了员工总数的5%。</p>
<p>2006年，新上任的总裁兼CEO阿梅里奥宣布裁员1000人，占总员工数5%。</p>
<p>2007年，联想集团又宣布在除了大中华区的其他三个区削减1400个工作岗位。</p>
<p>2009年，联想执行&ldquo;资源调配&rdquo;计划，在全球削减员工2500人，占员工总数11%。</p>
<p>据Gartner7月份数据显示，2013年联想集团全球市场份额较上季度增加1.8个百分点达到16.7%。，经过近30年的风雨打拼，终于超越惠普登顶全球PC市场第一的宝座。</p>
<p>两天前，联想集团董事局主席兼CEO杨元庆还宣布，自掏腰包拿出300万美元（折合人民币约1834万元）的个人奖金，奖励海内外近万名基层员工。</p>
<p>发展势头良好的联想，这次爆出大裁员的消息，着实让人有点惊讶。</p>
<p>不过，最新消息披露，有媒体求证联想市场部相关负责人，该负责人表示，该消息为谣言，联想并无裁员计划。该负责人同时还指出，联想正在向PC+转型，智能终端业务发展良好，因此要保证充分的人员支持。并不存在裁员的问题。&nbsp;&nbsp;&nbsp;</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130905/13N3541c0I10-4I12_lit.jpg{/gemel:field}
