{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140528/1-14052P93P4-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P93P4.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052P93P5-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P93P5.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052P93P6-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P93P6.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052P93P7-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P93P7.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052P93P8-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P93P8.jpg {/gemel:img}
