{gemel:field name='keywords'}站长之家, 富士康内部, 富{/gemel:field}
{gemel:field name='description'}我们无意渲染，也无意贬低。所有信息来自实地走访，所有照片来自现场拍摄。我们能做的也只是原味呈现，带给你一个足够真实的富士康。{/gemel:field}
{gemel:field name='title'}还原一个真实的富士康(图集){/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
