<?php
$z[0]=Array("field","站长之家, 富士康内部, 富",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","我们无意渲染，也无意贬低。所有信息来自实地走访，所有照片来自现场拍摄。我们能做的也只是原味呈现，带给你一个足够真实的富士康。",75,303);
$z[1][4]['name']="description";
$z[2]=Array("field","还原一个真实的富士康(图集)",305,379);
$z[2][4]['name']="title";
$z[3]=Array("field","",381,418);
$z[3][4]['name']="writer";
$z[4]=Array("field","",420,457);
$z[4][4]['name']="source";
$z[5]=Array("field","",459,494);
$z[5][4]['name']="body";
$z[6]=Array("field","",496,534);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",536,573);
$z[7][4]['name']="litpic";

?>