<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/160614/dt8-e-01.jpg ",96,235);
$z[1][4]['ddimg']="/upload/allimg/160614/dt8-e-01-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1158";
$z[1][4]['height']="520";
$z[2]=Array("img"," /upload/allimg/160614/dt8-e-02.jpg ",237,376);
$z[2][4]['ddimg']="/upload/allimg/160614/dt8-e-02-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1158";
$z[2][4]['height']="520";
$z[3]=Array("img"," /upload/allimg/160614/dt8-e-03.jpg ",378,517);
$z[3][4]['ddimg']="/upload/allimg/160614/dt8-e-03-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="1158";
$z[3][4]['height']="520";
$z[4]=Array("img"," /upload/allimg/160614/dt8-e-04.jpg ",519,658);
$z[4][4]['ddimg']="/upload/allimg/160614/dt8-e-04-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1158";
$z[4][4]['height']="520";

?>