{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/170713/dcgf-series-carbonated-drink-production-line-01-lp.jpg' text='' width='530' height='450'} /upload/allimg/170713/dcgf-series-carbonated-drink-production-line-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170713/dcgf-series-carbonated-drink-production-line-02-lp.jpg' text='' width='530' height='450'} /upload/allimg/170713/dcgf-series-carbonated-drink-production-line-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170713/dcgf-series-carbonated-drink-production-line-03-lp.jpg' text='' width='530' height='450'} /upload/allimg/170713/dcgf-series-carbonated-drink-production-line-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170713/dcgf-series-carbonated-drink-production-line-04-lp.jpg' text='' width='530' height='450'} /upload/allimg/170713/dcgf-series-carbonated-drink-production-line-04.jpg {/gemel:img}
