<li class="clear">
      <div class="text_left li_left text_03">
        <h2><a href="[field:typelink/]">[field:typename/]</a></h2>
        <p>[field:description/]</p>
        <ul class="clear">
          <li class="li_right">
              <a href=""><img src="/upload/products/list-03-01.png" alt="PVC Edge banding" title="PVC Edge banding" width="173" height="114" /></a>
              <h3>Monochrome</h3>
          </li>
          <li>
              <a href=""><img src="/upload/products/list-03-02.png" alt="PVC Edge banding" title="PVC Edge banding" width="173" height="114" /></a>
              <h3>Grain</h3>
        </ul>
      </div>
      <div class="img_right">
          <img src="/upload/products/list-big-03.png" alt="PVC Edge banding" title="PVC Edge banding" width="850" height="562" />
          <div class="right_bg">
             <a href="[field:typelink/]">MORE</a>
          </div>         
      </div>
    </li>