<?php
$z[0]=Array("typeurl","",0,16);
$z[1]=Array("typename","",63,80);
$z[2]=Array("arcurl","",266,281);
$z[3]=Array("litpic","",315,330);
$z[4]=Array("arcurl","",361,376);
$z[5]=Array("typeurl","",617,633);
$z[6]=Array("typename","",681,698);
$z[7]=Array("arcurl","",885,900);
$z[8]=Array("litpic","",934,949);
$z[9]=Array("arcurl","",980,995);
$z[10]=Array("typeurl","",1236,1252);
$z[11]=Array("typename","",1300,1317);
$z[12]=Array("arcurl","",1504,1519);
$z[13]=Array("litpic","",1553,1568);
$z[14]=Array("arcurl","",1599,1614);
$z[15]=Array("typeurl","{/gemel}\">MORE >></a><span>{gemel:type typeid=\"12\" }[field:typename ",1855,1936);
$z[16]=Array("arcurl","",2123,2138);
$z[17]=Array("litpic","",2172,2187);
$z[18]=Array("arcurl","",2218,2233);
$z[19]=Array("title","",2775,2789);
$z[20]=Array("description","",2837,2898);
$z[20][4]['function']="cn_substrR(html2text(@me),20)";

?>