[field:typeurl/]{/gemel}">MORE >></a><span>{gemel:type typeid="9" }[field:typename/]{/gemel}</span><div class="clear"></div></div>
	<div class="index_pro_con">
		<ul>
            {gemel:arclist typeid='9' orderby='weight' row='4' flag="c"}
			<li>
            <a href="[field:arcurl/]" class="index_pro_img"><img src="[field:litpic/]" /></a>
            <a href="[field:arcurl/]" class="index_pro_text">SATA ILL 固态硬盘</a>
            </li>
            {/gemel:arclist}
		</ul>
		<div class="clear"></div>
	</div>
</div>

<div class="index_pro">
	<div class="index_pro_tit"><a href="{gemel:type typeid="10" }[field:typeurl/]{/gemel}">MORE >></a><span>{gemel:type typeid="10" }[field:typename/]{/gemel}</span><div class="clear"></div></div>
	<div class="index_pro_con">
		<ul>
            {gemel:arclist typeid='10' orderby='weight' row='4' flag="c"}
			<li>
            <a href="[field:arcurl/]" class="index_pro_img"><img src="[field:litpic/]" /></a>
            <a href="[field:arcurl/]" class="index_pro_text">SATA ILL 固态硬盘</a>
            </li>
            {/gemel:arclist}
		</ul>
		<div class="clear"></div>
	</div>
</div>

<div class="index_pro">
	<div class="index_pro_tit"><a href="{gemel:type typeid="11" }[field:typeurl/]{/gemel}">MORE >></a><span>{gemel:type typeid="11" }[field:typename/]{/gemel}</span><div class="clear"></div></div>
	<div class="index_pro_con">
		<ul>
            {gemel:arclist typeid='11' orderby='weight' row='4' flag="c"}
			<li>
            <a href="[field:arcurl/]" class="index_pro_img"><img src="[field:litpic/]" /></a>
            <a href="[field:arcurl/]" class="index_pro_text">SATA ILL 固态硬盘</a>
            </li>
            {/gemel:arclist}
		</ul>
		<div class="clear"></div>
	</div>
</div>

<div class="index_pro">
	<div class="index_pro_tit"><a href="{gemel:type typeid="12" }[field:typeurl]{/gemel}">MORE >></a><span>{gemel:type typeid="12" }[field:typename /]{/gemel}</span><div class="clear"></div></div>
	<div class="index_pro_con">
		<ul>
            {gemel:arclist typeid='12' orderby='weight' row='4' flag="c"}
			<li>
            <a href="[field:arcurl/]" class="index_pro_img"><img src="[field:litpic/]" /></a>
            <a href="[field:arcurl/]" class="index_pro_text">SATA ILL 固态硬盘</a>
            </li>
            {/gemel:arclist}
		</ul>
		<div class="clear"></div>
	</div>
</div>

<div class="main2">
    <a href="{gemel typeid="15" }[file:typeurl/]{/gemel}" class="index_solution"></a>
    <div class="index_news">
        <a href="{gemel typeid="17" }[file:typeurl/]{/gemel}" class="index_news_tit"></a>
        <div class="index_news_con">
            {gemel:arclist typeid='15' orderby='weight' titlelen='120' row='1' flag="c"}
            <a class="index_news_text">[field:title/]</a>
            <p class="index_news_profile">[field:description function='cn_substrR(html2text(@me),20)'/]...</p>
            {/gemel:arclist}
        </div>
    </div>
    <a href="{gemel typeid="15" }[file:typeurl]{/gemel}" class="index_questions"></a>
    <div class="clear"></div>
</div>
{gemel:include filename="head.htm"