<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:quick_type itemname="Terminal Type" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="Tab Crimp,Tab & Receptacle,Receptacle"  maxlength="250" page="">
</field:quick_type>
<field:quick_orientation itemname="Terminal Orientation" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default="Straight,Piggyback,Flag"  maxlength="250" page="">
</field:quick_orientation>
<field:quick_width itemname="Tab width" autofield="1" notsend="0" type="checkbox" isnull="true" islist="0" default=".110in,.187in,.205in,.250in"  maxlength="250" page="">
</field:quick_width>
<field:diagram_img itemname="Diagram" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:diagram_img>
<field:specification_terminals itemname="表格参数" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:specification_terminals>
