<li>
                       <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="505" height="256"/></a>
                       <h2><a href="[field:arcurl/]">[field:title/]</a></h2>
                       <div class="arrow">
                             <a href="[field:arcurl/]">&nbsp;</a>
                       </div>                   
                  </li>