<?php
$z[0]=Array("field","",86,108);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",110,133);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                    <li>\r\n                        <div class=\"img\">\r\n                            <a href=\"[field:arcurl/]\">\r\n                                <img src=\"[field:litpic/]\" width=\"360\" height=\"240\" title=\"[field:title/]\" alt=\"[field:title/]\"/>\r\n                            </a>\r\n                        </div>    \r\n                        <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n                        <p>1220*2440*5~20mm</p>\r\n                    </li>\r\n                    ",246,855);
$z[2][4]['orderby']="weight";
$z[2][4]['titlelen']="40";
$z[2][4]['row']="6";
$z[2][4]['addfields']="blist_img";
$z[2][4]['channelid']="2";
$z[3]=Array("field","",911,933);
$z[3][4]['name']="typeurl";

?>