<?php
$z[0]=Array("arcurl","",86,101);
$z[1]=Array("litpic","",113,128);
$z[2]=Array("typename","",137,154);
$z[3]=Array("title","",157,171);
$z[4]=Array("typename","",178,195);
$z[5]=Array("title","",198,212);
$z[6]=Array("arcurl","",363,378);
$z[7]=Array("typename","",380,397);
$z[8]=Array("arcurl","",449,464);
$z[9]=Array("typename","",473,490);
$z[10]=Array("title","",493,507);
$z[11]=Array("title","",509,523);
$z[12]=Array("arcurl","",571,586);
$z[13]=Array("typename","",595,612);
$z[14]=Array("title","",615,629);

?>