<div class="list-text">
              <h2><a href="{gemel:field.typeurl/}">{gemel:field.typename/}</a></h2>
              <div class="list">
                   <ul class="clear">
                        {gemel:arclist orderby='weight' titlelen='40' row='40' addfields='pro_spec' channelid='2'}                   
                        <li>
                             <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="298" height="450" /></a>
                             <div class="product-specifications">
                                   [field:pro_spec/]
                             </div>
                             <h3><a href="[field:arcurl/]">KBQ-165</a></h3>
                             <em></em>
                        </li>
                        {/gemel:arclist}
                   </ul>
              </div>
        </div>