<li>
                        <a href="[field:arcurl/]" target="_blank"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="367" height="274" /></a>
                        <h2><a href="[field:arcurl/]" target="_blank" title="[field:title/]">[field:title/]</a></h2>
                        <p>[field:description function='cn_substrR(html2text(@me),200)'/]...</p>
                        <div class="read"><a href="[field:arcurl/]" target="_blank">Read More</a> </div>
                  </li>