{gemel:field name='keywords'}站长之家, 58同城, 58同城上{/gemel:field}
{gemel:field name='description'}58同城宣布行使完超额配售165万份ADS，募集资金增至2.3亿美元，比最初预期的1.5亿美元高出50%，这是中国公司今年以来在美上市融资的最高金额。{/gemel:field}
{gemel:field name='title'}58同城行使超额配售权 融资额增至2.3亿美元{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0T942160-1JM.jpg" border="0" /></p>
<p><strong>腾讯科技讯</strong>（范晓东）58同城宣布行使完超额配售165万份ADS，募集资金增至2.3亿美元，比最初预期的1.5亿美元高出50%，这是中国公司今年以来在美上市融资的最高金额。</p>
<p>58同城于11月1日在纽交所挂牌，上市首日报收24.31美元，较17美元的发行价，上涨43% ，其中盘间最高曾上涨至26.82美元。据悉，新股上市，为稳定后市股价，一般都会采用&ldquo;绿鞋&rdquo;机制（即超额配售权）来护航。而其最终是否行使，股价与市场信心是较为重要的因素。</p>
<p>一般而言，承销商在股票上市之日起30天内，可以择机按同一发行价格比预定规模多发15%（一般不超过15%）的股份。如果股票上市之后的价格低于发行价，主承销商用事先超额发售股票获得的资金（事先认购超额发售投资者的资金），按不高于发行价的价格从二级市场买入，然后分配给提出超额认购申请的投资者；如果股票上市后的价格高于发行价，主承销商就要求发行人增发15%的股票，分配给事先提出认购申请的投资者。</p>
<p>58同城此次IPO共发行1100万份ADS（1份ADS相当于2普通股），超额配售165万份ADS（发行股数的15%），发行后总股本约1.6亿股，最终定价17美元/ADS。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131106/13SI0T942160-1JM_lit.jpg{/gemel:field}
