<ul class="clear on">
                {gemel:arclist orderby='weight' titlelen='100' row='8'}
                <li><a href="[field:arcurl/]"><img src="[field:litpic/]" width="270" height="270" alt="[field:typename/] - [field:title/]" title="[field:typename/] - [field:title/]">
                    <span>[field:title/]</span>
                </a></li>
                {/gemel:arclist}
            </ul>