<?php
$z[0]=Array("arcurl","",122,137);
$z[1]=Array("related_img","",149,169);
$z[2]=Array("typename","",178,195);
$z[3]=Array("title","",198,212);
$z[4]=Array("typename","",219,236);
$z[5]=Array("title","",239,253);
$z[6]=Array("arcurl","",422,437);
$z[7]=Array("typename","",446,463);
$z[8]=Array("title","",466,480);
$z[9]=Array("title","",482,496);
$z[10]=Array("arcurl","",539,554);
$z[11]=Array("typename","",563,580);
$z[12]=Array("title","",583,597);

?>