<li>
                   <div class="box">
                       <div class="img">
                           <a href="[field:arcurl/]"><img src="[field:related_img/]" title="[field:typename/] - [field:title/]" alt="[field:typename/] - [field:title/]" width="276" height="232" /></a>
                       </div>
                   </div>
                   <div class="title">
                       <h3><a href="[field:arcurl/]" title="[field:typename/] - [field:title/]">[field:title/]</a></h3>
                       <a href="[field:arcurl/]" title="[field:typename/] - [field:title/]">READ MORE</a>
                   </div>
              </li>