{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140709/luxury-vibrator-vya8-01-lp.jpg' text='' width='270' height='290'} /upload/allimg/140709/luxury-vibrator-vya8-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140709/luxury-vibrator-vya8-02-lp.jpg' text='' width='270' height='290'} /upload/allimg/140709/luxury-vibrator-vya8-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140709/luxury-vibrator-vya8-03-lp.jpg' text='' width='270' height='290'} /upload/allimg/140709/luxury-vibrator-vya8-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140709/luxury-vibrator-vya8-04-lp.jpg' text='' width='270' height='290'} /upload/allimg/140709/luxury-vibrator-vya8-04.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140709/luxury-vibrator-vya8-05-lp.jpg' text='' width='270' height='290'} /upload/allimg/140709/luxury-vibrator-vya8-05.jpg {/gemel:img}
