{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140714/90236-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90236-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90236-b-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90236-b.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90033-b-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90033-b.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90034-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90034-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90257-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90257-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90242-b-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90242-b.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90236-a半身.jpg-50' text='' width='270' height='290'} /upload/allimg/140714/90236-a半身.jpg-50 {/gemel:img}
