<div class="pro_list">
							<img src="/upload/team/team-pic-01.jpg" alt="Youdao translation" title="Youdao translation" width="354" height="257" />
							<a href="#">{gemel:field name='typename'/}</a>
							<div class="pro_info">
								<h1>{gemel:field name='typename'/}</h1>
								<p>box-product</p>
								<ul>
									<li>weight: 480g (include packing) </li>
									<li>function: 7-segment frequency </li>
									<li>material: silicone battery: </li>
									<li>rechargeable charging </li>
									<li>time: 1 hour time of duration: </li>
									<li>3hours color: green pink purple</li>
								</ul>
							</div>
						</div>