<li><a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src="{gemel:field name='typepic'/}" alt="{gemel:field name='typename'/}" title="{gemel:field name='typename'/}" width="88" height="88" /><span>{gemel:field name='typename'/}</span></a>
                               <!--<ul class="son_menu">
                                       {gemel:channelartlist typeid='4' row='6' type='son' currentstyle='select'}
                                         
                                           <li><a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src="{gemel:field name='typepic'/}" alt="{gemel:field name='typename'/}" title="{gemel:field name='typename'/}" width="88" height="88" /><span>{gemel:field name='typename'/}</span></a></li>