{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/160613/drt-e-01-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160613/drt-e-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160613/drt-e-02-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160613/drt-e-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160613/drt-e-03-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160613/drt-e-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160613/drt-e-04-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160613/drt-e-04.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160613/drt-e-05-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160613/drt-e-05.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160613/drt-e-06-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160613/drt-e-06.jpg {/gemel:img}
