<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/141217/01.jpg ",96,231);
$z[1][4]['ddimg']="/upload/allimg/141217/01-lp.jpg";
$z[1][4]['text']="大苏打";
$z[1][4]['width']="834";
$z[1][4]['height']="372";
$z[2]=Array("img"," /upload/allimg/141217/02.jpg ",233,359);
$z[2][4]['ddimg']="/upload/allimg/141217/02-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="834";
$z[2][4]['height']="372";
$z[3]=Array("img"," /upload/allimg/141217/03.jpg ",361,487);
$z[3][4]['ddimg']="/upload/allimg/141217/03-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="834";
$z[3][4]['height']="372";
$z[4]=Array("img"," /upload/allimg/141218/04.jpg ",489,615);
$z[4][4]['ddimg']="/upload/allimg/141218/04-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="834";
$z[4][4]['height']="372";
$z[5]=Array("img"," /upload/allimg/141218/05.jpg ",617,743);
$z[5][4]['ddimg']="/upload/allimg/141218/05-lp.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="834";
$z[5][4]['height']="372";

?>