{gemel:field name='keywords'}站长之家, 婚外情网站, 网{/gemel:field}
{gemel:field name='description'}新加坡政府日前封杀了婚外情网站Ashley Madison，因为它积极宣扬婚外情，损害了该国的公共利益。{/gemel:field}
{gemel:field name='title'}新加坡封杀婚外情网站Ashley Madison{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131112/13T2215195O10-233G.jpg" border="0" width="550" alt="新加坡封杀婚外情网站Ashley Madison" height="359" style="border: 0px;" /></p>
<p>腾讯科技 乐学 11月12日 编译</p>
<p>新加坡政府日前封杀了婚外情网站Ashley Madison，因为它积极宣扬婚外情，损害了该国的公共利益。</p>
<p>在上周五晚发布的一份声明中，新加坡内容管制机构Media Development Authority（媒体发展部，简称MDA）称，它不可能允许&ldquo;公然践踏&rdquo;新加坡&ldquo;家庭价值和公共道德&rdquo;的网站运营，并已责令当地互联网服务提供商阻止人们访问该网站。</p>
<p>Ashley Madison是一家总部位于加拿大的约会网站和社交媒体平台，旨在为已婚人士安排&ldquo;约会、一夜情和婚外情&rdquo;。它的宣传口号是：&ldquo;生命苦短，及时行乐。&rdquo;现在，它在澳大利亚、香港和英国等多个国家拥有超过1600万个注册用户。在它的Facebook页面上，该公司称它的&ldquo;领先服务&rdquo;已在全球拥有&ldquo;惊人的注册用户数量&rdquo;。</p>
<p>本月，Ashley Madison网站宣布将会登陆新加坡，采用域名ashleymadison.sg，并要求感兴趣的用户用他们的电子邮件地址进行注册。在周五晚，该网站已被新加坡当局封杀，但是人们仍然能够通过VPN（虚拟专用网络）进行访问。</p>
<p>如果Ashley Madison网站将其名称变更为Amberly Madison，试图逃避当局的监查，那么MDA又该如何如何应对呢？MDA声称，新加坡政府已意识到了封杀被禁网站的方法并不是非常理想的办法，例如，被禁网站只要变更其网站的名称就可以逃过审查。而且，它还补充说，要阻止每一个提供这种内容的网站也不现实。</p>
<p>&ldquo;但是，这样做可以表明新加坡反对这种内容的立场。&rdquo;正因如此，MDA称它已采取措施封杀了&ldquo;一些网站&rdquo;，但是，这只是一种&ldquo;象征性的做法&rdquo;，旨在彰显新加坡当局反对的内容。</p>
<p>根据新加坡《互联网行为准则》（Internet Code of Practice），&ldquo;任何违反公共利益、公共道德、公共秩序、公共安全、国家和谐的内容，或新加坡相关法律禁止的内容&rdquo;都应该被禁止。按照惯例，被封杀的网站往往包含有色情、暴力和煽动性的内容。例如，在2012年，MDA封杀了一部反对穆斯林的YouTube视频，理由是它激起了&ldquo;宗教仇恨、冲突或偏见&rdquo;。</p>
<p>&ldquo;Ashley Madison网站显得刺眼的原因是，它积极宣扬婚外情，并竭力提供便利；而且它还宣称将会推出专门针对新加坡人的网站。&rdquo;MDA说，该部门还指出，Ashley Madison网站的创始人据说会在11月17日飞抵新加坡，亲自启动该网站的上线仪式。</p>
<p>获悉Ashley Madison网站准备推出新加坡版后，新加坡内阁部长和广大公众均表达了不满。新加坡一个旨在&ldquo;阻止Ashley Madison网站&rdquo;的Facebook页面，自从10月23日推出以来就已获得了超过2.7万个&ldquo;赞&rdquo;。而新加坡社会和家庭发展部部长陈振声（Chan Chun Sing）在其Facebook页面上明确表示，他不欢迎这样的网络进驻新加坡。</p>
<p>上个月，新加坡政府声称，它正在考虑是否封杀提供盗版电影和音乐等内容的网站，但相关决策尚未最终确定下来。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131112/13T2215195O10-233G_lit.jpg{/gemel:field}
