<div class="news_list">
            <div class="news_list_left"><a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="200" height="150" /></a></div>
            <div class="news_list_right">
                <p class="news_list_text"><a href="[field:arcurl/]">[field:title/]</a></p>
                <p class="news_list_time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</p>
                <p class="news_list_des">[field:description function='cn_substrR(html2text(@me),200)'/]...</p>
                <p class="news_list_more"><a href="[field:arcurl/]">Read More</a></p>
            </div>
        </div>