<?php
$z[0]=Array("arcurl","",74,89);
$z[1]=Array("litpic","",101,116);
$z[2]=Array("title","",125,139);
$z[3]=Array("title","",146,160);
$z[4]=Array("arcurl","",295,310);
$z[5]=Array("title","",312,326);
$z[6]=Array("pubdate","",378,425);
$z[6][4]['function']="MyDate('Y-m-d',@me)";
$z[7]=Array("description","",472,534);
$z[7][4]['function']="cn_substrR(html2text(@me),200)";
$z[8]=Array("arcurl","",594,609);

?>