{gemel:field name='keywords'}站长之家, 当当, 双11域名{/gemel:field}
{gemel:field name='description'}电商行业在“双11”促销战上的竞争已从拼价格、物流升级到流量争夺暗战。北京商报记者近日从知情人士处获悉，当当已斥资百万元购得“shuang11.com”域名，并将其打造为电商{/gemel:field}
{gemel:field name='title'}当当百万元买下“双11”域名 做电商分享导购网站{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>电商行业在&ldquo;双11&rdquo;促销战上的竞争已从拼价格、物流升级到流量争夺暗战。北京商报记者近日从知情人士处获悉，当当已斥资百万元购得&ldquo;shuang11.com&rdquo;域名，并将其打造为电商分享导购网站，直接截流&ldquo;双11&rdquo;用户。</p>
<p>消息称，在&ldquo;双11&rdquo;前夕，当当网重金购得&ldquo;shuang11.com&rdquo;域名，将其运营为&ldquo;&lsquo;双11&rsquo;购物导航&rdquo;网站，目前已正式上线。北京商报记者登录该网站发现，其定位于精品导航网站，主要分为&ldquo;达人推荐&rdquo;、&ldquo;电商新闻&rdquo;和&ldquo;热门商品&rdquo;三大板块。首页有服装、名表、美妆、箱包、3C、家电、美酒、食品和图书音像等推荐产品。对于此域名购买一事，当当网市场部相关负责人未予否认。</p>
<p>巧合的是，阿里巴巴集团自去年开始对电商导购网站重视有加，多次加码自己的分享类产品。此前亦有消息传出，阿里正在尝试以2亿美元的价格收购分享导购网站蘑菇街，希望借导航网站为用户提供精准的个性化服务。</p>
<p>事实上，重视分享导购抑或是抢占&ldquo;双11&rdquo;域名等&ldquo;第二入口&rdquo;，都是有利于电商获得更多的用户流量。而随着&ldquo;&lsquo;双11&rsquo;经济&rdquo;的热度逐年增加，从两个电商争先布局&ldquo;精品导购&rdquo;来看，B2C电商对未来&ldquo;第二入口&rdquo;的重视程度可见一斑。&ldquo;无论电商网站具有如何的价格、物流优势，如果从流量源头失去控制力，等于是白忙活一场&rdquo;，业内人士如是坦言。</p>
<p>同时，业内人士也指出，&ldquo;双11&rdquo;域名争夺只是电商&ldquo;双11&rdquo;竞争的冰山一角，流量把控固然重要，但是&ldquo;物流&rdquo;、&ldquo;退换货&rdquo;等硬性体验都将是影响电商&ldquo;双11&rdquo;决战胜负的关键因素。</p>
<p>而对此，当当网已做好决战的最后准备。当当相关负责人士向北京商报记者介绍，11月5日店庆日到11月11日将是当当网店庆月&ldquo;闭幕周&rdquo;，其将直指&ldquo;双11&rdquo;，从当当网的广告投放来看，其促销力度将在3-5折区间。</p>
<p>此外对于&ldquo;双11&rdquo;最为重要的&ldquo;物流&rdquo;环节，当当物流方面负责人具体介绍称，当当网所有物流配送环节至少增加50%资源投入，同时还部署&ldquo;金牌最后一公里&rdquo;配送服务，细化到&ldquo;现金找零&rdquo;、&ldquo;短信提醒&rdquo;、&ldquo;现场验货&rdquo;等环节，都将纳入对快递的单项考核，保证物品按时、完好地送到用户手中。</p>
<p>北京商报记者 魏蔚</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
