{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/160126/home-about-01.jpg-50' text='' width='240' height='180'} /upload/allimg/160126/home-about-01.jpg-50 {/gemel:img}
{gemel:img ddimg='/upload/allimg/160126/pvc-coated-webbings-01.jpg-50' text='' width='240' height='180'} /upload/allimg/160126/pvc-coated-webbings-01.jpg-50 {/gemel:img}
