{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140528/1-14052PTS4-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PTS4.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PTS5-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PTS5.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PTS6-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PTS6.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PTS7-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PTS7.jpg {/gemel:img}
