<li>
                {gemel:arclist titlelen='38' row='1'}
				<div class="indexpro_img">
					<a href="[field:arcurl/]">
                    <img src="[field:pic/]" width="110" height="90" title="[field:title/]" style="margin-top:10px;" alt="[field:title/]"/>
                    </a>
					<span></span>
				</div>
                {/gemel:arclist}
				<a href="{gemel:field name='typeurl'/}" class="indexpro_text">{gemel:field name='typename'/}</a>
			</li>