{gemel:field name='keywords'}站长之家, 腾讯云, 安全宝{/gemel:field}
{gemel:field name='description'}在腾讯云主页、安全宝主页已经在banner上赫然的写到：安全宝与腾讯云成为战略合作伙伴，自此，腾讯与安全宝、百度与加速乐、360自建的网站卫士，这也意味着免费CDN市场已经{/gemel:field}
{gemel:field name='title'}腾讯云与安全宝合作 CND市场3BT格式成型{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p>在腾讯云主页、安全宝主页已经在banner上赫然的写到：安全宝与腾讯云成为战略合作伙伴，自此，腾讯与安全宝、百度与加速乐、360自建的网站卫士，这也意味着免费CDN市场已经三足鼎立。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130923/13OZ141635c0-13302.gif" border="0" width="534" alt="腾讯云与安全宝合作 CND市场3BT格式成型" title="腾讯云与安全宝合作 CND市场3BT格式成型" height="256" /></p>
<p>不过目前腾讯云还在内测，只针对企业用户申请，普通用户没资格内测。云服务是今年各个互联网巨头争夺的一块领地，先是Google Drive，后有阿里云、百度云、腾讯云，这些看似和中小站长没什么关系，但大家使用的云主机就是云服务其中一项功能。</p>
<p>尽管360没有类似云服务，但它已经和国内多家知名IDC成为战略合作伙伴，有些IDC与360合作后，站长购买的虚拟主机会默认启用360的CDN。正因如此，360的免费CDN是目前网站使用量最大的。</p>
<p>在互联网源头，巨头都在圈地布局，CDN就是最重要的一块，在这样的大环境下，腾讯与安全宝合作是必然，之前安全宝的腾讯收购的DNSpod合作就是例子。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130923/13OZ141635c0-13302_lit.gif{/gemel:field}
