{gemel:field name='keywords'}站长之家, 小米3, 联通版{/gemel:field}
{gemel:field name='description'}今日，小米公司针对“小米手机3联通版在宣传的时候说的是采用高通骁龙MSM8974AB处理器，而实际上采用的是高通骁龙MSM8274AB处理器”这一问题做出回应：2014年1月2日前购买{/gemel:field}
{gemel:field name='title'}小米回应米3联通版问题：可为用户全额退款{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p><strong>站长之家（Chinaz.com）1月2日消息</strong>&nbsp; 今日，小米公司针对&ldquo;小米手机3联通版在宣传的时候说的是采用高通骁龙MSM8974AB处理器，而实际上采用的是高通骁龙MSM8274AB处理器&rdquo;这一问题做出回应：2014年1月2日前购买小米手机3联通版的用户可于本公告发布一周内致电小米客服热线，选择全额退款。</p>
<p>日前，一条微博称&ldquo;小米手机3联通版在宣传的时候说的是采用高通骁龙MSM8974AB处理器，而实际上采用的是高通骁龙MSM8274AB处理器&rdquo;，这是真的吗？</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c140103/13XG5UEC10-154221.jpg" border="0" alt="1388650838398" /></p>
<p>经调查后发现，小米手机3联通版采用的处理器就是MSM8274AB版本，而非MSM8974AB版本。（）</p>
<p>实情曝光后，一时间议论纷纷。今日，小米公司便针对这一问题，给出回应！</p>
<p>小米表示，<strong>高通公司和小米的技术交流文档中，一直使用骁龙8974AB统称整个骁龙800 8x74AB系列产品。小米在发布会上延用了这一称谓，确为不够严谨，我们深感歉意。2014年1月2日前购买小米手机3联通版的用户可于本公告发布一周内致电小米客服热线，选择全额退款</strong>。</p>
<p>以下为声明全文：</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c140103/13XG5UI3R0-1D5A.jpg" border="0" alt="小米的官方声明：不满意可以全额退款" style="border: black 1px solid;" /></p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c140103/13XG5UEC10-154221_lit.jpg{/gemel:field}
