{gemel:field name='keywords'}站长之家, 年度图片, 女同{/gemel:field}
{gemel:field name='description'}焦虑和等待成为2013年的关键词，有的人熬出头，有的人还在熬着。熬着的人们本无差别，疲惫的战士在废墟中渴望自由，劳累的人们在地下心满意足。他们对世界充满期待，他们对{/gemel:field}
{gemel:field name='title'}2013网易新闻年度图片【一直熬】篇{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
