<?php
$z[0]=Array("field","站长之家, 年度图片, 女同",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","焦虑和等待成为2013年的关键词，有的人熬出头，有的人还在熬着。熬着的人们本无差别，疲惫的战士在废墟中渴望自由，劳累的人们在地下心满意足。他们对世界充满期待，他们对",75,355);
$z[1][4]['name']="description";
$z[2]=Array("field","2013网易新闻年度图片【一直熬】篇",357,439);
$z[2][4]['name']="title";
$z[3]=Array("field","",441,478);
$z[3][4]['name']="writer";
$z[4]=Array("field","",480,517);
$z[4][4]['name']="source";
$z[5]=Array("field","",519,554);
$z[5][4]['name']="body";
$z[6]=Array("field","",556,594);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",596,633);
$z[7][4]['name']="litpic";

?>