	
	
	
	
	
<field:body itemname="详细介绍" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">	
</field:body>	

<field:xinxi itemname="产品信息" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:xinxi>

<field:canshu itemname="产品参数" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:canshu>
