<li>
                            <a href="[field:arcurl/]" class="redeem_list_img"><img src="[field:litpic/]" /></a>
                            <a href="[field:arcurl/]">[field:title/]</a><br />
                            <span class="price"></span><br />
                            <span class="credits">[field:credits/]</span>
                            <div class="cboth"></div>
                        </li>