<li ><a href="[field:arcurl/]">
                            <img src="[field:index_news/]" height="227" alt="[field:title/]" width="384" title="[field:title/]" />
                            <h3>[field:title/]</h3>
                            <!-- <p>July 23rd 2017</p> -->
                            <p>[field:description function='cn_substrR(html2text(@me),100)'/]..</p>
                            <span>View More</span>
                        </a></li>