{gemel:field name='keywords'}站长之家, 凡客LOGO, 凡客换{/gemel:field}
{gemel:field name='description'}凡客诚品正在酝酿改变LOGO样式，新的LOGO样式在凡客粉丝团微博中出现。据了解，这是凡客诚品首次尝试更换LOGO。{/gemel:field}
{gemel:field name='title'}凡客或首换LOGO 内测图标曝光{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}
                                                            <p>据悉，凡客诚品正在酝酿改变LOGO样式，新的LOGO样式在凡客粉丝团微博中出现。据了解，这是凡客诚品首次尝试更换LOGO。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130905/13N35422DDP-114K.jpg" border="0" /></p>
<p style="text-align: center;"><strong>凡客新版LOGO效果图</strong></p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130905/13N35422IY40-2O96.jpg" border="0" /></p>
<p style="text-align: center;"><strong>凡客目前LOGO图</strong></p>
<p>凡客诚品媒体公关部总监焦宏宇向亿邦动力网透露：&ldquo;凡客的LOGO已经历经6年，我们一直在寻找更年轻、更时尚的LOGO，但一直都没有超越现在的版本。这次我们只是小范围测试，不代表会更换。&rdquo;</p>
<p>凡客诚品现有LOGO由高塔设计公司设计，从2007年凡客诚品创立使用至今。新版LOGO相关信息目前暂未公布。而对于新版LOGO，网友评价不一，有网友认为&ldquo;很有街头潮范儿&rdquo;，而有人认为很一般。凡客诚品官网目前仍采用原有LOGO。</p>
<p>评论人士推测，此次凡客酝酿新LOGO或是新品牌推广的开端。据悉，陈年日前宣布9月中旬凡客会开始新一轮品牌推广。&ldquo;除了和中国好声音合作，凡客接下来的品牌推广会更加互联网化，届时用户将看到凡客重新做品牌的方法。&rdquo;</p>
<p><strong>【更多电商独家新闻，关注亿邦动力网微信。微信搜：亿邦动力网】</strong></p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130905/13N35422Mb30-3HR.jpg" border="0" /></p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130905/13N35422DDP-114K_lit.jpg{/gemel:field}
