<?php
$z[0]=Array("typelink","",62,79);
$z[1]=Array("typename","",81,98);
$z[2]=Array("sonchannel2","\r\n                                        <li class=\"c3\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                            [field:sonchannel3]\r\n                                            <li class=\"c4\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                            [/field:sonchannel3]\r\n                                        ",149,587);

?>