<div class="three-list">
                        <div class="three-add">
                            <em></em>
                        </div>
                        <h4><a href="{gemel:field.typeurl/}?check=true">{gemel:field.typename/}</a></h4>
                        <div class="three-sort">
                          {gemel:channel type='onlyson'}
                          <p>
                             <i></i><a href="[field:typeurl/]?check=true">[field:typename/]</a>
                          </p>
                          {/gemel:channel}
                        </div>
                    </div>