<li>
	 	 	 	 	 <h2><a href="[field:arcurl/]">[field:title/]</a></h2>
	 	 	 	 	 <a href="[field:arcurl/]"><img src="/images/down-icon.png" title="[field:title/]" alt="[field:title/]" width="162" height="182"/></a>
	 	 	 	 	 <p>[field:description function='cn_substrR(html2text(@me),100)'/]..</p>
	 	 	 	 	 <p>More products let you know</p>
	 	 	 	 	 <div class="icon">
	 	 	 	 	 	<em class="e1"></em>
	 	 	 	 	 	<em class="e2"></em>
	 	 	 	 	 	<a href="[field:arcurl/]"></a>
	 	 	 	 	 </div>
	 	 	 	 </li>