<?php
$z[0]=Array("arcurl","",86,101);
$z[1]=Array("litpic","",113,128);
$z[2]=Array("typename","",137,154);
$z[3]=Array("title","",157,171);
$z[4]=Array("typename","",178,195);
$z[5]=Array("title","",198,212);
$z[6]=Array("arcurl","",376,391);
$z[7]=Array("shorttitle","",393,412);
$z[8]=Array("arcurl","",464,479);
$z[9]=Array("typename","",488,505);
$z[10]=Array("title","",508,522);
$z[11]=Array("title","",524,538);
$z[12]=Array("arcurl","",586,601);
$z[13]=Array("typename","",610,627);
$z[14]=Array("title","",630,644);

?>