
                                <li>
                                    <div class="menulist_img"><a href="[field:typeurl/]"><img src="/images/product/cctv-monitors-menu.jpg" title="CCTV Monitors" alt="CCTV Monitors"/></a></div>
                                    <div class="menulist_right">
                                        <a href="[field:typeurl/]" class="menulist_text text_overflow">[field:typename/]</a>
                                        <p class="menulist_des">[field:description function='substrR(html2text(@me),200)'/]</p>
                                    </div>
                                </li>
                                