{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/150129/pvc-woodgrain-color-edge-banding-m-01-lp.jpg' text='' width='990' height='454'} /upload/allimg/150129/pvc-woodgrain-color-edge-banding-m-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150129/pvc-woodgrain-color-edge-banding-m-02-lp.jpg' text='' width='990' height='454'} /upload/allimg/150129/pvc-woodgrain-color-edge-banding-m-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150129/pvc-woodgrain-color-edge-banding-m-03-lp.jpg' text='' width='990' height='454'} /upload/allimg/150129/pvc-woodgrain-color-edge-banding-m-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150129/pvc-woodgrain-color-edge-banding-m-04-lp.jpg' text='' width='990' height='454'} /upload/allimg/150129/pvc-woodgrain-color-edge-banding-m-04.jpg {/gemel:img}
