<li class="clear">
      <div class="img_left">
          <img src="/upload/products/list-big-04.png" alt="PVC Edge banding" title="PVC Edge banding" width="892" height="562" />
          <div class="left_bg">
             <a href="[field:typelink/]">MORE</a>
          </div>
      </div>
      <div class="text_right text_04">
        <h2><a href="[field:typelink/]">[field:typename/]</a></h2>
        <p>[field:description/]</p>
        <ul class="clear">
          <li class="li_right">
              <a href="/product/3d-crystal-edge-banding/double-color-with-high-glossy-edge-bandi.html"><img src="/upload/products/list-04-02.png" alt="Double Color With High Glossy Edge Banding" title="Double Color With High Glossy Edge Banding" width="173" height="114" /></a>
              <h3>Double Color With High Glossy Edge Banding</h3>
          </li>
          <li>
              <a href="/product/3d-crystal-edge-banding/3d-edge-banding.html"><img src="/upload/products/list-04-01.png" alt="3D Edge Banding" title="3D Edge Banding" width="173" height="114" /></a>
              <h3>3D Edge Banding</h3>
        </ul>
      </div>
    </li>