{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/150724/cosmetic-kiosk-01-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150724/cosmetic-kiosk-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150724/cosmetic-kiosk-02-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150724/cosmetic-kiosk-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150724/cosmetic-kiosk-03-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150724/cosmetic-kiosk-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150724/cosmetic-kiosk-04-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150724/cosmetic-kiosk-04.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150724/cosmetic-kiosk-05-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150724/cosmetic-kiosk-05.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150724/cosmetic-kiosk-06-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150724/cosmetic-kiosk-06.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150724/cosmetic-kiosk-07-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150724/cosmetic-kiosk-07.jpg {/gemel:img}
