{gemel:field name='keywords'}站长之家, 宝洁高管, 数字{/gemel:field}
{gemel:field name='description'}宝洁高管：数字营销已死 网络仅为传播渠道 广告行业最核心的并不是新技术，最根本的还是广告创意。{/gemel:field}
{gemel:field name='title'}宝洁高管：数字营销已死 网络仅为传播渠道{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130923/13OZ140TZ40-194T.jpg" border="0" /></p>
<p><strong>腾讯科技 晨曦 9月22日编译</strong></p>
<p>在互联网普及的1990和2000年代，出现了&ldquo;数字营销&rdquo;和&ldquo;网络营销&rdquo;新词，指的是通过互联网进行品牌和产品营销。</p>
<p>不过，在今天新技术、新平台层出不穷的背景下，宝洁（全世界最大的广告主）负责品牌的高层日前表示，网络营销（或数字营销）的概念已死，网络仅仅是厂商传递品牌信息、和消费者沟通的一个通道而已。</p>
<p>宝洁负责全球品牌建设的高管毕瑞哲（Marc Pritchard）日前在一个集中全球大广告主的行业会议Dmexco上表示：&ldquo;不要根据所使用的工具形成数字营销的概念，比如各种平台、二维码或者更多的新技术。&rdquo;</p>
<p>这位高层表示，在宝洁看来，数字营销的时代已经结束了，所谓的数字化工具，只不过是和消费者沟通的一种手段而已，广告界应该关注的还是通过各种创意、新鲜的广告，来进行品牌建设。</p>
<p>毕瑞哲在会上还举了一个例子，比如一则Braun电动剃须刀的广告，首先会在网络上播出，刺激销售量，随后这则广告也会在传统媒体上播出。他表示，毕瑞哲只不过在进行一次有计划的广告宣传活动，而并不是一次单纯的网络营销。</p>
<p>毕瑞哲表示，这种新的理念，给宝洁的品牌宣传带来了很大的创新空间，他们可以利用各种新技术和互联网手段，比如网络搜索、社交网络、移动广告、二维码，来进行广告创意。</p>
<p>毕瑞哲表示，数字技术或互联网技术，提供了品牌信息传递给消费者的一种全新方式，可以捕捉消费者的想象力。不过，广告行业最核心的并不是新技术，最根本的还是广告创意。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130923/13OZ140TZ40-194T_lit.jpg{/gemel:field}
