<li>
                        <div class="img">
                            <a href="[field:arcurl/]">
                                <img src="[field:litpic/]" width="360" height="240" title="[field:title/]" alt="[field:title/]"/>
                            </a>
                        </div>    
                        <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
                        <p>1220*2440*5~20mm</p>
                    </li>