<li>
						<div class="img">
							<a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="333" height="192"/></a>
							<p>2016-12-07</p>
						</div>
						<div class="text">
							<h4><a href="[field:arcurl/]">[field:title/]</a></h4>
							<p><p>[field:description function='cn_substrR(html2text(@me),100)'/]..</p></p>
							<a href="[field:arcurl/]">readmore</a>
						</div>
					</li>