<?php
$z[0]=Array("typelink","",50,67);
$z[1]=Array("typename","",69,86);
$z[2]=Array("sonchannel1","\r\n                            <li class=\"c2\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                [field:sonchannel2]\r\n                                <li class=\"c3\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                    [field:sonchannel3]\r\n                                    <li class=\"c4\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                    [/field:sonchannel3]\r\n                                [/field:sonchannel2]\r\n                            ",125,725);

?>