{gemel:field name='keywords'}站长之家, 苏宁云商, PPT{/gemel:field}
{gemel:field name='description'}苏宁云商2日晚间发布公告称，2013年12月30日已完成对PPTV的收购，占有PPTV44%的股权，成为其第一大股东。{/gemel:field}
{gemel:field name='title'}苏宁云商完成收购PPTV 占44%股份成第一大股东{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c140103/13XG5VJRZ-42133.jpg" border="0" /></p>
<p>网易科技讯 1月3日消息，苏宁云商2日晚间发布公告称，2013年12月30日已完成对PPTV的收购，占有PPTV44%的股权，成为其第一大股东。</p>
<p>公告称，苏宁云商公司子公司Great Universe limited（为公司全资子公司香港苏宁电器有限公司在开曼群岛设立的全资子公司）与PPTV相关方完成了相关股权转让交割手续，并完成向其管理层发放股权。</p>
<p>公告显示，截至2013年12月31日，苏宁云商已通过子公司向转让方支付对价款21777.62万美元，该对价款以自有资金及向国家开发银行股份有限公司贷款支付。依据协议，剩余对价款将在交割后一年内支付完成。</p>
<p>2013年10月28日，苏宁云商和弘毅投资联合宣布向PPTV投资4.2亿美元。其中，苏宁投资2.5亿美元，占有PPTV44%的股权。(苏素）</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c140103/13XG5VJRZ-42133_lit.jpg{/gemel:field}
