<?php
$z[0]=Array("arclist","\r\n                    <div class=\"pro_more_img\">\r\n                        <a href=\"jacascrit:viod(0);\">\r\n                        <img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\"/>\r\n                        </a>\r\n                    </div>\r\n                    ",26,369);
$z[0][4]['titlelen']="38";
$z[0][4]['row']="1";
$z[0][4]['flag']="c";
$z[1]=Array("field","",454,483);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",485,515);
$z[2][4]['name']="typename";
$z[3]=Array("field","",548,623);
$z[3][4]['name']="description";
$z[3][4]['function']="cn_substrR(html2text(@me),200)";

?>