<li>
                    {gemel:arclist titlelen='38' row='1' flag='c'}
                    <div class="pro_more_img">
                        <a href="jacascrit:viod(0);">
                        <img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]"/>
                        </a>
                    </div>
                    {/gemel:arclist}
                    <div class="pro_more_right">
                        <a href="{gemel:field name='typeurl'/}">{gemel:field name='typename'/}</a>
                        <p>{gemel:field name='description' function='cn_substrR(html2text(@me),200)'/}</p>
                    </div>
                </li>