{gemel:field name='keywords'}站长之家, 富士康, iPad,{/gemel:field}
{gemel:field name='description'}据平板新视界报道，苹果确实是有一款12.9英寸的大屏平板电脑正在富士康进行测试，目前样机正在做UI方面的调试，待机器完全定型，才有可能投入生产。{/gemel:field}
{gemel:field name='title'}富士康调试12.9英寸iPad maxi 或将明年3月推出{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>据平板新视界报道，苹果确实是有一款12.9英寸的大屏平板电脑正在富士康进行测试，目前样机正在做UI方面的调试，待机器完全定型，才有可能投入生产。而这款产品很可能将会在明年3月份发布。虽然我们不能完全确定消息来源的准确性，但是这种可能并不是不存在。另外此前也有消息称屏的大尺寸iPad是 11.4英寸。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0U436430-112G.jpg" border="0" /></p>
<p>可能有不少朋友感到奇怪，苹果怎么可能会推更大尺寸的iPad平板电脑，其实这个道理跟之前苹果为什么要推出iPad mini一样，因为这是苹果平板产品线的空白区域。而且根据各大研究机构的报告显示，明年大尺寸平板电脑市场将会有较大增长，这这部分主要是因为微软Surface平板以及Intel方案的平板笔记本二合一产品的带动。而且在未来，跨界融合依旧是大势所趋，目前众多的品牌平板厂商也在力推。同时在目前的市场上，这一趋势已经在5英寸-7英寸之间的平板手机融合性产品上显现。</p>
<p>当然，可能有朋友会说苹果13.3英寸有Macbook，没必要出个更大尺寸的iPad，但是如果反过来，我们从价格区间来看，目前最便宜的的 Macbook是11.6英寸，价格在6000以上， 而iPad Air在4000多左右，而这中间有着2000多的价格空白区间，这一价格区间苹果并没有合适的产品来覆盖。</p>
<p>总的来看，苹果确实有可能会推出一款大尺寸的平板电脑来对冲其他大尺寸平板的冲击，或许这款平板也将会配备配套的键盘，以实现平板与笔记本的跨界融合。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131106/13SI0U436430-112G_lit.jpg{/gemel:field}
