
                                <li>
                                    <div class="menulist_img"><a href="[field:typeurl/]"><img src="[field:typepic/]" title="[field:typename/]" alt="[field:typename/]"/></a></div>
                                    <div class="menulist_right">
                                        <a href="[field:typeurl/]" class="menulist_text text_overflow">[field:typename/]</a>
                                        <p class="menulist_des">[field:description /]</p>
                                    </div>
                                </li>
                                