{gemel:field name='keywords'}站长之家, 色情网站, 黄色{/gemel:field}
{gemel:field name='description'}据英国广播公司4日报道，英国官方记录显示，英国议会两院电脑去年点击黄色网站累计超过30万次。{/gemel:field}
{gemel:field name='title'}英国官方显示：英议会电脑去年上黄网30万次{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}
                                                            <p>【环球时报记者 陈宗伦】据英国广播公司4日报道，英国官方记录显示，英国议会两院电脑去年点击黄色网站累计超过30万次。</p>
<p>议会下院发言人表示，目前尚不清楚点击这些黄色网站的是议员，还是其他工作人员。议会认为这些数据并非都是&ldquo;主动访问&rdquo;，有可能是第三方软件或网站通过弹出窗口自动连接，从而导致黄色网站访问数据被夸大。</p>
<p>报道称，目前英国议会办公场所工作人员约为5000人。议会电脑点击色情网站的次数在几个月中变化惊人：11月为114884次，而2月份仅为15次。</p>
<p>据报道，英国首相卡梅伦7月宣布将严打色情网站，向连接互联网的家庭提供自动网络过滤器。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
