<li class="clear">

            <a href="[field:arcurl/]" class="news-img">
                <img src="[field:litpic/]" width="200" height="200" alt="[field:title/]" title="[field:title/]">
            </a>
                <div class="news-info">
                    <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
                    <p>[field:description function='cn_substrR(html2text(@me),100)'/]..</p>
                    <a href="[field:arcurl/]" class="more">VIEW MORE</a>
                </div>
            </li>
            <!-- <li class="clear">
            <a href="" class="news-img">
                <img src="/images/case-intro-01.jpg" width="200" height="200" alt="">
            </a>
                <div class="news-info">
                    <h3><a href="">Fence lamp display</a></h3>
                    <p>Our fence lighting is also an option for Europe clients in high-status neighborhoods. Its beauty would not be changed, whether raining or shining, they still look...</p>
                    <a href="" class="more">VIEW MORE</a>
                </div>
            </li>
            <li class="clear">
            <a href="" class="news-img">
                <img src="/images/case-intro-01.jpg" width="200" height="200" alt="">
            </a>
                <div class="news-info">
                    <h3><a href="">Fence lamp display</a></h3>
                    <p>Our fence lighting is also an option for Europe clients in high-status neighborhoods. Its beauty would not be changed, whether raining or shining, they still look...</p>
                    <a href="" class="more">VIEW MORE</a>
                </div>
            </li>
            <li class="clear">
            <a href="" class="news-img">
                <img src="/images/case-intro-01.jpg" width="200" height="200" alt="">
            </a>
                <div class="news-info">
                    <h3><a href="">Fence lamp display</a></h3>
                    <p>Our fence lighting is also an option for Europe clients in high-status neighborhoods. Its beauty would not be changed, whether raining or shining, they still look...</p>
                    <a href="" class="more">VIEW MORE</a>
                </div>
            </li> -->