<?php
$z[0]=Array("field","",88,117);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",148,178);
$z[1][4]['name']="typepic2";
$z[2]=Array("field","",187,217);
$z[2][4]['name']="typename";
$z[3]=Array("field","",224,254);
$z[3][4]['name']="typename";
$z[4]=Array("field","",289,319);
$z[4][4]['name']="typepic2";
$z[5]=Array("field","",538,567);
$z[5][4]['name']="typeurl";
$z[6]=Array("field","",588,618);
$z[6][4]['name']="typename";

?>