<li class="clear">
                              <div class="img">
                                   <a href=""><img src="/images/news-01.jpg" title="3E-E26 HongKong  Electronic" alt="3E-E26 HongKong  Electronic" width="160" height="95" /></a>
                              </div>
                              <div class="text">
                                    <h3><a href="" title="">3E-E26 HongKong  Electronic</a></h3>
                                    <p>SHOW: 2015.10.13-2015.10.16</p>
                                    <a href="">READ MORE</a>    
                              </div>   
                           </li>