<?php
$z[0]=Array("typelink","",54,71);
$z[1]=Array("typename","",73,90);
$z[2]=Array("sonchannel1","\r\n                                <li class=\"c2\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                    [field:sonchannel2]\r\n                                    <li class=\"c3\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                        [field:sonchannel3]\r\n                                        <li class=\"c4\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                        [/field:sonchannel3]\r\n                                    [/field:sonchannel2]\r\n                                ",133,765);

?>