<?php
$z[0]=Array("pagestyle","",0,92);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/131009/1-131009120G0.jpg ",94,238);
$z[1][4]['ddimg']="/upload/allimg/131009/1-131009120G0-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="205";
$z[1][4]['height']="150";
$z[2]=Array("img"," /upload/allimg/131009/1-131009120G3.jpg ",240,384);
$z[2][4]['ddimg']="/upload/allimg/131009/1-131009120G3-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="205";
$z[2][4]['height']="150";
$z[3]=Array("img"," /upload/allimg/131009/1-131009120G6.jpg ",386,530);
$z[3][4]['ddimg']="/upload/allimg/131009/1-131009120G6-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="205";
$z[3][4]['height']="150";
$z[4]=Array("img"," /upload/allimg/131009/1-131009120G8.jpg ",532,676);
$z[4][4]['ddimg']="/upload/allimg/131009/1-131009120G8-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="205";
$z[4][4]['height']="150";
$z[5]=Array("img"," /upload/allimg/131009/1-131009120H3.jpg ",678,822);
$z[5][4]['ddimg']="/upload/allimg/131009/1-131009120H3-lp.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="205";
$z[5][4]['height']="150";

?>