<li>
                        <div class="downloadlist_left">
                            <span>22</span>
                            <a href="[field:download/]">下载</a>      
                        </div>
                        <div class="downloadlist_right">
                            <a href="[field:download/]">[field:title/]</a>
                            <p class="downloadlist_des">[field:description function='cn_substrR(html2text(@me),120)'/]...</p>
                            <p>[field:pubdate function="MyDate('Y-m-d H:i',@me)"/]</p>
                        </div>
                        <div class="clear"></div>
                    </li>