<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/140528/1-14052PZ446.jpg ",96,242);
$z[1][4]['ddimg']="/upload/allimg/140528/1-14052PZ446-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="734";
$z[1][4]['height']="321";
$z[2]=Array("img"," /upload/allimg/140528/1-14052PZ447.jpg ",244,390);
$z[2][4]['ddimg']="/upload/allimg/140528/1-14052PZ447-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="734";
$z[2][4]['height']="321";
$z[3]=Array("img"," /upload/allimg/140528/1-14052PZ448.jpg ",392,538);
$z[3][4]['ddimg']="/upload/allimg/140528/1-14052PZ448-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="734";
$z[3][4]['height']="321";

?>