<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/140528/1-14052Q01041.jpg ",96,238);
$z[1][4]['ddimg']="/upload/allimg/140528/1-14052Q01041-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="";
$z[1][4]['height']="";
$z[2]=Array("img"," /upload/allimg/140528/1-14052Q01042.jpg ",240,382);
$z[2][4]['ddimg']="/upload/allimg/140528/1-14052Q01042-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="";
$z[2][4]['height']="";
$z[3]=Array("img"," /upload/allimg/140528/1-14052Q01043.jpg ",384,526);
$z[3][4]['ddimg']="/upload/allimg/140528/1-14052Q01043-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="";
$z[3][4]['height']="";

?>