{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140528/1-14052PZG6-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PZG6.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PZG7-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PZG7.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PZG8-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PZG8.jpg {/gemel:img}
