<?php
$z[0]=Array("arcurl","",86,101);
$z[1]=Array("litpic","",113,128);
$z[2]=Array("typename","",137,154);
$z[3]=Array("title","",157,171);
$z[4]=Array("typename","",178,195);
$z[5]=Array("title","",198,212);
$z[6]=Array("arcurl","",368,383);
$z[7]=Array("typename","",385,402);
$z[8]=Array("arcurl","",458,473);
$z[9]=Array("typename","",482,499);
$z[10]=Array("title","",502,516);
$z[11]=Array("title","",518,532);
$z[12]=Array("arcurl","",580,595);
$z[13]=Array("typename","",604,621);
$z[14]=Array("title","",624,638);

?>