<?php
$z[0]=Array("arclist","\r\n				<div class=\"indexpro_img\">\r\n					<a href=\"[field:arcurl/]\">\r\n                    <img src=\"[field:litpic/]\" width=\"217\" height=\"120\" title=\"[field:title/]\" alt=\"[field:title/]\"/>\r\n                    </a>\r\n					<span>{gemel:field name='new_pro'/}</span>\r\n				</div>\r\n                ",22,407);
$z[0][4]['titlelen']="38";
$z[0][4]['row']="1";
$z[0][4]['flag']="c";
$z[0][4]['addfields']="new_pro";
$z[0][4]['channelid']="3";
$z[1]=Array("field","",422,451);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",475,505);
$z[2][4]['name']="typename";

?>