<li>
                {gemel:arclist titlelen='38' row='1' flag='c' addfields='new_pro' channelid='3'}
				<div class="indexpro_img">
					<a href="[field:arcurl/]">
                    <img src="[field:litpic/]" width="217" height="120" title="[field:title/]" alt="[field:title/]"/>
                    </a>
					<span>{gemel:field name='new_pro'/}</span>
				</div>
                {/gemel:arclist}
				<a href="{gemel:field name='typeurl'/}" class="indexpro_text">{gemel:field name='typename'/}</a>
			</li>