<?php
$z[0]=Array("field","站长之家, 诺基亚, 谷歌",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","图片中是一个三星GalaxyS3被掰为两半,与KitKat巧克力的广告十分相似,其广告语也采用了雀巢的Have a break(放松一下, break也有弄坏的意思)。",72,292);
$z[1][4]['name']="description";
$z[2]=Array("field","诺基亚对谷歌Android KitKat放出\"死亡威胁\"",294,382);
$z[2][4]['name']="title";
$z[3]=Array("field","",384,421);
$z[3][4]['name']="writer";
$z[4]=Array("field","",423,460);
$z[4][4]['name']="source";
$z[5]=Array("field","\n                                                            <p style=\"text-align: center; text-indent: 0;\"><img src=\"/upload/allimg/c130905/13N3542294H0-64949.jpg\" border=\"0\" /></p>\n<p>图片中是一个三星GalaxyS3被掰为两半,与KitKat巧克力的广告十分相似,其广告语也采用了雀巢的Have a break(放松一下, break也有弄坏的意思)。</p>\n<p>诺基亚曾经也对三星的Ativ S系列Windows Phone进行了无情地嘲讽.而在本周,诺基亚英国分公司在三星Galaxy S4的广告牌前边停了一辆大卡车,车身上满满的是诺基亚Lumia 1020的广告.可是诺基亚的这些努力还是没能使其击败三星,后者在上个季度销售了超过7000万台手机,而诺基亚仅有740万,而这也打破了其自己的销售记录。</p>\n<p style=\"text-align: center; text-indent: 0;\"><img src=\"/upload/allimg/c130905/13N35422c620-KG8.png\" border=\"0\" /></p>",462,1402);
$z[5][4]['name']="body";
$z[6]=Array("field","",1404,1442);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/upload/allimg/c130905/13N3542294H0-64949_lit.jpg",1444,1530);
$z[7][4]['name']="litpic";

?>