{gemel:field name='keywords'}站长之家, 诺基亚, 谷歌{/gemel:field}
{gemel:field name='description'}图片中是一个三星GalaxyS3被掰为两半,与KitKat巧克力的广告十分相似,其广告语也采用了雀巢的Have a break(放松一下, break也有弄坏的意思)。{/gemel:field}
{gemel:field name='title'}诺基亚对谷歌Android KitKat放出"死亡威胁"{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130905/13N3542294H0-64949.jpg" border="0" /></p>
<p>图片中是一个三星GalaxyS3被掰为两半,与KitKat巧克力的广告十分相似,其广告语也采用了雀巢的Have a break(放松一下, break也有弄坏的意思)。</p>
<p>诺基亚曾经也对三星的Ativ S系列Windows Phone进行了无情地嘲讽.而在本周,诺基亚英国分公司在三星Galaxy S4的广告牌前边停了一辆大卡车,车身上满满的是诺基亚Lumia 1020的广告.可是诺基亚的这些努力还是没能使其击败三星,后者在上个季度销售了超过7000万台手机,而诺基亚仅有740万,而这也打破了其自己的销售记录。</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130905/13N35422c620-KG8.png" border="0" /></p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130905/13N3542294H0-64949_lit.jpg{/gemel:field}
