<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/151215/arc-01.png ",96,230);
$z[1][4]['ddimg']="/upload/allimg/151215/arc-01-lp.png";
$z[1][4]['text']="";
$z[1][4]['width']="540";
$z[1][4]['height']="670";
$z[2]=Array("img"," /upload/allimg/151215/arc-02.png ",232,366);
$z[2][4]['ddimg']="/upload/allimg/151215/arc-02-lp.png";
$z[2][4]['text']="";
$z[2][4]['width']="540";
$z[2][4]['height']="670";
$z[3]=Array("img"," /upload/allimg/151215/arc-03.png ",368,502);
$z[3][4]['ddimg']="/upload/allimg/151215/arc-03-lp.png";
$z[3][4]['text']="";
$z[3][4]['width']="540";
$z[3][4]['height']="670";

?>