{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/151215/arc-01-lp.png' text='' width='540' height='670'} /upload/allimg/151215/arc-01.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151215/arc-02-lp.png' text='' width='540' height='670'} /upload/allimg/151215/arc-02.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151215/arc-03-lp.png' text='' width='540' height='670'} /upload/allimg/151215/arc-03.png {/gemel:img}
