{gemel:field name='keywords'}站长之家, 百度搜索, 360搜{/gemel:field}
{gemel:field name='description'}数据公司Hitwise今日发布的搜索数据显示，2013年8月百度搜索点击份额为74.34%，较上月微涨；360搜索份额为15.12%，较上月微跌。其中，360搜索份额中导航站75.4%，自有品牌s{/gemel:field}
{gemel:field name='title'}Hitwise：8月百度搜索份额微涨 360微跌{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}
                                                            <p style="text-indent: 0px; text-align: center;"><img src="/upload/allimg/c130905/13N35422493410-J2R.jpg" border="0" width="550" alt="Hitwise今日发布的8月搜索市场数据" height="413" /></p>
<p style="text-align: center;">Hitwise今日发布的8月搜索市场数据</p>
<p>新浪科技讯 9月4日下午消息，数据公司Hitwise今日发布的搜索数据显示，2013年8月百度搜索点击份额为74.34%，较上月微涨；360搜索份额为15.12%，较上月微跌。其中，360搜索份额中导航站75.4%，自有品牌so.com占24.6%，仍以360导航和浏览器贡献为主。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130905/13N35422493410-J2R_lit.jpg{/gemel:field}
