<?php
$z[0]=Array("field","站长之家, 百度搜索, 360搜",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","数据公司Hitwise今日发布的搜索数据显示，2013年8月百度搜索点击份额为74.34%，较上月微涨；360搜索份额为15.12%，较上月微跌。其中，360搜索份额中导航站75.4%，自有品牌s",75,339);
$z[1][4]['name']="description";
$z[2]=Array("field","Hitwise：8月百度搜索份额微涨 360微跌",341,425);
$z[2][4]['name']="title";
$z[3]=Array("field","",427,464);
$z[3][4]['name']="writer";
$z[4]=Array("field","",466,503);
$z[4][4]['name']="source";
$z[5]=Array("field","\n                                                            <p style=\"text-indent: 0px; text-align: center;\"><img src=\"/upload/allimg/c130905/13N35422493410-J2R.jpg\" border=\"0\" width=\"550\" alt=\"Hitwise今日发布的8月搜索市场数据\" height=\"413\" /></p>\n<p style=\"text-align: center;\">Hitwise今日发布的8月搜索市场数据</p>\n<p>新浪科技讯 9月4日下午消息，数据公司Hitwise今日发布的搜索数据显示，2013年8月百度搜索点击份额为74.34%，较上月微涨；360搜索份额为15.12%，较上月微跌。其中，360搜索份额中导航站75.4%，自有品牌so.com占24.6%，仍以360导航和浏览器贡献为主。</p>",505,1207);
$z[5][4]['name']="body";
$z[6]=Array("field","",1209,1247);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/upload/allimg/c130905/13N35422493410-J2R_lit.jpg",1249,1335);
$z[7][4]['name']="litpic";

?>