<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/160108/waterproof-medical-belt-01.jpg-50 ",96,273);
$z[1][4]['ddimg']="/upload/allimg/160108/waterproof-medical-belt-01.jpg-50";
$z[1][4]['text']="";
$z[1][4]['width']="458";
$z[1][4]['height']="458";

?>