		
	  <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='图片集' ischannel='1' link='content_i_list.php?channelid=2' linkadd='album_add.php?channelid=2' channelid='2' rank='' target='main' />
  <m:item name='下载模型' ischannel='1' link='content_list.php?channelid=14' linkadd='article_add.php?channelid=14' channelid='14' rank='' target='main' />
		
