{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140620/1-1406201T559-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201T559.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201T605-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201T605.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201T646-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201T646.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201TF2-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201TF2.jpg {/gemel:img}
