{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140620/1-1406201AJ7-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201AJ7.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201AK0-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201AK0.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201AK3-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201AK3.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201AK9-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201AK9.jpg {/gemel:img}
