{gemel:field name='keywords'}站长之家, 小米, 米Pad, 移{/gemel:field}
{gemel:field name='description'}今日下午2点，小米将在北京国家会议中心正式召开“年度产品发布会”，而小米3手机、小米电视、小米pad都在消费者的期待中，此次新品发布会牵动着亿万粉丝的心。{/gemel:field}
{gemel:field name='title'}小米年度发布会前瞻小米3、米pad、电视或亮相{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}
                                                            <p><strong>速途网9月5日消息(报道 张雨芹)</strong> 今日下午2点，小米将在北京国家会议中心正式召开&ldquo;年度产品发布会&rdquo;，而小米3手机、小米电视、小米pad都在消费者的期待中，此次新品发布会牵动着亿万粉丝的心。</p>
<p><img src="/upload/allimg/c130905/13N35423349150-161M.jpg" border="0" style="display: block; margin-left: auto; margin-right: auto;" /></p>
<p>　<strong>　图：小米年度发布会「倚天剑、屠龙刀」的主题宣传海报(速途网配图)</strong></p>
<p>此前，小米发布会邀请函曝光，全新的类似于画册与小尺寸平板电脑相当包装盒引发业内猜想，这或许是小米公司的一个暗示，米Pad终于要来了?此外，从宣传海报中「倚天剑、屠龙刀」的主题来看，这一次小米很有可能会为我们带来两款不同的产品，小米3手机、小米电视、小米笔记本都在消费者的期待中。</p>
<p><img src="/upload/allimg/c130905/13N354233a3P-21518.png" border="0" /></p>
<p style="text-align: center;">　<strong>　图：小米3三代谍照曝光(速途网配图)</strong></p>
<p>目前还有消息称，小米3代摄像头组合为1300万像素主摄像头+500万前置摄像头，将有两个版本，而它们配备的都是5寸屏幕，供应商为夏普和JDI，处理器分为Tegra 4和骁龙800。其中前者支持移动的td-SCDMA网络，而后者则支持电信和联通网络，骁龙800版的小米3代会比Tegra 4版本上市时间晚一个月左右，外形设计上很有可能极其方正硬朗的，有明显的Lumia路线。</p>
<p><img src="/upload/allimg/c130905/13N35423534420-391b.png" border="0" style="display: block; margin-left: auto; margin-right: auto;" /></p>
<p style="text-align: center;">　　<strong>图：小米电视谍照曝光(速途网配图)</strong></p>
<p>　　而小米电视谍照也多次传出，从包装箱照片来看，曝光的小米电视型号为L47M1-AA，尺寸为47英寸，分辨率达到1080P级别，支持杜比音效、dts数字化影院系统并且内建Wi-Fi同时内置米联等应用。有消息称小米电视与之前发布的乐视TV一样都由富士康代工制造。若传闻属实，小米电视一旦发布，依照小米此前风格，必将对市场造成很大震动。</p>
<p>　　当然，在9月5日下午发布会之前，一切还有变数。同时在召开发布会之前小米公司第四轮融资尘埃落定，雷军在微博上确认小米100亿美元的估值。届时在发布会上有会给大家带来哪些惊喜，让我们拭目以待。</p>
<p>&nbsp;</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130905/13N35423349150-161M_lit.jpg{/gemel:field}
