<?php
$z[0]=Array("field","",46,68);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",70,93);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","                                      \r\n                 <li>\r\n                     <a href=\"[field:arcurl/]\"><img src=\"/images/home-products-01.png\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"384\" height=\"287\" /></a>\r\n                     <p><a href=\"[field:arcurl/]\">[field:shorttitle/]</a></p>\r\n                 </li>\r\n                 ",155,573);
$z[2][4]['orderby']="weight";
$z[2][4]['titlelen']="40";
$z[2][4]['row']="10";

?>