<li class="clear">
                  <div class="img">
                      <a href="{gemel:field name='typeurl'/}index.html#case-box"><img src="{gemel:field name='typepic2'/}" title="{gemel:field name='typename'/}" alt="{gemel:field name='typename'/}" width="54" height="54" /></a>
                  </div>
                  <h3><a href="{gemel:field name='typeurl'/}index.html#case-box">{gemel:field name='typename'/}</a></h3>
              </li>