<?php
$z[0]=Array("arclist","\r\n				<div class=\"indexpro_img\">\r\n					<a href=\"jacascrit:viod(0);\">\r\n                    <img src=\"[field:litpic/]\" width=\"217\" height=\"120\" title=\"[field:title/]\" alt=\"[field:title/]\"/>\r\n                    </a>\r\n					<span>[field:new_pro/]</span>\r\n				</div>\r\n                ",22,397);
$z[0][4]['titlelen']="38";
$z[0][4]['row']="1";
$z[0][4]['flag']="c";
$z[0][4]['addfields']="new_pro";
$z[0][4]['channelid']="2";
$z[1]=Array("field","",412,441);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",465,495);
$z[2][4]['name']="typename";

?>