<?php
$z[0]=Array("type","<a href='{gemel:field name='typeurl'/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",4,269);
$z[0][4]['typeid']="1";
$z[1]=Array("channelartlist","\r\n                                         \r\n                                           <li><a href='{gemel:field name='typeurl'",368,572);
$z[1][4]['typeid']="4";
$z[1][4]['row']="6";
$z[1][4]['type']="son";
$z[1][4]['currentstyle']="select";
$z[2]=Array("field","",581,608);
$z[2][4]['name']="currentstyle";
$z[3]=Array("field","",620,649);
$z[3][4]['name']="typepic";
$z[4]=Array("field","",656,686);
$z[4][4]['name']="typename";
$z[5]=Array("field","",695,725);
$z[5][4]['name']="typename";
$z[6]=Array("field","",758,788);
$z[6][4]['name']="typename";

?>