{gemel:field name='keywords'}站长之家, 微软, Skype中国{/gemel:field}
{gemel:field name='description'}微软本周表示，尽管TOM在线即将停止Skype在中国的运营，但微软不会完全接管Skype的中国业务，而是将组建新的合资公司。这与媒体此前报道不同。{/gemel:field}
{gemel:field name='title'}微软称不会接管Skype中国业务：将组建合资公司{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>新浪科技讯 北京时间11月12日早间消息，微软本周表示，尽管TOM在线即将停止Skype在中国的运营，但微软不会完全接管Skype的中国业务，而是将组建新的合资公司。这与媒体此前报道不同。</p>
<p>此前的媒体报道来自TOM在线上周发布的不准确公告。当时TOM在线表示，微软将从11月24日开始接管Skype在中国的业务。此外公告还宣布，Skype在中国的用户数已突破1亿。</p>
<p>Skype亚太区主管朱德&middot;哈康姆比(Judd Harcombe)此次表示：&ldquo;Skype致力于向用户提供尽可能好的体验，并确认与TOM在线的合作即将结束。我们感谢过去多年中他们的合作和支持。&rdquo;</p>
<p>他同时表示：&ldquo;TOM在线错误地夸大了我们在中国的连接用户数。我们在全球范围内拥有超过3亿连接用户，但不会公布不同国家的用户数。在中国，Skype通过合资公司提供软件，这符合现有程序，并按照当地法律履行义务。我们将很快分享新合资公司的最新消息。&rdquo;(维金)</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
