<li>
                <div class="list_left">
                      <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="398" height="275" /></a>
                </div>
                <div class="list_right">
                      <h2>[field:title/]</h2>
                      <p>[field:description function='cn_substr(@me,240)'/]....</p>
                      <a href="[field:arcurl/]">Read More</a>
                </div>
          </li>