<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/140709/anal-vibrator-vmls2509-01.jpg ",96,268);
$z[1][4]['ddimg']="/upload/allimg/140709/anal-vibrator-vmls2509-01-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="270";
$z[1][4]['height']="290";
$z[2]=Array("img"," /upload/allimg/140709/anal-vibrator-vmls2509-02.jpg ",270,442);
$z[2][4]['ddimg']="/upload/allimg/140709/anal-vibrator-vmls2509-02-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="270";
$z[2][4]['height']="290";
$z[3]=Array("img"," /upload/allimg/140709/anal-vibrator-vmls2509-03.jpg ",444,616);
$z[3][4]['ddimg']="/upload/allimg/140709/anal-vibrator-vmls2509-03-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="270";
$z[3][4]['height']="290";
$z[4]=Array("img"," /upload/allimg/140709/anal-vibrator-vmls2509-04.jpg ",618,790);
$z[4][4]['ddimg']="/upload/allimg/140709/anal-vibrator-vmls2509-04-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="270";
$z[4][4]['height']="290";
$z[5]=Array("img"," /upload/allimg/140709/anal-vibrator-vmls2509-05.jpg ",792,964);
$z[5][4]['ddimg']="/upload/allimg/140709/anal-vibrator-vmls2509-05-lp.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="270";
$z[5][4]['height']="290";

?>