<li class="clear">
                            <a href="[field:arcurl/]"><img src="[field:index_news01/]" alt="[field:title/]" width="165" height="132" title="[field:title/]" /> </a>
                            <div class="list-text">
                                <h4><a href="[field:arcurl/]">[field:title/]</a></h4>
                                <p><a href="[field:arcurl/]">[field:description function='cn_substrR(html2text(@me),100)'/]..</a></p>
                            </div>
                        </li>