<li class="clear">
					<div class="img">
						<a href="[field:arcurl/]"><img src="/images/latest-news-01.jpg" title="[field:title/]" alt="[field:title/]" width="84" height="84"/></a>
					</div>
					<div class="text">
						<h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
						<p>[field:description function='cn_substrR(html2text(@me),68)'/]...</p>
					</div>
				</li>