<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/170621/sdt2-01.jpg ",96,232);
$z[1][4]['ddimg']="/upload/allimg/170621/sdt2-01-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="566";
$z[1][4]['height']="429";
$z[2]=Array("img"," /upload/allimg/170621/sdt2-01.jpg-50 ",234,373);
$z[2][4]['ddimg']="/upload/allimg/170621/sdt2-01.jpg-50";
$z[2][4]['text']="";
$z[2][4]['width']="566";
$z[2][4]['height']="429";
$z[3]=Array("img"," /upload/allimg/170621/sdt2-02.png ",375,511);
$z[3][4]['ddimg']="/upload/allimg/170621/sdt2-02-lp.png";
$z[3][4]['text']="";
$z[3][4]['width']="566";
$z[3][4]['height']="429";

?>