<li class="clear">
                  <div class="img">
                      <a href="{gemel:field name='typeurl'/}index.html#case-box"><img src="/images/case/led-high-bay.jpg" title="{gemel:field name='typename'/}" alt="{gemel:field name='typename'/}" width="54" height="54" /></a><!--{gemel:field name='typepic2'/}-->
                  </div>
                  <div class="case-con">  
                        <div class="middle">   
                             <div class="inner">
                                <h3><a href="{gemel:field name='typeurl'/}index.html#case-box">{gemel:field name='typename'/}</a></h3>
                             </div>    
                        </div>     
                  </div> 
              </li>