{gemel:field name='keywords'}站长之家, 比尔·盖茨, 微{/gemel:field}
{gemel:field name='description'}上个月，微软公司CEO史蒂夫·鲍尔默突然宣布即将退休，微软创始人比尔盖茨将再度出山执掌公司的老话题又被炒了起来。在最近Business Insider对盖茨的采访中，盖茨重申了他{/gemel:field}
{gemel:field name='title'}比尔·盖茨：我不会再当微软CEO{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p>上个月，微软公司CEO史蒂夫&middot;鲍尔默突然宣布即将退休，微软创始人比尔盖茨将再度出山执掌公司的老话题又被炒了起来。不过，就像以往一样，在最近Business Insider对盖茨的采访中，盖茨重申了他的态度：不会再度担任微软掌门人。</p>
<p>BI在采访中询问盖茨有关是否重新执掌公司时，盖茨并没有坚定地否认这个问题，他说：&ldquo;不会的，我曾经担任微软CEO，如今，我作为微软董事会主席，将部分地参与帮助微软找到新的CEO。&rdquo;</p>
<p>当然，盖茨只是委婉的否认而已。从目前掌握的情况来看，盖茨一直忙于盖茨&middot;梅琳达基金会的工作，无意同时也没必要再度出任CEO。</p>
<p>以下就是BI的采访及盖茨的回答：</p>
<p>BI：你一直对全球健康和贫困问题充满激情，不过，有没有这种可能&mdash;&mdash;放弃当前的基金会工作而再度出任微软首席执行官？</p>
<p>盖茨：不会的，我曾经担任微软首席执行官一段时间，如今，我是微软的董事会主席，我将参与部分的相关工作，我的专职工作仍在基金会这边，我不会专职于微软首席执行官这一职位。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
