<?php
$z[0]=Array("field","",13,42);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",51,78);
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",90,119);
$z[2][4]['name']="typepic";
$z[3]=Array("field","",126,156);
$z[3][4]['name']="typename";
$z[4]=Array("field","",165,195);
$z[4][4]['name']="typename";
$z[5]=Array("field","",228,258);
$z[5][4]['name']="typename";
$z[6]=Array("type","<a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",405,707);
$z[6][4]['typeid']="12";
$z[7]=Array("type","<a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",757,1059);
$z[7][4]['typeid']="13";
$z[8]=Array("type","<a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",1109,1411);
$z[8][4]['typeid']="14";
$z[9]=Array("type","<a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",1461,1763);
$z[9][4]['typeid']="15";
$z[10]=Array("type","<a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",1813,2115);
$z[10][4]['typeid']="16";
$z[11]=Array("type","<a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"88\" height=\"88\" /><span>{gemel:field name='typename'/}</span></a>",2165,2467);
$z[11][4]['typeid']="17";

?>