<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/150824/cmp-01-01.jpg ",96,236);
$z[1][4]['ddimg']="/upload/allimg/150824/cmp-01-01-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="495";
$z[1][4]['height']="365";
$z[2]=Array("img"," /upload/allimg/150824/cmp-01-02.jpg ",238,378);
$z[2][4]['ddimg']="/upload/allimg/150824/cmp-01-02-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="495";
$z[2][4]['height']="365";
$z[3]=Array("img"," /upload/allimg/150824/cmp-01-03.jpg ",380,520);
$z[3][4]['ddimg']="/upload/allimg/150824/cmp-01-03-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="495";
$z[3][4]['height']="365";
$z[4]=Array("img"," /upload/allimg/150824/cmp-01-04.jpg ",522,662);
$z[4][4]['ddimg']="/upload/allimg/150824/cmp-01-04-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="495";
$z[4][4]['height']="365";

?>