{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/150824/cmp-01-01-lp.jpg' text='' width='495' height='365'} /upload/allimg/150824/cmp-01-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150824/cmp-01-02-lp.jpg' text='' width='495' height='365'} /upload/allimg/150824/cmp-01-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150824/cmp-01-03-lp.jpg' text='' width='495' height='365'} /upload/allimg/150824/cmp-01-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150824/cmp-01-04-lp.jpg' text='' width='495' height='365'} /upload/allimg/150824/cmp-01-04.jpg {/gemel:img}
