{gemel:field name='keywords'}站长之家, 苹果, ios7, 漏洞{/gemel:field}
{gemel:field name='description'}苹果2天前开放最新的移动操作系统iOS 7下载，随即频频爆出漏洞。继“iOS 7可以绕过锁屏直接删除照片”引发广泛讨论外，今天又有国外媒体爆出“iOS 7可以让任何人在已密码锁{/gemel:field}
{gemel:field name='title'}苹果iOS 7再现漏洞  低级错误值得深思{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p class="p0"><strong>站长之家（<font face="Times New Roman">Chinaz.com</font><font face="宋体">）9月22日</font>讯：</strong>苹果2天前开放最新的移动操作系统iOS&nbsp;7下载，随即被频频爆出漏洞。继&ldquo;iOS&nbsp;7可以绕过锁屏直接删除照片&rdquo;引发广泛讨论外，今天又有国外媒体爆出&ldquo;iOS&nbsp;7可以让任何人在已密码锁屏的iPhone拨打电话&rdquo;的漏洞，再次引发消费者的担忧。</p>
<p style="text-align: center;"><img src="/upload/allimg/c130923/13OZ1405T420-13631.jpg" border="0" alt="苹果ios7显现漏洞" /></p>
<p style="text-align: center; font-size: 12px; text-indent: 0;">苹果ios7显现漏洞</p>
<p>据悉，约旦人Karam&nbsp;Daoud发现了该漏洞。在他上传的视频中可以看出，一部运行iOS&nbsp;7的iPhone处于锁屏状态时点击&ldquo;紧急呼叫&rdquo;按钮，然后随便输入任何号码并不停地快速按动呼叫按钮，直到系统崩溃并出现苹果Logo的黑屏，这个电话就可以被成功拨打出去。国外某知名媒体作家Andy&nbsp;Greenberg，针对这一漏洞做出了测试，证实老款的iPhone机型也同样存在这一问题。但连续第二次激发这个漏洞时拨打时间有所延迟。</p>
<p>这次漏洞虽然不同上次&ldquo;可以锁屏删照片&rdquo;，这种涉及隐私的担忧，但问题依然十分严重。&ldquo;利用这一漏洞可以任意拨打任何号码，比如收费高昂的付费号码、国际长途等，如果被人恶意利用，那么就可能让机主损失惨重。&rdquo;有媒体发出警告称。</p>
<p>事实上，这早已不是iOS系统历史上第一个被发现的&ldquo;紧急呼叫&rdquo;漏洞了，因为在iOS&nbsp;6中也存在着用户可以绕过锁屏而打开联系人或者通话界面的漏洞。那么，为什么苹果一而再的犯这种看似十分低级又关联重大的错误呢？</p>
<p>&ldquo;&lsquo;乔布斯时代&rsquo;结束后，苹果失去了对产品品质的把控，开始像android一样注重为系统增加新功能，而不在能确保一些基本功能的安全，苹果产品正在变得平庸。&rdquo;有不少人这样归结。或许，对于苹果来说，当中的有些批评过于苛刻，毕竟它还有许多相较其他产品独到的地方，但无论如何，类似低级的错误着实应引起苹果的重视。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130923/13OZ1405T420-13631_lit.jpg{/gemel:field}
