<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/140505/1-140505202431.jpg ",96,244);
$z[1][4]['ddimg']="/upload/allimg/140505/1-140505202431-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="73";
$z[1][4]['height']="45";
$z[2]=Array("img"," /upload/allimg/140505/1-140505202432.jpg ",246,394);
$z[2][4]['ddimg']="/upload/allimg/140505/1-140505202432-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="72";
$z[2][4]['height']="54";

?>