<?php
$z[0]=Array("field","站长之家, Bing, 自动填充功",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","Bing发布了一个“零距离深度体验”，这是一项新的搜索功能，能直接从搜索框快捷找到与搜索词相关的信息，并提供深层链接介绍。",76,293);
$z[1][4]['name']="description";
$z[2]=Array("field","Bing推出自动填充功能升级版：零距离体验",295,386);
$z[2][4]['name']="title";
$z[3]=Array("field","",388,425);
$z[3][4]['name']="writer";
$z[4]=Array("field","",427,464);
$z[4][4]['name']="source";
$z[5]=Array("field","<p style=\"text-align:center;\">      </p>\n                                                            <p>Bing发布了一个&ldquo;零距离深度体验&rdquo;，这是一项新的搜索功能，能直接从搜索框快捷找到与搜索词相关的信息，并提供深层链接介绍。Bing说到：我们的任务是帮助您用更少的时间进行搜索用更多的时间把事情做好。如下图所示：</p>\n<p style=\"text-align: center; text-indent: 0;\"><img src=\"/upload/allimg/c130925/13P0S05Z5250-19211.jpg\" border=\"0\" width=\"537\" alt=\"Bing推出自动填充功能升级版：零距离体验\" title=\"Bing推出自动填充功能升级版：零距离体验\" height=\"388\" /></p>\n<p>这个新的搜索功能我认为应该是<strong>&ldquo;自动填充&rdquo;的升级版</strong>，目前仅在英文版中才出现。可以看到，搜索某个人名(明星)左侧出现自动填充的关键词，中间出现任务头像、简介，右侧出现相关的新闻、图片搜索。</p>\n<p>这功能可以使用户的再减少一个点击，试想下，如果Google或百度也出这个功能，那么会是个什么情况?搜索引擎会指引用户搜出更完整、更精准的关键词，从而使得搜索结果、竞价广告更加匹配，何乐而不为呢？</p>",466,1779);
$z[5][4]['name']="body";
$z[6]=Array("field","",1781,1819);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/upload/allimg/c130925/13P0S05Z5250-19211_lit.jpg",1821,1907);
$z[7][4]['name']="litpic";

?>