<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/150327/ac-6b14-3b-02x-m-01.jpg ",96,256);
$z[1][4]['ddimg']="/upload/allimg/150327/ac-6b14-3b-02x-m-01-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="712";
$z[1][4]['height']="352";

?>