<li>
                        <div class="downloadlist_left">
                            <span>22</span>
                            <a href="/upload/pdf/download.php?filename=[field:download/]">下载</a>      
                        </div>
                        <div class="downloadlist_right">
                            <a href="[field:arcurl/]">[field:title/]</a>
                            <p>[field:description function='cn_substrR(html2text(@me),120)'/]...</p>
                        </div>
                    </li>