{gemel:field name='keywords'}站长之家, Twitter, TwitterI{/gemel:field}
{gemel:field name='description'}据悉，Twitter进行首次公开招股（IPO）计划融资10多亿美元的资金，该公司支付给承销商的佣金仅为募集资金总额的3.25%。资本市场数据和咨询公司Ipreo提供的数据显示，虽然按{/gemel:field}
{gemel:field name='title'}陷阱还是机遇？Twitter将获10亿美元授信额度{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131015/13QR14M53160-140H.jpg" border="0" alt="陷阱还是机遇？Twitter将获10亿美元授信额度" /></p>
<p>腾讯科技 无忌&nbsp;10月14日编译</p>
<p>消息人士透露，Twitter从投资银行获得10亿美元授信额度的工作已接近完成。</p>
<p>据悉，Twitter进行首次公开招股（IPO）计划融资10多亿美元的资金，该公司支付给承销商的佣金仅为募集资金总额的3.25%。资本市场数据和咨询公司Ipreo提供的数据显示，虽然按此比例计算，承销商仍将获得数千万美元的费用，但是3.25%也将是一年多来在美国证券市场进行首次公开招股的最低佣金比例。</p>
<p>更为重要的是，Twitter将会从代理首次公开招股的投资银行获得10亿美元的信贷额度，以支持公司的成长，而这项工作已接近于完成。不过在一些市场分析师看来，相对于近年来上市的其它一些互联网公司，投资银行向Twitter授予如此高额的信贷额度要更加危险。</p>
<p>Twitter的这一安排，表明备受瞩目的硅谷公司如今已能够控制华尔街。消息人士称，作为这类公司教科书式的模式，Twitter要求负责首次公开招股事宜的投资银行向公司提供信誉额度。这种方式能够让准备上市的企业，在进行首次公开招股时最大限度的在华尔街获取到现金。</p>
<p>对一些投资银行而言，提供信贷额度能够与准备上市的企业建立起关系。对投资银行而言，能够负责热门企业的首次公开招股事宜，将是他们耀武扬威的资本，将有助于未来承担更多企业的首次公开招股事宜。但是在这种情况下，投资银行将不得不向这些企业提供信贷支持。</p>
<p>Ipreo的统计数据显示，</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131015/13QR14M53160-140H_lit.jpg{/gemel:field}
