{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140714/96305-b--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96305-b-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96305-c--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96305-c-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96318-a--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96318-a-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96318-b--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96318-b-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96318-c--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96318-c-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96832-b--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96832-b-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/96833-a--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/96833-a-.jpg {/gemel:img}
