<li class="clear"><a href="[field:arcurl/]" class="intro-img">
                <img src="[field:litpic/]" width="200" height="200" alt=""><i>&nbsp;</i></a>
                <div class="intro-info">
                    <h3>[field:title/]</h3>
                    <p>[field:description function='cn_substrR(html2text(@me),100)'/]..</p>
                    <a href="[field:arcurl/]"></a>
                </div>
            </li>