<li class="clear">
      <div class="img_left">
          <img src="/upload/products/list-big-02.png" alt="Screw cover" title="Screw cover" width="892" height="562" />
          <div class="left_bg">
             <a href="[field:typelink/]">MORE</a>
          </div>
      </div>
      <div class="text_right text_02">
        <h2><a href="[field:typelink/]">[field:typename/]</a></h2>
        <p>[field:description/]</p>
        <a class="more" href="[field:typelink/]">View more</a>
      </div>
    </li>