<?php
$z[0]=Array("field","",13,42);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",54,83);
$z[1][4]['name']="typepic";
$z[2]=Array("field","",90,120);
$z[2][4]['name']="typename";
$z[3]=Array("field","",129,159);
$z[3][4]['name']="typename";
$z[4]=Array("field","",192,222);
$z[4][4]['name']="typename";
$z[5]=Array("channelartlist","\r\n                                         \r\n                                           <li><a href='{gemel:field name='typeurl'",332,536);
$z[5][4]['typeid']="4";
$z[5][4]['row']="6";
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="select";
$z[6]=Array("field","",545,572);
$z[6][4]['name']="currentstyle";
$z[7]=Array("field","",584,613);
$z[7][4]['name']="typepic";
$z[8]=Array("field","",620,650);
$z[8][4]['name']="typename";
$z[9]=Array("field","",659,689);
$z[9][4]['name']="typename";
$z[10]=Array("field","",722,752);
$z[10][4]['name']="typename";

?>