{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/150727/skin-care-showcase-01-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150727/skin-care-showcase-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150727/skin-care-showcase-02-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150727/skin-care-showcase-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150727/skin-care-showcase-03-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150727/skin-care-showcase-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150727/skin-care-showcase-04-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150727/skin-care-showcase-04.jpg {/gemel:img}
