<?php
$z[0]=Array("include","",0,43);
$z[0][4]['filename']="meta_css_js.htm";
$z[1]=Array("include","",53,89);
$z[1][4]['filename']="head.htm";
$z[2]=Array("field","",193,244);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",318,341);
$z[3][4]['name']="typename";
$z[4]=Array("field","",362,384);
$z[4][4]['name']="content";
$z[5]=Array("channelartlist","\r\n                       <li><a href='{gemel:field.typeurl/}' class='{gemel:field.currentstyle/}'><span style=\"padding-right:15px;\"><</span>{gemel:field.typename/}</a></li>\r\n                     ",571,864);
$z[5][4]['typeid']="2";
$z[5][4]['row']="10";
$z[5][4]['type']="son";
$z[5][4]['currentstyle']="select";
$z[6]=Array("include","",1432,1470);
$z[6][4]['filename']="footer.htm";

?>