<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",770,804);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n    <div class=\"about_banner\" style=\"background:url([field:pic/]) center top no-repeat;\"></div>\r\n    ",844,1000);
$z[4][4]['name']="about_banner";
$z[4][4]['row']="1";
$z[5]=Array("include","",1073,1114);
$z[5][4]['filename']="common_left.htm";
$z[6]=Array("field","",1193,1221);
$z[6][4]['name']="position";
$z[7]=Array("field","",1319,1339);
$z[7][4]['name']="content";
$z[8]=Array("include","",1432,1468);
$z[8][4]['filename']="footer.htm";

?>