<?php
$z[0]=Array("typelink","",43,60);
$z[1]=Array("typename","",62,79);
$z[2]=Array("sonchannel0","\r\n                                <li class=\"c1\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                    [field:sonchannel1]\r\n                                    <li class=\"c2\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                        [field:sonchannel2]\r\n                                        <li class=\"c3\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                            [field:sonchannel3]\r\n                                            <li class=\"c4\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                                            [/field:sonchannel3]\r\n                                        [/field:sonchannel2]\r\n                                    [/field:sonchannel1]\r\n                                ",122,1000);

?>