<?php
$z[0]=Array("field","",70,99);
$z[0][4]['name']="typepic";
$z[1]=Array("field","",106,136);
$z[1][4]['name']="typename";
$z[2]=Array("field","",145,175);
$z[2][4]['name']="typename";
$z[3]=Array("field","",236,266);
$z[3][4]['name']="typename";
$z[4]=Array("field","",311,340);
$z[4][4]['name']="content";
$z[5]=Array("global","@me=2",376,438);
$z[5][4]['name']="itemindex";
$z[5][4]['runphp']="no";

?>