		
	  <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='产品中心' ischannel='1' link='content_list.php?channelid=3' linkadd='archives_add.php?channelid=3' channelid='3' rank='' target='main' />
  <m:item name='品牌介绍' ischannel='1' link='content_list.php?channelid=14' linkadd='archives_add.php?channelid=14' channelid='14' rank='' target='main' />
  <m:item name='下载中心' ischannel='1' link='content_list.php?channelid=15' linkadd='archives_add.php?channelid=15' channelid='15' rank='' target='main' />
  <m:item name='会员中心' ischannel='1' link='content_list.php?channelid=16' linkadd='archives_add.php?channelid=16' channelid='16' rank='' target='main' />
  <m:item name='积分兑换' ischannel='1' link='content_list.php?channelid=17' linkadd='archives_add.php?channelid=17' channelid='17' rank='' target='main' />
		
