<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",65,100);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",216,267);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",300,320);
$z[3][4]['name']="title";
$z[4]=Array("field","\r\n                            <li>\r\n                                <img src=\"[field:imgsrctrue/]\" width=\"870\" height=\"555\" title=\"[field:title/]\" alt=\"[field:title/]\" />\r\n                            </li>\r\n                           ",567,843);
$z[4][4]['name']="imgurls";
$z[5]=Array("field","",1113,1168);
$z[5][4]['name']="id";
$z[5][4]['function']="get_image_list(@me)";
$z[6]=Array("field","",1354,1374);
$z[6][4]['name']="title";
$z[7]=Array("field","",1380,1405);
$z[7][4]['name']="shorttitle";
$z[8]=Array("field","",1429,1448);
$z[8][4]['name']="body";
$z[9]=Array("arclist","\r\n               <li>\r\n                   <div class=\"img\">\r\n                         <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"246\" height=\"220\" /></a>\r\n                   </div>\r\n                   <h3><a href=\"[field:arcurl/]\">[field:shorttitle/]</a></h3>\r\n                   <a href=\"[field:arcurl/]\">VIEW MORE</a>\r\n               </li>\r\n               ",1616,2107);
$z[9][4]['row']="4";
$z[9][4]['titlelen']="150";
$z[9][4]['orderby']="pubdate";
$z[10]=Array("include","",2199,2237);
$z[10][4]['filename']="footer.htm";

?>