<?php
$z[0]=Array("field","",254,281);
$z[0][4]['name']="title";
$z[1]=Array("global","",282,309);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",353,386);
$z[2][4]['name']="description";
$z[3]=Array("field","",423,453);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",1074,1110);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1153,1204);
$z[5][4]['name']="position";
$z[5][4]['function']="position_preg(@me)";
$z[6]=Array("field","",1383,1403);
$z[6][4]['name']="title";
$z[7]=Array("field","",1433,1459);
$z[7][4]['name']="description";
$z[8]=Array("field","\r\n                            <li><img src=\"[field:imgsrctrue/]\"/></li>\r\n                            ",1633,1776);
$z[8][4]['name']="imgurls";
$z[9]=Array("field","",2009,2064);
$z[9][4]['name']="id";
$z[9][4]['function']="get_image_list(@me)";
$z[10]=Array("field","",2394,2414);
$z[10][4]['name']="title";
$z[11]=Array("arclist","\r\n                        <a href=\"javascript:viod(0);\">[field:title/]</a>\r\n                        ",3121,3278);
$z[11][4]['orderby']="weight";
$z[11][4]['row']="20";
$z[12]=Array("field","",5740,5762);
$z[12][4]['name']="content";
$z[13]=Array("include","",6495,6535);
$z[13][4]['filename']="pro_menu.htm";
$z[14]=Array("include","",6537,6575);
$z[14][4]['filename']="footer.htm";

?>