<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",583,617);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n        <li id=\"[field:id/]\" style=\"background:url([field:pic/]) center top no-repeat;\" class=\"now\"></li>\r\n        ",659,829);
$z[4][4]['name']="about_banner";
$z[4][4]['row']="1";
$z[5]=Array("field","",895,923);
$z[5][4]['name']="position";
$z[6]=Array("type","[field:typename/]",1013,1061);
$z[6][4]['typeid']="";
$z[7]=Array("field","",2462,2481);
$z[7][4]['name']="title";
$z[8]=Array("field","",2549,2577);
$z[8][4]['name']="product_number";
$z[9]=Array("field","",2677,2702);
$z[9][4]['name']="product_use";
$z[10]=Array("field","",3487,3505);
$z[10][4]['name']="body";
$z[11]=Array("field","",3572,3596);
$z[11][4]['name']="parameters";
$z[12]=Array("field","",3645,3671);
$z[12][4]['name']="products_img";
$z[13]=Array("field","",3729,3760);
$z[13][4]['name']="products_download";
$z[14]=Array("field","",3762,3781);
$z[14][4]['name']="title";
$z[15]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",3969,4088);
$z[15][4]['type']="son";
$z[16]=Array("include","",4157,4193);
$z[16][4]['filename']="footer.htm";

?>