<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",66,101);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",214,238);
$z[2][4]['name']="typename";
$z[3]=Array("field","",245,269);
$z[3][4]['name']="typename";
$z[4]=Array("field","",375,426);
$z[4][4]['name']="position";
$z[4][4]['function']="position_preg(@me)";
$z[5]=Array("field","",459,479);
$z[5][4]['name']="title";
$z[6]=Array("field","",601,621);
$z[6][4]['name']="title";
$z[7]=Array("field","",640,659);
$z[7][4]['name']="body";
$z[8]=Array("arclist","\r\n             <li>\r\n                 <p><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\r\n             </li>\r\n             ",772,1002);
$z[8][4]['row']="6";
$z[8][4]['titlelen']="100";
$z[8][4]['orderby']="pubdate";
$z[8][4]['idlist']="";
$z[9]=Array("type","[field:typelink /]",1074,1133);
$z[9][4]['typeid']="~typeid~";
$z[10]=Array("prenext","",1292,1332);
$z[10][4]['get']="pre";
$z[10][4]['sitelang']="en";
$z[11]=Array("prenext","",1366,1407);
$z[11][4]['get']="next";
$z[11][4]['sitelang']="en";
$z[12]=Array("include","",1493,1531);
$z[12][4]['filename']="footer.htm";

?>