<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",66,101);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",185,207);
$z[2][4]['name']="typepic";
$z[3]=Array("field","",240,264);
$z[3][4]['name']="seotitle";
$z[4]=Array("field","",273,297);
$z[4][4]['name']="seotitle";
$z[5]=Array("field","",616,667);
$z[5][4]['name']="position";
$z[5][4]['function']="position_preg(@me)";
$z[6]=Array("field","",700,720);
$z[6][4]['name']="title";
$z[7]=Array("field","",842,862);
$z[7][4]['name']="title";
$z[8]=Array("field","",881,900);
$z[8][4]['name']="body";
$z[9]=Array("arclist","\r\n             <li>\r\n                 <p><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\r\n             </li>\r\n             ",1013,1243);
$z[9][4]['row']="6";
$z[9][4]['titlelen']="100";
$z[9][4]['orderby']="pubdate";
$z[9][4]['idlist']="";
$z[10]=Array("type","[field:typelink /]",1315,1374);
$z[10][4]['typeid']="~typeid~";
$z[11]=Array("prenext","",1533,1573);
$z[11][4]['get']="pre";
$z[11][4]['sitelang']="en";
$z[12]=Array("prenext","",1607,1648);
$z[12][4]['get']="next";
$z[12][4]['sitelang']="en";
$z[13]=Array("include","",1734,1772);
$z[13][4]['filename']="footer.htm";

?>