<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",65,100);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",209,260);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",293,313);
$z[3][4]['name']="title";
$z[4]=Array("field","",401,421);
$z[4][4]['name']="title";
$z[5]=Array("field","\r\n                    <li>\r\n                        <img src=\"[field:imgsrctrue/]\" width=\"1040\" height=\"498\" title=\"[field:title/]\" alt=\"[field:title/]\" />\r\n                    </li>\r\n                    ",557,803);
$z[5][4]['name']="imgurls";
$z[6]=Array("field","",1063,1118);
$z[6][4]['name']="id";
$z[6][4]['function']="get_image_list(@me)";
$z[7]=Array("field","",1347,1366);
$z[7][4]['name']="body";
$z[8]=Array("arclist","\r\n                         <li><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"267\" height=\"200\" /></a></li>\r\n                         ",1583,1846);
$z[8][4]['row']="9";
$z[8][4]['titlelen']="150";
$z[8][4]['orderby']="pubdate";
$z[9]=Array("include","",2098,2136);
$z[9][4]['filename']="footer.htm";

?>