<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",65,100);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",213,237);
$z[2][4]['name']="typename";
$z[3]=Array("field","",244,268);
$z[3][4]['name']="typename";
$z[4]=Array("field","",367,418);
$z[4][4]['name']="position";
$z[4][4]['function']="position_preg(@me)";
$z[5]=Array("field","",451,471);
$z[5][4]['name']="title";
$z[6]=Array("field","",580,600);
$z[6][4]['name']="title";
$z[7]=Array("field","",615,634);
$z[7][4]['name']="body";
$z[8]=Array("arclist","\r\n             <li>\r\n                 <p><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\r\n             </li>\r\n             ",741,971);
$z[8][4]['row']="6";
$z[8][4]['titlelen']="100";
$z[8][4]['orderby']="pubdate";
$z[8][4]['idlist']="";
$z[9]=Array("type","[field:typelink /]",1043,1102);
$z[9][4]['typeid']="~typeid~";
$z[10]=Array("prenext","",1261,1301);
$z[10][4]['get']="pre";
$z[10][4]['sitelang']="cn";
$z[11]=Array("prenext","",1335,1376);
$z[11][4]['get']="next";
$z[11][4]['sitelang']="cn";
$z[12]=Array("include","",1462,1500);
$z[12][4]['filename']="footer.htm";

?>