<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",65,100);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",262,313);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",346,366);
$z[3][4]['name']="title";
$z[4]=Array("field","",440,459);
$z[4][4]['name']="body";
$z[5]=Array("include","",553,591);
$z[5][4]['filename']="footer.htm";

?>