<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",65,100);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",247,298);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",331,351);
$z[3][4]['name']="title";
$z[4]=Array("field","",481,501);
$z[4][4]['name']="title";
$z[5]=Array("field","",520,539);
$z[5][4]['name']="body";
$z[6]=Array("arclist","\r\n                 <li>\r\n                     <p><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\r\n                 </li>\r\n                 ",666,912);
$z[6][4]['row']="6";
$z[6][4]['titlelen']="100";
$z[6][4]['orderby']="pubdate";
$z[6][4]['idlist']="";
$z[7]=Array("type","[field:typelink /]",996,1055);
$z[7][4]['typeid']="~typeid~";
$z[8]=Array("prenext","",1236,1276);
$z[8][4]['get']="pre";
$z[8][4]['sitelang']="en";
$z[9]=Array("prenext","",1312,1353);
$z[9][4]['get']="next";
$z[9][4]['sitelang']="en";
$z[10]=Array("include","",1464,1502);
$z[10][4]['filename']="footer.htm";

?>