<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",583,617);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n        <li id=\"[field:id/]\" style=\"background:url([field:pic/]) center top no-repeat;\" class=\"now\"></li>\r\n        ",659,829);
$z[4][4]['name']="about_banner";
$z[4][4]['row']="1";
$z[5]=Array("field","",895,923);
$z[5][4]['name']="position";
$z[6]=Array("type","[field:typename/]",1013,1061);
$z[6][4]['typeid']="";
$z[7]=Array("field","",1172,1191);
$z[7][4]['name']="litpic";
$z[8]=Array("field","",1269,1287);
$z[8][4]['name']="body";
$z[9]=Array("field","",1704,1726);
$z[9][4]['name']="products";
$z[10]=Array("field","",1793,1812);
$z[10][4]['name']="guide";
$z[11]=Array("field","",1903,1960);
$z[11][4]['name']="typeid";
$z[11][4]['function']="GetTopInfo(@me,0,2)";
$z[12]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",2027,2146);
$z[12][4]['type']="son";
$z[13]=Array("include","",2215,2251);
$z[13][4]['filename']="footer.htm";

?>