<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",112,147);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",301,352);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",385,405);
$z[3][4]['name']="title";
$z[4]=Array("field","\r\n                      <li>\r\n                          <img src=\"[field:imgsrctrue/]\" width=\"540\" height=\"368\" title=\"[field:typename/] - [field:title/]\" alt=\"[field:typename/] - [field:title/]\" />\r\n                      </li>\r\n                      ",617,910);
$z[4][4]['name']="imgurls";
$z[5]=Array("field","",2049,2104);
$z[5][4]['name']="id";
$z[5][4]['function']="get_image_list(@me)";
$z[6]=Array("field","",2362,2382);
$z[6][4]['name']="title";
$z[7]=Array("field","",2453,2478);
$z[7][4]['name']="shorttitle";
$z[8]=Array("field","",2843,2862);
$z[8][4]['name']="body";
$z[9]=Array("include","",2970,3008);
$z[9][4]['filename']="footer.htm";

?>