<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",583,617);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n<div class=\"about_banner\" style=\"background:url([field:pic/]) center top no-repeat;\"></div>\r\n",623,771);
$z[4][4]['name']="about_banner";
$z[4][4]['row']="1";
$z[5]=Array("field","",829,857);
$z[5][4]['name']="position";
$z[6]=Array("type","[field:typename/]",947,995);
$z[6][4]['typeid']="";
$z[7]=Array("field","",1099,1124);
$z[7][4]['name']="title";
$z[8]=Array("field","",1206,1261);
$z[8][4]['name']="pubdate";
$z[8][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[9]=Array("field","",1298,1324);
$z[9][4]['name']="writer";
$z[10]=Array("field","",1380,1406);
$z[10][4]['name']="source";
$z[11]=Array("field","",1506,1523);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",1645,1669);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",1700,1725);
$z[13][4]['get']="next";
$z[14]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",1938,2057);
$z[14][4]['type']="son";
$z[15]=Array("include","",2126,2162);
$z[15][4]['filename']="footer.htm";

?>