<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("type","\r\n<div class=\"products-banner\">\r\n     <img src=\"[field:typepic/]\" title=\"[field:seotitle/]\" alt=\"[field:seotitle/]\" width=\"1600\" height=\"430\" />\r\n</div>\r\n",124,314);
$z[2][4]['type']="tid";
$z[3]=Array("field","",440,491);
$z[3][4]['name']="position";
$z[3][4]['function']="position_preg(@me)";
$z[4]=Array("type","\r\n        <h1 class=\"none\">[field:typename/]</h1>\r\n        ",568,663);
$z[4][4]['typeid']="2";
$z[5]=Array("arclist","\r\n                <li>\r\n                    <a href=\"[field:certificate_url/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" width=\"246\" height=\"312\" alt=\"[field:title/]\"></a>\r\n                    <h2>[field:title/]</h2>\r\n                </li>\r\n                ",753,1143);
$z[5][4]['type']="tid";
$z[5][4]['orderby']="weight";
$z[5][4]['titlelen']="100";
$z[5][4]['row']="8";
$z[5][4]['channelid']="15";
$z[5][4]['addfields']="certificate_url";
$z[6]=Array("pagelist","",1211,1283);
$z[6][4]['listitem']="index,end,pageno";
$z[6][4]['listsize']="4";
$z[6][4]['sitelang']="en";
$z[7]=Array("include","",1389,1427);
$z[7][4]['filename']="footer.htm";

?>