<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",65,100);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",240,291);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",324,344);
$z[3][4]['name']="title";
$z[4]=Array("field","\r\n                    <li>\r\n                        <img src=\"[field:imgsrctrue/]\" width=\"495\" height=\"365\" title=\"[field:title/]\" alt=\"[field:title/]\" />\r\n                    </li>\r\n                    ",537,782);
$z[4][4]['name']="imgurls";
$z[5]=Array("field","",1009,1064);
$z[5][4]['name']="id";
$z[5][4]['function']="get_image_list(@me)";
$z[6]=Array("field","",1258,1278);
$z[6][4]['name']="title";
$z[7]=Array("field","",1289,1314);
$z[7][4]['name']="shorttitle";
$z[8]=Array("field","",1339,1361);
$z[8][4]['name']="outline";
$z[9]=Array("field","",1488,1507);
$z[9][4]['name']="body";
$z[10]=Array("arclist","\r\n                     <li>\r\n                          <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"232\" height=\"198\" /></a>\r\n                          <h3><a href=\"[field:arcurl/]\">[field:shorttitle/]</a></h3>\r\n                     </li>\r\n                     ",1700,2092);
$z[10][4]['row']="9";
$z[10][4]['titlelen']="150";
$z[10][4]['orderby']="pubdate";
$z[11]=Array("include","",2269,2307);
$z[11][4]['filename']="footer.htm";

?>