<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",102,137);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",297,348);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",381,401);
$z[3][4]['name']="title";
$z[4]=Array("field","\r\n                        <li>\r\n                            <img src=\"[field:imgsrctrue/]\" width=\"554\" height=\"332\" title=\"[field:typename/] - [field:title/]\" alt=\"[field:typename/] - [field:title/]\" />\r\n                        </li>\r\n                        ",642,943);
$z[4][4]['name']="imgurls";
$z[5]=Array("field","",2607,2662);
$z[5][4]['name']="id";
$z[5][4]['function']="get_image_list(@me)";
$z[6]=Array("field","",3150,3173);
$z[6][4]['name']="typename";
$z[7]=Array("field","",3176,3196);
$z[7][4]['name']="title";
$z[8]=Array("field","",3222,3245);
$z[8][4]['name']="typename";
$z[9]=Array("arclist","\r\n                    <li>\r\n                        <div class=\"img\">\r\n                            <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:typename/] - [field:title/]\" alt=\"[field:typename/] - [field:title/]\" width=\"245\" height=\"190\"/></a>\r\n                        </div>\r\n                        <div class=\"text\">\r\n                            <h3><a href=\"[field:arcurl/]\" title=\"[field:typename/] - [field:title/]\">[field:title/]</a></h3>\r\n                        </div>                  \r\n                    </li>\r\n                ",9024,9668);
$z[9][4]['row']="4";
$z[9][4]['titlelen']="100";
$z[9][4]['flag']="c";
$z[9][4]['orderby']="weight";
$z[10]=Array("include","",11661,11699);
$z[10][4]['filename']="footer.htm";
$z[11]=Array("field","",11779,11807);
$z[11][4]['name']="phpurl";
$z[12]=Array("field","",11835,11859);
$z[12][4]['name']="id";
$z[13]=Array("field","",11868,11893);
$z[13][4]['name']="mid";

?>