<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",65,100);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",281,332);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",365,385);
$z[3][4]['name']="title";
$z[4]=Array("field","",423,443);
$z[4][4]['name']="title";
$z[5]=Array("field","",458,477);
$z[5][4]['name']="body";
$z[6]=Array("field","\r\n                  <li>\r\n                      <img src=\"[field:imgsrctrue/]\" width=\"458\" height=\"458\" title=\"[field:title/]\" alt=\"[field:title/]\" />\r\n                  </li>\r\n                  ",821,1058);
$z[6][4]['name']="imgurls";
$z[7]=Array("field","",1290,1345);
$z[7][4]['name']="id";
$z[7][4]['function']="get_image_list(@me)";
$z[8]=Array("arclist","\r\n             <li>\r\n                   <div class=\"img\">\r\n                       <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"282\" height=\"232\" /></a>\r\n                   </div>\r\n                   <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n                   <a href=\"[field:arcurl/]\">View Details</a>\r\n              </li>\r\n              ",1713,2195);
$z[8][4]['row']="4";
$z[8][4]['titlelen']="150";
$z[8][4]['orderby']="weight";
$z[9]=Array("include","",2285,2323);
$z[9][4]['filename']="footer.htm";

?>