<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",117,152);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",350,401);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",434,454);
$z[3][4]['name']="title";
$z[4]=Array("field","\r\n                 <img src=\"[field:imgsrctrue/]\" alt=\"[field:typename/]\" width=\"480\" height=\"450\" title=\"[field:typename/]\">\r\n                  ",668,855);
$z[4][4]['name']="imgurls";
$z[5]=Array("field","",1012,1032);
$z[5][4]['name']="title";
$z[6]=Array("field","",1063,1082);
$z[6][4]['name']="body";
$z[7]=Array("field","",1657,1682);
$z[7][4]['name']="pro_detail";
$z[8]=Array("field","",1960,1991);
$z[8][4]['name']="applicable_scope";
$z[9]=Array("field","",2158,2184);
$z[9][4]['name']="pro_feature";
$z[10]=Array("arclist","\r\n                      <li> <a href=\"[field:arcurl/]\">\r\n                        <img src=\"[field:pro_related/]\" width=\"260\" height=\"260\" alt=\"[field:typename/] - [field:title/]\" title=\"[field:typename/] - [field:title/]\">\r\n                        <span>[field:title/]</span>\r\n                      </a></li>\r\n                       ",2565,3018);
$z[10][4]['type']="tid";
$z[10][4]['orderby']="weight";
$z[10][4]['titlelen']="100";
$z[10][4]['addfields']="pro_related";
$z[10][4]['channelid']="2";
$z[10][4]['row']="4";
$z[11]=Array("include","",3473,3511);
$z[11][4]['filename']="footer.htm";

?>