<li>
                       <a href=""><img src="" title="" alt="" width="336" height="314" /></a>
                       <div class="con">
                             <em class="up">&nbsp;</em>
                             <h2><a href="">Metal Stamping Parts</a></h2>
                             <h3><a href="">CMC-01</a></h3>
                             <em class="cn">&nbsp;</em>
                             <span><a href="">Read more</a></span>
                       </div>
                  </li>