{gemel:field name='keywords'}站长之家, 苹果发布会,{/gemel:field}
{gemel:field name='description'}苹果将于北京时间9月11日凌晨1点在其加州库比蒂诺总部举行发布会，或将发布新一代iPhone。数个小时后，它还将在北京、东京和柏林单独举行发布会。{/gemel:field}
{gemel:field name='title'}不止北京 柏林东京也有单独的苹果发布会{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}
                                                            <p>苹果将于北京时间9月11日凌晨1点在其加州库比蒂诺总部举行发布会，或将发布新一代iPhone。数个小时后，它还将在北京、东京和柏林单独举行发布会。</p>
<p>在这三个发布会上，苹果将会播一段库比蒂诺发布会的视频，并提供一些其它的内容。</p>
<p>其实这并非苹果第一次这么做，它之前曾在伦敦和东京举行过类似的活动，但这是苹果第一次在其最重要的市场之一中国举行这类发布会。这一安排也进一步加剧了人们对苹果准备宣布将在该国新增中国移动这家运营商合作伙伴的猜测。</p>
<p>中国移动拥有超过7亿用户，不仅是中国第一大运营商，放眼全球它也无人可比。业内人士指出，它是剩下的少数几家能够显著推动iPhone销售的运营商之一。鉴于苹果上一财季在华营收同比下滑14%，它很可能想要与该运营商合作拉动iPhone销售。</p>
<p><img src="/upload/allimg/c130905/13N35424194030-15542.jpg" border="0" /></p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130905/13N35424194030-15542_lit.jpg{/gemel:field}
