<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:blist_img itemname="主列表产品图" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="300" page="">
</field:blist_img>
