<li><i>&nbsp;</i><a href="{gemel:field.typeurl/}">{gemel:field.typename/}</a></li>
                <!-- <li><i>&nbsp;</i><a href="">Straight(Dry) Drawing Machine</a></li>
                <li><i>&nbsp;</i><a href="">Straight(Dry) Drawing Machine</a></li>
                <li><i>&nbsp;</i><a href="">Straight(Dry) Drawing Machine</a></li>
                <li><i>&nbsp;</i><a href="">Straight(Dry) Drawing Machine</a></li>
                <li><i>&nbsp;</i><a href="">Straight(Dry) Drawing Machine</a></li>
                <li><i>&nbsp;</i><a href="">Straight(Dry) Drawing Machine</a></li> -->