<li>
                    <a href="[field:typelink/]"><img src="/images/home-pro-01.jpg" title="" alt="" width="278" height="270" /></a>
                    <div class="title">
                          <div class="left">
                                <h2><a href="[field:typelink/]">PCM <br/>PROTECTION BOARD</a></h2>
                          </div>
                          <a href="[field:typelink/]"><em></em></a>
                    </div>
               </li>