{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/151028/b3005-01-lp.png' text='' width='870' height='555'} /upload/allimg/151028/b3005-01.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151028/b3005-02-lp.png' text='' width='870' height='555'} /upload/allimg/151028/b3005-02.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151028/b3005-03-lp.png' text='' width='870' height='555'} /upload/allimg/151028/b3005-03.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151028/b3005-04-lp.png' text='' width='870' height='555'} /upload/allimg/151028/b3005-04.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151028/b3005-05-lp.png' text='' width='870' height='555'} /upload/allimg/151028/b3005-05.png {/gemel:img}
