<li>   
                     <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:typename/] - [field:title/]" alt="[field:typename/] - [field:title/]" width="282" height="232" /></a>
                     <h3><a href="[field:arcurl/]" title="[field:typename/] - [field:title/]">[field:title/]</a></h3>
                     <span><a href="[field:arcurl/]">READ MORE</a></span>  
                </li>