<?php
$z[0]=Array("field","站长之家, 阿里巴巴, 来往",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","阿里巴巴旗下移动社交平台来往宣布，将推出共同成长计划，出资帮助传统机构、线上线下商家、媒体和普通人，在移动平台上建立自己的“地盘”。",75,315);
$z[1][4]['name']="description";
$z[2]=Array("field","阿里2亿推广来往：拉一人用支付宝奖励5元",317,409);
$z[2][4]['name']="title";
$z[3]=Array("field","",411,448);
$z[3][4]['name']="writer";
$z[4]=Array("field","",450,487);
$z[4][4]['name']="source";
$z[5]=Array("field","<p style=\"text-align:center;\">          </p>\n                                                            <p style=\"text-align: center; text-indent: 0;\"><img src=\"/upload/allimg/c140103/13XG5V2A120-139B7.jpg\" border=\"0\" /></p>\n<p style=\"text-align: center;\">阿里来往宣布出资2亿推广计划 用户邀请一人使用&ldquo;来往&rdquo;奖励5元</p>\n<p>【TechWeb报道】12月31日消息，阿里巴巴旗下移动社交平台来往宣布，将推出共同成长计划，出资帮助传统机构、线上线下商家、媒体和普通人，在移动平台上建立自己的&ldquo;地盘&rdquo;。</p>\n<p>该计划首期预算为2亿元，预计将帮助数万传统机构、名人、商家和创业者，拉动用户参与。</p>\n<p>该计划内容包括，在最新发布的来往版本中，来往在设置中增加了&ldquo;邀请&rdquo;功能，用户可以发暗号约朋友来往，每成功邀请1人，邀请者即可获得5元奖励，获邀者也可以获得5元新人红包。</p>\n<p>这意味着只要符合规则拉入一个&ldquo;新人&rdquo;使用来往，则可以获得阿里方面5元钱的奖励，该奖励将会通过支付宝的方式兑付。</p>\n<p>来往方面强调，扶持计划对参与者一视同仁，不管是名人明星、大型机构还是普通个人用户，只要是有意愿参与，来往均会大力支持。（八品）</p>",489,1899);
$z[5][4]['name']="body";
$z[6]=Array("field","",1901,1939);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/upload/allimg/c140103/13XG5V2A120-139B7_lit.jpg",1941,2026);
$z[7][4]['name']="litpic";

?>