{gemel:field name='keywords'}站长之家, 阿里巴巴, 来往{/gemel:field}
{gemel:field name='description'}阿里巴巴旗下移动社交平台来往宣布，将推出共同成长计划，出资帮助传统机构、线上线下商家、媒体和普通人，在移动平台上建立自己的“地盘”。{/gemel:field}
{gemel:field name='title'}阿里2亿推广来往：拉一人用支付宝奖励5元{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c140103/13XG5V2A120-139B7.jpg" border="0" /></p>
<p style="text-align: center;">阿里来往宣布出资2亿推广计划 用户邀请一人使用&ldquo;来往&rdquo;奖励5元</p>
<p>【TechWeb报道】12月31日消息，阿里巴巴旗下移动社交平台来往宣布，将推出共同成长计划，出资帮助传统机构、线上线下商家、媒体和普通人，在移动平台上建立自己的&ldquo;地盘&rdquo;。</p>
<p>该计划首期预算为2亿元，预计将帮助数万传统机构、名人、商家和创业者，拉动用户参与。</p>
<p>该计划内容包括，在最新发布的来往版本中，来往在设置中增加了&ldquo;邀请&rdquo;功能，用户可以发暗号约朋友来往，每成功邀请1人，邀请者即可获得5元奖励，获邀者也可以获得5元新人红包。</p>
<p>这意味着只要符合规则拉入一个&ldquo;新人&rdquo;使用来往，则可以获得阿里方面5元钱的奖励，该奖励将会通过支付宝的方式兑付。</p>
<p>来往方面强调，扶持计划对参与者一视同仁，不管是名人明星、大型机构还是普通个人用户，只要是有意愿参与，来往均会大力支持。（八品）</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c140103/13XG5V2A120-139B7_lit.jpg{/gemel:field}
