{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140714/90055-a全身-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90055-a全身.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90060-a.jpg-50' text='' width='270' height='290'} /upload/allimg/140714/90060-a.jpg-50 {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90060-a半身-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90060-a半身.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90060-a全身-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90060-a全身.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90062-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90062-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90062-a半身-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90062-a半身.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90062-a全身-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90062-a全身.jpg {/gemel:img}
