{gemel:field name='keywords'}站长之家, Snapchat, 腾讯,{/gemel:field}
{gemel:field name='description'}阅后即焚 Snapchat 正在进行一轮涉及两亿美元的融资，腾讯正在试图领投 Snapchat 的此轮融资。瞬时图片分享应用 Snapchat 是继 Facebook、Twitter 之后的硅谷最亮新星。此{/gemel:field}
{gemel:field name='title'}腾讯试图领投阅后即焚 Snapchat 两亿刀融资{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0U632U0-22054.png" border="0" title="QQ截图20131106094350.png" /></p>
<p>华尔街日报报道，阅后即焚 Snapchat 正在进行一轮涉及两亿美元的融资，腾讯正在试图领投 Snapchat 的此轮融资。</p>
<p>瞬时图片分享应用&ldquo;阅后即焚 Snapchat&rdquo;创建于 2011 年 5 月，在几乎没有进行任何宣传推广的情况下，一年后进入苹果应用商店排行榜前十，经历了 Facebook 的山寨产品 Poke 的冲击仍然屹立不倒，是继 Facebook、Twitter 之后的硅谷最亮新星。Snapchat 在 2012 年 5 月获得 48.5 万美元种子轮融资，在 2012 年 12 月获得 1250 万美元 A 轮融资，在 2013 年 6 月获得 6000 万 B 轮融资。截止目前，Snapchat 共融资 7300 万美元。Snapchat 正在进行 C 轮融资，计划融资两亿美元，估值 40 亿美元。</p>
<p>这并不是腾讯在硅谷的第一次风险投资。腾讯的现金储备超过 50 亿美元。今年夏天，腾讯领投了一轮对美国闪购电商 Fab 的投资，Fab 该轮融资涉及金额 1.5 亿美元。</p>
<p>腾讯也并非唯一一家在硅谷进行风险投资的中国公司。上月，阿里巴巴刚刚领投了一轮对美国电商 ShopRunner 的投资，ShopRunner 该轮融资涉及金额 2.06 亿美元。移动浏览器 UCWeb 也曾表示正在积极谋求美国的投资机会。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131106/13SI0U632U0-22054_lit.png{/gemel:field}
