<?php
$z[0]=Array("field","站长之家, Snapchat, 腾讯,",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","阅后即焚 Snapchat 正在进行一轮涉及两亿美元的融资，腾讯正在试图领投 Snapchat 的此轮融资。瞬时图片分享应用 Snapchat 是继 Facebook、Twitter 之后的硅谷最亮新星。此",72,329);
$z[1][4]['name']="description";
$z[2]=Array("field","腾讯试图领投阅后即焚 Snapchat 两亿刀融资",331,422);
$z[2][4]['name']="title";
$z[3]=Array("field","",424,461);
$z[3][4]['name']="writer";
$z[4]=Array("field","",463,500);
$z[4][4]['name']="source";
$z[5]=Array("field","<p style=\"text-align:center;\">          </p>\n                                                            <p style=\"text-align: center; text-indent: 0;\"><img src=\"/upload/allimg/c131106/13SI0U632U0-22054.png\" border=\"0\" title=\"QQ截图20131106094350.png\" /></p>\n<p>华尔街日报报道，阅后即焚 Snapchat 正在进行一轮涉及两亿美元的融资，腾讯正在试图领投 Snapchat 的此轮融资。</p>\n<p>瞬时图片分享应用&ldquo;阅后即焚 Snapchat&rdquo;创建于 2011 年 5 月，在几乎没有进行任何宣传推广的情况下，一年后进入苹果应用商店排行榜前十，经历了 Facebook 的山寨产品 Poke 的冲击仍然屹立不倒，是继 Facebook、Twitter 之后的硅谷最亮新星。Snapchat 在 2012 年 5 月获得 48.5 万美元种子轮融资，在 2012 年 12 月获得 1250 万美元 A 轮融资，在 2013 年 6 月获得 6000 万 B 轮融资。截止目前，Snapchat 共融资 7300 万美元。Snapchat 正在进行 C 轮融资，计划融资两亿美元，估值 40 亿美元。</p>\n<p>这并不是腾讯在硅谷的第一次风险投资。腾讯的现金储备超过 50 亿美元。今年夏天，腾讯领投了一轮对美国闪购电商 Fab 的投资，Fab 该轮融资涉及金额 1.5 亿美元。</p>\n<p>腾讯也并非唯一一家在硅谷进行风险投资的中国公司。上月，阿里巴巴刚刚领投了一轮对美国电商 ShopRunner 的投资，ShopRunner 该轮融资涉及金额 2.06 亿美元。移动浏览器 UCWeb 也曾表示正在积极谋求美国的投资机会。</p>",502,2095);
$z[5][4]['name']="body";
$z[6]=Array("field","",2097,2135);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/upload/allimg/c131106/13SI0U632U0-22054_lit.png",2137,2222);
$z[7][4]['name']="litpic";

?>