<li>
                            <a href="[field:arcurl/]" class="recommended_list_img"><img src="[field:litpic/]" /></a>
                            <div class="recommended_list_right">
                                <p class="recommended_list_tit"><a href="[field:arcurl/]">[field:title/]</a></p>
                                <p class="recommended_list_profile">[field:description function='cn_substrR(html2text(@me),400)'/]...</p>
                                <a class="recommended_more" href="[field:arcurl/]"></a>
                            </div>
                            <div class="clear"></div>
                        </li>