<li><a href="#"><img src="[field:litpic/]" width="448" height="275" title="Plastic Case TFT LCD Monitor" alt="Plastic Case TFT LCD Monitor" /></a></li>
                            {/gemel:arclist }
                        </ul>
                    </div>
                    <div class="showpic_s">
                        <a class="prev" href="javascript:viod(0);"></a>
                        <ul>
                        <li class="pro_on"><img src="/images/product/lcd-tft-plastic-case-01-s.jpg" width="73" height="45" title="Plastic Case TFT LCD Monitor" alt="Plastic Case TFT LCD Monitor" /></li>
                        <li><img src="/images/product/lcd-tft-plastic-case-02-s.jpg" width="73" height="45" title="Plastic Case TFT LCD Monitor" alt="Plastic Case TFT LCD Monitor" /></li>
                        </ul>
                        <a class="next" href="javascript:viod(0);"></a>
                    </div>
                </div>
            </div>
            <div class="pro_hot">
                <h2 class="h2">Feature</h2>     
                <div class="pro_hot_con">
                    <h2>Plastic Case TFT LCD Monitor</h2>
                    <p class="texing">
                        <span>Value product</span>
                        <span>Plastic case</span>
                        <span>TFT LCD panel</span>
                        <span>Input: BNC VGA RCA HDMI</span>
                        <span>OSD menu</span>
                        <span>Energy saving</span>
                        <span>Over 60,000 hours lifespan</span>
                    </p> 
                    <p><strong>Accessory:</strong> power adapter x 1pc ,power cable x 1pc,stand x 1pc,VGA cable x 1pc,remote controller x 1pc,user manual x 1pc</p>
                    <div class="pro_model">
                        <a href="javascript:viod(0);" class="colorred">EMLCD15P</a>
                        <a href="javascript:viod(0);">EMLCD17P</a>
                        <a href="javascript:viod(0);">EMLCD19P</a>
                        <a href="javascript:viod(0);">EMLCD22P</a>
                    </div>
                    <div class="tab_sc"></div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
$(function(){
	$(".s_b_right").slide({mainCell:".showpic_s ul",autoPage:true,effect:"left",autoPlay:false,vis:4,scroll:4});//多图切换
	$(".showpic_m ul li").eq(0).show();
	showpro(".showpic_m ul li",".showpic_s ul li","pro_on");//多图切换
	tablesc(".pro_model a",".pordtable","colorred",".tab_sc",".pordtable_left");//表格参数
})
</script>
{gemel:include filename="pro_menu.htm"