{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/141217/01-lp.jpg' text='' width='834' height='372'} /upload/allimg/141217/01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/141217/02-lp.jpg' text='' width='834' height='372'} /upload/allimg/141217/02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/141217/03-lp.jpg' text='' width='834' height='372'} /upload/allimg/141217/03.jpg {/gemel:img}
