<?php
$z[0]=Array("uptime","	\n",8,166);
$z[0][4]['itemname']="上架时间";
$z[0][4]['autofield']="1";
$z[0][4]['notsend']="0";
$z[0][4]['type']="datetime";
$z[0][4]['isnull']="true";
$z[0][4]['islist']="0";
$z[0][4]['default']="";
$z[0][4]['maxlength']="250";
$z[0][4]['page']="";
$z[1]=Array("body","	\n",168,324);
$z[1][4]['itemname']="详细介绍";
$z[1][4]['autofield']="1";
$z[1][4]['notsend']="0";
$z[1][4]['type']="htmltext";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="0";
$z[1][4]['default']="";
$z[1][4]['maxlength']="";
$z[1][4]['page']="split";

?>