<li>
                        <a href="[field:arcurl/]" class="testimonials_list_img"><img src="[field:litpic/]" /></a>
                        <div class="news_list_right">
                            <a href="[field:arcurl/]" class="testimonials_list_tit">[field:title/]</a>
                            <p class="testimonials_list_time">[field:pubdate function="MyDate('Y-m-d',@me)"/]</p>
                            <p class="testimonials_list_profile">[field:description function='cn_substrR(html2text(@me),280)'/]<a class="testimonials_more" href="[field:arcurl/]">[详情]</a></p>
                        </div>
                        <div class="clear"></div>
                    </li>