
<div class="banner_box">
    <div class="showpic">
        <ul>
        <li id="[field:id/]" style="background:url([field:pic/]) center top no-repeat;" class="now"></li>
        <li style="background:#063;">图片待加入</li>
        <li style="background:#09F;">图片待加入</li>
        <li style="background:#666;">图片待加入</li>
        </ul>
    </div>
    <div class="num">
        <ul>
        <li class="on">[field:text/]</li>
        <li></li>
        <li></li>
        <li></li>
        </ul>
    </div>
    <div class="go_left"></div>
    <div class="go_right"></div>
    <div></div>
</div>
