<?php
$z[0]=Array("body","\r\n	\r\n",15,174);
$z[0][4]['itemname']="产品说明";
$z[0][4]['autofield']="1";
$z[0][4]['notsend']="0";
$z[0][4]['type']="htmltext";
$z[0][4]['isnull']="true";
$z[0][4]['islist']="0";
$z[0][4]['default']="";
$z[0][4]['maxlength']="";
$z[0][4]['page']="split";
$z[1]=Array("parameters","\r\n",180,346);
$z[1][4]['itemname']="产品参数";
$z[1][4]['autofield']="1";
$z[1][4]['notsend']="0";
$z[1][4]['type']="htmltext";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="0";
$z[1][4]['default']="";
$z[1][4]['maxlength']="500";
$z[1][4]['page']="";

?>