<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/140620/1-1406201J932.jpg ",96,244);
$z[1][4]['ddimg']="/upload/allimg/140620/1-1406201J932-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="734";
$z[1][4]['height']="321";
$z[2]=Array("img"," /upload/allimg/140620/1-1406201J938.jpg ",246,394);
$z[2][4]['ddimg']="/upload/allimg/140620/1-1406201J938-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="734";
$z[2][4]['height']="321";
$z[3]=Array("img"," /upload/allimg/140620/1-1406201J942.jpg ",396,544);
$z[3][4]['ddimg']="/upload/allimg/140620/1-1406201J942-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="734";
$z[3][4]['height']="321";
$z[4]=Array("img"," /upload/allimg/140625/1-140625100932.jpg ",546,696);
$z[4][4]['ddimg']="/upload/allimg/140625/1-140625100932-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="734";
$z[4][4]['height']="321";

?>