<li>
                            <div class="news_img"><a href="[field:arcurl/]"><img src="[field:litpic/]" width="58" height="58" alt="[field:title/]" title="[field:title/]"/></a></div>
                            <div class="news_text"><a href="[field:arcurl/]">[field:title/] ...</a><p style="margin-top:3px;"><a href="[field:arcurl/]">Read More...</a></p></div>
                            <div class="clear"></div>
                        </li>