{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140620/1-1406201IS9-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201IS9.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201IT5-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201IT5.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201IU1-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201IU1.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201IZ2-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201IZ2.jpg {/gemel:img}
