{gemel:field name='keywords'}站长之家, IT男, 客户信息{/gemel:field}
{gemel:field name='description'}“您需要商铺吗？”“您的公司需要贷款吗？”类似营销电话令人厌烦，然而谁出卖了我们的信息？浙江海宁警方近日破获了一起非法售卖公民个人信息的案件，嫌疑人徐某贩卖300{/gemel:field}
{gemel:field name='title'}浙江“IT男”非法贩卖300多万条客户资料被刑拘{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>新华网杭州11月6日专电(记者周竟)&ldquo;您需要商铺吗？&rdquo;&ldquo;您的公司需要贷款吗？&rdquo;类似营销电话令人厌烦，然而谁出卖了我们的信息？浙江海宁警方近日破获了一起非法售卖公民个人信息的案件，嫌疑人徐某贩卖300余万条客户资料被刑拘。</p>
<p>据警方调查，徐某27岁，4年前大学毕业后进入杭州某网络公司从事&ldquo;企业推广&rdquo;工作。工作期间，他曾多次从&ldquo;灵通人士&rdquo;处购得客户资料。2011年，手上已经积累下一定资源的徐某不甘心只拿几千元的工资，辞职回海宁老家干起了买卖他人信息的&ldquo;事业&rdquo;。从2011年6月至今，徐某非法出售300多万条公民信息，获利50余万元。</p>
<p>据徐某交代，其主要出售公司资料，里面包含个人信息。这些资料除了以前积累下来的，其他都是网上搜索整理或者从别处购买而来。把资料分门别类后，徐某通过QQ兜售。</p>
<p>根据徐某的交代，警方又顺藤摸瓜，分别在宁波、金华、杭州等地抓获了5名涉嫌在互联网上非法获取公民个人信息的&ldquo;买家&rdquo;。为收集生意上的客户资料，王某、郑某、曾某、胡某、祝某多次通过互联网向徐某购买公民个人信息，购买量达数十万条。</p>
<p>目前，徐某已被警方刑事拘留，王某等5人被取保候审，案件还在进一步调查中。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
