<?php
$z[0]=Array("field","站长之家, 广告平台, Fli",0,70);
$z[0][4]['name']="keywords";
$z[1]=Array("field","继Google推出HTML5网站和广告设计工具 Web Designer后，广告平台Flite也推出HTML 5广告在线制作工具。",72,239);
$z[1][4]['name']="description";
$z[2]=Array("field","广告平台Flite：推HTML 5在线制作工具",241,324);
$z[2][4]['name']="title";
$z[3]=Array("field","",326,363);
$z[3][4]['name']="writer";
$z[4]=Array("field","",365,402);
$z[4][4]['name']="source";
$z[5]=Array("field","<p style=\"text-align:center;\">          </p>\n                                                            <p>继Google推出HTML5网站和广告设计工具 Web Designer后，广告平台Flite也推出HTML 5广告在线制作工具。</p>\n<p></p>\n<p>在Google的Web designer中制成的广告可直接发布到DoubleClick和AdMob等广告平台上。而Flite本就是一家广告平台，它可让广告主和创意机构实现广告创作、投放、内容实时更新和效果监测。</p>\n<p>之前它就有一款广告创作工具DESIGN STUDIO，现在它为HTML 5推出了新版。和Google Web Designer需要下载软件不同的是，Flite这款免费工具是在线的，在浏览器中就能完成编辑操作，完成的广告支持在各移动设备上显示。这个工具还有一个特点，就是它能让创意人员作出内容时效性更强且交互性更强的广告，比如它可拖拽社交媒体的消息流到广告上。</p>\n<p>对于在广告领域HTML 5对Flash平台的侵蚀，Flite CEO Will Price称转变时间比人们预计得要长，但2014年后广告主和营销机构确实就能完全放掉Flash了。</p>",404,1583);
$z[5][4]['name']="body";
$z[6]=Array("field","",1585,1623);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","",1625,1662);
$z[7][4]['name']="litpic";

?>