{gemel:field name='keywords'}站长之家, 广告平台, Fli{/gemel:field}
{gemel:field name='description'}继Google推出HTML5网站和广告设计工具 Web Designer后，广告平台Flite也推出HTML 5广告在线制作工具。{/gemel:field}
{gemel:field name='title'}广告平台Flite：推HTML 5在线制作工具{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>继Google推出HTML5网站和广告设计工具 Web Designer后，广告平台Flite也推出HTML 5广告在线制作工具。</p>
<p></p>
<p>在Google的Web designer中制成的广告可直接发布到DoubleClick和AdMob等广告平台上。而Flite本就是一家广告平台，它可让广告主和创意机构实现广告创作、投放、内容实时更新和效果监测。</p>
<p>之前它就有一款广告创作工具DESIGN STUDIO，现在它为HTML 5推出了新版。和Google Web Designer需要下载软件不同的是，Flite这款免费工具是在线的，在浏览器中就能完成编辑操作，完成的广告支持在各移动设备上显示。这个工具还有一个特点，就是它能让创意人员作出内容时效性更强且交互性更强的广告，比如它可拖拽社交媒体的消息流到广告上。</p>
<p>对于在广告领域HTML 5对Flash平台的侵蚀，Flite CEO Will Price称转变时间比人们预计得要长，但2014年后广告主和营销机构确实就能完全放掉Flash了。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
