<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/170413/tt187-11.jpg ",96,234);
$z[1][4]['ddimg']="/upload/allimg/170413/tt187-11-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="550";
$z[1][4]['height']="500";
$z[2]=Array("img"," /upload/allimg/170413/tt187-12.jpg ",236,374);
$z[2][4]['ddimg']="/upload/allimg/170413/tt187-12-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="550";
$z[2][4]['height']="500";
$z[3]=Array("img"," /upload/allimg/170413/tt187-13.jpg ",376,514);
$z[3][4]['ddimg']="/upload/allimg/170413/tt187-13-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="550";
$z[3][4]['height']="500";
$z[4]=Array("img"," /upload/allimg/170413/tt187-14.jpg ",516,654);
$z[4][4]['ddimg']="/upload/allimg/170413/tt187-14-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="550";
$z[4][4]['height']="500";

?>