<li>
                         <div class="product_img">
                              <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="210" height="210"/></a>
                         </div>
                         <p><a href="[field:arcurl/]">[field:title/]</a></p>
                    </li>
                    {/gemel:list}     
               </ul>
         </div>
         <div class="products_list_box">
               <ul class="clear">
                    {gemel:list orderby='weight' pagesize='8' titlelen='50'}
                    <li>
                         <div class="product_img">
                              <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="210" height="210"/></a>
                         </div>
                         <p><a href="[field:arcurl/]">[field:title/]</a></p>
                    </li>
                    {/gemel:list}     
               </ul>
         </div>
         <div class="products_list_box">
               <ul class="clear">
                    {gemel:list orderby='weight' pagesize='8' titlelen='50'}
                    <li>
                         <div class="product_img">
                              <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="210" height="210"/></a>
                         </div>
                         <p><a href="[field:arcurl/]">[field:title/]</a></p>
                    </li>
                    {/gemel:list}     
               </ul>
         </div>
         <div class="products_list_box">
               <ul class="clear">
                    {gemel:list orderby='weight' pagesize='8' titlelen='50'}
                    <li>
                         <div class="product_img">
                              <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="210" height="210"/></a>
                         </div>
                         <p><a href="[field:arcurl/]">[field:title/]</a></p>
                    </li>
                    {/gemel:list}     
               </ul>
         </div>
         <div class="products_list_box">
               <ul class="clear">
                    {gemel:list orderby='weight' pagesize='8' titlelen='50'}
                    <li>
                         <div class="product_img">
                              <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="210" height="210"/></a>
                         </div>
                         <p><a href="[field:arcurl/]">[field:title/]</a></p>
                    </li>
                    {/gemel:list}     
               </ul>
         </div>
         <div class="products_list_box">
               <ul class="clear">
                    {gemel:list orderby='weight' pagesize='8' titlelen='50'}
                    <li>
                         <div class="product_img">
                              <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="210" height="210"/></a>
                         </div>
                         <p><a href="[field:arcurl/]">[field:title/]</a></p>
                    </li>
                    {/gemel:list}     
               </ul>
         </div>
         <div class="products_list_box">
               <ul class="clear">
                    {gemel:list orderby='weight' pagesize='8' titlelen='50'}
                    <li>
                         <div class="product_img">
                              <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="210" height="210"/></a>
                         </div>
                         <p><a href="[field:arcurl/]">[field:title/]</a></p>
                    </li>
                    {/gemel:list}     
               </ul>
         </div>
      </div>
      <div class="w980">
          <ul class="page">
                  {gemel:pagelist listitem="index,end,pageno" listsize="4" sitelang='en'