<li>
                      <img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="366" height="366"/>
                      <h2>[field:title/]</h2>
                      <div class="readmore">
                           <a href="[field:arcurl/]"><img src="/images/products/read.png" title="[field:title/]" alt="[field:title/]" width="366" height="460" /></a>
                           <h3>[field:title/]</h3>
                           <a href="[field:arcurl/]" class="more">Read more</a>
                      </div>
                  </li>