<?php
$z[0]=Array("field","",57,86);
$z[0][4]['name']="typepic";
$z[1]=Array("field","",93,123);
$z[1][4]['name']="typename";
$z[2]=Array("field","",132,162);
$z[2][4]['name']="typename";
$z[3]=Array("field","",223,253);
$z[3][4]['name']="typename";
$z[4]=Array("field","",298,327);
$z[4][4]['name']="content";
$z[5]=Array("global","",363,421);
$z[5][4]['name']="itemindex";
$z[5][4]['runphp']="yes";

?>