<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/140428/1-14042Q45336.png ",96,244);
$z[1][4]['ddimg']="/upload/allimg/140428/1-14042Q45336-lp.png";
$z[1][4]['text']="";
$z[1][4]['width']="448";
$z[1][4]['height']="275";
$z[2]=Array("img"," /upload/allimg/140428/1-14042Q45354.png ",246,394);
$z[2][4]['ddimg']="/upload/allimg/140428/1-14042Q45354-lp.png";
$z[2][4]['text']="";
$z[2][4]['width']="448";
$z[2][4]['height']="275";

?>