	
	
	
	
	
<field:body itemname="产品说明" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">
	
</field:body>
	

<field:parameters itemname="产品参数" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="">
</field:parameters>


<field:products_img itemname="产品图片" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="">
</field:products_img>
