<field:job_targets itemname="招聘岗位" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_targets>
<field:job_vacancies itemname="招聘人数" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_vacancies>
<field:job_add itemname="区域" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_add>
<field:job_expiration itemname="截止日期" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:job_expiration>
<field:department itemname="部门" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:department>
