<li>
                                                <a href="{gemel:field.typeurl/}"><img src="{gemel:field.typepic2/}" alt="" width="388" height="260" /></a>
                                                <div class="pro-layer">
                                                    <h3>{gemel:field.typename/}</h3>
                                                    <p>3/5 gallon water filling machine</p>
                                                    <a class="bt rect-btn noajax" href="{gemel:field.typeurl/}">
                                                        <svg>
                                                            <defs>
                                                                <linearGradient id="home-about" x1="0%" y1="0%" x2="100%" y2="0%">
                                                                    <stop offset="0%" stop-color="#FFF">
                                                                        <animate attributeName="stop-color" values="#FFF;#F5F5F5;#FFF;#FFF" dur="2s" repeatCount="indefinite"></animate>
                                                                    </stop>
                                                                    <stop offset="33%" stop-color="#FFF">
                                                                        <animate attributeName="stop-color" values="#F5F5F5;#FFF;#FFF;#FFF" dur="2s" repeatCount="indefinite"></animate>
                                                                    </stop>
                                                                    <stop offset="66%" stop-color="#F5F5F5">
                                                                        <animate attributeName="stop-color" values="#FFF;#F5F5F5;#FFF;#FFF;" dur="2s" repeatCount="indefinite"></animate>
                                                                    </stop>
                                                                </linearGradient>
                                                            </defs>
                                                            <rect x="0" y="0" fill="none" width="100%" height="100%" stroke="url(#home-about)"></rect>
                                                        </svg>
                                                        <p data-txt="Showroom">VIEW MORE</p>
                                                    </a>
                                                </div>
                                            </li>