<li>
                        <div class="img">
                            <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:typename/] - [field:title/]" alt="[field:typename/] - [field:title/]" width="240" height="184"/></a>
                        </div>
                        <div class="text">
                            <div class="icon">
                                <a href="[field:arcurl/]"><img src="/images/hot-icon.png" title="[field:typename/] - [field:title/]" alt="[field:typename/] - [field:title/]" width="100" height="93"/></a> 
                            </div>
                            <h2><a href="[field:arcurl/]">[field:typename/]</a></h2>
                            <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
                            <em></em>
                        </div>
                    </li>