{gemel:field name='keywords'}站长之家, twitter, Twitter大{/gemel:field}
{gemel:field name='description'}据国外媒体报道，《金融时报》网站称Twitter正在招聘大中华区媒体合作主管，预计该职位将负责提升Twitter在中国香港、台湾地区的媒体影响力。Twitter随后证实了招聘信息，{/gemel:field}
{gemel:field name='title'}Twitter证实正招聘大中华区媒体合作主管{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p style="text-align: center;"><img src="/upload/allimg/c130923/13OZ140934150-22004.jpg" border="0" /></p>
<p style="text-align: center;">Twitter上周对外公布，公司已秘密提交了上市申请</p>
<p>【TechWeb报道】9月22日消息，据国外媒体报道，《金融时报》网站称Twitter正在招聘大中华区媒体合作主管，预计该职位将负责提升Twitter在中国香港、台湾地区的媒体影响力。Twitter随后证实了招聘信息，但拒绝透露更多有关该职位的信息。</p>
<p>《金融时报》称，在更具体的方面，媒体合作主管将负责拉拢演员、运动员等名人注册、使用Twitter，联络电视台等媒体开展合作，以起到活跃用户、增加Twitter媒体效应的作用。大中华地区媒体主管将负责在香港、台湾以及大陆地区的上述业务。</p>
<p>除了招聘大中华区媒体主管外，Twitter还在其他10个国家招聘类似的职位，比如在日本、印度和德国地区的招聘显示，Twitter希望开展与当地电视台的合作，在巴西和加拿大招聘显示，Twitter希望展开与当地体育名人、机构的合作。</p>
<p>而除了招聘海外媒体合作主管外，Twitter近期还设立多个新的海外办事处，其中包括澳大利亚、法国和荷兰设立新的办事处等。此外，Twitter还从旧金山总部派出了一部分资深员工，负责管理国际业务，比如国际增长事务副总裁凯蒂&middot;雅克布斯&middot;斯坦顿(Katie Jacobs Stanton)被派驻Twitter巴黎办事处，而国际销售事务副总裁塞莱什&middot;拉奥(Shailesh Rao)被派新加坡办事处。</p>
<p>Twitter上周对外公布，已秘密提交了上市申请。市场研究机构eMarketer数据显示，2013年，Twitter海外营收预计只有9910万美元，远低于4.837亿美元的美国营收，而到2015年，Twitter在美国以外的营收将占到总营收的近四分之一。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130923/13OZ140934150-22004_lit.jpg{/gemel:field}
