{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/170619/pro-art-01-lp.jpg' text='' width='566' height='425'} /upload/allimg/170619/pro-art-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/straight-drawing-machine-02-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/straight-drawing-machine-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/straight-drawing-machine-03-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/straight-drawing-machine-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/straight-drawing-machine-04-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/straight-drawing-machine-04.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/straight-drawing-machine-05-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/straight-drawing-machine-05.jpg {/gemel:img}
