<?php
$z[0]=Array("arclist","\r\n				<div class=\"indexpro_img\">\r\n					<a href=\"[field:arcurl/]\">\r\n                    <img src=\"[field:litpic/]\" width=\"217\" height=\"120\" title=\"[field:title/]\" style=\"margin-top:10px;\" alt=\"[field:title/]\"/>\r\n                    </a>\r\n					<span></span>\r\n				</div>\r\n                ",22,369);
$z[0][4]['titlelen']="38";
$z[0][4]['row']="1";
$z[0][4]['flag']="c";
$z[1]=Array("field","",384,413);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",437,467);
$z[2][4]['name']="typename";

?>