<li>
                        <a href="[field:arcurl/]"><img src="[field:index_case/]" width="380" height="240" alt="" />
                            <em>&nbsp;</em>
                            <span class="case-title">[field:title/]</span>
                            <span class="case-con">[field:description function='cn_substrR(html2text(@me),100)'/]..</span>
                            <span class="case-more"><i>&nbsp;</i>Read more</span>
                        </a>
                    </li>