<li>
                            <a href="[field:arcurl/]" class="news_list_img"><img src="[field:litpic/]" /></a>
                            <div class="brand_list_right">
                                <p class="brand_list_tit"><a href="[field:arcurl/]">[field:title/]</a></p>
                                <p class="brand_list_profile">[field:description function='cn_substrR(html2text(@me),100)'/]...</p>
                                <a class="brand_more" href="[field:arcurl/]"></a>
                            </div>
                            <div class="clear"></div>
                        </li>