<li>
                    <a href=""><img src="/images/home-pro-04.jpg" title="" alt="" width="" height="" /></a>
                    <div class="title">
                          <div class="left">
                                <h2><a href="">PCM PROTECTION BOARD</a></h2>
                          </div>
                          <a href=""><em></em></a>
                    </div>
               </li>