{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140620/1-1406201QQ8-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201QQ8.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201QR1-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201QR1.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201QR4-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201QR4.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201QR7-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201QR7.jpg {/gemel:img}
