<div class="list_text clear">
              <h2><a href="/multihead-weigher/">Multihead Weigher</a></h2>
              <div class="list_img">
                   <a href="/multihead-weigher/"><img src="/images/list-01.jpg" title="" alt="" width="306" height="306" /></a>
              </div>
              <div class="list">
                   <ul class="clear">
                        <li>
                             <a href=""><img src="/images/01.jpg" title="" alt="" width="178" height="172" /></a>
                             <p><a href=""> 2012 Version Standard Weigher</a></p>
                        </li>
                        <li>
                             <a href=""><img src="/images/01.jpg" title="" alt="" width="178" height="172" /></a>
                             <p><a href=""> 2012 Version Standard Weigher</a></p>
                        </li>
                        <li>
                             <a href=""><img src="/images/01.jpg" title="" alt="" width="178" height="172" /></a>
                             <p><a href=""> 2012 Version Standard Weigher</a></p>
                        </li>
                   </ul>
                   <div class="more"><a href="/multihead-weigher/">&gt;&gt;More</a></div>
              </div>
        </div>