	
	
	
	
	
<field:body itemname="图片右侧广告" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">
	
</field:body>
	

<field:xinxi itemname="产品信息" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:xinxi>

<field:canshu itemname="产品参数" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:canshu>

<field:download itemname="资料下载" autofield="1" notsend="0" type="addon" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:download>

