<li>
                                   <div class="img">
                                        <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="190" height="190" /></a>
                                   </div>
                                   <h3><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h3>
                              </li>