<?php
$z[0]=Array("field","",13,42);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",51,78);
$z[1][4]['name']="currentstyle";
$z[2]=Array("field","",90,119);
$z[2][4]['name']="typepic";
$z[3]=Array("field","",126,156);
$z[3][4]['name']="typename";
$z[4]=Array("field","",165,195);
$z[4][4]['name']="typename";
$z[5]=Array("field","",228,258);
$z[5][4]['name']="typename";
$z[6]=Array("sql","\r\n                                              <li><a href=\"[field:array runphp='yes'] @me=GetOneTypeUrlA(@me);[/field:array]\">[field:typename/]</a></li>\r\n                                           ",427,696);
$z[6][4]['sql']="Select id from gemel_arctype where reid=4";

?>