{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/160614/dt8-d-01-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/dt8-d-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/dt8-d-02-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/dt8-d-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/dt8-d-03-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/dt8-d-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/dt8-d-04-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/dt8-d-04.jpg {/gemel:img}
