<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:product_number itemname="产品编号" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:product_number>
<field:product_use itemname="产品用途" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:product_use>
<field:capacity itemname="容量" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:capacity>
<field:parameters itemname="产品参数" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="">
</field:parameters>
<field:products_img itemname="产品图片" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="">
</field:products_img>
<field:products_download itemname="相关下载" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="">
</field:products_download>
