{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140620/1-1406201TK6-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201TK6.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201TK9-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201TK9.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201TP6-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201TP6.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201TR2-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201TR2.jpg {/gemel:img}
