<li>
                            <div class="img">
                                <a href="{gemel:field.typeurl/}"><img src="" title="{gemel:field.typename/}" alt="{gemel:field.typename/}" width="" height=""/></a>
                            </div>
                            <h2><a href="{gemel:field.typeurl/}">{gemel:field.typename/}</a></h2>
                            <div class="list">
                                <p><a href=""></a></p>
                            </div>
                        </li>