<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/150320/ac-6b14-2b-01x-m-01.jpg ",96,256);
$z[1][4]['ddimg']="/upload/allimg/150320/ac-6b14-2b-01x-m-01-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="712";
$z[1][4]['height']="352";
$z[2]=Array("img"," /upload/allimg/150320/ac-6b14-2b-01x-m-02.jpg ",258,418);
$z[2][4]['ddimg']="/upload/allimg/150320/ac-6b14-2b-01x-m-02-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="712";
$z[2][4]['height']="352";
$z[3]=Array("img"," /upload/allimg/150320/ac-6b14-2b-01x-m-03.jpg ",420,580);
$z[3][4]['ddimg']="/upload/allimg/150320/ac-6b14-2b-01x-m-03-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="712";
$z[3][4]['height']="352";

?>