<?php
$z[0]=Array("field","",54,111);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopInfo(@me,0,2)";
$z[1]=Array("channel","\r\n            <li class='pro_li_bg'>\r\n                <a href='[field:typeurl/]' class='prolist_a1'>[field:typename/]</a>\r\n                <div class=\"pro_icon\"></div>\r\n                <div class=\"clear\"></div>\r\n            </li>\r\n            ",194,475);
$z[1][4]['type']="son";
$z[2]=Array("rpad","",684,711);
$z[2][4]['name']="sub_tell";

?>