{gemel:field name='keywords'}站长之家, 新Surface, 微软平{/gemel:field}
{gemel:field name='description'}尴尬的微软：新Surface本体平庸 创新在键盘！ 一言以蔽之，作为Surface 2或Surface Pro 2的用户，你只需要在再花上1000块人民币左右，就能够拥有一台与笔记本体验类似的平{/gemel:field}
{gemel:field name='title'}尴尬的微软：新Surface本体平庸 创新在键盘！{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">      </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130925/13P0S05613560-14156.jpg" border="0" /></p>
<p><strong>腾讯科技 娄池 9月24日报道</strong></p>
<p>微软昨日发布了Surface 2和Surface Pro 2，Surface 2售价3288元起，Surface Pro 2售价人民币6588元起。和外界事先的猜想一样，两款产品并无任何让人眼前一亮的创新之处。尽管发布会上诸多微软高管试图创造出一种惊喜连连的氛围，但效果平平。</p>
<p>微软一如既往的热衷于强调效率和办公，整场发布会上充斥着有关速度提升和效率提升的介绍，甚至在展示Surface 2运行游戏的环节里，主持人都要开心的告诉台下观众，&ldquo;现在后台的Office仍在运行，我就喜欢一边Skype，一边工作，一边游戏&rdquo;。</p>
<p>显然拥有新款Surface的消费者不需要为不能全天办公而烦恼了，微软对工作狂群体拥有足够的吸引力，但据调研公司Gartner此前发布的报告称，购买平板电脑的用户绝大多数用于娱乐，其中包括玩游戏、阅读，流媒体或看电视直播等。</p>
<p>就目前发布会上体现的内容来看，微软两款新Surface在娱乐功能上尚无力与iPad抗衡，不过为了体现Surface的办公优势，在外设配件上下足了功夫，发布了数款专门为Surface打造的配件：</p>
<p>Touch Cover 2触控式键盘盖，配备了背光键盘，价格908元；Type Cover 2机械键盘盖，更加坚固，也增加了背光功能，价格988元；可充电键盘盖，确保在长时间的会议，价格未定；Surface Pro座充，类似Thinkpad扩展坞，帮Surface增加网口、USB口、扬声器，价格1488元&hellip;&hellip;</p>
<p>一言以蔽之，作为Surface 2或Surface Pro 2的用户，你只需要在再花上1000块人民币左右，就能够拥有一台与笔记本体验类似的平板电脑了。</p>
<p>这意味着Surface 2或Surface Pro 2的直接竞争对手是诸多笔记本电脑，但某PC厂商大陆高管向腾讯科技表示，Surface Pro 2的在性价比上与笔记本产品相比不具优势，而Surface 2针对的Windows RT市场一直没有打开，所以不看好两款新品。</p>
<p>不过，微软昨日的大秀并非全无亮点，一款名为Surface RemixProject的混音应用及其专用的Touch Cover (触控式键盘)创意十足，这款Touch Cover的按键布局与标准键盘版的Touch Cover 2完全不同，更适用于混音游戏。</p>
<p>这意味着触控式键盘将有更广泛的用途，不同应用对应不同键盘和按钮布局的时代即将来临，传统的键盘人机交互模式或将发生改变。目前微软对Touch Cover 2的介绍有限，键盘区域能否自由划分尚不得而知。</p>
<p>但据微软介绍，新款触控式键盘具备1092个感应器，远超上一代80個的数量，毫无疑问，模拟传统键盘并不需要这么多的感应器，或许从下代Touch Cover开始，数十年不变的传统键盘的时代将会结束。</p>
<p>这是微软在人机交互领域的重大突破，但Surface最大的创新居然是平板之外的键盘，这或许让微软有些尴尬。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130925/13P0S05613560-14156_lit.jpg{/gemel:field}
