{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/150724/makeup-stand-01-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150724/makeup-stand-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150724/makeup-stand-02-lp.jpg' text='' width='1040' height='498'} /upload/allimg/150724/makeup-stand-02.jpg {/gemel:img}
