{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140620/1-1406201II6-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201II6.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201II9-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201II9.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201IJ2-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201IJ2.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201IJ5-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201IJ5.jpg {/gemel:img}
