<li>
                    <a href="[field:typelink/]"><img src="/images/home-pro-02.jpg" title="" alt="" width="278" height="270" /></a>
                    <div class="title">
                          <div class="left">
                                <h2><a href="">PCM PROTECTION BOARD</a></h2>
                          </div>
                          <a href=""><em></em></a>
                    </div>
               </li>