		
	  <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='图片集' ischannel='1' link='content_i_list.php?channelid=2' linkadd='album_add.php?channelid=2' channelid='2' rank='' target='main' />
  <m:item name='证书集' ischannel='1' link='content_list.php?channelid=15' linkadd='archives_add.php?channelid=15' channelid='15' rank='' target='main' />
  <m:item name='equipment' ischannel='1' link='content_i_list.php?channelid=16' linkadd='album_add.php?channelid=16' channelid='16' rank='' target='main' />
  <m:item name='Terminals' ischannel='1' link='content_i_list.php?channelid=17' linkadd='album_add.php?channelid=17' channelid='17' rank='' target='main' />
  <m:item name='Board Connector' ischannel='1' link='content_i_list.php?channelid=19' linkadd='album_add.php?channelid=19' channelid='19' rank='' target='main' />
  <m:item name='Wire Connector' ischannel='1' link='content_i_list.php?channelid=20' linkadd='album_add.php?channelid=20' channelid='20' rank='' target='main' />
		
