<?php
$z[0]=Array("field","",94,116);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",137,160);
$z[1][4]['name']="typename";
$z[2]=Array("field","",167,190);
$z[2][4]['name']="typename";
$z[3]=Array("field","",299,321);
$z[3][4]['name']="typeurl";
$z[4]=Array("field","",323,346);
$z[4][4]['name']="typename";
$z[5]=Array("arclist","\r\n                                <p><a href=\"[field:arcurl/]\">[field:title/]</a></p>\r\n                                ",437,627);
$z[5][4]['orderby']="weight";
$z[5][4]['titlelen']="40";
$z[5][4]['row']="14";

?>