<li>
                        <a href="[field:arcurl/]" class="news_con_img"><img src="[field:litpic/]" /></a>
                        <div class="news_con_right">
                            <p class="news_con_tit"><a href="news2.html">[field:title/]([field:pubdate function="MyDate('Y-m-d',@me)"/])</a></p>
                            <p class="news_con_profile">[field:description function='cn_substrR(html2text(@me),100)'/]</p>
                            <a class="news_more" href="[field:arcurl/]"></a>
                        </div>
                        <div class="clear"></div>
                    </li>