
                        <li>
                            <a href="[field:link/]">
                                <img src="[field:pic/]" width="1600" height="824" alt="[field:text/]" title="[field:text/]">
                                <!--  <div class="banner-text">
                                    <h2>10 YEARS<br> 
CLEAR AS NEW</h2>
                                    <p>The color will not change in at least 5 years.
                                    </p>
                                    <p>100% acrylic.</p>
                                </div> -->
                            </a>
                        </li>
                        