<?php
$z[0]=Array("field","",58,80);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",82,105);
$z[1][4]['name']="typename";
$z[2]=Array("arclist","                   \r\n                        <li>\r\n                             <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"298\" height=\"450\" /></a>\r\n                             <p><a href=\"[field:arcurl/]\"> [field:shorttitle/]</a></p>\r\n                        </li>\r\n                        ",213,637);
$z[2][4]['orderby']="weight";
$z[2][4]['titlelen']="40";
$z[2][4]['row']="40";

?>