
                <li class="pro_li_bg"> 
                    <a href="[field:typeurl/]" class="prolist_a1">[field:typename/]</a>
                    <div class="pro_icon"></div>
                    <div class="clear"></div>
                    <ul class="pro_list2">
                        [field:sonchannel0]
                        <li><a href="#">[field:typename/]</a></li>  
                        [/field:sonchannel0] 
                    </ul>  
                </li>
                