<?php
$z[0]=Array("pagestyle","",0,92);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/131009/1-131009142209.jpg ",94,240);
$z[1][4]['ddimg']="/upload/allimg/131009/1-131009142209-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="530";
$z[1][4]['height']="394";
$z[2]=Array("img"," /upload/allimg/131009/1-131009142213.jpg ",242,388);
$z[2][4]['ddimg']="/upload/allimg/131009/1-131009142213-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="517";
$z[2][4]['height']="339";

?>