<?php
$z[0]=Array("arcurl","",86,101);
$z[1]=Array("litpic","",113,128);
$z[2]=Array("typename","",137,154);
$z[3]=Array("title","",157,171);
$z[4]=Array("typename","",178,195);
$z[5]=Array("title","",198,212);
$z[6]=Array("arcurl","",411,426);
$z[7]=Array("typename","",467,484);
$z[8]=Array("title","",487,501);
$z[9]=Array("typename","",508,525);
$z[10]=Array("title","",528,542);
$z[11]=Array("arcurl","",653,668);
$z[12]=Array("typename","",670,687);
$z[13]=Array("arcurl","",739,754);
$z[14]=Array("title","",756,770);

?>