{gemel:field name='keywords'}站长之家, 双十一, 当当网{/gemel:field}
{gemel:field name='description'}“#当店庆月遇见双11#当当网14周年店庆10.15正式开幕！百万图书3折！服装1.5折！”昨夜当当网官方微博发布消息，不过，该条微博随即就被删除，但还是被眼尖的网友截图留存{/gemel:field}
{gemel:field name='title'}图书3折服装1.5折 疑当当炒作备战双十一{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center;"><img src="/upload/allimg/c131015/13QR14Q20540-42018.jpg" border="0" width="250" alt="c3190db1jw1e9kzv2fqvqj20hs0qo772" style="border: 0px;" /></p>
<p><strong>站长之家（Chinaz.com）10月15日报道：</strong>&ldquo;#当店庆月遇见双11#当当网14周年店庆10.15正式开幕！百万图书3折！服装1.5折！&rdquo;昨夜当当网官方微博发布消息，不过，该条微博随即就被删除，但还是被眼尖的网友截图留存，也引来诸多网友的关注。而对微博内容，截至目前，当当网尚未作出任何回应。</p>
<p>图书3折，服装1.5折，不言而喻，这是备战双11的节奏。</p>
<p>前几日，当当网CEO李国庆的一封关于部署&ldquo;双十一作战&rdquo;的内部邮件被媒体公开，标志着当当网正式开启了&ldquo;双十一&rdquo;应战模式。除此之外，目前，天猫、京东、聚美优品、1号店也已相继发布今年&ldquo;双十一&rdquo;迎战策略。&nbsp;&nbsp;</p>
<p>根据李国庆的邮件显示，今年&ldquo;双十一&rdquo;当当网要打破常规，价格上将采取&ldquo;5折+折上折&rdquo;的方式，时间上大促销将贯彻整个十一月。</p>
<p>此次官微的&ldquo;疏忽&rdquo;，无疑将当当的折扣策略提前剧透给了消费者。</p>
<p>有分析人士就认为，这次的&ldquo;疏忽&rdquo;看起来更像是一次有预谋的炒作，借机宣传当当网的双十一与店庆促销活动，与前几日被媒体公开的李国庆内部邮件类似。</p>
<p>近两年，当当网持续亏损，股价也持续走低，截至目前，当当网在美市值仅为8.52亿美元，在中概股中排名较后，股价为10.36美元，低于发行价的16美元。根据艾瑞发布的2013Q2中国B2C购物网站交易规模市场份额数据显示，当当网的市场份额仅剩1.8%，受对手冲击非常大。</p>
<p>在这样的形势下，对于今年年初开始转型做平台电商的当当而言，&ldquo;双十一&rdquo;的重要性毋庸置疑。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131015/13QR14Q20540-42018_lit.jpg{/gemel:field}
