<li>
                                       <a href="[field:arcurl/]"><img src="field:pro_c/]" title="field:title/]" alt="field:title/]" width="298" height="284" /></a>
                                       <h3><a href="[field:arcurl/]">field:shorttitle/]</a></h3>
                                  </li>
                                  {/gemel:type}
                             </ul>
                       </div>
                       <div class="typename">
                             {gemel:type typeid='1'}
                             <h3><a href="[field:typelink/]">[field:typename/]</a></h3>
                             <a href="[field:typelink/]">READ MORE</a>
                             {/gemel:type}
                       </div>
                  </li>
                  <li class="even">
                       <div class="typename">
                             {gemel:type typeid='2'}
                             <h3><a href="[field:typelink/]">[field:typename/]</a></h3>
                             <a href="[field:typelink/]">READ MORE</a>
                             {/gemel:type}
                       </div>
                       <div class="hot-son">
                             <ul class="clear">
                                  {gemel:arclist flag="c" typeid='2' row='6' titlelen='40' orderby='weight' addfields='pro_c' channelid='2'}
                                  <li>
                                       <a href="[field:arcurl/]"><img src="field:pro_c/]" title="field:title/]" alt="field:title/]" width="298" height="284" /></a>
                                       <h3><a href="[field:arcurl/]">field:shorttitle/]</a></h3>
                                  </li>
                                  {/gemel:type}
                             </ul>
                       </div>
                  </li>
                  <li>
                       <div class="hot-son">
                             <ul class="clear">
                                  {gemel:arclist flag="c" typeid='3' row='6' titlelen='40' orderby='weight' addfields='pro_c' channelid='2'}
                                  <li>
                                       <a href="[field:arcurl/]"><img src="field:pro_c/]" title="field:title/]" alt="field:title/]" width="298" height="284" /></a>
                                       <h3><a href="[field:arcurl/]">field:shorttitle/]</a></h3>
                                  </li>
                                  {/gemel:type}
                             </ul>
                       </div>
                       <div class="typename">
                             {gemel:type typeid='3'}
                             <h3><a href="[field:typelink/]">[field:typename/]</a></h3>
                             <a href="[field:typelink/]">READ MORE</a>
                             {/gemel:type}
                       </div>
                  </li>
                  <li class="even">
                       <div class="typename">
                             {gemel:type typeid='4'}
                             <h3><a href="[field:typelink/]">[field:typename/]</a></h3>
                             <a href="[field:typelink/]">READ MORE</a>
                             {/gemel:type}
                       </div>
                       <div class="hot-son">
                             <ul class="clear">
                                  {gemel:arclist flag="c" typeid='4' row='6' titlelen='40' orderby='weight' addfields='pro_c' channelid='2'}
                                  <li>
                                       <a href="[field:arcurl/]"><img src="field:pro_c/]" title="field:title/]" alt="field:title/]" width="298" height="284" /></a>
                                       <h3><a href="[field:arcurl/]">field:shorttitle/]</a></h3>
                                  </li>
                                  {/gemel:type}
                             </ul>
                       </div>
                  </li>
            </ul>  
        </div>
    </div>    
</div> 
<!--hot-products end-->
<div class="w1200 home-technology">
    <h2>TECHNOLOGY</h2>
    <p class="from">From 2011 to now, We have the honor became the speaker designated manufacturer for Disney, Also very well and finished the Disney orders. so we confidently think that the (Disney)speakers we are maked will have more  sales miracle in the year coming.</p>
    <h3><a href="">Karaoke Speaker kbq-706</a></h3>
    <div class="effect-list">
          <ul class="clear">
               <li>
                    <em class="em1"></em>
                    <p>Bluetooth(support 2.0/3.0)</p>
               </li>
               <li class="right">
                    <em class="em2"></em>
                    <p>LED screen display with remote control</p>
               </li>
               <li>
                    <em  class="em3"></em>
                    <p>Support USB cable</p>
               </li>
               <li class="right">
                    <em class="em4"></em>
                    <p>Metal antenna FM radio with 360-degree rotating</p>
               </li>
               <li>
                    <em class="em5"></em>
                    <p>Support TF cable</p>
               </li>
               <li class="right">
                    <em class="em6"></em>
                    <p>Audio input</p>
               </li>
               <li>
                    <em class="em7"></em>
                    <p>Coolest animated LED marquee at front-panel</p>
               </li>
               <li class="right">
                    <em class="em8"></em>
                    <p>2 external microphone slots to Karaoke function</p>
               </li>
          </ul>
          <div class="img-box">
                 <a href=""><img src="/images/home-kbq-706.gif" title="Karaoke Speaker kbq-706" alt="Karaoke Speaker kbq-706" width="426" height="426" /></a>
                 <ul class="clear">
                      <li><img src="/images/home-kbq-706-01.png" title="Karaoke Speaker kbq-706" alt="Karaoke Speaker kbq-706" width="426" height="426" /></li>
                      <li><img src="/images/home-kbq-706-02.png" title="Karaoke Speaker kbq-706" alt="Karaoke Speaker kbq-706" width="426" height="426" /></li>
                      <li><img src="/images/home-kbq-706-03.png" title="Karaoke Speaker kbq-706" alt="Karaoke Speaker kbq-706" width="426" height="426" /></li>
                      <li><img src="/images/home-kbq-706-04.png" title="Karaoke Speaker kbq-706" alt="Karaoke Speaker kbq-706" width="426" height="426" /></li>
                      <li><img src="/images/home-kbq-706-05.png" title="Karaoke Speaker kbq-706" alt="Karaoke Speaker kbq-706" width="426" height="426" /></li>
                      <li><img src="/images/home-kbq-706-06.png" title="Karaoke Speaker kbq-706" alt="Karaoke Speaker kbq-706" width="426" height="426" /></li>
                      <li><img src="/images/home-kbq-706-07.png" title="Karaoke Speaker kbq-706" alt="Karaoke Speaker kbq-706" width="426" height="426" /></li>
                      <li><img src="/images/home-kbq-706-08.png" title="Karaoke Speaker kbq-706" alt="Karaoke Speaker kbq-706" width="426" height="426" /></li>    
                 </ul>
          </div>
    </div>
</div>
<!--home-about start-->
<div class="home-about-box">
    <img src="/images/home-about-bg.jpg" title="ABOUT US" alt="ABOUT US" width="1600" height="895"> 
    <div class="w1200">
          <h2>ABOUT US</h2>
          <p class="s"><strong><a href="/about/">Shenzhen King Bei Qi Electronic Co., Ltd.</a></strong> which specializes in designing, researching and developing, manufacturing and selling and also servicing, is a multi-media speaker manufacturer.</p>
          <div class="home-about-content clear">
                <div class="left">
                      <h3>Ali third-party audits video</h3>
                      <div class="img">
                         <a href="https://www.youtube.com/watch?v=ryIjtS7tSEM&amp;;lightbox[width]=900&amp;amo;lightbox[height]=500&amp;lightbox[modal]=true" rel="group1" class="lightbox"><img src="/images/home-about-video.jpg" title="Ali third-party audits video" alt="Ali third-party audits video" width="572" height="365" /></a>
                         <a href="https://www.youtube.com/watch?v=ryIjtS7tSEM&amp;;lightbox[width]=900&amp;amo;lightbox[height]=500&amp;lightbox[modal]=true" rel="group1" class="lightbox radius"><em></em></a>
                      </div>
                </div>
                <div class="right">
                      <ul class="clear">
                           <li class="clear">
                                <span>2007</span>
                                <p>Shenzhen King Bei Qi Electronic Company eastablished.</p>
                           </li>
                           <li class="clear">
                                <span>2012</span>
                                <p>Shenzhen King Bei Qi Electronic Company was honored to be the authorized speaker manufacturer of Disney.</p>
                           </li>
                           <li class="clear">
                                <span>2014</span>
                                <p>Shenzhen King Bei Qi Electronic Company took the lead in launching bluetooth wooden speakers series which have gained consistent highly favourable reputation from the market.</p>
                           </li>
                           <li class="clear">
                                <span>2015</span>
                                <p>Shenzhen King Bei Qi Electronic Company will continuously adhere to the principle "survive by pursuing excellent quality, develop by innovation and win the market by high reputation" to quality-control product strictly and do our best to make our clients win profit. Meanwhile, we will abide by our service concept: "pragmatic refinement, customer-oriented" to make progress with our clients hand in hand from home and aborad, creating a much more brilliant business performance and serving both the consumers and the society better !</p>
                           </li>
                      </ul>
                </div>
          </div>
          <a href="/about/" class="more">READ MORE</a>
    </div>
</div>
<!--home-about end-->
<!-- footer  begin -->
{gemel:include filename="footer.htm"