<li>
                            <div class="downloadlist_left">
                                <img src="[field:litpic/]" alt="资料下载" />
                                <a class="preview" href="[field:files_url/]">预览</a>|
                                <a href="/upload/pdf/download.php" onclick="downloadfile()">下载</a>       
                            </div>
                            <div class="downloadlist_right">
                                <a href="[field:files_url/]">[field:title/]</a>
                                <p>[field:description function='cn_substrR(html2text(@me),120)'/]...</p>
                            </div>
                        </li>