[filed:typename]{/gemel}</a>
            <ul>
            {gemel:channel typeid="1" type='top' rows="5"} 
            <li><a href="[field:typeurl/]">[field:typename/]</a></li>
            {/gemel:channel2}
            </ul>
        </li>
        <li class="siteweb_line">
            <a href="#" class="siteweb_tit">{gemel:type typeid="7" }[filed:typename]{/gemel}</a>
            <ul>
            {gemel:channel typeid="7" type='top' rows="5"} 
            <li><a href="[field:typeurl/]">[field:typename/]</a></li>
            {/gemel:channel2}
            </ul>
        </li>
        <li class="siteweb_line">
            <a href="#" class="siteweb_tit">{gemel:type typeid="13" }[filed:typename]{/gemel}</a>
            <ul>
            {gemel:channel typeid="13" type='top' rows="5"} 
            <li><a href="[field:typeurl/]">[field:typename/]</a></li>
            {/gemel:channel2}
            </ul>
        </li>
        <li class="siteweb_line">
            <a href="#" class="siteweb_tit">{gemel:type typeid="25" }[filed:typename]{/gemel}</a>
            <ul>
            {gemel:channel typeid="25" type='top' rows="5"} 
            <li><a href="[field:typeurl/]">[field:typename/]</a></li>
            {/gemel:channel2}
            </ul>
        </li>
        <li class="siteweb_line">
            <a href="#" class="siteweb_tit">{gemel:type typeid="21" }[filed:typename]{/gemel}</a>
            <ul>
            {gemel:channel typeid="21" type='top' rows="5"} 
            <li><a href="[field:typeurl/]">[field:typename/]</a></li>
            {/gemel:channel2}
            </ul>
        </li>
        </ul>
        <div></div>
    </div>
</div>

<div class="footer_box">
    <div class="footer">
        <div class="footer_right">
            {gemel:type typeid="20" }<a href="[field:typeurl/]">[field:typename/]</a>{/gemel}|
            {gemel:type typeid="21" }<a href="[field:typeurl/]">[field:typename/]</a>{/gemel}|
            {gemel:type typeid="21" }<a href="[field:typeurl/]">[field:typename/]</a>{/gemel}|
            {gemel:type typeid="21" }<a href="[field:typeurl/]">[field:typename/]</a>{/gemel}|
            {gemel:type typeid="21" }<a href="[field:typeurl/]">[field:typename/]</a>{/gemel}    
        </div>
        <div class="footer_left">{gemel:global.cfg_powerby