<li>
            	<div class="img">
            		<a href="[field:arcurl/]"><img src="/images/pro-01.jpg" title="[field:title/] - [field:typename/]" alt="[field:title/] - [field:typename/]" width="202" height="176"/></a>
            	</div>
            	<h3><a href="[field:arcurl/]" title="[field:title/] - [field:typename/]">[field:title/]</a></h3>
            	<a href="[field:arcurl/]">view more</a>
            </li>