<li class="clear">
                   <div class="news-img">
                       <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="170" height="140" /></a>
                   </div>
                   <div class="news-text">
                        <h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>
                        <p>[field:description function='cn_substrR(html2text(@me),150)'/]..</p>
                        <a href="[field:arcurl/]">MORE</a> 
                   </div>                       
              </li>