<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/150724/cosmetic-cabinet-01.jpg-50 ",96,260);
$z[1][4]['ddimg']="/upload/allimg/150724/cosmetic-cabinet-01.jpg-50";
$z[1][4]['text']="";
$z[1][4]['width']="1040";
$z[1][4]['height']="498";
$z[2]=Array("img"," /upload/allimg/150724/cosmetic-cabinet-03.jpg-50 ",262,426);
$z[2][4]['ddimg']="/upload/allimg/150724/cosmetic-cabinet-03.jpg-50";
$z[2][4]['text']="";
$z[2][4]['width']="1040";
$z[2][4]['height']="498";
$z[3]=Array("img"," /upload/allimg/150724/cosmetic-cabinet-04.jpg-50 ",428,592);
$z[3][4]['ddimg']="/upload/allimg/150724/cosmetic-cabinet-04.jpg-50";
$z[3][4]['text']="";
$z[3][4]['width']="1040";
$z[3][4]['height']="498";
$z[4]=Array("img"," /upload/allimg/150724/cosmetic-cabinet-05.jpg ",594,755);
$z[4][4]['ddimg']="/upload/allimg/150724/cosmetic-cabinet-05-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="1040";
$z[4][4]['height']="498";
$z[5]=Array("img"," /upload/allimg/150724/cosmetic-cabinet-06.jpg ",757,918);
$z[5][4]['ddimg']="/upload/allimg/150724/cosmetic-cabinet-06-lp.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="1040";
$z[5][4]['height']="498";

?>