		
	  <m:item name='普通文章' ischannel='1' link='content_list.php?channelid=1' linkadd='article_add.php?channelid=1' channelid='1' rank='' target='main' />
  <m:item name='棋博士中心' ischannel='1' link='content_list_s.php?channelid=14' linkadd='archives_add.php?channelid=14' channelid='14' rank='' target='main' />
  <m:item name='中心活动' ischannel='1' link='content_list.php?channelid=15' linkadd='archives_add.php?channelid=15' channelid='15' rank='' target='main' />
  <m:item name='家长感言' ischannel='1' link='content_list.php?channelid=16' linkadd='archives_add.php?channelid=16' channelid='16' rank='' target='main' />
  <m:item name='人才招聘' ischannel='1' link='content_list.php?channelid=17' linkadd='archives_add.php?channelid=17' channelid='17' rank='' target='main' />
  <m:item name='友情链接' ischannel='1' link='content_list.php?channelid=18' linkadd='archives_add.php?channelid=18' channelid='18' rank='' target='main' />
  <m:item name='常见问题' ischannel='1' link='content_list.php?channelid=19' linkadd='archives_add.php?channelid=19' channelid='19' rank='' target='main' />
		
