<li>
                           <div class="img">
                               <a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="360" height="240"/></a>
                           </div>
                           <h2><a href="[field:arcurl/]">[field:shorttitle/]</a></h2>
                           <p>[field:pro_size/]</p>
                      </li>