{gemel:field name='keywords'}站长之家, 新浪视频, PPT{/gemel:field}
{gemel:field name='description'}今日有媒体报道称，阿里巴巴正计划投资新浪视频，入股比例可能高于18%，谈判已经有了实质进展；而另有投资界人士则向腾讯科技表示，PPTV和苏宁的谈判依然在进行之中，目前{/gemel:field}
{gemel:field name='title'}阿里或入股新浪视频苏宁仍在接洽PPTV{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c130905/13N354235YY0-45495.jpg" border="0" /></p>
<p>腾讯科技讯（范晓东）9月5日消息，今日有媒体报道称，阿里巴巴正计划投资新浪视频，入股比例可能高于18%，谈判已经有了实质进展；而另有投资界人士则向腾讯科技表示，PPTV和苏宁的谈判依然在进行之中，目前而言，二者合作成功的可能性更高。</p>
<p>早在8月14日，曾传出阿里巴巴集团与湖南卫视将斥资4亿美元联手收购PPTV，但腾讯科技多方求证后获悉，各方仍在谈判阶段尚无定论，并有知情人士向腾讯科技透露，另一互联网公司新浪也介入阿里巴巴和PPTV合作谈判之中。</p>
<p>新浪视频在视频行业领域影响力不足，但是今年获得NBA赛事多项独家直播权，随着在线视频广告的规模增长越来越大，新浪发力视频可暂时缓解门户广告与微博长期左右互搏的难题，并把新浪体育和社区、电商结合，加速频道业务的独立化运营。</p>
<p>阿里投资新浪视频也能对其客厅战略形成补充，并提升IPO估值。2010年6月，阿里巴巴与华数传媒成立合资公司华数淘宝，并上线华数淘宝电视商城和淘花网两大平台，输出视频内容，但发展不温不火，而今年7月，阿里巴巴旗下阿里云与华数、海信等进行合作，再此推出装载有阿里云OS的互联网电视。</p>
<p>前期绯闻不断的PPTV的命运则一直未能落定，一位PPTV市场部人士向腾讯科技透露，PPTV最近获得一笔数额不高的资金流入，暂时缓解了现金流压力。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c130905/13N354235YY0-45495_lit.jpg{/gemel:field}
