{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/150824/ctp-01-lp.jpg' text='' width='495' height='365'} /upload/allimg/150824/ctp-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150824/ctp-02-lp.jpg' text='' width='495' height='365'} /upload/allimg/150824/ctp-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150824/ctp-03-lp.jpg' text='' width='495' height='365'} /upload/allimg/150824/ctp-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150824/ctp-04-lp.jpg' text='' width='495' height='365'} /upload/allimg/150824/ctp-04.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/150824/ctp-05-lp.jpg' text='' width='495' height='365'} /upload/allimg/150824/ctp-05.jpg {/gemel:img}
