<li>
                    <a href="[field:arcurl/]" class="news_con_img"><img src="[field:litpic/]" alt="[field:title function='html2text(@me)'/]" /></a>
                    <div class="news_con_right">
                        <p class="news_con_tit"><a href="[field:arcurl/]">[field:title/]([field:pubdate function="MyDate('Y-m-d',@me)"/])</a></p>
                        <p class="news_con_profile">[field:description function='cn_substrR(html2text(@me),200)'/]</p>
                        <a class="news_more" href="[field:arcurl/]"></a>
                    </div>
                </li>