<?php
$z[0]=Array("arcurl","",35,50);
$z[1]=Array("litpic","",83,98);
$z[2]=Array("title","",105,145);
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("arcurl","",262,277);
$z[4]=Array("title","",279,293);
$z[5]=Array("pubdate","",294,341);
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("description","",404,466);
$z[6][4]['function']="cn_substrR(html2text(@me),200)";
$z[7]=Array("arcurl","",523,538);

?>