<li>
                        <a class="charity_con_img" href="[field:arcurl/]"><img src="[field:litpic/]" alt="[field:title/]" title="[field:title/]" /></a>
                        <div class="charity_text">
                            <h2><a href="[field:arcurl/]">[field:title/]</a><h2>
                            <p>[field:description function='cn_substrR(html2text(@me),200)'/]....</p>
                        </div>
                    </li>