{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140714/90112-b-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90112-b.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90163-a--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90163-a-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90163-b--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90163-b-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90225-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90225-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90027-a-1-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90027-a-1.jpg {/gemel:img}
