<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/140714/90112-b.jpg ",96,232);
$z[1][4]['ddimg']="/upload/allimg/140714/90112-b-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="270";
$z[1][4]['height']="290";
$z[2]=Array("img"," /upload/allimg/140714/90163-a-.jpg ",234,372);
$z[2][4]['ddimg']="/upload/allimg/140714/90163-a--lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="270";
$z[2][4]['height']="290";
$z[3]=Array("img"," /upload/allimg/140714/90163-b-.jpg ",374,512);
$z[3][4]['ddimg']="/upload/allimg/140714/90163-b--lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="270";
$z[3][4]['height']="290";
$z[4]=Array("img"," /upload/allimg/140714/90225-a.jpg ",514,650);
$z[4][4]['ddimg']="/upload/allimg/140714/90225-a-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="270";
$z[4][4]['height']="290";
$z[5]=Array("img"," /upload/allimg/140714/90027-a-1.jpg ",652,792);
$z[5][4]['ddimg']="/upload/allimg/140714/90027-a-1-lp.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="270";
$z[5][4]['height']="290";

?>