{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140709/love-egg-vhgd29-01-lp.jpg' text='' width='270' height='290'} /upload/allimg/140709/love-egg-vhgd29-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140709/love-egg-vhgd29-02-lp.jpg' text='' width='270' height='290'} /upload/allimg/140709/love-egg-vhgd29-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140709/love-egg-vhgd29-03-lp.jpg' text='' width='270' height='290'} /upload/allimg/140709/love-egg-vhgd29-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140709/love-egg-vhgd29-04-lp.jpg' text='' width='270' height='290'} /upload/allimg/140709/love-egg-vhgd29-04.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140709/love-egg-vhgd29-05-lp.jpg' text='' width='270' height='290'} /upload/allimg/140709/love-egg-vhgd29-05.jpg {/gemel:img}
