{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140528/1-14052PU443-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PU443.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PU444-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PU444.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PU445-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PU445.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140528/1-14052PU446-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052PU446.jpg {/gemel:img}
