{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140528/1-14052P93P7-lp.jpg' text='' width='734' height='321'} /upload/allimg/140528/1-14052P93P7.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201J932-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201J932.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201J938-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201J938.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140620/1-1406201J942-lp.jpg' text='' width='734' height='321'} /upload/allimg/140620/1-1406201J942.jpg {/gemel:img}
