{gemel:field name='keywords'}站长之家, 苏宁, 苏宁易购{/gemel:field}
{gemel:field name='description'}首届O2O购物节阻击天猫“双十一”，苏宁云商(002024.sz)公布了前三天的销售数据：11月8日到11月11日，前三天订单总量近600万单，预计四天将整体超过1000万单，门店销售同比{/gemel:field}
{gemel:field name='title'}苏宁云商首届O2O购物节或破千万订单{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center;"><img src="/upload/allimg/c131112/13T22150B9460-14945.jpg" border="0" alt="fck_2013111113316_0" /></p>
<p style="text-align: center; font-size: 12px; text-indent: 0;">&nbsp;</p>
<p><span style="text-indent: 2em;">首届O2O购物节阻击天猫&ldquo;双十一&rdquo;，苏宁云商(002024.sz)公布了前三天的销售数据：11月8日到11月11日，前三天订单总量近600万单，预计四天将整体超过1000万单，门店销售同比增长近100%，南京地区销售同比增长400%。</span></p>
<p>其中，百货以131.6万单排订单数量排在第一位，紧随其后的是美妆89.25万单，母婴59.5万单以及3C的29.75万单，汽车卖出量亦达45辆。此次购物节，苏宁云台6000多家商户全部参与，商户订单达到128万单，OVO视频购物下单数量达到26万单，最高同时在线人数为960万人次，合计浏览量达5.6亿次。</p>
<p>与以往不同的是，本次双十一O2O成为关注焦点，如苏宁云商率先举办&ldquo;O2O网购节&rdquo;、随后国美电器、天猫与银泰商业集团等电商也纷纷采取跟随策略。</p>
<p>中国电子商务研究中心分析师莫岱青接受《第一财经日报》记者采访时表示，电商企业向线下延伸、搭建完整销售与体验链，而传统零售企业跨界向线上延展已成趋势。&ldquo;O2O模式&rdquo;在推动电商行业商业模式升级的同时，也为传统零售企业打通线上渠道。但究竟是苏宁云商模式&ldquo;1+1&gt;2&rdquo;，还是天猫银泰组合&ldquo;1+1&lt;2&rdquo;，还将拭目以待。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131112/13T22150B9460-14945_lit.jpg{/gemel:field}
