<div class="list clear">
                            <div class="img">
                                <a href="[field:arcurl/]"><img src="footer_news" title="[field:title/]" alt="[field:title/]" width="83" height="76"/></a>
                            </div>
                            <div class="text">
                                <h4><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h4>
                                <p>[field:description function='cn_substrR(html2text(@me),100)'/]...</p>
                            </div>
                        </div>