{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/160614/db7840-011-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/db7840-011.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/db7840-012-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/db7840-012.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/db7840-013-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/db7840-013.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/db7840-014-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/db7840-014.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/db7840-015-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160614/db7840-015.jpg {/gemel:img}
