{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140714/90239-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90239-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90239-b-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90239-b.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90242-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90242-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90242-b半身-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90242-b半身.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90243-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90243-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90243-a半身-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90243-a半身.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90243-a全身-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90243-a全身.jpg {/gemel:img}
