{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/151218/kbq-704-1-lp.png' text='' width='540' height='670'} /upload/allimg/151218/kbq-704-1.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/kbq-704-2-lp.png' text='' width='540' height='670'} /upload/allimg/151218/kbq-704-2.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/kbq-704-3-lp.png' text='' width='540' height='670'} /upload/allimg/151218/kbq-704-3.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/kbq-704-4-lp.png' text='' width='540' height='670'} /upload/allimg/151218/kbq-704-4.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/kbq-704-5-lp.png' text='' width='540' height='670'} /upload/allimg/151218/kbq-704-5.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/kbq-704-6-lp.png' text='' width='540' height='670'} /upload/allimg/151218/kbq-704-6.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/kbq-704-7-lp.PNG' text='' width='540' height='670'} /upload/allimg/151218/kbq-704-7.PNG {/gemel:img}
