{gemel:field name='keywords'}站长之家, WordPress3.0, 后台{/gemel:field}
{gemel:field name='description'}自从2.7版本之后，Wordpress管理系统在界面设计方面并无太大改变，而在如今这个追求视觉盛宴的时代，用户们越来越在意，或者说是更加期待优秀的设计。因此Wordpress开发团{/gemel:field}
{gemel:field name='title'}官方发布WordPress 3.8全新后台界面设计{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p><strong>站长之家（Chinaz.com）11月6日消息</strong>&nbsp; 自从2.7版本之后，Wordpress管理系统在界面设计方面并无太大改变，而在如今这个追求视觉盛宴的时代，用户们越来越在意，或者说是更加期待优秀的设计。因此Wordpress开发团队表示，他们将带来更加符合用户审美的设计。</p>
<p>MP6便是率先彰显&ldquo;现代化&rdquo;的设计，它是对现有框架的一个重大改进，存在极大的可能性。下面就一起看看这个集美学与实用性于一体的后台界面截图吧！</p>
<p>主面板：</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0Ub1050-14429.png" border="0" alt="" /></p>
<p>定制器：</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0V2L130-29322.png" border="0" alt="" /></p>
<p>添加文章界面：</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0V4942Z-32525.png" border="0" alt="" /></p>
<p>插件界面：</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0V55X60-45061.png" border="0" alt="" /></p>
<p>各种不同的风格选择：</p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0V633540-53560.png" border="0" alt="" /></p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0Vb0340-64360.png" border="0" alt="" /></p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0W044620-N029.png" border="0" alt="" /></p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0W100T0-X040.png" border="0" alt="" /></p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0W1K1Z-94417.png" border="0" alt="" /></p>
<p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131106/13SI0W2SO0-1091C.png" border="0" alt="" /></p>
<p>Via：</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131106/13SI0Ub1050-14429_lit.png{/gemel:field}
