<?php
$z[0]=Array("top","\r\n  <m:item name='采集节点管理' link='co_main.php' rank='co_ListNote' target='main' class='cjjdgl' />\r\n  <m:item name='临时内容管理' link='co_url.php' rank='co_ViewNote' target='main' class='lsnrgl' />\r\n  <m:item name='导入采集规则' link='co_get_corule.php' rank='co_GetOut' target='main' class='drcjgz'/>\r\n  <m:item name='监控采集模式' link='co_gather_start.php' rank='co_GetOut' target='main' class='jkcjms'/>\r\n  <m:item name='采集未下载内容' link='co_do.php?dopost=coall' rank='co_GetOut' target='main' class='cjwxznr'/>\r\n",51,742);
$z[0][4]['item']="1_";
$z[0][4]['name']="采集管理";
$z[0][4]['display']="none";
$z[0][4]['rank']="co_NewRule,co_ListNote,co_ViewNote,co_Switch,co_GetOut";
$z[0][4]['class']="cjgl";

?>