<div class="applicationdiv">
            <h1 class="title"><a href="{gemel:field name='typeurl'/}">{gemel:field name='typename'/}</a></h1>
            <ul class="applicationul">
                {gemel:arclist titlelen='38' row='4' flag='c' addfields='app_img' channelid='16'}
                <li class="featLeft">
                <a href="[field:app_img/]" rel="prettyPhoto[]" title="[field:title/]"><img src="[field:litpic/]" alt="[field:title/]" title="[field:title/]"/></a>
                <span>[field:title/]</span>
                </li>
                {/gemel:arclist}
            </ul>
        </div>