{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/170621/wet-drawing-machine-1-01-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/wet-drawing-machine-1-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/wet-drawing-machine-1-02-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/wet-drawing-machine-1-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/wet-drawing-machine-1-03-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/wet-drawing-machine-1-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/wet-drawing-machine-1-04-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/wet-drawing-machine-1-04.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/170621/wet-drawing-machine-1-05-lp.jpg' text='' width='566' height='429'} /upload/allimg/170621/wet-drawing-machine-1-05.jpg {/gemel:img}
