<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/170621/wet-drawing-machine-1-01.jpg ",96,266);
$z[1][4]['ddimg']="/upload/allimg/170621/wet-drawing-machine-1-01-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="566";
$z[1][4]['height']="429";
$z[2]=Array("img"," /upload/allimg/170621/wet-drawing-machine-1-02.jpg ",268,438);
$z[2][4]['ddimg']="/upload/allimg/170621/wet-drawing-machine-1-02-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="566";
$z[2][4]['height']="429";
$z[3]=Array("img"," /upload/allimg/170621/wet-drawing-machine-1-03.jpg ",440,610);
$z[3][4]['ddimg']="/upload/allimg/170621/wet-drawing-machine-1-03-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="566";
$z[3][4]['height']="429";
$z[4]=Array("img"," /upload/allimg/170621/wet-drawing-machine-1-04.jpg ",612,782);
$z[4][4]['ddimg']="/upload/allimg/170621/wet-drawing-machine-1-04-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="566";
$z[4][4]['height']="429";
$z[5]=Array("img"," /upload/allimg/170621/wet-drawing-machine-1-05.jpg ",784,954);
$z[5][4]['ddimg']="/upload/allimg/170621/wet-drawing-machine-1-05-lp.jpg";
$z[5][4]['text']="";
$z[5][4]['width']="566";
$z[5][4]['height']="429";

?>