{gemel:field name='keywords'}站长之家, 马明哲, 壹钱包{/gemel:field}
{gemel:field name='description'}据曝光的平安集团董事长马明哲在平安集团新年内部讲话中，再次提到1月中旬上市的移动社交金融服务平台“壹钱包”。南都记者昨日下载内测版体验，实际体验一般，实用工具中{/gemel:field}
{gemel:field name='title'}“壹钱包”内测马明哲带头推广 实际体验一般{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c140103/13XG5V635V0-34607.jpg" border="0" /></p>
<p style="text-align: center;">&ldquo;壹钱包&rdquo;内测马明哲带头推广</p>
<p>在马云高调推动来往后，平安的马明哲，也带头推动在内部的电子钱包&mdash;&mdash;&mdash;&ldquo;壹钱包&rdquo;</p>
<p>据曝光的平安集团董事长马明哲在平安集团新年内部讲话中，再次提到1月中旬上市的移动社交金融服务平台&ldquo;壹钱包&rdquo;。南都记者昨日下载内测版体验，实际体验一般，实用工具中仅有&ldquo;友钱&rdquo;、&ldquo;应用&rdquo;、&ldquo;充值&rdquo;和&ldquo;红包&rdquo;四个子项目。</p>
<p>平安集团昨日回复南都记者称，综合金融、科技引领是平安战略，公司正在沿着这个方向积极探索。壹钱包正在开发过程中，目前没有具体信息。而据平安有关人士透露，壹钱包的测试版本已修改多次，还不能确定最终的版本。</p>
<p><strong>定位为互联网金融核心平台</strong></p>
<p>曝光的马明哲在平安集团新年内部讲话中透露，&ldquo;壹钱包&rdquo;可以帮助客户进行财富管理、健康管理、生活管理的移动社交金融服务平台，也是平安员工离不开的移动工作管理平台。</p>
<p>在马明哲未来的战略定位中，&ldquo;壹钱包&rdquo;将是整个平安互联网金融的核心平台，为广大客户与全体平安人提供全新的移动智能服务体验，这将使中国平安综合金融的发展步入一个新的时代。</p>
<p>平安集团昨日回复南都记者称，&ldquo;综合金融、科技引领是平安战略，公司正在沿着这个方向积极探索。&rdquo;</p>
<p><strong>最终版本还未确定</strong></p>
<p>马明哲在讲话中希望&ldquo;壹钱包&rdquo;成为&ldquo;公司差异化、核心竞争力的利器&rdquo;。而据平安集团有关人员透露，&ldquo;壹钱包&rdquo;的设计长达半年多。平安集团官方亦在昨日对南都记者表示，&ldquo;壹钱包正在开发过程中，目前没有具体信息。&rdquo;</p>
<p>针对2013年12月23日最新版本要求收取0.1元注册费的情况，平安集团亦表示，当前是面向内部员工测试，&ldquo;壹钱包&rdquo;正式上线会后取消。</p>
<p>事实上，12月23日版的&ldquo;壹钱包&rdquo;版本较为简易，实用工具中仅有&ldquo;友钱&rdquo;、&ldquo;应用&rdquo;、&ldquo;充值&rdquo;和&ldquo;红包&rdquo;四个子项目。而应用中心则可以下载&ldquo;临用钱&rdquo;、&ldquo;健康卡&rdquo;、&ldquo;陆金所&rdquo;和&ldquo;万里通&rdquo;积分平台等平安集团下属的app。</p>
<p>事实上，壹钱包关联的部分应用跟平安集团重点打造的陆金所和平安付等新增的两大共享平台关联较大。据目前的版本情况显示，&ldquo;临用钱&rdquo;可以在便利店快速提取现金。而&ldquo;健康卡&rdquo;则是平安付科技与平安养老保险推出的新产品，被平安副董事长邵海峰定义为&ldquo;保险客户向支付业务迁移&rdquo;的一次尝试。此外，陆金所则是进行p2p融资的重要平台。</p>
<p>据平安有关人士透露，壹钱包的测试版本已修改多次，还不能确定最终的版本。</p>
<p>采写：南都记者 梁小婵</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c140103/13XG5V635V0-34607_lit.jpg{/gemel:field}
