{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/151218/a-208-1-lp.png' text='' width='540' height='670'} /upload/allimg/151218/a-208-1.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/a-208-2-lp.png' text='' width='540' height='670'} /upload/allimg/151218/a-208-2.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/a-208-3-lp.png' text='' width='540' height='670'} /upload/allimg/151218/a-208-3.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/a-208-4-lp.png' text='' width='540' height='670'} /upload/allimg/151218/a-208-4.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/a-208-5-lp.png' text='' width='540' height='670'} /upload/allimg/151218/a-208-5.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/a-208-6-lp.png' text='' width='540' height='670'} /upload/allimg/151218/a-208-6.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/a-208-7-lp.png' text='' width='540' height='670'} /upload/allimg/151218/a-208-7.png {/gemel:img}
