<li>
                      <img src="/images/products/cwk2.jpg" title="[field:title/]" alt="[field:title/]" width="366" height="366"/>
                      <h2>[field:title/]</h2>
                      <p>{gemel:field.typename/}</p>
                      <div class="readmore">
                           <h3>[field:title/]</h3>
                           <a href="[field:arcurl/]">Read more</a>
                      </div>
                  </li>