<li>
                         <a href="[field:video/];lightbox[width]=900&amo;lightbox[height]=500&amp;lightbox[modal]=true" rel="group1" class="lightbox"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="238" height="216" /></a>
                         <p><a href="[field:video/];lightbox[width]=900&amo;lightbox[height]=500&amp;lightbox[modal]=true" rel="group1" class="lightbox" >[field:title/]</a></p>
                    </li>