<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",78,113);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",202,253);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("list","\r\n          <li>\r\n                <div class=\"list_left\">\r\n                      <a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"398\" height=\"275\" /></a>\r\n                </div>\r\n                <div class=\"list_right\">\r\n                      <h2>[field:title/]</h2>\r\n                      <p>[field:description function='cn_substr(@me,240)'/]....</p>\r\n                      <a href=\"[field:arcurl/]\" target=\"_blank\">Read More</a>\r\n                </div>\r\n          </li>\r\n          ",453,1078);
$z[3][4]['orderby']="weight";
$z[3][4]['pagesize']="5";
$z[3][4]['titlelen']="100";
$z[4]=Array("pagelist","",1141,1213);
$z[4][4]['listitem']="index,end,pageno";
$z[4][4]['listsize']="4";
$z[4][4]['sitelang']="en";
$z[5]=Array("include","",1507,1543);
$z[5][4]['filename']="foot.htm";

?>