<div class="exhibition_list">      
                        <div class="exhibition_pic">
                            <a href="[field:arcurl/]"><img src="[field:litpic/]" width="51" height="51" alt="[field:title/]" title="[field:title/]"></a></div>
                        <div class="exhibition_content">
                            <a href="[field:arcurl/]">[field:title/]</a></div>
                        <div class="clear"></div>
                    </div>