{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/160614/db7824-01.jpg-50' text='' width='1158' height='520'} /upload/allimg/160614/db7824-01.jpg-50 {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/db7824-02.jpg-50' text='' width='1158' height='520'} /upload/allimg/160614/db7824-02.jpg-50 {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/db7824-03.jpg-50' text='' width='1158' height='520'} /upload/allimg/160614/db7824-03.jpg-50 {/gemel:img}
{gemel:img ddimg='/upload/allimg/160614/db7824-04.jpg-50' text='' width='1158' height='520'} /upload/allimg/160614/db7824-04.jpg-50 {/gemel:img}
