<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/160614/db7824-01.jpg-50 ",96,240);
$z[1][4]['ddimg']="/upload/allimg/160614/db7824-01.jpg-50";
$z[1][4]['text']="";
$z[1][4]['width']="1158";
$z[1][4]['height']="520";
$z[2]=Array("img"," /upload/allimg/160614/db7824-02.jpg-50 ",242,386);
$z[2][4]['ddimg']="/upload/allimg/160614/db7824-02.jpg-50";
$z[2][4]['text']="";
$z[2][4]['width']="1158";
$z[2][4]['height']="520";
$z[3]=Array("img"," /upload/allimg/160614/db7824-03.jpg-50 ",388,532);
$z[3][4]['ddimg']="/upload/allimg/160614/db7824-03.jpg-50";
$z[3][4]['text']="";
$z[3][4]['width']="1158";
$z[3][4]['height']="520";
$z[4]=Array("img"," /upload/allimg/160614/db7824-04.jpg-50 ",534,678);
$z[4][4]['ddimg']="/upload/allimg/160614/db7824-04.jpg-50";
$z[4][4]['text']="";
$z[4][4]['width']="1158";
$z[4][4]['height']="520";

?>