{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/160601/dr-g-01-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-g-01.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160601/dr-g-02-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-g-02.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160601/dr-g-03-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-g-03.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160601/dr-g-04-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-g-04.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160601/dr-g-05-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-g-05.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160601/dr-g-06-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-g-06.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/160601/dr-g-07-lp.jpg' text='' width='1158' height='520'} /upload/allimg/160601/dr-g-07.jpg {/gemel:img}
