{gemel:field name='keywords'}站长之家, 苹果第二, 科技{/gemel:field}
{gemel:field name='description'}根据品牌与市场调查公司CoreBrand对1万名副总裁级别企业高管进行的调查显示，在科技行业最受尊敬品牌中，苹果排名第二。{/gemel:field}
{gemel:field name='title'}科技产业最受尊敬品牌排名：IBM第一 苹果第二{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131114/13T4101MKV0-2N21.jpg" border="0" /></p>
<p><strong>腾讯科技 瑾瑜 11月14日编译</strong></p>
<p>根据品牌与市场调查公司CoreBrand对1万名副总裁级别企业高管进行的调查显示，在科技行业最受尊敬品牌中，苹果排名第二。</p>
<p>CoreBrand编制了一份《美国最具影响力品牌》排名名单，其对众多全球最大企业的高管们进行了访问，要求高管们对品牌熟悉度和品牌好感度进行排名。（名单上的企业均已上市至少五年。在名单中所列出品牌均是CoreBrand跟踪五年以上的企业。）</p>
<p>以下是高管们最钦佩的科技界品牌前五位：</p>
<p>1. IBM</p>
<p>虽苹果备受消费者推崇，但是IBM却为企业提供了无与伦比的IT服务。IBM专于数据分析及云计算，且在新兴市场增长迅速。</p>
<p>2. 苹果</p>
<p>苹果推出了新一代iPad Air及搭载iOS 7操作系统的iPhone 5s等产品，其时刻准备着夺回&ldquo;最具创造力的公司&rdquo;这个头衔。该公司之所以屈居第二，原因或许是，苹果在今年大部分时间中平庸的表现。</p>
<p>3.微软</p>
<p>微软的Windows操作系统虽然比不上谷歌(微博)的Android，但是微软的平台至今仍是众多开发者们的首选。</p>
<p>4.雅虎</p>
<p>雅虎CEO玛丽莎&middot;梅耶尔（Marissa Mayer）最广为人知的就是，能够化腐朽为神奇，将一个品牌&ldquo;变废为宝&rdquo;。梅耶尔加入后，雅虎的主页及邮箱服务改头换面，并收购了轻博客平台Tumblr。</p>
<p>5. 德州仪器</p>
<p>德州仪器在半导体生产方面声名远扬，该公司良好的商业道德一直备受赞誉。</p>
<p>由于追踪时间未达5年，CoreBrand这份名单中并未包含谷歌。Corebrand表示，如果只是对企业高层进行调查，那么得出排名结果也就不足为奇。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131114/13T4101MKV0-2N21_lit.jpg{/gemel:field}
