{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140714/90245-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90245-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90245-a--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90245-a-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90245-b-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90245-b.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90245-b--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90245-b-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90246-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90246-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90246-b-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90246-b.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90254-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90254-a.jpg {/gemel:img}
