<?php
$z[0]=Array("arcurl","",86,101);
$z[1]=Array("litpic","",113,128);
$z[2]=Array("typename","",137,154);
$z[3]=Array("title","",157,171);
$z[4]=Array("typename","",178,195);
$z[5]=Array("title","",198,212);
$z[6]=Array("arcurl","",363,378);
$z[7]=Array("shorttile","",380,398);
$z[8]=Array("arcurl","",450,465);
$z[9]=Array("typename","",474,491);
$z[10]=Array("title","",494,508);
$z[11]=Array("title","",510,524);
$z[12]=Array("arcurl","",572,587);
$z[13]=Array("typename","",596,613);
$z[14]=Array("title","",616,630);

?>