{gemel:field name='keywords'}站长之家, 工信部, 手机预{/gemel:field}
{gemel:field name='description'}手机厂商预装软件必须要通过工信部的审核关卡，不得安装未经用户同意，擅自收集、修改用户信息的软件。这对国产手机厂商来说是一个考验，目前主要国产手机厂商都将应用预装{/gemel:field}
{gemel:field name='title'}工信部：下月起手机预装软件须先报备{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p style="text-align: center; text-indent: 0;"><img src="/upload/allimg/c131015/13QR14QV4F-53400.jpg" border="0" /></p>
<p style="text-align: center;">（工信部：下月起手机预装软件须先报备）</p>
<p>搜狐IT记者 宿艺</p>
<p>工信部颁布的《关于加强移动智能终端进网管理的通知》将于下月正式实施。</p>
<p>手机厂商预装软件必须要通过工信部的审核关卡，不得安装未经用户同意，擅自收集、修改用户信息的软件。这对国产手机厂商来说是一个考验，目前主要国产手机厂商都将应用预装作为扩大营收的手段。</p>
<p>国内手机预装软件途径主要有：</p>
<p>运营商集采手机要求预装；手机厂商发货之前预装；手机销售渠道中，经销商层层预装一线销售人员为盈利预装；</p>
<p>工信部此次《通知》目的在于解决目前国产手机应用预装乱象。不过分析人士认为，目前国产手机厂商都处于&ldquo;微利&rdquo;或者亏损。刷机渠道也已形成完整地下产业链，《通知》仅从手机出厂方面对手机厂商进行了某种约束，但却并未出台配套的监督实施和惩罚措施，能否达到实际意义还有待观察。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}/upload/allimg/c131015/13QR14QV4F-53400_lit.jpg{/gemel:field}
