<li>
                   <div class="h3">
                       <h3>{gemel:field.typename/}<span id="zan"></span></h3>
                   </div>
                   <ul>
                       {gemel:arclist orderby='weight' shorttitlelen='40' titlelen='40'}
                       <li><a href="[field:arcurl/]" title="[field:title/]" >[field:shorttitle/]</a></li>
                       {/gemel:arclist}
                   </ul>
              </li>