<tr>
                           <td><a href="[field:arcurl/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="150" height="104" /></a></td>
                           <td>[field:shorttitle/]</td>
                           <td>[field:working_current/]</td>
                           <td>[field:pcm_size/]</td>
                           <td>[field:balancing_pcm/]</td>
                           <td>[field:temp_control/]</td>
                      </tr>