	
	
	
<field:description2 itemname="产品描述" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:description2>	
	
<field:body itemname="产品说明" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="" page="split">
	
</field:body>
	
<field:guide itemname="使用指南" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="500" page="">
</field:guide>
