<?php
$z[0]=Array("pagestyle","",0,94);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/151218/kbq-06m-1.png ",96,236);
$z[1][4]['ddimg']="/upload/allimg/151218/kbq-06m-1-lp.png";
$z[1][4]['text']="";
$z[1][4]['width']="540";
$z[1][4]['height']="670";
$z[2]=Array("img"," /upload/allimg/151218/kbq-06m-2.png ",238,378);
$z[2][4]['ddimg']="/upload/allimg/151218/kbq-06m-2-lp.png";
$z[2][4]['text']="";
$z[2][4]['width']="540";
$z[2][4]['height']="670";
$z[3]=Array("img"," /upload/allimg/151218/kbq-06m-3.png ",380,520);
$z[3][4]['ddimg']="/upload/allimg/151218/kbq-06m-3-lp.png";
$z[3][4]['text']="";
$z[3][4]['width']="540";
$z[3][4]['height']="670";
$z[4]=Array("img"," /upload/allimg/151218/kbq-06m-4.png ",522,662);
$z[4][4]['ddimg']="/upload/allimg/151218/kbq-06m-4-lp.png";
$z[4][4]['text']="";
$z[4][4]['width']="540";
$z[4][4]['height']="670";
$z[5]=Array("img"," /upload/allimg/151218/kbq-06m-5.png ",664,804);
$z[5][4]['ddimg']="/upload/allimg/151218/kbq-06m-5-lp.png";
$z[5][4]['text']="";
$z[5][4]['width']="540";
$z[5][4]['height']="670";

?>