{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/151218/kbq-06m-1-lp.png' text='' width='540' height='670'} /upload/allimg/151218/kbq-06m-1.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/kbq-06m-2-lp.png' text='' width='540' height='670'} /upload/allimg/151218/kbq-06m-2.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/kbq-06m-3-lp.png' text='' width='540' height='670'} /upload/allimg/151218/kbq-06m-3.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/kbq-06m-4-lp.png' text='' width='540' height='670'} /upload/allimg/151218/kbq-06m-4.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151218/kbq-06m-5-lp.png' text='' width='540' height='670'} /upload/allimg/151218/kbq-06m-5.png {/gemel:img}
