<li class="clear">
      <div class="img_left">
          <img src="/upload/products/list-big-04.png" alt="PVC Edge banding" title="PVC Edge banding" width="892" height="562" />
          <div class="left_bg">
             <a href="[field:typelink/]">MORE</a>
          </div>
      </div>
      <div class="text_right text_02">
        <h2><a href="[field:typelink/]">[field:typename/]</a></h2>
        <p>[field:description/]</p>
        <ul class="clear">
          <li class="li_right">
              <a href=""><img src="/upload/products/list-04-01.png" alt="PVC Edge banding" title="PVC Edge banding" width="173" height="114" /></a>
              <h3>3D edge banding</h3>
          </li>
          <li>
              <a href=""><img src="/upload/products/list-04-02.png" alt="PVC Edge banding" title="PVC Edge banding" width="173" height="114" /></a>
              <h3>Double color light edge</h3>
        </ul>
      </div>
    </li>