<li>
                             <div class="news_imgage">
                                <a href="[field:arcurl/]"><img src="[field:litpic/]" width="200" height="139" alt="[field:title/]" title="[field:title/]"/></a>
                             </div>
                             <div class="news_title">
                                <h2><a href="[field:arcurl/]">[field:title/]</a></h2>
                                <p class="news_profile">[field:description/]...</p>
                                <p class="news_read"><a href="[field:arcurl/]">Read more...</a></p>
                             </div>
                             <div class="clear"></div>
                         </li>