{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/140714/90035-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90035-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90035-c-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90035-c.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90044-a-lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90044-a.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90046-a--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90046-a-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90049-a--lp.jpg' text='' width='270' height='290'} /upload/allimg/140714/90049-a-.jpg {/gemel:img}
{gemel:img ddimg='/upload/allimg/140714/90257-a.jpg-50' text='' width='270' height='290'} /upload/allimg/140714/90257-a.jpg-50 {/gemel:img}
