{gemel:field name='keywords'}站长之家, 高级债券, 新浪{/gemel:field}
{gemel:field name='description'}今日早间，新浪宣布计划发行6亿美元可转换高级债券，于2018年到期。不过，其尚未确定债券的可转换率和相关条款。{/gemel:field}
{gemel:field name='title'}新浪将发6亿美元可转换高级债券 于2018年到期{/gemel:field}
{gemel:field name='writer'}{/gemel:field}
{gemel:field name='source'}{/gemel:field}
{gemel:field name='body'}<p style="text-align:center;">          </p>
                                                            <p>今日早间，新浪宣布计划发行6亿美元可转换高级债券，于2018年到期。不过，其尚未确定债券的可转换率和相关条款。</p>
<p>新浪称，如果可转换债券超额配售，将计划向认购者提供30天的选择权，从而使后者能够购买附加的9000万美元可转换高级债券。同时，上述债券可根据持有人意愿，最早在第二个交易日转换为公司普通股。此外，债券持有人将有权在2016年12月1日要求新浪以票面本金外加上未支付的利息，赎回全部或部分的债券。</p>
<p>对于资金的用途，新浪表示，计划使用此次募集资金中的1亿美元用于回购公司已发行普通股，剩余资金将被用于企业一般用途和潜在的收购业务等。</p>
<p>受第三季度业绩利好影响，新浪股价周三上涨11.38%，报收于84.55美元。</p>{/gemel:field}
{gemel:field name='pubdate'}{/gemel:field}
{gemel:field name='litpic'}{/gemel:field}
