<?php
$z[0]=Array("pagestyle","",0,92);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="100";
$z[0][4]['col']="100";
$z[0][4]['value']="3";
$z[1]=Array("img"," /upload/allimg/131009/1-131009142K3.jpg ",94,238);
$z[1][4]['ddimg']="/upload/allimg/131009/1-131009142K3-lp.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="409";
$z[1][4]['height']="296";
$z[2]=Array("img"," /upload/allimg/131009/1-131009142K6.jpg ",240,384);
$z[2][4]['ddimg']="/upload/allimg/131009/1-131009142K6-lp.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="621";
$z[2][4]['height']="473";
$z[3]=Array("img"," /upload/allimg/131009/1-131009142K9.jpg ",386,530);
$z[3][4]['ddimg']="/upload/allimg/131009/1-131009142K9-lp.jpg";
$z[3][4]['text']="";
$z[3][4]['width']="488";
$z[3][4]['height']="346";
$z[4]=Array("img"," /upload/allimg/131009/1-131009142P2.jpg ",532,676);
$z[4][4]['ddimg']="/upload/allimg/131009/1-131009142P2-lp.jpg";
$z[4][4]['text']="";
$z[4][4]['width']="641";
$z[4][4]['height']="434";

?>