<li>
                            <a class="product-img" href="[field:arcurl/]">
                                <img src="[field:litpic/]" width="282" height="259" alt="[field:title/]" title="[field:title/]">
                            </a>
                            <a class="product-txt" href="[field:arcurl/]">
                                <!-- <i>[field:title/]</i> -->
                                <span>[field:title/]</span>
                            </a>
                        </li>