<?php
$z[0]=Array("arcurl","",33,48);
$z[1]=Array("title","",57,71);
$z[2]=Array("litpic","",83,98);
$z[3]=Array("title","",107,121);
$z[4]=Array("title","",128,142);
$z[5]=Array("arcurl","",246,261);
$z[6]=Array("title","",270,284);
$z[7]=Array("title","",326,340);
$z[8]=Array("title","",347,361);
$z[9]=Array("arcurl","",431,446);
$z[10]=Array("title","",455,469);
$z[11]=Array("title","",471,485);

?>