<li>
                  <a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]" title="[field:title/]" alt="[field:title/]" width="278" height="375" /></a>
                  <div class="text">
                      <a href="[field:arcurl/]" title="[field:title/]"><img src="/images/case-list.png" title="[field:title/]" alt="[field:title/]" width="278" height="375" /></a>
                      <h2><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></h2>  
                  </div>                                  
              </li>