<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",165,216);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("channelartlist","\r\n                 <li><a href=\"javascript:void(0);\">{gemel:field name='typename'/}</a></li><!--{gemel:field name='typeurl'/}-->\r\n                ",367,588);
$z[3][4]['typeid']="2";
$z[3][4]['row']="9";
$z[3][4]['type']="top";
$z[4]=Array("arclist","\r\n                    <li>\r\n                         <div class=\"product_img\">\r\n                              <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"210\" height=\"210\"/></a>\r\n                         </div>\r\n                         <p><a href=\"[field:arcurl/]\">[field:title/]</a></p>\r\n                    </li>\r\n                    ",770,1249);
$z[4][4]['row']="8";
$z[4][4]['titlelen']="24";
$z[4][4]['orderby']="pubdate";
$z[4][4]['typeid']="5";
$z[5]=Array("arclist","\r\n                    <li>\r\n                         <div class=\"product_img\">\r\n                              <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"210\" height=\"210\"/></a>\r\n                         </div>\r\n                         <p><a href=\"[field:arcurl/]\">[field:title/]</a></p>\r\n                    </li>\r\n                    ",1382,1862);
$z[5][4]['row']="10";
$z[5][4]['titlelen']="24";
$z[5][4]['orderby']="pubdate";
$z[5][4]['typeid']="6";
$z[6]=Array("pagelist","",1995,2067);
$z[6][4]['listitem']="index,end,pageno";
$z[6][4]['listsize']="4";
$z[6][4]['sitelang']="en";
$z[7]=Array("include","",2164,2202);
$z[7][4]['filename']="footer.htm";

?>