{gemel:pagestyle maxwidth='800' pagepicnum='' ddmaxwidth='200' row='100' col='100' value='3'/}
{gemel:img ddimg='/upload/allimg/151030/b2192-01-lp.png' text='' width='870' height='555'} /upload/allimg/151030/b2192-01.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151030/b2192-02-lp.png' text='' width='870' height='555'} /upload/allimg/151030/b2192-02.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151030/b2192-03-lp.png' text='' width='870' height='555'} /upload/allimg/151030/b2192-03.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151030/b2192-05-lp.png' text='' width='870' height='555'} /upload/allimg/151030/b2192-05.png {/gemel:img}
{gemel:img ddimg='/upload/allimg/151030/b2192-06-lp.png' text='' width='870' height='555'} /upload/allimg/151030/b2192-06.png {/gemel:img}
