<a href="{gemel:field name='typeurl'/}" class="{gemel:field.currentstyle/}">1</a>
       <a href="{gemel:field name='typeurl'/}" class="{gemel:field.currentstyle/}">2</a>
       <a href="{gemel:field name='typeurl'/}" class="{gemel:field.currentstyle/}">3</a>
       <a href="{gemel:field name='typeurl'/}" class="{gemel:field.currentstyle/}">4</a>
       <a href="{gemel:field name='typeurl'/}" class="{gemel:field.currentstyle/}">5</a>
       <a href="{gemel:field name='typeurl'/}" class="{gemel:field.currentstyle/}">6</a>
       <a href="{gemel:field name='typeurl'/}" class="{gemel:field.currentstyle/}">7</a>