
                                <li style="background:none!important; padding-left:0!important;">
                                    <div class="menulist_img"><a href="[field:typeurl/]"><img src="[field:typepic/]" title="[field:typename/]" alt="[field:typename/]"/></a></div>
                                    <div class="menulist_right">
                                        <a href="[field:typeurl/]" class="menulist_text text_overflow">[field:typename/]</a>
                                        <p class="menulist_des">[field:description function='cn_substrR(html2text(@me),60)' /]</p>
                                    </div>
                                </li>
                                