<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1357,1391);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n<div class=\"about_banner\" style=\"background:url([field:pic/]) center top no-repeat;\"></div>\r\n",1395,1543);
$z[4][4]['name']="about_banner";
$z[4][4]['row']="1";
$z[5]=Array("field","",1601,1629);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",1836,1955);
$z[6][4]['type']="son";
$z[7]=Array("type","[field:typename/]",2056,2104);
$z[7][4]['typeid']="";
$z[8]=Array("include","",6144,6180);
$z[8][4]['filename']="footer.htm";

?>