<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1359,1393);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n        <li id=\"[field:id/]\" style=\"background:url([field:pic/]) center top no-repeat;\" class=\"now\"></li>\r\n        ",1435,1605);
$z[4][4]['name']="about_banner";
$z[4][4]['row']="1";
$z[5]=Array("field","",1671,1699);
$z[5][4]['name']="position";
$z[6]=Array("type","[field:typename/]",1789,1837);
$z[6][4]['typeid']="";
$z[7]=Array("type","[field:typename/]",5884,5933);
$z[7][4]['typeid']="1";
$z[8]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",6000,6130);
$z[8][4]['type']="son";
$z[8][4]['typeid']="1";
$z[9]=Array("include","",6199,6235);
$z[9][4]['filename']="footer.htm";

?>