<li>
                        <a href="[field:arcurl/]" class="news_list_img"><img src="[field:litpic/]" /></a>
                        <div class="news_list_right">
                            <p class="news_list_tit"><a href="[field:arcurl/]">[field:title/]([field:pubdate function="MyDate('Y-m-d',@me)"/])</a></p>
                            <p class="news_list_profile">[field:description function='cn_substrR(html2text(@me),320)'/]</p>
                            <a class="news_more" href="[field:arcurl/]"></a>
                        </div>
                        <div class="clear"></div>
                    </li>