<?php
$z[0]=Array("rpad","",90,125);
$z[0][4]['name']="dimensional_code";
$z[1]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",200,283);
$z[1][4]['typeid']="9";
$z[2]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",297,381);
$z[2][4]['typeid']="10";
$z[3]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",395,478);
$z[3][4]['typeid']="1";
$z[4]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",492,575);
$z[4][4]['typeid']="3";
$z[5]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",589,672);
$z[5][4]['typeid']="5";
$z[6]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",686,769);
$z[6][4]['typeid']="4";
$z[7]=Array("global","",829,854);
$z[7][4]['name']="cfg_powerby";
$z[8]=Array("global","",866,889);
$z[8][4]['name']="cfg_beian";

?>