<?php
$z[0]=Array("type","\r\n               <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n               ",147,266);
$z[0][4]['typeid']="1";
$z[1]=Array("channelartlist"," \r\n               <h2><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h2>\r\n               ",361,521);
$z[1][4]['typeid']="1";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",646,731);
$z[2][4]['typeid']="5";
$z[3]=Array("type","<h2><a href=\"[field:typelink/]?id=0\">Products &amp; Service</a></h2>",826,930);
$z[3][4]['typeid']="5";
$z[4]=Array("type","<h2><a href=\"[field:typelink/]?id=1\">Quality &amp; Certification</a></h2>",947,1056);
$z[4][4]['typeid']="5";
$z[5]=Array("type","<h2><a href=\"[field:typelink/]?id=2\">Main Customer</a></h2>",1073,1168);
$z[5][4]['typeid']="5";
$z[6]=Array("type","<h2><a href=\"[field:typelink/]?id=3\">Development</a></h2>",1185,1278);
$z[6][4]['typeid']="5";
$z[7]=Array("rpad","",1536,1571);
$z[7][4]['name']="footer_contact";

?>