<?php
$z[0]=Array("arclist","\r\n                          <li class=\"clear\">\r\n                              <div class=\"img\">\r\n                                   <a href=\"[field:arcurl/]\"><img src=\"[field:footer_img/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"160\" height=\"95\" /></a>\r\n                              </div>\r\n                              <div class=\"text\">\r\n                                    <h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n                                    <p>SHOW: [field:add_time/]</p>\r\n                                    <a href=\"[field:arcurl/]\">READ MORE</a>    \r\n                              </div>   \r\n                           </li>     \r\n                           ",207,1058);
$z[0][4]['orderby']="weight";
$z[0][4]['typeid']="7";
$z[0][4]['titlelen']="180";
$z[0][4]['row']="3";
$z[0][4]['addfields']="add_time,footer_img";
$z[0][4]['channelid']="1";

?>