<?php
$z[0]=Array("rpad","",370,402);
$z[0][4]['name']="footer_info";
$z[1]=Array("rpad","",408,440);
$z[1][4]['name']="google_link";
$z[2]=Array("rpad","",927,959);
$z[2][4]['name']="contact_way";
$z[3]=Array("global","",1133,1160);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("type","\r\n            <p>[field:typename/]: ",1235,1307);
$z[4][4]['typeid']="1";
$z[5]=Array("channelartlist","\r\n                <a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a> ",1308,1449);
$z[5][4]['typeid']="6,7,8,9";

?>