<?php
$z[0]=Array("global","",106,133);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",140,167);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("banner","\r\n       <li>\r\n          <a href=\"skype:[field:link/]?add\" title=\"[field:text/]\">&nbsp;</a>\r\n          <h3><a href=\"skype:[field:link/]?add\" title=\"[field:text/]\">[field:text/]</a></h3>\r\n       </li>\r\n       ",723,978);
$z[2][4]['name']="skype_list";
$z[3]=Array("channelartlist","\r\n                        <p><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></p>\r\n                        ",1757,1932);
$z[3][4]['typeid']="1";
$z[4]=Array("channelartlist","\r\n                        <p><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></p>\r\n                        ",2160,2335);
$z[4][4]['typeid']="9";

?>