<?php
$z[0]=Array("channelartlist","\r\n                 <p><a href=\"{gemel:field name='typeurl'/}\">&gt; {gemel:field name='typename'/}</a></p>\r\n                 ",198,397);
$z[0][4]['typeid']="2";
$z[0][4]['row']="4";
$z[0][4]['type']="son";
$z[1]=Array("arclist","\r\n                 <p><a href=\"[field:arcurl/]\">[field:title/]</a><br/><span>[field:pubdate function='strftime(\"%b %d, %Y\",@me)'/]</span></p>\r\n                 ",535,778);
$z[1][4]['orderby']="weight";
$z[1][4]['row']="2";
$z[1][4]['typeid']="10";
$z[1][4]['titlelen']="90";

?>