<?php
$z[0]=Array("channelartlist","\r\n                <li><i>&nbsp;</i><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                <!-- <li><i>&nbsp;</i><a href=\"\">Straight(Dry) Drawing Machine</a></li>\r\n                <li><i>&nbsp;</i><a href=\"\">Straight(Dry) Drawing Machine</a></li>\r\n                <li><i>&nbsp;</i><a href=\"\">Straight(Dry) Drawing Machine</a></li>\r\n                <li><i>&nbsp;</i><a href=\"\">Straight(Dry) Drawing Machine</a></li>\r\n                <li><i>&nbsp;</i><a href=\"\">Straight(Dry) Drawing Machine</a></li>\r\n                <li><i>&nbsp;</i><a href=\"\">Straight(Dry) Drawing Machine</a></li> -->\r\n            ",160,843);
$z[0][4]['typeid']="2";
$z[1]=Array("rpad","",996,1027);
$z[1][4]['name']="index_link";
$z[2]=Array("rpad","",1143,1177);
$z[2][4]['name']="index_contact";
$z[3]=Array("global","",2568,2595);
$z[3][4]['name']="cfg_powerby";

?>