<?php
$z[0]=Array("channelartlist","\r\n                <li><i>&nbsp;</i><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                    ",158,336);
$z[0][4]['typeid']="2";
$z[1]=Array("rpad","",512,546);
$z[1][4]['name']="index_contact";
$z[2]=Array("rpad","",676,707);
$z[2][4]['name']="index_link";
$z[3]=Array("global","",1803,1830);
$z[3][4]['name']="cfg_powerby";

?>