<?php
$z[0]=Array("type","<a href=\"[field:typeurl/]\"[field:open_new/]>[field:typename/]</a>",180,281);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<a href=\"[field:typeurl/]\"[field:open_new/]>[field:typename/]</a>",296,397);
$z[1][4]['typeid']="7";
$z[2]=Array("type","<a href=\"[field:typeurl/]\"[field:open_new/]>[field:typename/]</a>",412,514);
$z[2][4]['typeid']="10";
$z[3]=Array("type","<a href=\"[field:typeurl/]\"[field:open_new/]>[field:typename/]</a>",529,631);
$z[3][4]['typeid']="12";
$z[4]=Array("type","<a href=\"[field:typeurl/]\"[field:open_new/]>[field:typename/]</a>",646,748);
$z[4][4]['typeid']="14";
$z[5]=Array("global","",807,834);
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",834,858);
$z[6][4]['name']="cfg_cnzz";
$z[7]=Array("global","",937,959);
$z[7][4]['name']="cfg_kf";

?>