<?php
$z[0]=Array("global","",60,85);
$z[0][4]['name']="cfg_powerby";
$z[1]=Array("type","<li><a href=\"[field:typeurl/]\" class=\"first\">[field:typename/]</a></li>",189,292);
$z[1][4]['typeid']="1";
$z[2]=Array("channel","<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",306,412);
$z[2][4]['type']="son";
$z[2][4]['typeid']="1";
$z[3]=Array("type","<li><a href=\"[field:typeurl/]\" class=\"first\">[field:typename/]</a></li>",455,558);
$z[3][4]['typeid']="2";
$z[4]=Array("channel","<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",572,678);
$z[4][4]['type']="son";
$z[4][4]['typeid']="2";
$z[5]=Array("type","<li><a href=\"[field:typeurl/]\" class=\"first\">[field:typename/]</a></li>",721,824);
$z[5][4]['typeid']="3";
$z[6]=Array("channel","<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",838,944);
$z[6][4]['type']="son";
$z[6][4]['typeid']="3";
$z[7]=Array("type","<li><a href=\"[field:typeurl/]\" class=\"first\">[field:typename/]</a></li>",987,1090);
$z[7][4]['typeid']="4";
$z[8]=Array("channel","<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",1104,1210);
$z[8][4]['type']="son";
$z[8][4]['typeid']="4";
$z[9]=Array("type","<li><a href=\"[field:typeurl/]\" class=\"first\">[field:typename/]</a></li>",1253,1356);
$z[9][4]['typeid']="5";
$z[10]=Array("channel","<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",1370,1476);
$z[10][4]['type']="son";
$z[10][4]['typeid']="5";
$z[11]=Array("type","<li><a href=\"[field:typeurl/]\" class=\"first\">[field:typename/]</a></li>",1519,1622);
$z[11][4]['typeid']="6";
$z[12]=Array("channel","<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>",1636,1742);
$z[12][4]['type']="son";
$z[12][4]['typeid']="6";

?>