<?php
$z[0]=Array("channelartlist","\r\n                <li><a href=\"{gemel:field.typeurl/}\"><i>&nbsp;</i>{gemel:field.typename/}</a></li>\r\n                ",167,349);
$z[0][4]['typeid']="2";
$z[0][4]['row']="5";
$z[1]=Array("rpad","",436,471);
$z[1][4]['name']="footer_contact";
$z[2]=Array("rpad","",548,581);
$z[2][4]['name']="footer_about";
$z[3]=Array("rpad","",654,685);
$z[3][4]['name']="index_flow";
$z[4]=Array("global","",1810,1837);
$z[4][4]['name']="cfg_powerby";

?>