<?php
$z[0]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",31,112);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",119,201);
$z[1][4]['typeid']="34";
$z[2]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",208,290);
$z[2][4]['typeid']="29";
$z[3]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",297,379);
$z[3][4]['typeid']="27";
$z[4]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",386,468);
$z[4][4]['typeid']="26";
$z[5]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",475,556);
$z[5][4]['typeid']="7";
$z[6]=Array("global","",595,620);
$z[6][4]['name']="cfg_powerby";

?>