<?php
$z[0]=Array("type","<a href=\"[field:typeurl/]\"[field:open_new/]>[field:typename/]</a>",180,277);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<a href=\"[field:typeurl/]\"[field:open_new/]>[field:typename/]</a>",292,389);
$z[1][4]['typeid']="7";
$z[2]=Array("type","<a href=\"[field:typeurl/]\"[field:open_new/]>[field:typename/]</a>",404,502);
$z[2][4]['typeid']="10";
$z[3]=Array("type","<a href=\"[field:typeurl/]\"[field:open_new/]>[field:typename/]</a>",517,615);
$z[3][4]['typeid']="12";
$z[4]=Array("type","<a href=\"[field:typeurl/]\"[field:open_new/]>[field:typename/]</a>",630,728);
$z[4][4]['typeid']="14";
$z[5]=Array("global","",787,812);
$z[5][4]['name']="cfg_powerby";
$z[6]=Array("global","",812,834);
$z[6][4]['name']="cfg_cnzz";
$z[7]=Array("global","",913,933);
$z[7][4]['name']="cfg_kf";

?>