<?php
$z[0]=Array("arclist","\r\n                        <div class=\"list clear\">\r\n                            <div class=\"img\">\r\n                                <a href=\"[field:arcurl/]\"><img src=\"[field:footer_news/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"83\" height=\"76\"/></a>\r\n                            </div>\r\n                            <div class=\"text\">\r\n                                <h4><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h4>\r\n                                <p>[field:description function='cn_substrR(html2text(@me),68)'/]...</p>\r\n                            </div>\r\n                        </div>\r\n                        ",1556,2330);
$z[0][4]['orderby']="weight";
$z[0][4]['typeid']="5";
$z[0][4]['titlelen']="180";
$z[0][4]['row']="1";
$z[0][4]['addfields']="footer_news";
$z[0][4]['channelid']="1";
$z[1]=Array("channelartlist","\r\n                        <h4><i></i><a href=\"{gemel:field.typeurl/}\" title=\"{gemel:field.typename/}\">{gemel:field.typename/}</a></h4>\r\n                        ",3242,3458);
$z[1][4]['typeid']="1";

?>