<?php
$z[0]=Array("type","<a href=\"[field:typeurl/]\">Latest News</a>",101,180);
$z[0][4]['typeid']="17";
$z[1]=Array("arclist","\r\n					<li>\r\n						<a href=\"[field:arcurl/]\" class=\"indexnews_text text_overflow\">[field:title/]</a>\r\n						<p class=\"indexnews_des text_overflow\">[field:description/]</p>\r\n						<p class=\"indexnews_date\">[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</p>\r\n					</li>\r\n                    ",228,593);
$z[1][4]['titlelen']="38";
$z[1][4]['row']="3";
$z[1][4]['flag']="c";
$z[1][4]['typeid']="17";
$z[2]=Array("type","<a href=\"[field:typeurl/]\">Products Categories</a>",689,775);
$z[2][4]['typeid']="2";
$z[3]=Array("channel","\r\n                    <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                    ",867,1029);
$z[3][4]['typeid']="2";
$z[3][4]['row']="5";
$z[3][4]['type']="son";
$z[4]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",1154,1238);
$z[4][4]['typeid']="9";
$z[5]=Array("arclist","\r\n                    <li><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"79\" height=\"63\"  title=\"[field:title/]\" /></a></li>\r\n                    ",1326,1558);
$z[5][4]['titlelen']="38";
$z[5][4]['row']="2";
$z[5][4]['flag']="c";
$z[5][4]['typeid']="9";
$z[6]=Array("type","<div class=\"social_des\">[field:description/]<br /><br /><a href=\"[field:typeurl/]\">YunNan Di-xi Charity School</a></div>",1642,1798);
$z[6][4]['typeid']="9";
$z[7]=Array("rpad","",1980,2015);
$z[7][4]['name']="footer_contact";
$z[8]=Array("global","",2119,2146);
$z[8][4]['name']="cfg_powerby";
$z[9]=Array("rpad","",2185,2218);
$z[9][4]['name']="footer_share";
$z[10]=Array("global","",2278,2300);
$z[10][4]['name']="cfg_kf";
$z[11]=Array("global","",2302,2324);
$z[11][4]['name']="cfg_ga";

?>