<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",78,113);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",359,410);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("list","\r\n              <li>\r\n                   <img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"269\" height=\"179\" />\r\n                   <div class=\"enlarge\">\r\n                      <a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"/images/enlarge.png\" width=\"34\" height=\"34\" title=\"[field:title/]\" alt=\"[field:title/]\"/></a>\r\n                      <p>[field:title/]</p>\r\n                   </div>\r\n              </li>\r\n              ",505,1042);
$z[3][4]['orderby']="weight";
$z[3][4]['pagesize']="12";
$z[3][4]['titlelen']="100";
$z[4]=Array("pagelist","",1103,1175);
$z[4][4]['listitem']="index,end,pageno";
$z[4][4]['listsize']="4";
$z[4][4]['sitelang']="en";
$z[5]=Array("include","",1278,1314);
$z[5][4]['filename']="foot.htm";

?>