<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",78,113);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",310,361);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",394,414);
$z[3][4]['name']="title";
$z[4]=Array("pagelist","",865,937);
$z[4][4]['listitem']="index,end,pageno";
$z[4][4]['listsize']="4";
$z[4][4]['sitelang']="en";
$z[5]=Array("include","",1040,1076);
$z[5][4]['filename']="foot.htm";

?>