<?php
$z[0]=Array("channel2"," \r\n             <li>\r\n                <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                   <ul class=\"sub_menu\">\r\n                       [field:sonchannel0]\r\n                       <li><a href='[field:typeurl/]'><img src=\"[field:typepic/]\" alt=\"[field:typename/]\" title=\"[field:typename/]\" width=\"53\" height=\"53\" /><span>[field:typename/]</span></a></li>\r\n                       [/field:sonchannel0]\r\n                   </ul>\r\n             </li>\r\n            ",327,855);
$z[0][4]['type']="top";
$z[0][4]['row']="4";

?>