<?php
$z[0]=Array("rpad","",116,144);
$z[0][4]['name']="top_tel";
$z[1]=Array("channel2"," \r\n            <li>\r\n                <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                <ul>\r\n                     [field:sonchannel0]\r\n                     <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n                     [/field:sonchannel0]\r\n                </ul>\r\n            </li>\r\n            ",308,689);
$z[1][4]['type']="top";
$z[1][4]['row']="7";

?>