<?php
$z[0]=Array("channel2","\r\n        <li><a class=\"biaoshi\" href=\"[field:typeurl/]\" [field:rel/]>[field:typename/]</a>\r\n			<ul class=\"menu_list\">\r\n                [field:sonchannel0]\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                [/field:sonchannel0] \r\n			</ul>\r\n		</li>\r\n        ",985,1320);
$z[0][4]['type']="top";
$z[0][4]['rows']="8";

?>