<?php
$z[0]=Array("global","",225,251);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",254,279);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",312,393);
$z[2][4]['typeid']="12";
$z[3]=Array("rpad","",434,461);
$z[3][4]['name']="top_blog";
$z[4]=Array("channel"," \r\n            <li><a href=\"[field:typeurl/]\"[field:open_new/]>[field:typename/]</a></li>\r\n            ",1088,1237);
$z[4][4]['type']="top";
$z[4][4]['row']="6";

?>