<?php
$z[0]=Array("global","",183,209);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",212,237);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("type","<a href=\"[field:typelink /]\">[field:typename /]</a>",267,350);
$z[2][4]['typeid']="9";
$z[3]=Array("rpad","",366,393);
$z[3][4]['name']="top_tell";
$z[4]=Array("channel2","\r\n            <li class=\"menulist\">\r\n                <a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a><div class=\"menu_line\"></div>\r\n                <ul>\r\n                     [field:sonchannel0]\r\n                     <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n                     [/field:sonchannel0] \r\n                </ul>\r\n            </li>\r\n            ",738,1175);
$z[4][4]['type']="top";
$z[4][4]['rows']="10";

?>