<?php
$z[0]=Array("type","<a href=\"[field:typeurl/]\">SITEMAP</a>",426,497);
$z[0][4]['typeid']="28";
$z[1]=Array("channel"," \r\n            <a class=\"menuhover\" href=\"[field:typeurl/]\">[field:typename/]</a>\r\n            ",591,733);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[2]=Array("channel","\r\n            <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n            ",936,1070);
$z[2][4]['type']="son";
$z[2][4]['row']="10";
$z[2][4]['typeid']="1";
$z[3]=Array("channel","\r\n            <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n            ",1142,1276);
$z[3][4]['type']="son";
$z[3][4]['row']="10";
$z[3][4]['typeid']="2";
$z[4]=Array("channel","\r\n            <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n            ",1348,1482);
$z[4][4]['type']="son";
$z[4][4]['row']="10";
$z[4][4]['typeid']="3";
$z[5]=Array("channel","\r\n            <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n            ",1555,1689);
$z[5][4]['type']="son";
$z[5][4]['row']="10";
$z[5][4]['typeid']="4";
$z[6]=Array("channel","\r\n            <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n            ",1759,1893);
$z[6][4]['type']="son";
$z[6][4]['row']="10";
$z[6][4]['typeid']="5";
$z[7]=Array("channel","\r\n            <a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n            ",1964,2098);
$z[7][4]['type']="son";
$z[7][4]['row']="10";
$z[7][4]['typeid']="6";
$z[8]=Array("rpad","",2142,2203);
$z[8][4]['name']="about_banner";
$z[8][4]['function']="RepListBanner(@me)";

?>