<?php
$z[0]=Array("rpad","",79,109);
$z[0][4]['name']="top_welcome";
$z[1]=Array("rpad","",171,201);
$z[1][4]['name']="top_message";
$z[2]=Array("rpad","",252,277);
$z[2][4]['name']="top_qq";
$z[3]=Array("rpad","",327,354);
$z[3][4]['name']="top_sina";
$z[4]=Array("global","",445,471);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",474,499);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("rpad","",909,935);
$z[6][4]['name']="top_tel";
$z[7]=Array("rpad","",960,985);
$z[7][4]['name']="top_qq";
$z[8]=Array("rpad","",1031,1058);
$z[8][4]['name']="top_sina";
$z[9]=Array("channel"," \r\n            <li><a href=\"[field:typeurl/]\" [field:id runphp='yes'] if(@me=='28'){ @me=\"target='_blank'\";} else {@me=\"\";}[/field:id]>[field:typename/]</a><br /><span>[field:seotitle/]</span></li>\r\n            ",1334,1592);
$z[9][4]['type']="top";
$z[9][4]['rows']="6";
$z[10]=Array("rpad","",1655,1686);
$z[10][4]['name']="about_banner";

?>