<?php
$z[0]=Array("global","",225,253);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",256,283);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",316,401);
$z[2][4]['typeid']="12";
$z[3]=Array("rpad","",442,471);
$z[3][4]['name']="top_blog";
$z[4]=Array("channel"," \r\n            <li><a href=\"[field:typeurl/]\"[field:open_new/]>[field:typename/]</a></li>\r\n            ",1098,1251);
$z[4][4]['type']="top";
$z[4][4]['row']="6";

?>