<?php
$z[0]=Array("global","",278,306);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",345,376);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",602,629);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",891,926);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n            <li>\r\n                 <a href=\"[field:link/]\"><img src=\"[field:pic/]\" title=\"[field:text/]\" alt=\"[field:text/]\" width=\"1600\" height=\"640\" /></a>\r\n            </li>\r\n            ",1055,1296);
$z[4][4]['name']="index_banner";
$z[5]=Array("banner","\r\n            <li>&nbsp;</li>\r\n            ",2030,2122);
$z[5][4]['name']="index_banner";
$z[6]=Array("include","",8014,8052);
$z[6][4]['filename']="footer.htm";

?>