<?php
$z[0]=Array("global","",277,305);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",344,375);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",533,560);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",822,857);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("arclist"," \r\n                            <li>\r\n                                 <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"238\" height=\"216\" /></a>\r\n                                 <p><a href=\"[field:arcurl/]\">[field:shorttitle/]</a></p>\r\n                            </li>\r\n                            ",5619,6055);
$z[4][4]['orderby']="weight";
$z[4][4]['row']="8";
$z[4][4]['typeid']="2";
$z[4][4]['titlelen']="40";
$z[5]=Array("arclist"," \r\n                            <li>\r\n                                 <a href=\"[field:video/]&;lightbox[width]=900&amo;lightbox[height]=500&lightbox[modal]=true\" rel=\"group1\" class=\"lightbox\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"238\" height=\"216\" /></a>\r\n                                 <p><a href=\"[field:video/]&;lightbox[width]=900&amo;lightbox[height]=500&lightbox[modal]=true\" rel=\"group1\" class=\"lightbox\">[field:shorttitle/]</a></p>\r\n                            </li>\r\n                            ",7646,8306);
$z[5][4]['orderby']="weight";
$z[5][4]['typeid']="8";
$z[5][4]['row']="8";
$z[5][4]['titlelen']="40";
$z[5][4]['addfields']="video";
$z[5][4]['channelid']="1";
$z[6]=Array("include","",8501,8539);
$z[6][4]['filename']="footer.htm";

?>