<?php
$z[0]=Array("global","",278,306);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",345,376);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",699,726);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",999,1034);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n            <li>\r\n                 <a href=\"[field:link/]\"><img src=\"[field:pic/]\" title=\"[field:text/]\" alt=\"[field:text/]\" width=\"1600\" height=\"762\" /></a>\r\n            </li>\r\n            ",1161,1402);
$z[4][4]['name']="index_banner";
$z[5]=Array("banner","\r\n            <li></li>\r\n            ",1587,1673);
$z[5][4]['name']="index_banner";
$z[6]=Array("global","",1815,1842);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("arclist","\r\n            <li>\r\n            	<div class=\"img\">\r\n            		<a href=\"[field:arcurl/]\"><img src=\"[field:home_img/]\" title=\"[field:title/] - [field:typename/]\" alt=\"[field:title/] - [field:typename/]\" width=\"202\" height=\"176\"/></a>\r\n            	</div>\r\n            	<h3><a href=\"[field:arcurl/]\" title=\"[field:title/] - [field:typename/]\">[field:title/]</a></h3>\r\n            	<a href=\"[field:arcurl/]\">view more</a>\r\n            </li>\r\n            ",2176,2756);
$z[7][4]['row']="5";
$z[7][4]['typeid']="2";
$z[7][4]['titlelen']="100";
$z[7][4]['flag']="c";
$z[7][4]['orderby']="weight";
$z[7][4]['addfields']="home_img";
$z[7][4]['channelid']="2";
$z[8]=Array("arclist","\r\n				<li class=\"clear\">\r\n					<div class=\"img\">\r\n						<a href=\"[field:arcurl/]\"><img src=\"[field:news_index/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"84\" height=\"84\"/></a>\r\n					</div>\r\n					<div class=\"text\">\r\n						<h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n						<p>[field:description function='cn_substrR(html2text(@me),68)'/]...</p>\r\n					</div>\r\n				</li>\r\n                ",9918,10465);
$z[8][4]['orderby']="update";
$z[8][4]['typeid']="4";
$z[8][4]['titlelen']="180";
$z[8][4]['row']="3";
$z[8][4]['addfields']="news_index";
$z[8][4]['channelid']="1";
$z[9]=Array("include","",10723,10761);
$z[9][4]['filename']="footer.htm";

?>