<?php
$z[0]=Array("global","",278,306);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",345,376);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",708,735);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",1008,1043);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n            <li>\r\n                 <a href=\"[field:link/]\"><img src=\"[field:pic/]\" title=\"[field:text/]\" alt=\"[field:text/]\" width=\"1600\" height=\"762\" /></a>\r\n            </li>\r\n            ",1170,1411);
$z[4][4]['name']="index_banner";
$z[5]=Array("banner","\r\n            <li></li>\r\n            ",1970,2056);
$z[5][4]['name']="index_banner";
$z[6]=Array("global","",2178,2205);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("include","",11794,11832);
$z[7][4]['filename']="footer.htm";

?>