<?php
$z[0]=Array("field","",254,279);
$z[0][4]['name']="title";
$z[1]=Array("global","",280,305);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",349,380);
$z[2][4]['name']="description";
$z[3]=Array("field","",417,445);
$z[3][4]['name']="keywords";
$z[4]=Array("type","<a href=\"[field:typeurl/]\">加盟首页</a>",961,1037);
$z[4][4]['typeid']="26";
$z[5]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1121,1199);
$z[5][4]['typeid']="36";
$z[6]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1213,1291);
$z[6][4]['typeid']="37";
$z[7]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1305,1383);
$z[7][4]['typeid']="35";
$z[8]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1397,1475);
$z[8][4]['typeid']="26";
$z[9]=Array("field","",1530,1550);
$z[9][4]['name']="content";
$z[10]=Array("include","",1578,1618);
$z[10][4]['filename']="sub_footer.htm";

?>