<?php
$z[0]=Array("global","",278,306);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",345,376);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",643,670);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",932,967);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n            <li>\r\n                 <a href=\"[field:link/]\"><img src=\"[field:pic/]\" title=\"[field:text/]\" alt=\"[field:text/]\" width=\"1600\" height=\"456\" /></a>\r\n            </li>\r\n            ",1096,1337);
$z[4][4]['name']="index_banner";
$z[5]=Array("banner","\r\n            <li></li>\r\n            ",1522,1608);
$z[5][4]['name']="index_banner";
$z[6]=Array("global","",1720,1747);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"/images/home-pro-01.jpg\" title=\"PCM Protection Board\" alt=\"PCM Protection Board\" width=\"278\" height=\"270\" /></a>\r\n                    <div class=\"title\">\r\n                          <div class=\"left\">\r\n                                <h2><a href=\"[field:typelink/]\">PCM <br/>Protection Board</a></h2>\r\n                          </div>\r\n                          <a href=\"[field:typelink/]\"><em></em></a>\r\n                    </div>\r\n               </li>\r\n               ",1882,2468);
$z[7][4]['typeid']="7";
$z[8]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"/images/home-pro-02.jpg\" title=\"Portable UPS power supply\" alt=\"Portable UPS power supply\" width=\"278\" height=\"270\" /></a>\r\n                    <div class=\"title\">\r\n                          <div class=\"left\">\r\n                                <h2><a href=\"[field:typelink/]\">Portable <br/>UPS power supply</a></h2>\r\n                          </div>\r\n                          <a href=\"[field:typelink/]\"><em></em></a>\r\n                    </div>\r\n               </li>\r\n               ",2485,3087);
$z[8][4]['typeid']="46";
$z[9]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"/images/home-pro-03.jpg\" title=\"Battery pack\" alt=\"Battery pack\" width=\"278\" height=\"270\" /></a>\r\n                    <div class=\"title\">\r\n                          <div class=\"left\">\r\n                                <h2><a href=\"[field:typelink/]\">Battery pack</a></h2>\r\n                          </div>\r\n                          <a href=\"[field:typelink/]\"><em></em></a>\r\n                    </div>\r\n               </li>\r\n               ",3104,3661);
$z[9][4]['typeid']="5";
$z[10]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"/images/home-pro-04.jpg\" title=\"Battery charger\" alt=\"Battery charger\" width=\"278\" height=\"270\" /></a>\r\n                    <div class=\"title\">\r\n                          <div class=\"left\">\r\n                                <h2><a href=\"[field:typelink/]\">Battery charger</a></h2>\r\n                          </div>\r\n                          <a href=\"[field:typelink/]\"><em></em></a>\r\n                    </div>\r\n               </li>\r\n               ",3678,4244);
$z[10][4]['typeid']="6";
$z[11]=Array("include","",7074,7112);
$z[11][4]['filename']="footer.htm";

?>