<?php
$z[0]=Array("channeltitle","",254,306);
$z[0][4]['order']="backward";
$z[0][4]['character']="_";
$z[1]=Array("global","",307,334);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",378,409);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",446,474);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("global","",602,638);
$z[4][4]['name']="realname_authenticat";
$z[5]=Array("include","",1438,1474);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",1517,1568);
$z[6][4]['name']="position";
$z[6][4]['function']="position_preg(@me)";
$z[7]=Array("channelartlist","\r\n        <div class=\"applicationdiv\">\r\n            <h1 class=\"title\"><a target=\"_blank\" href=\"{gemel:field name='typeurl'/}\">{gemel:field name='typename'/}</a></h1>\r\n            <ul class=\"applicationul\">\r\n                {gemel:arclist titlelen='38' row='4' flag='c' addfields='app_img' channelid='16'}\r\n                <li>\r\n                <a href=\"[field:app_img/]\" rel=\"prettyPhoto[]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" title=\"[field:title/]\"/></a>\r\n                <span>[field:title/]</span>\r\n                </li>\r\n                {/gemel:arclist}\r\n            </ul>\r\n        </div>\r\n        ",1612,2314);
$z[7][4]['row']="99";
$z[7][4]['typeid']="4";
$z[8]=Array("include","",2336,2374);
$z[8][4]['filename']="footer.htm";

?>