<?php
$z[0]=Array("global","",288,316);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",360,391);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",713,740);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",1004,1039);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n                        <li>\r\n                            <a href=\"[field:link/]\">\r\n                                <img src=\"[field:pic/]\" width=\"1600\" height=\"670\" alt=\"[field:text/]\" title=\"[field:text/]\">\r\n                                <!--  <div class=\"banner-text\">\r\n                                    <h2>10 YEARS<br> \r\nCLEAR AS NEW</h2>\r\n                                    <p>The color will not change in at least 5 years.\r\n                                    </p>\r\n                                    <p>100% acrylic.</p>\r\n                                </div> -->\r\n                            </a>\r\n                        </li>\r\n                        ",1224,1952);
$z[4][4]['name']="index_banner";
$z[4][4]['row']="7";
$z[5]=Array("banner","\r\n                        <li></li>\r\n                        ",2121,2239);
$z[5][4]['name']="index_banner";
$z[5][4]['row']="7";
$z[6]=Array("channelartlist","\r\n                            <li>\r\n                                <a href=\"{gemel:field.typeurl/}\"><img src=\"{gemel:field.content/}\" alt=\"{gemel:field.typename/}\" / width=\"60\" height=\"60\" title=\"{gemel:field.typename/}\"></a>\r\n                            </li>\r\n                            ",2966,3313);
$z[6][4]['typeid']="1";
$z[7]=Array("channelartlist","\r\n                        <li>\r\n                       \r\n                            <a href=\"{gemel:field.typeurl/}\"><img src=\"{gemel:field.typepic/}\" alt=\"{gemel:field.typename/}\" width=\"380\" height=\"380\" title=\"{gemel:field.typename/}\" />\r\n                                <p>{gemel:field.typename/}</p>\r\n                            </a>\r\n                            \r\n                        </li>\r\n                        ",4442,4924);
$z[7][4]['typeid']="1";
$z[8]=Array("type","\r\n                <p>\r\n                [field:content/]\r\n                </p>\r\n",10578,10693);
$z[8][4]['typeid']="2";
$z[9]=Array("include","",12634,12672);
$z[9][4]['filename']="footer.htm";

?>