<?php
$z[0]=Array("global","",278,306);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",345,376);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",548,575);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",837,872);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n            <li>\r\n                 <a href=\"[field:link/]\"><img src=\"[field:pic/]\" title=\"[field:text/]\" alt=\"[field:text/]\" width=\"1040\" height=\"466\" /></a>\r\n                 <span><a href=\"[field:link/]\">READMORE+</a></span>\r\n            </li>\r\n            ",1005,1323);
$z[4][4]['name']="index_banner";
$z[4][4]['row']="7";
$z[5]=Array("banner","\r\n            <li>&nbsp;</li>\r\n            ",1496,1596);
$z[5][4]['name']="index_banner";
$z[5][4]['row']="7";
$z[6]=Array("include","",9531,9569);
$z[6][4]['filename']="footer.htm";

?>