<?php
$z[0]=Array("global","",278,306);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",345,376);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",602,629);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",891,926);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n            <li>\r\n                 <a href=\"[field:link/]\"><img src=\"[field:pic/]\" title=\"[field:text/]\" alt=\"[field:text/]\" width=\"1600\" height=\"640\" /></a>\r\n            </li>\r\n            ",1055,1296);
$z[4][4]['name']="index_banner";
$z[5]=Array("banner","\r\n            <li>&nbsp;</li>\r\n            ",1469,1561);
$z[5][4]['name']="index_banner";
$z[6]=Array("arclist","\r\n                  <li>\r\n                       <a href=\"[field:arcurl /]\"><img src=\"[field:hot_img /]\" title=\"[field:title /]\" alt=\"[field:title /]\" width=\"336\" height=\"314\" /></a>\r\n                       <div class=\"con\">\r\n                             <em class=\"up\">&nbsp;</em>\r\n                             <h2><a href=\"[field:arcurl /]\">[field:title /]</a></h2>\r\n                             <h3><a href=\"[field:arcurl /]\">[field:shorttitle /]</a></h3>\r\n                             <em class=\"cn\">&nbsp;</em>\r\n                             <span><a href=\"[field:arcurl /]\">Read more</a></span>\r\n                       </div>\r\n                  </li> \r\n                 ",2048,2837);
$z[6][4]['flag']="c";
$z[6][4]['row']="24";
$z[6][4]['titlelen']="60";
$z[6][4]['orderby']="weight";
$z[6][4]['addfields']="hot_img";
$z[6][4]['channelid']="2";
$z[7]=Array("arclist","\r\n                <li>\r\n                     <a href=\"[field:arcurl/]\"><img src=\"[field:new_home/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"120\" height=\"120\" /></a>\r\n                     <div class=\"content\">\r\n                           <h3><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\r\n                           <p>[field:description function='cn_substrR(html2text(@me),65)'/]...</p>\r\n                           <span><a href=\"[field:arcurl/]\">View More</a></span>\r\n                     </div>\r\n                </li>\r\n                ",8123,8791);
$z[7][4]['orderby']="weight";
$z[7][4]['typeid']="5";
$z[7][4]['titlelen']="40";
$z[7][4]['row']="3";
$z[7][4]['addfields']="new_home";
$z[7][4]['channelid']="1";
$z[8]=Array("include","",9364,9402);
$z[8][4]['filename']="footer.htm";

?>