<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",105,140);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("global","",260,287);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",294,321);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("field","",444,495);
$z[4][4]['name']="position";
$z[4][4]['function']="position_preg(@me)";
$z[5]=Array("field","",538,562);
$z[5][4]['name']="seotitle";
$z[6]=Array("banner","\r\n               <li><img src=\"[field:pic/]\" title=\"Products &amp; Service\" alt=\"Products &amp; Service\" width=\"484\" height=\"302\"/></li>\r\n               ",1625,1825);
$z[6][4]['name']="about_show";
$z[7]=Array("banner","\r\n               <li><img src=\"[field:pic/]\" title=\"Main Customer\" alt=\"Main Customer\" width=\"484\" height=\"302\"/></li>\r\n               ",4264,4450);
$z[7][4]['name']="about_customer";
$z[8]=Array("include","",11321,11359);
$z[8][4]['filename']="footer.htm";

?>