<?php
$z[0]=Array("global","",278,306);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",345,376);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",647,674);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",936,971);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n            <li>\r\n                 <a href=\"[field:link/]\"><img src=\"[field:pic/]\" title=\"[field:text/]\" alt=\"[field:text/]\" width=\"1600\" height=\"740\" /></a>\r\n            </li>\r\n            ",1100,1341);
$z[4][4]['name']="index_banner";
$z[5]=Array("banner","\r\n            <li></li>\r\n            ",1514,1600);
$z[5][4]['name']="index_banner";
$z[6]=Array("arclist","\r\n                              <li>\r\n                                   <div class=\"img\">\r\n                                        <a href=\"[field:arcurl/]\"><img src=\"[field:home_img/]\" title=\"[field:title/] - [field:typename/]\" alt=\"[field:title/] - [field:typename/]\" width=\"190\" height=\"190\" /></a>\r\n                                   </div>\r\n                                   <h3><a href=\"[field:arcurl/]\" title=\"[field:title/] - [field:typename/]\">[field:title/]</a></h3>\r\n                              </li>\r\n                              ",3992,4670);
$z[6][4]['row']="12";
$z[6][4]['titlelen']="100";
$z[6][4]['orderby']="pubdate";
$z[6][4]['idlist']="";
$z[6][4]['typeid']="1,7";
$z[6][4]['addfields']="home_img";
$z[6][4]['channelid']="2";
$z[7]=Array("arclist","\r\n                              <li>\r\n                                   <div class=\"img\">\r\n                                        <a href=\"[field:arcurl/]\"><img src=\"[field:home_img/]\" title=\"[field:title/] - [field:typename/]\" alt=\"[field:title/] - [field:typename/]\" width=\"190\" height=\"190\" /></a>\r\n                                   </div>\r\n                                   <h3><a href=\"[field:arcurl/]\" title=\"[field:title/] - [field:typename/]\">[field:title/]</a></h3>\r\n                              </li>\r\n                              ",5080,5766);
$z[7][4]['row']="12";
$z[7][4]['titlelen']="100";
$z[7][4]['flag']="c";
$z[7][4]['orderby']="weight";
$z[7][4]['idlist']="";
$z[7][4]['typeid']="1,7";
$z[7][4]['addfields']="home_img";
$z[7][4]['channelid']="2";
$z[8]=Array("banner","\r\n                               <li><img src=\"[field:pic/]\" title=\"FOKSY CO., LTD.\" alt=\"FOKSY CO., LTD.\" width=\"468\" height=\"337\" /></li>\r\n                               ",6503,6723);
$z[8][4]['name']="index_about";
$z[9]=Array("include","",8331,8369);
$z[9][4]['filename']="footer.htm";

?>