<?php
$z[0]=Array("global","",277,305);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",344,375);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",461,488);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",750,785);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n            <li>\r\n                <a href=\"[field:link/]\"><img src=\"[field:pic/]\" width=\"1600\" height=\"692\" alt=\"[field:text/]\" title=\"[field:text/]\" /></a>\r\n                <span><a href=\"[field:link/]\">Learn more</a></span>\r\n            </li>\r\n            ",914,1231);
$z[4][4]['name']="index_banner";
$z[4][4]['row']="4";
$z[5]=Array("include","",9473,9511);
$z[5][4]['filename']="footer.htm";

?>