<?php
$z[0]=Array("field","",254,279);
$z[0][4]['name']="title";
$z[1]=Array("global","",280,305);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",349,380);
$z[2][4]['name']="description";
$z[3]=Array("field","",417,445);
$z[3][4]['name']="keywords";
$z[4]=Array("type","<a href=\"[field:typeurl/]\">加盟首页</a>",951,1027);
$z[4][4]['typeid']="26";
$z[5]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1111,1189);
$z[5][4]['typeid']="36";
$z[6]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1203,1281);
$z[6][4]['typeid']="37";
$z[7]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1295,1373);
$z[7][4]['typeid']="35";
$z[8]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1387,1465);
$z[8][4]['typeid']="26";
$z[9]=Array("include","",1503,1543);
$z[9][4]['filename']="sub_footer.htm";

?>