<?php
$z[0]=Array("global","",278,306);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",345,376);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",606,633);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",895,930);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n            <li>\r\n                 <a href=\"[field:link/]\"><img src=\"[field:pic/]\" title=\"[field:text/]\" alt=\"[field:text/]\" width=\"1600\" height=\"640\" /></a>\r\n            </li>\r\n            ",1059,1300);
$z[4][4]['name']="index_banner";
$z[5]=Array("banner","\r\n            <li>&nbsp;</li>\r\n            ",1473,1565);
$z[5][4]['name']="index_banner";
$z[6]=Array("banner","\r\n                                 <li><a href=\"/about/\"><img src=\"[field:pic/]\" title=\"ABOUT Y.Y.J.D\" alt=\"ABOUT Y.Y.J.D\" width=\"730\" height=\"430\"  /></a></li> \r\n                                 ",5680,5923);
$z[6][4]['name']="home_about";
$z[7]=Array("banner","\r\n                                 <li>&nbsp;</li>\r\n                                 ",6266,6398);
$z[7][4]['name']="home_about";
$z[8]=Array("arclist","\r\n                       <li>\r\n                            <a href=\"[field:arcurl /]\"><img src=\"[field:hot_img /]\" title=\"[field:title /]\" alt=\"[field:title /]\" width=\"578\" height=\"262\"  /></a> \r\n                            <h3><a href=\"[field:arcurl /]\">[field:title /]<i>&nbsp;</i></a></h3>\r\n                       </li>\r\n                       ",8132,8593);
$z[8][4]['flag']="c";
$z[8][4]['row']="24";
$z[8][4]['titlelen']="60";
$z[8][4]['orderby']="weight";
$z[8][4]['addfields']="hot_img";
$z[8][4]['channelid']="2";
$z[9]=Array("include","",8833,8871);
$z[9][4]['filename']="footer.htm";

?>