<?php
$z[0]=Array("global","",254,281);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",325,356);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",393,421);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",549,585);
$z[3][4]['name']="realname_authenticat";
$z[4]=Array("include","",1280,1316);
$z[4][4]['filename']="head.htm";
$z[5]=Array("banner","\r\n			<li style=\"background:url([field:pic/]) no-repeat center top ;\"></li>\r\n            ",1715,1860);
$z[5][4]['name']="index_banner";
$z[5][4]['row']="4";
$z[6]=Array("banner","\r\n		<li></li>\r\n        ",1976,2050);
$z[6][4]['name']="banner";
$z[6][4]['row']="4";
$z[7]=Array("channelartlist","\r\n			<li>\r\n                {gemel:arclist titlelen='38' row='1' flag='c' addfields='new_pro' channelid='2'}\r\n				<div class=\"indexpro_img\">\r\n					<a href=\"jacascrit:viod(0);\">\r\n                    <img src=\"[field:litpic/]\" width=\"217\" height=\"120\" title=\"[field:title/]\" alt=\"[field:title/]\"/>\r\n                    </a>\r\n					<span>[field:new_pro/]</span>\r\n				</div>\r\n                {/gemel:arclist}\r\n				<a href=\"{gemel:field name='typeurl'/}\" class=\"indexpro_text\">{gemel:field name='typename'/}</a>\r\n			</li>\r\n            ",2220,2812);
$z[7][4]['row']="4";
$z[7][4]['typeid']="2";
$z[8]=Array("include","",2869,2907);
$z[8][4]['filename']="footer.htm";

?>