<?php
$z[0]=Array("global","",277,305);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",344,375);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",461,488);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",750,785);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("type","\r\n                           <a href=\"[field:typelink/]\" class=\"img\"><img src=\"/images/banner-profile.jpg\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"110\" height=\"85\" /></a>\r\n                           <h3>[field:typename/]</h3>\r\n                           <p>[field:description function='cn_substrR(html2text(@me),40)'/]...</p>\r\n                           ",1235,1642);
$z[4][4]['typeid']="8";
$z[5]=Array("type","\r\n                           <a href=\"[field:typelink/]\" class=\"img\"><img src=\"/images/pvc-sheet.jpg\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"110\" height=\"85\" /></a>\r\n                           <h3>[field:typename/]</h3>\r\n                           <p>[field:description function='cn_substrR(html2text(@me),40)'/]...</p>\r\n                           ",1883,2285);
$z[5][4]['typeid']="9";
$z[6]=Array("type","\r\n                           <a href=\"[field:typelink/]\" class=\"img\"><img src=\"/images/banner-3d.jpg\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"110\" height=\"85\" /></a>\r\n                           <h3>[field:typename/]</h3>\r\n                           <p>[field:description function='cn_substrR(html2text(@me),40)'/]...</p>\r\n                           ",2525,2927);
$z[6][4]['typeid']="9";
$z[7]=Array("type","\r\n                           <a href=\"[field:typelink/]\" class=\"img\"><img src=\"/images/banner-cover.jpg\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"110\" height=\"85\" /></a>\r\n                           <h3>[field:typename/]</h3>\r\n                           <p>[field:description function='cn_substrR(html2text(@me),40)'/]...</p>\r\n                           ",3163,3568);
$z[7][4]['typeid']="7";
$z[8]=Array("type","\r\n             <li>\r\n                  <div class=\"box_left\">\r\n                       <a href=\"[field:typelink/]\"><img src=\"/images/home-product-01.jpg\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"243\" height=\"164\" /></a>\r\n                  </div>\r\n                  <div class=\"box_right\">\r\n                       <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n                       <p>[field:description function='cn_substrR(html2text(@me),57)'/]...</p> \r\n                       <span><a href=\"[field:typelink/]\">View more</a></span>  \r\n                  </div>                        \r\n             </li>\r\n             ",4989,5674);
$z[8][4]['typeid']="6";
$z[9]=Array("type","\r\n             <li>\r\n                  <div class=\"box_left\">\r\n                       <a href=\"[field:typelink/]\"><img src=\"/images/home-product-04.jpg\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"243\" height=\"164\" /></a>\r\n                  </div>\r\n                  <div class=\"box_right\">\r\n                       <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n                       <p>[field:description function='cn_substrR(html2text(@me),57)'/]...</p> \r\n                       <span><a href=\"[field:typelink/]\">View more</a></span>  \r\n                  </div>                        \r\n             </li>\r\n             ",5689,6374);
$z[9][4]['typeid']="7";
$z[10]=Array("type","\r\n             <li>\r\n                  <div class=\"box_left\">\r\n                       <a href=\"[field:typelink/]\"><img src=\"/images/home-product-02.jpg\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"243\" height=\"164\" /></a>\r\n                  </div>\r\n                  <div class=\"box_right\">\r\n                       <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n                       <p>[field:description function='cn_substrR(html2text(@me),57)'/]...</p> \r\n                       <span><a href=\"[field:typelink/]\">View more</a></span>  \r\n                  </div>                        \r\n             </li>\r\n              ",6389,7075);
$z[10][4]['typeid']="8";
$z[11]=Array("type","\r\n             <li>\r\n                  <div class=\"box_left\">\r\n                       <a href=\"[field:typelink/]\"><img src=\"/images/home-product-03.jpg\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"243\" height=\"164\" /></a>\r\n                  </div>\r\n                  <div class=\"box_right\">\r\n                       <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n                       <p>[field:description function='cn_substrR(html2text(@me),57)'/]...</p> \r\n                       <span><a href=\"[field:typelink/]\">View more</a></span>  \r\n                  </div>                        \r\n             </li> \r\n              ",7090,7777);
$z[11][4]['typeid']="9";
$z[12]=Array("include","",10423,10461);
$z[12][4]['filename']="footer.htm";

?>