<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",71,106);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",227,251);
$z[2][4]['name']="typename";
$z[3]=Array("field","",258,282);
$z[3][4]['name']="typename";
$z[4]=Array("field","",376,400);
$z[4][4]['name']="typename";
$z[5]=Array("field","",669,720);
$z[5][4]['name']="position";
$z[5][4]['function']="position_preg(@me)";
$z[6]=Array("include","",1929,1967);
$z[6][4]['filename']="footer.htm";

?>