<?php
$z[0]=Array("global","",278,306);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",345,376);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",609,636);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",898,933);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n            <li>\r\n                 <a href=\"[field:link/]\"><img src=\"[field:pic/]\" title=\"[field:text/]\" alt=\"[field:text/]\" width=\"1600\" height=\"660\" /></a>\r\n            </li>\r\n            ",1062,1303);
$z[4][4]['name']="index_banner";
$z[5]=Array("banner","\r\n            <li>&nbsp;</li>\r\n            ",1476,1568);
$z[5][4]['name']="index_banner";
$z[6]=Array("banner","\r\n                                 <li><a href=\"/about/\"><img src=\"[field:pic/]\" title=\"Shenzhen Jeya Headwear Co., Ltd.\" alt=\"Shenzhen Jeya Headwear Co., Ltd.\" width=\"794\" height=\"520\"  /></a></li> \r\n                                 ",4834,5115);
$z[6][4]['name']="home_about";
$z[7]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"[field:typepic2/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"343\" height=\"236\"  /></a>       \r\n                    <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n               </li>\r\n               ",7694,8038);
$z[7][4]['typeid']="6";
$z[8]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"[field:typepic2/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"343\" height=\"236\"  /></a>       \r\n                    <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n               </li>\r\n               ",8055,8400);
$z[8][4]['typeid']="24";
$z[9]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"[field:typepic2/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"343\" height=\"236\"  /></a>       \r\n                    <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n               </li>\r\n               ",8417,8761);
$z[9][4]['typeid']="7";
$z[10]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"[field:typepic2/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"343\" height=\"236\"  /></a>       \r\n                    <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n               </li>\r\n               ",8778,9123);
$z[10][4]['typeid']="25";
$z[11]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"[field:typepic2/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"343\" height=\"236\"  /></a>       \r\n                    <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n               </li>\r\n               ",9140,9485);
$z[11][4]['typeid']="27";
$z[12]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"[field:typepic2/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"343\" height=\"236\"  /></a>       \r\n                    <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n               </li>\r\n               ",9502,9847);
$z[12][4]['typeid']="32";
$z[13]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"[field:typepic2/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"343\" height=\"236\"  /></a>       \r\n                    <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n               </li>\r\n               ",9864,10209);
$z[13][4]['typeid']="26";
$z[14]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"[field:typepic2/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"343\" height=\"236\"  /></a>       \r\n                    <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n               </li>\r\n               ",10226,10571);
$z[14][4]['typeid']="35";
$z[15]=Array("type","\r\n               <li>\r\n                    <a href=\"[field:typelink/]\"><img src=\"[field:typepic2/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"343\" height=\"236\"  /></a>       \r\n                    <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n               </li>\r\n               ",10588,10933);
$z[15][4]['typeid']="36";
$z[16]=Array("include","",11104,11142);
$z[16][4]['filename']="footer.htm";

?>