<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",583,617);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n<div class=\"about_banner\" style=\"background:url([field:pic/]) center top no-repeat;\"></div>\r\n",621,769);
$z[4][4]['name']="about_banner";
$z[4][4]['row']="1";
$z[5]=Array("field","",827,855);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",1060,1179);
$z[6][4]['type']="son";
$z[7]=Array("type","[field:typename/]",1280,1328);
$z[7][4]['typeid']="";
$z[8]=Array("field","",1412,1432);
$z[8][4]['name']="content";
$z[9]=Array("include","",1511,1547);
$z[9][4]['filename']="footer.htm";

?>