<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",195,246);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("banner","\r\n                             <li><img src=\"[field:pic/]\" title=\"[field:text/]\" alt=\"[field:text/]\" width=\"933\" height=\"411\"/></li>\r\n                             ",572,792);
$z[3][4]['name']="about_banner";
$z[3][4]['row']="7";
$z[4]=Array("banner","\r\n                             <li>&nbsp;</li>\r\n                             ",957,1091);
$z[4][4]['name']="about_banner";
$z[4][4]['row']="7";
$z[5]=Array("include","",11307,11345);
$z[5][4]['filename']="footer.htm";

?>