<?php
$z[0]=Array("channeltitle","",254,304);
$z[0][4]['order']="backward";
$z[0][4]['character']="_";
$z[1]=Array("global","",305,330);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",374,405);
$z[2][4]['name']="description";
$z[3]=Array("field","",442,470);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",638,672);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",736,770);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",858,886);
$z[6][4]['name']="position";
$z[7]=Array("type","[field:typename/]",933,981);
$z[7][4]['typeid']="";
$z[8]=Array("list","\r\n                            <tr>    \r\n                                <td>[field:title/]</td>\r\n                                <td>[field:supplier/]</td>\r\n                                <td>[field:number/]</td>  \r\n                                <td>[field:format/]</td>\r\n                                <td><a href=\"#\">删除</a></td>  \r\n                            </tr>\r\n                            ",1832,2302);
$z[8][4]['pagesize']="9";
$z[8][4]['orderby']="weight";
$z[8][4]['titlelen']="16";
$z[9]=Array("include","",2481,2517);
$z[9][4]['filename']="footer.htm";

?>