<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",172,223);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",357,380);
$z[3][4]['name']="typename";
$z[4]=Array("field","",387,410);
$z[4][4]['name']="typename";
$z[5]=Array("include","",3388,3426);
$z[5][4]['filename']="footer.htm";

?>