<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",223,247);
$z[2][4]['name']="typename";
$z[3]=Array("field","",254,278);
$z[3][4]['name']="typename";
$z[4]=Array("field","",388,439);
$z[4][4]['name']="position";
$z[4][4]['function']="position_preg(@me)";
$z[5]=Array("include","",1695,1733);
$z[5][4]['filename']="footer.htm";

?>