<?php
$z[0]=Array("global","",277,305);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",344,375);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",560,587);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",849,884);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("arclist"," \r\n         <li>\r\n              <a href=\"[field:arcurl/]\" class=\"img\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"320\" height=\"239\" /></a>\r\n              <!--<a href=\"[field:arcurl/]\" class=\"img\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"384\" height=\"287\" /></a>-->\r\n              <p><a href=\"[field:arcurl/]\">[field:title/]</a></p>\r\n         </li>\r\n         ",7822,8333);
$z[4][4]['orderby']="weight";
$z[4][4]['row']="6";
$z[4][4]['typeid']="3";
$z[4][4]['titlelen']="60";
$z[5]=Array("include","",8483,8521);
$z[5][4]['filename']="footer.htm";

?>