<?php
$z[0]=Array("global","",254,281);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",322,350);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",390,421);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",549,585);
$z[3][4]['name']="realname_authenticat";
$z[4]=Array("include","",811,853);
$z[4][4]['filename']="menu_index.htm";
$z[5]=Array("banner","\r\n                     <li><a href=\"[field:link/]\"><img src=\"[field:pic/]\" width=\"1600\" height=\"676\" alt=\"[field:text/]\" title=\"[field:text/]\"/></a></li>\r\n               ",1002,1229);
$z[5][4]['name']="index_banner";
$z[5][4]['row']="5";
$z[6]=Array("include","",14654,14692);
$z[6][4]['filename']="footer.htm";

?>