<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",103,138);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",254,278);
$z[2][4]['name']="seotitle";
$z[3]=Array("field","",285,309);
$z[3][4]['name']="seotitle";
$z[4]=Array("field","",487,538);
$z[4][4]['name']="position";
$z[4][4]['function']="position_preg(@me)";
$z[5]=Array("field","",643,667);
$z[5][4]['name']="seotitle";
$z[6]=Array("channelartlist","\r\n           <h3><em></em><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h3>\r\n           ",745,906);
$z[6][4]['typeid']="52";
$z[7]=Array("include","",7146,7184);
$z[7][4]['filename']="footer.htm";

?>