<?php
$z[0]=Array("global","",254,281);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",325,356);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",393,421);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",549,585);
$z[3][4]['name']="realname_authenticat";
$z[4]=Array("include","",1068,1104);
$z[4][4]['filename']="head.htm";
$z[5]=Array("banner","\r\n        <li style=\"background:url([field:pic/]) center no-repeat;\" class=\"now\"></li>\r\n        ",1177,1330);
$z[5][4]['name']="index_banner";
$z[5][4]['row']="4";
$z[6]=Array("banner","\r\n        <li>[field:id/]</li>\r\n        ",1411,1502);
$z[6][4]['name']="banner";
$z[6][4]['row']="4";
$z[7]=Array("include","",1619,1655);
$z[7][4]['filename']="left.htm";
$z[8]=Array("type","<h2>[field:typename/]</h2>",1753,1815);
$z[8][4]['typeid']="3";
$z[9]=Array("rpad","",1854,1883);
$z[9][4]['name']="index_ad";
$z[10]=Array("type","\r\n        <h2>[field:typename/]</h2>\r\n        <div class=\"main_center_con\">\r\n            <div class=\"index_advantages\" id=\"cut1\">\r\n            [field:content/]\r\n            </div>\r\n            <div class=\"index_more\"><a href=\"[field:typeurl/]\">>> 了解更多</a></div>\r\n        </div>\r\n        ",1938,2270);
$z[10][4]['typeid']="67";
$z[11]=Array("type","\r\n        <h2>[field:typename/]</h2>\r\n        <div class=\"main_right_con\">\r\n            <div class=\"index_service_route\" id=\"cut2\">\r\n            [field:content/]\r\n            </div>\r\n            <div class=\"index_more\"><a href=\"[field:typeurl/]\">>> 了解更多</a></div>\r\n        </div>\r\n        ",2382,2716);
$z[11][4]['typeid']="68";
$z[12]=Array("type","\r\n        <h2>[field:typename/]</h2>\r\n        <div class=\"index_about\"><img src=\"[field:typepic/]\" alt=\"[field:typename/]\" title=\"[field:typename/]\" /></div>\r\n        ",2736,2939);
$z[12][4]['typeid']="1";
$z[13]=Array("include","",3002,3040);
$z[13][4]['filename']="footer.htm";

?>