<?php
$z[0]=Array("global","",254,281);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",322,350);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",390,421);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",549,585);
$z[3][4]['name']="realname_authenticat";
$z[4]=Array("banner","\r\n			<li><img src=\"[field:pic/]\" alt=\"[field:text/]\" title=\"[field:text/]\" /></li>\r\n			",1988,2132);
$z[4][4]['name']="index_banner";
$z[4][4]['row']="5";
$z[5]=Array("include","",6791,6829);
$z[5][4]['filename']="footer.htm";

?>