<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",71,106);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",215,266);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",309,333);
$z[3][4]['name']="seotitle";
$z[4]=Array("rpad","",609,641);
$z[4][4]['name']="contact_way";
$z[5]=Array("include","",2862,2900);
$z[5][4]['filename']="footer.htm";

?>