<?php
$z[0]=Array("global","",269,296);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",339,367);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",409,440);
$z[2][4]['name']="cfg_description";
$z[3]=Array("include","",448,484);
$z[3][4]['filename']="link.htm";
$z[4]=Array("banner","\r\n				<li>\r\n					<img src=\"[field:pic/]\" alt=\"[field:title/]\" title=\"[field:title/]\" />\r\n					<div class=\"banner_main\">\r\n						<a href=\"[field:link/]\" class=\"btn_readmore\" title=\"Readmore\"></a>\r\n					</div>\r\n				</li>\r\n				",976,1248);
$z[4][4]['name']="index_banner";
$z[5]=Array("global","",1894,1921);
$z[5][4]['name']="cfg_webname";
$z[6]=Array("global","",1930,1957);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("include","",12021,12060);
$z[7][4]['filename']="contact.htm";
$z[8]=Array("include","",12130,12168);
$z[8][4]['filename']="footer.htm";

?>