<?php
$z[0]=Array("global","",254,281);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",322,350);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",390,421);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",549,585);
$z[3][4]['name']="realname_authenticat";
$z[4]=Array("banner","\r\n                <li><img src=\"[field:pic/]\" width=\"1600\" height=\"467\" alt=\"[field:text/]\" title=\"[field:text/]\"/></li>\r\n           ",2000,2198);
$z[4][4]['name']="index_banner_chinese";
$z[4][4]['row']="5";

?>