<?php
$z[0]=Array("field","",254,279);
$z[0][4]['name']="title";
$z[1]=Array("global","",280,305);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",349,380);
$z[2][4]['name']="description";
$z[3]=Array("field","",417,445);
$z[3][4]['name']="keywords";
$z[4]=Array("type","<a href=\"[field:typeurl/]\">加盟首页</a>",1653,1729);
$z[4][4]['typeid']="26";
$z[5]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1813,1891);
$z[5][4]['typeid']="36";
$z[6]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1905,1983);
$z[6][4]['typeid']="37";
$z[7]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1997,2075);
$z[7][4]['typeid']="35";
$z[8]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",2089,2167);
$z[8][4]['typeid']="26";
$z[9]=Array("type","<a href=\"[field:typeurl/]\" target=\"_blank\">我已仔细阅读并同意 棋博士用户隐私条款</a>",6247,6382);
$z[9][4]['typeid']="29";
$z[10]=Array("include","",6530,6570);
$z[10][4]['filename']="sub_footer.htm";

?>