<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",768,802);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n        <li id=\"[field:id/]\" style=\"background:url([field:pic/]) center top no-repeat;\" class=\"now\"></li>\r\n        ",883,1047);
$z[4][4]['name']="banner";
$z[4][4]['row']="4";
$z[5]=Array("banner","\r\n        <li class=\"on\">[field:id/]</li>\r\n        ",1121,1219);
$z[5][4]['name']="banner";
$z[5][4]['row']="4";
$z[6]=Array("type","\r\n    <div class=\"index_about\">\r\n        <div class=\"common_tit\">关于我们</div>\r\n        <div class=\"index_about_con\">\r\n            <p><img src=\"[field:typepic/]\" /></p>\r\n            <p class=\"index_about_con_text\">[field:content/]<a href=\"[field:typelink/]\">了解更多>></a></p>\r\n        </div>\r\n    </div>\r\n    ",1405,1757);
$z[6][4]['typeid']="6";
$z[7]=Array("arclist","\r\n            <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n            ",1921,2088);
$z[7][4]['typeid']="3";
$z[7][4]['orderby']="weight";
$z[7][4]['row']="8";
$z[7][4]['titlelen']="50";
$z[7][4]['flag']="c";
$z[8]=Array("rpad","",2278,2306);
$z[8][4]['name']="index_gg1";
$z[9]=Array("rpad","",2327,2355);
$z[9][4]['name']="index_gg2";
$z[10]=Array("include","",2436,2472);
$z[10][4]['filename']="footer.htm";

?>