<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",71,106);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",208,259);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("global","",360,387);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",394,421);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("field","",544,567);
$z[5][4]['name']="seotitle";
$z[6]=Array("global","",570,597);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("banner","\r\n              <li><img src=\"[field:pic/]\" title=\"{gemel:global.cfg_webname/}\" alt=\"{gemel:global.cfg_webname/}\" width=\"1600\" height=\"396\"/></li>\r\n              ",2104,2312);
$z[7][4]['name']="about_img";
$z[8]=Array("banner","\r\n            <li></li>\r\n            ",2411,2494);
$z[8][4]['name']="about_img";
$z[9]=Array("include","",6401,6439);
$z[9][4]['filename']="footer.htm";

?>