<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",227,278);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("banner","\r\n                 <li><img src=\"[field:pic/]\" title=\"Foksy co., Ltd.\" alt=\"Foksy co., Ltd.\" width=\"642\" height=\"508\"/></li>\r\n                 ",457,647);
$z[3][4]['name']="about_show";
$z[4]=Array("include","",20195,20233);
$z[4][4]['filename']="footer.htm";

?>