<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",223,247);
$z[2][4]['name']="typename";
$z[3]=Array("field","",254,278);
$z[3][4]['name']="typename";
$z[4]=Array("field","",380,431);
$z[4][4]['name']="position";
$z[4][4]['function']="position_preg(@me)";
$z[5]=Array("arclist","\r\n               <li>\r\n                    <div class=\"video\">\r\n                          <iframe width=\"626\" height=\"420\" src=\"[field:litpic/]\" frameborder=\"0\" allowfullscreen></iframe> \r\n                    </div>\r\n                    <div class=\"video-title\">\r\n                          <div class=\"middle\">\r\n                                <div class=\"linner\">\r\n                                      <h3>[field:title/]</h3>\r\n                                </div>\r\n                          </div>\r\n                    </div>\r\n               </li>\r\n               ",2116,2770);
$z[5][4]['row']="60";
$z[5][4]['titlelen']="100";
$z[5][4]['orderby']="pubdate";
$z[5][4]['typeid']="76";
$z[6]=Array("list","\r\n              <li>\r\n                   <em></em>\r\n                   <h3><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h3>\r\n                   <span>[field:add_time/]</span>                     \r\n              </li>\r\n              ",4326,4688);
$z[6][4]['orderby']="weight";
$z[6][4]['pagesize']="15";
$z[6][4]['titlelen']="180";
$z[6][4]['addfields']="add_time";
$z[6][4]['channelid']="1";
$z[7]=Array("pagelist","",5845,5917);
$z[7][4]['listitem']="index,end,pageno";
$z[7][4]['listsize']="4";
$z[7][4]['sitelang']="en";
$z[8]=Array("include","",5982,6020);
$z[8][4]['filename']="footer.htm";

?>