<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",117,152);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",294,345);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",400,424);
$z[3][4]['name']="seotitle";
$z[4]=Array("global","",571,598);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",633,660);
$z[5][4]['name']="cfg_webname";

?>