<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",225,249);
$z[2][4]['name']="typename";
$z[3]=Array("field","",258,282);
$z[3][4]['name']="typename";
$z[4]=Array("field","",353,377);
$z[4][4]['name']="typename";
$z[5]=Array("field","",770,821);
$z[5][4]['name']="position";
$z[5][4]['function']="position_preg(@me)";
$z[6]=Array("include","",9479,9517);
$z[6][4]['filename']="footer.htm";

?>