<?php
$z[0]=Array("global","",278,306);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",345,376);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",738,765);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",1027,1062);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n            <li>\r\n                 <a href=\"[field:link/]\"><img src=\"[field:pic/]\" title=\"[field:text/]\" alt=\"[field:text/]\" width=\"1600\" height=\"762\" /></a>\r\n            </li>\r\n            ",1189,1430);
$z[4][4]['name']="index_banner";
$z[5]=Array("banner","\r\n            <li></li>\r\n            ",1615,1701);
$z[5][4]['name']="index_banner";
$z[6]=Array("global","",1807,1834);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("arclist","\r\n     			<li>\r\n     				<div class=\"img\">\r\n     					<a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/] - [field:typename/]\" alt=\"[field:title/] - [field:typename/]\" width=\"240\" height=\"184\"/></a>\r\n     				</div>\r\n     				<div class=\"text\">\r\n     					<div class=\"icon\">\r\n     						<a href=\"[field:arcurl/]\"><img src=\"/images/hot-icon.png\" title=\"[field:title/] - [field:typename/]\" alt=\"[field:title/] - [field:typename/]\" width=\"100\" height=\"93\"/></a> \r\n     					</div>\r\n     					<h3><a href=\"[field:arcurl/]\">[field:typename/]</a></h3>\r\n     					<h4><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h4>\r\n                        <em></em>\r\n     				</div>\r\n     			</li>\r\n                ",4911,5743);
$z[7][4]['row']="5";
$z[7][4]['typeid']="1";
$z[7][4]['titlelen']="100";
$z[7][4]['flag']="a";
$z[7][4]['orderby']="weight";
$z[8]=Array("include","",5834,5872);
$z[8][4]['filename']="footer.htm";

?>