<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",583,617);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n        <li id=\"[field:id/]\" style=\"background:url([field:pic/]) center top no-repeat;\" class=\"now\"></li>\r\n        ",659,829);
$z[4][4]['name']="about_banner";
$z[4][4]['row']="1";
$z[5]=Array("field","",895,923);
$z[5][4]['name']="position";
$z[6]=Array("type","[field:typename/]",1013,1061);
$z[6][4]['typeid']="";
$z[7]=Array("field","",1143,1163);
$z[7][4]['name']="content";
$z[8]=Array("field","",1249,1306);
$z[8][4]['name']="typeid";
$z[8][4]['function']="GetTopInfo(@me,0,2)";
$z[9]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",1373,1492);
$z[9][4]['type']="son";
$z[10]=Array("include","",1561,1597);
$z[10][4]['filename']="footer.htm";

?>