<?php
$z[0]=Array("channeltitle","",254,304);
$z[0][4]['order']="backward";
$z[0][4]['character']="_";
$z[1]=Array("global","",305,330);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",374,405);
$z[2][4]['name']="description";
$z[3]=Array("field","",442,470);
$z[3][4]['name']="keywords";
$z[4]=Array("include","",638,672);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",736,770);
$z[5][4]['filename']="left.htm";
$z[6]=Array("field","",858,886);
$z[6][4]['name']="position";
$z[7]=Array("type","[field:typename/]",933,981);
$z[7][4]['typeid']="";
$z[8]=Array("field","",1092,1112);
$z[8][4]['name']="content";
$z[9]=Array("channel","\r\n                    <div class=\"moudle_about\">\r\n                        <div class=\"moudle_img\"><img src=\"[field:typepic/]\" /></div>\r\n                        <a class=\"moudle_url\" href=\"[field:typeurl/]\">\r\n                            <span class=\"moudle_tit\">[field:typename/]</span><br />\r\n                            <span class=\"moudle_seo\">[field:seotitle/]</span>\r\n                        </a>\r\n                        <div class=\"moudle_des\">[field:description function='cn_substrR(html2text(@me),120)'/]...</div>\r\n                    </div>\r\n                    ",1199,1819);
$z[9][4]['type']="son";
$z[9][4]['typeid']="5";
$z[10]=Array("include","",1983,2019);
$z[10][4]['filename']="footer.htm";

?>