<?php
$z[0]=Array("global","",288,316);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",360,391);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",713,740);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",1302,1337);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("global","",1360,1388);
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("rpad","",1950,1981);
$z[5][4]['name']="fir_banner";
$z[6]=Array("banner","\r\n                        <li data-delay=\"5\" data-src=\"5\" data-trans3d=\"tr6,tr17,tr22,tr23,tr26,tr27,tr29,tr32,tr34,tr35,tr53,tr54,tr62,tr63,tr4,tr13\" data-trans2d=\"tr3,tr8,tr12,tr19,tr22,tr25,tr27,tr29,tr31,tr34,tr35,tr38,tr39,tr41\"><img src=\"/images/blank.png\" data-src=\"[field:pic/]\" data-thumb=\"/images/blank.png\" width=\"1600\" height=\"660\" />\r\n                            <a data-type=\"link\" href=\"[field:link/]\" target=\"_blank\"></a>\r\n                        </li>\r\n                        ",2128,2679);
$z[6][4]['name']="index_banner";
$z[6][4]['row']="4";
$z[7]=Array("channelartlist","\r\n                                <li>\r\n                                    <a href=\"{gemel:field.typeurl/}\"><img src=\"{gemel:field.typepic/}\" alt=\"{gemel:field.typename/}\" width=\"330\" height=\"320\"  title=\"{gemel:field.typename/}\" />\r\n                                        <span>{gemel:field.typename/}</span>\r\n                                         <p>More&nbsp;>></p></a>\r\n                                </li>\r\n                                ",4168,4697);
$z[7][4]['typeid']="5,6,7,8";
$z[7][4]['orderby']="weight";
$z[8]=Array("rpad","",5129,5161);
$z[8][4]['name']="index_about";
$z[9]=Array("rpad","",5179,5210);
$z[9][4]['name']="about_icon";
$z[10]=Array("rpad","",5379,5412);
$z[10][4]['name']="index_sample";
$z[11]=Array("include","",5466,5504);
$z[11][4]['filename']="footer.htm";

?>