<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",226,250);
$z[2][4]['name']="typename";
$z[3]=Array("field","",257,281);
$z[3][4]['name']="typename";
$z[4]=Array("field","",1197,1248);
$z[4][4]['name']="position";
$z[4][4]['function']="position_preg(@me)";
$z[5]=Array("include","",2592,2630);
$z[5][4]['filename']="footer.htm";

?>