<?php
$z[0]=Array("global","",278,306);
$z[0][4]['name']="cfg_keywords";
$z[1]=Array("global","",345,376);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",699,726);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("include","",999,1034);
$z[3][4]['filename']="nav.htm";
$z[4]=Array("banner","\r\n            <li>\r\n                 <a href=\"[field:link/]\"><img src=\"[field:pic/]\" title=\"[field:text/]\" alt=\"[field:text/]\" width=\"1600\" height=\"430\" /></a>\r\n            </li>\r\n            ",1166,1407);
$z[4][4]['name']="index_banner";
$z[5]=Array("banner","\r\n            <li></li>\r\n            ",1970,2056);
$z[5][4]['name']="index_banner";
$z[6]=Array("global","",2244,2271);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",2491,2518);
$z[7][4]['name']="cfg_webname";
$z[8]=Array("global","",2525,2552);
$z[8][4]['name']="cfg_webname";
$z[9]=Array("include","",8222,8260);
$z[9][4]['filename']="footer.htm";

?>