<?php
$z[0]=Array("include","",0,43);
$z[0][4]['filename']="meta_css_js.htm";
$z[1]=Array("include","",53,89);
$z[1][4]['filename']="head.htm";
$z[2]=Array("field","",158,209);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",373,396);
$z[3][4]['name']="typename";
$z[4]=Array("field","",410,432);
$z[4][4]['name']="content";
$z[5]=Array("include","",489,527);
$z[5][4]['filename']="footer.htm";

?>