<?php
$z[0]=Array("type","<h2>[field:typename/]</h2>",65,128);
$z[0][4]['typeid']="43";
$z[1]=Array("channel"," \r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",148,289);
$z[1][4]['type']="son";
$z[1][4]['row']="12";
$z[1][4]['typeid']="43";
$z[2]=Array("type","<h2>[field:typename/]</h2>",343,406);
$z[2][4]['typeid']="56";
$z[3]=Array("channel"," \r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",426,567);
$z[3][4]['type']="son";
$z[3][4]['row']="12";
$z[3][4]['typeid']="56";
$z[4]=Array("rpad","",668,701);
$z[4][4]['name']="left_contact";

?>