<?php
$z[0]=Array("channel","\r\n                <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",128,259);
$z[0][4]['type']="son";
$z[1]=Array("type","<a href=\"[field:typeurl/]\">为什么选择棋博士</a>",396,483);
$z[1][4]['typeid']="4";
$z[2]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",493,574);
$z[2][4]['typeid']="12";
$z[3]=Array("type","<a href=\"[field:typeurl/]\">[field:typename/]</a>",584,665);
$z[3][4]['typeid']="27";

?>