<?php
$z[0]=Array("field","",54,113);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopInfo(@me,0,2)";
$z[1]=Array("channel","\r\n            <li class=\"pro_li_bg\">\r\n                <a href=\"[field:typeurl/]\" class=\"prolist_a1\" >[field:typename/]</a>\r\n            </li>\r\n            ",196,412);
$z[1][4]['typeid']="";
$z[1][4]['type']="son";
$z[1][4]['row']="10";
$z[2]=Array("rpad","",471,504);
$z[2][4]['name']="left_contact";

?>