<?php
$z[0]=Array("type","<h2>[field:typename/]</h2>",69,132);
$z[0][4]['typeid']="43";
$z[1]=Array("channel"," \r\n            <li>\r\n                <a class=\"main_left_img\" href=\"[field:typeurl/]\"><img src=\"[field:typepic/]\" alt=\"[field:typename/]\" title=\"[field:typename/]\" /></a>\r\n                <a class=\"main_left_text\" href=\"[field:typeurl/]\">[field:typename/]</a>\r\n            </li>\r\n            ",203,558);
$z[1][4]['type']="son";
$z[1][4]['row']="15";
$z[1][4]['typeid']="43";
$z[2]=Array("type","<h2>[field:typename/]</h2>",884,947);
$z[2][4]['typeid']="56";
$z[3]=Array("channel"," \r\n            <li>\r\n                <a class=\"main_left_img\" href=\"[field:typeurl/]\"><img src=\"[field:typepic/]\" alt=\"[field:typename/]\" title=\"[field:typename/]\" /></a>\r\n                <a class=\"main_left_text\" href=\"[field:typeurl/]\">[field:typename/]</a>\r\n            </li>\r\n            ",1018,1373);
$z[3][4]['type']="son";
$z[3][4]['row']="15";
$z[3][4]['typeid']="56";

?>