<?php
$z[0]=Array("field","",63,113);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopInfo(@me,0,3)";
$z[1]=Array("channel","\r\n            <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            ",184,307);
$z[1][4]['type']="son";
$z[2]=Array("type","<a href=\"[field:typeurl/]\"><img src=\"/templets/style/images/contact.jpg\" /></a>",376,488);
$z[2][4]['typeid']="11";
$z[3]=Array("type","<a href=\"[field:typeurl/]\"><img src=\"/templets/style/images/feedback.jpg\" /></a>",527,640);
$z[3][4]['typeid']="21";

?>