<?php
$z[0]=Array("field","",63,113);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopInfo(@me,0,3)";
$z[1]=Array("channel2","\r\n        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n        <div class=\"menu_son\">\r\n            [field:sonchannel0]\r\n            <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n            [/field:sonchannel0]\r\n        </div>\r\n        ",166,464);
$z[1][4]['type']="son";
$z[1][4]['typeid']="6";
$z[2]=Array("type","<a href=\"[field:typeurl/]\"></a>",518,582);
$z[2][4]['typeid']="12";

?>