<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",199,221);
$z[2][4]['name']="typepic";
$z[3]=Array("field","",230,253);
$z[3][4]['name']="typename";
$z[4]=Array("field","",260,283);
$z[4][4]['name']="typename";
$z[5]=Array("field","",378,429);
$z[5][4]['name']="position";
$z[5][4]['function']="position_preg(@me)";
$z[6]=Array("field","",555,578);
$z[6][4]['name']="typename";
$z[7]=Array("list","\r\n                      <li>\r\n                           <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"232\" height=\"198\"/></a>\r\n                           <h2><a href=\"[field:arcurl/]\">[field:shorttitle/]</a></h2>\r\n                           <span><a href=\"[field:arcurl/]\">Read more</a></span>\r\n                      </li>\r\n                      ",680,1155);
$z[7][4]['orderby']="weight";
$z[7][4]['pagesize']="6";
$z[7][4]['titlelen']="100";
$z[8]=Array("pagelist","",1248,1320);
$z[8][4]['listitem']="index,end,pageno";
$z[8][4]['listsize']="4";
$z[8][4]['sitelang']="en";
$z[9]=Array("channelartlist","\r\n                 <li><i>&nbsp;</i><h3><a href=\"{gemel:field name='typeurl'/}\">{gemel:field name='typename'/}</a></h3></li>\r\n                 ",1461,1680);
$z[9][4]['typeid']="1";
$z[9][4]['row']="20";
$z[9][4]['type']="son";
$z[10]=Array("include","",1986,2024);
$z[10][4]['filename']="footer.htm";

?>