<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",227,278);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("list","\r\n               <li>\r\n                   <a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"240\" height=\"155\" /></a>\r\n                   <span>[field:title/]</span>\r\n               </li>\r\n               ",995,1346);
$z[3][4]['orderby']="weight";
$z[3][4]['pagesize']="12";
$z[3][4]['titlelen']="100";
$z[4]=Array("pagelist","",1412,1484);
$z[4][4]['listitem']="index,end,pageno";
$z[4][4]['listsize']="4";
$z[4][4]['sitelang']="en";
$z[5]=Array("include","",1531,1569);
$z[5][4]['filename']="footer.htm";

?>