<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",583,617);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n        <li id=\"[field:id/]\" style=\"background:url([field:pic/]) center top no-repeat;\" class=\"now\"></li>\r\n        ",659,828);
$z[4][4]['name']="news_banner";
$z[4][4]['row']="1";
$z[5]=Array("field","",894,922);
$z[5][4]['name']="position";
$z[6]=Array("type","[field:typename/]",1012,1060);
$z[6][4]['typeid']="";
$z[7]=Array("arclist","\r\n					<li><span>( [field:pubdate function=\"MyDate('Y-m-d',@me)\"/] )</span><a href=\"[field:files_url/]\">[field:title/]</a></li>\r\n                    ",1173,1427);
$z[7][4]['orderby']="weight";
$z[7][4]['addfields']="files_url";
$z[7][4]['row']="10";
$z[7][4]['channelid']="15";
$z[7][4]['titlelen']="60";
$z[8]=Array("pagelist","",1553,1632);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[8][4]['sitelang']="cn";
$z[9]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",1838,1957);
$z[9][4]['type']="son";
$z[10]=Array("include","",2026,2062);
$z[10][4]['filename']="footer.htm";

?>