<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",98,133);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",198,220);
$z[2][4]['name']="typepic";
$z[3]=Array("field","",229,253);
$z[3][4]['name']="typename";
$z[4]=Array("field","",260,284);
$z[4][4]['name']="typename";
$z[5]=Array("field","",462,513);
$z[5][4]['name']="position";
$z[5][4]['function']="position_preg(@me)";
$z[6]=Array("field","",607,631);
$z[6][4]['name']="seotitle";
$z[7]=Array("channelartlist","\r\n                    <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a><i></i></li>\r\n                    ",767,943);
$z[7][4]['typeid']="6";
$z[8]=Array("list","\r\n                    <li>\r\n                        <a href=\"[field:certificate_url/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" width=\"246\" height=\"312\" alt=\"[field:title/]\"></a>\r\n                        <h2>[field:title/]</h2>\r\n                    </li>\r\n                    ",1098,1496);
$z[8][4]['orderby']="weight";
$z[8][4]['titlelen']="100";
$z[8][4]['pagesize']="8";
$z[8][4]['channelid']="15";
$z[8][4]['addfields']="certificate_url";
$z[9]=Array("pagelist","",1592,1664);
$z[9][4]['listitem']="index,end,pageno";
$z[9][4]['listsize']="4";
$z[9][4]['sitelang']="en";
$z[10]=Array("include","",1770,1808);
$z[10][4]['filename']="footer.htm";

?>