<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",269,320);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("channelartlist","\r\n              <h3><a href=\"{gemel:field.typeurl/}\" class=\"{gemel:field.pro_hot/}\">{gemel:field.typename/}</a></h3>\r\n              ",522,720);
$z[3][4]['typeid']="7";
$z[3][4]['row']="100";
$z[4]=Array("field","",870,892);
$z[4][4]['name']="typepic";
$z[5]=Array("field","",901,924);
$z[5][4]['name']="typename";
$z[6]=Array("field","",931,954);
$z[6][4]['name']="typename";
$z[7]=Array("field","",987,1009);
$z[7][4]['name']="typepic";
$z[8]=Array("field","",1102,1125);
$z[8][4]['name']="typename";
$z[9]=Array("list","\r\n                       <li>\r\n                           <div class=\"img\">\r\n                               <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/] - [field:typename/]\" alt=\"[field:title/] - [field:typename/]\" width=\"160\" height=\"160\" /></a>\r\n                           </div>\r\n                           <h3><a href=\"[field:arcurl/]\" title=\"[field:title/] - [field:typename/]\">[field:title/]</a></h3>\r\n                       </li>\r\n                       ",1229,1791);
$z[9][4]['orderby']="weight";
$z[9][4]['pagesize']="15";
$z[9][4]['titlelen']="100";
$z[10]=Array("pagelist","",1887,1959);
$z[10][4]['listitem']="index,end,pageno";
$z[10][4]['listsize']="4";
$z[10][4]['sitelang']="en";
$z[11]=Array("include","",2065,2103);
$z[11][4]['filename']="footer.htm";

?>