<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",583,617);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n<div class=\"about_banner\" style=\"background:url([field:pic/]) center top no-repeat;\"></div>\r\n",621,769);
$z[4][4]['name']="about_banner";
$z[4][4]['row']="1";
$z[5]=Array("field","",827,855);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",1059,1178);
$z[6][4]['type']="son";
$z[7]=Array("type","[field:typename/]",1279,1327);
$z[7][4]['typeid']="";
$z[8]=Array("list","   \r\n					<li><div class=\"pro_list_img\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" /></a></div><a href=\"[field:arcurl/]\" class=\"pro_list_tit\">[field:title/]</a><a href=\"[field:arcurl/]\" class=\"pro_list_details\">DETAILS+</a></li>\r\n                    ",1454,1779);
$z[8][4]['pagesize']="9";
$z[8][4]['orderby']="weight";
$z[8][4]['titlelen']="16";
$z[9]=Array("pagelist","",1945,2024);
$z[9][4]['listitem']="index,end,pre,next,pageno";
$z[9][4]['listsize']="5";
$z[9][4]['sitelang']="cn";
$z[10]=Array("include","",2117,2153);
$z[10][4]['filename']="footer.htm";

?>