<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",105,140);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",250,273);
$z[2][4]['name']="typename";
$z[3]=Array("field","",280,303);
$z[3][4]['name']="typename";
$z[4]=Array("field","",337,359);
$z[4][4]['name']="typepic";
$z[5]=Array("field","",522,573);
$z[5][4]['name']="position";
$z[5][4]['function']="position_preg(@me)";
$z[6]=Array("include","",696,736);
$z[6][4]['filename']="nav-left.htm";
$z[7]=Array("field","",823,846);
$z[7][4]['name']="typename";
$z[8]=Array("php"," AddFilter(22,1,'quick_type,quick_orientation,quick_width');",988,1071);
$z[9]=Array("list","\r\n                    <li>\r\n                        <div class=\"img\">\r\n                            <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:typename/] - [field:title/]\" alt=\"[field:typename/] - [field:title/]\" width=\"252\" height=\"187\"/></a>\r\n                        </div>\r\n                        <div class=\"text\">\r\n                            <h3><a href=\"[field:arcurl/]\">[field:typename/]</a></h3>\r\n                            <h4><a href=\"[field:arcurl/]\" title=\"[field:typename/] - [field:title/]\">[field:title/]</a></h4>\r\n                            <a href=\"[field:arcurl/]\" title=\"[field:typename/] - [field:title/]\">view more</a>\r\n                        </div>\r\n                    </li>\r\n                    ",1236,2054);
$z[9][4]['orderby']="weight";
$z[9][4]['pagesize']="12";
$z[9][4]['titlelen']="100";
$z[10]=Array("pagelist","",2146,2218);
$z[10][4]['listitem']="index,end,pageno";
$z[10][4]['listsize']="4";
$z[10][4]['sitelang']="en";
$z[11]=Array("include","",2360,2398);
$z[11][4]['filename']="footer.htm";

?>