<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",243,266);
$z[2][4]['name']="typename";
$z[3]=Array("field","",273,296);
$z[3][4]['name']="typename";
$z[4]=Array("field","",331,353);
$z[4][4]['name']="typepic";
$z[5]=Array("field","",466,517);
$z[5][4]['name']="position";
$z[5][4]['function']="position_preg(@me)";
$z[6]=Array("field","",606,629);
$z[6][4]['name']="typename";
$z[7]=Array("list","\r\n                      <li>\r\n                           <div class=\"img\">\r\n                               <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"246\" height=\"220\"/></a>\r\n                           </div>\r\n                           <h2><a href=\"[field:arcurl/]\">[field:shorttitle/]</a></h2>\r\n                      </li>\r\n                      ",726,1206);
$z[7][4]['orderby']="weight";
$z[7][4]['pagesize']="12";
$z[7][4]['titlelen']="100";
$z[8]=Array("pagelist","",1289,1361);
$z[8][4]['listitem']="index,end,pageno";
$z[8][4]['listsize']="4";
$z[8][4]['sitelang']="en";
$z[9]=Array("include","",1448,1486);
$z[9][4]['filename']="footer.htm";

?>