<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",105,140);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",250,273);
$z[2][4]['name']="typename";
$z[3]=Array("field","",280,303);
$z[3][4]['name']="typename";
$z[4]=Array("field","",337,359);
$z[4][4]['name']="typepic";
$z[5]=Array("field","",522,573);
$z[5][4]['name']="position";
$z[5][4]['function']="position_preg(@me)";
$z[6]=Array("include","",696,736);
$z[6][4]['filename']="nav-left.htm";
$z[7]=Array("field","",823,846);
$z[7][4]['name']="typename";
$z[8]=Array("channelartlist","\r\n                    <li>\r\n                        <div class=\"img\">\r\n                            <a href=\"{gemel:field.typeurl/}\"><img src=\"{gemel:field.typepic2/}\" title=\"{gemel:field.typename/}\" alt=\"{gemel:field.typename/}\" width=\"252\" height=\"187\"/></a>\r\n                        </div>\r\n                        <div class=\"text\">\r\n                            <h3><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h3>\r\n                            <a href=\"{gemel:field.typeurl/}\" title=\"{gemel:field.typename/}\">view more</a>\r\n                        </div>\r\n                    </li>\r\n                    ",945,1625);
$z[8][4]['typeid']="13";
$z[9]=Array("include","",1795,1833);
$z[9][4]['filename']="footer.htm";

?>