<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",71,106);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",207,230);
$z[2][4]['name']="typename";
$z[3]=Array("field","",237,260);
$z[3][4]['name']="typename";
$z[4]=Array("field","",294,316);
$z[4][4]['name']="typepic";
$z[5]=Array("field","",464,515);
$z[5][4]['name']="position";
$z[5][4]['function']="position_preg(@me)";
$z[6]=Array("channelartlist","\r\n                    <li>\r\n                        <div class=\"middle\">\r\n                            <div class=\"linner\">\r\n                               <h3><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h3>\r\n                            </div>\r\n                        </div>\r\n                        <em></em>\r\n                    </li>\r\n                    ",738,1170);
$z[6][4]['typeid']="2";
$z[7]=Array("field","",1300,1323);
$z[7][4]['name']="typename";
$z[8]=Array("list","\r\n                    <li>\r\n                        <div class=\"img\">\r\n                            <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:typename/] - [field:title/]\" alt=\"[field:typename/] - [field:title/]\" width=\"245\" height=\"190\"/></a>\r\n                        </div>\r\n                        <div class=\"text\">\r\n                            <h2><a href=\"[field:arcurl/]\" title=\"[field:typename/] - [field:title/]\">[field:title/]</a></h2>\r\n                            <a href=\"[field:arcurl/]\" title=\"[field:typename/] - [field:title/]\">view more</a>\r\n                        </div>\r\n                    </li>\r\n                    ",1422,2154);
$z[8][4]['orderby']="weight";
$z[8][4]['pagesize']="12";
$z[8][4]['titlelen']="100";
$z[9]=Array("pagelist","",2246,2318);
$z[9][4]['listitem']="index,end,pageno";
$z[9][4]['listsize']="4";
$z[9][4]['sitelang']="en";
$z[10]=Array("include","",2422,2460);
$z[10][4]['filename']="footer.htm";

?>