<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",171,194);
$z[2][4]['name']="typepic2";
$z[3]=Array("field","",203,226);
$z[3][4]['name']="typename";
$z[4]=Array("field","",233,256);
$z[4][4]['name']="typename";
$z[5]=Array("field","",290,312);
$z[5][4]['name']="typepic";
$z[6]=Array("field","",455,506);
$z[6][4]['name']="position";
$z[6][4]['function']="position_preg(@me)";
$z[7]=Array("field","",649,672);
$z[7][4]['name']="typename";
$z[8]=Array("channelartlist","\r\n                    <li>\r\n                        <h2><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h2>\r\n                        <div class=\"list\">\r\n                             {gemel:channel type='onlyson'}\r\n                              <h4><a href=\"[field:typeurl/]\">[field:typename/]</a></h4>\r\n                             {/gemel:channel}\r\n                        </div>\r\n                    </li>\r\n                 ",714,1224);
$z[8][4]['typeid']="7,8,42,43,44,45";
$z[9]=Array("list","\r\n                      <tr>\r\n                           <td><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"150\" height=\"104\" /></a></td>\r\n                           <td>[field:shorttitle/]</td>\r\n                           <td>[field:working_current/]</td>\r\n                           <td>[field:pcm_size/]</td>\r\n                           <td>[field:balancing_pcm/]</td>\r\n                           <td>[field:temp_control/]</td>\r\n                      </tr>\r\n                      ",2022,2712);
$z[9][4]['orderby']="weight";
$z[9][4]['pagesize']="10";
$z[9][4]['titlelen']="100";
$z[9][4]['addfields']="working_current,pcm_size,balancing_pcm,temp_control";
$z[9][4]['channelid']="15";
$z[10]=Array("pagelist","",2905,2977);
$z[10][4]['listitem']="index,end,pageno";
$z[10][4]['listsize']="4";
$z[10][4]['sitelang']="en";
$z[11]=Array("include","",3228,3266);
$z[11][4]['filename']="footer.htm";
$z[12]=Array("type","[field:typelink /]",3754,3814);
$z[12][4]['typeid']="0";
$z[12][4]['row']="1";

?>