<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",404,455);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("list","\r\n                <li class=\"clear\"> \r\n                     <div class=\"img\">\r\n                          <img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"703\" height=\"335\" />\r\n                     </div>\r\n                     <div class=\"con\">  \r\n                        <div class=\"middle\">   \r\n                             <div class=\"inner\">\r\n                                <h2><i></i>[field:title/]</h2>\r\n                                [field:body/]\r\n                             </div>    \r\n                        </div>     \r\n                     </div>                 \r\n                </li>\r\n                ",615,1364);
$z[3][4]['orderby']="weight";
$z[3][4]['pagesize']="8";
$z[3][4]['titlelen']="60";
$z[3][4]['addfields']="body";
$z[3][4]['channelid']="1";
$z[4]=Array("include","",1821,1859);
$z[4][4]['filename']="footer.htm";

?>