<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",223,247);
$z[2][4]['name']="typename";
$z[3]=Array("field","",254,278);
$z[3][4]['name']="typename";
$z[4]=Array("field","",380,431);
$z[4][4]['name']="position";
$z[4][4]['function']="position_preg(@me)";
$z[5]=Array("field","",513,537);
$z[5][4]['name']="typename";
$z[6]=Array("channelartlist","\r\n              <li class=\"clear\">\r\n                  <div class=\"img\">\r\n                      <a href=\"{gemel:field name='typeurl'/}index.html#case-box\"><img src=\"{gemel:field name='typepic2'/}\" title=\"{gemel:field name='typename'/}\" alt=\"{gemel:field name='typename'/}\" width=\"54\" height=\"54\" /></a><!--{gemel:field name='typepic2'/}-->\r\n                  </div>\r\n                  <div class=\"case-con\">  \r\n                        <div class=\"middle\">   \r\n                             <div class=\"inner\">\r\n                                <h3><a href=\"{gemel:field name='typeurl'/}index.html#case-box\">{gemel:field name='typename'/}</a></h3>\r\n                             </div>    \r\n                        </div>     \r\n                  </div> \r\n              </li>\r\n              ",621,1482);
$z[6][4]['typeid']="3";
$z[6][4]['row']="18";
$z[6][4]['type']="top";
$z[7]=Array("list","\r\n              <li>\r\n                  <a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"278\" height=\"375\" /></a>\r\n                  <div class=\"text\">\r\n                      <a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"/images/case-list.png\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"278\" height=\"375\" /></a>\r\n                      <h2><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h2>  \r\n                  </div>                                  \r\n              </li>\r\n              ",1629,2308);
$z[7][4]['orderby']="weight";
$z[7][4]['pagesize']="8";
$z[7][4]['titlelen']="180";
$z[8]=Array("pagelist","",2387,2459);
$z[8][4]['listitem']="index,end,pageno";
$z[8][4]['listsize']="4";
$z[8][4]['sitelang']="en";
$z[9]=Array("include","",2524,2562);
$z[9][4]['filename']="footer.htm";

?>