<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",363,414);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("channelartlist","\r\n                    <li>\r\n                         <a href=\"{gemel:field.typeurl/}\"><img src=\"{gemel:field.typepic2/}\" title=\"{gemel:field.typename/}\" alt=\"{gemel:field.typename/}\" width=\"494\" height=\"228\" /></a>\r\n                         <h2><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h2>\r\n                         <span><a href=\"{gemel:field.typeurl/}\">Read more </a></span>\r\n                    </li>\r\n                    ",628,1139);
$z[3][4]['row']="20";
$z[3][4]['typeid']="1";
$z[4]=Array("include","",1245,1283);
$z[4][4]['filename']="footer.htm";

?>