<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",171,193);
$z[2][4]['name']="typepic";
$z[3]=Array("field","",202,225);
$z[3][4]['name']="typename";
$z[4]=Array("field","",232,255);
$z[4][4]['name']="typename";
$z[5]=Array("field","",289,311);
$z[5][4]['name']="typepic";
$z[6]=Array("field","",459,510);
$z[6][4]['name']="position";
$z[6][4]['function']="position_preg(@me)";
$z[7]=Array("channelartlist","\r\n            <h3><i></i><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h3>\r\n            ",668,828);
$z[7][4]['typeid']="1";
$z[8]=Array("field","",916,939);
$z[8][4]['name']="typename";
$z[9]=Array("field","",1031,1053);
$z[9][4]['name']="content";
$z[10]=Array("list","\r\n                    <li>   \r\n                         <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:typename/] - [field:title/]\" alt=\"[field:typename/] - [field:title/]\" width=\"260\" height=\"208\" /></a>\r\n                         <h3><a href=\"[field:arcurl/]\" title=\"[field:typename/] - [field:title/]\">[field:title/]</a></h3>\r\n                         <span><a href=\"[field:arcurl/]\">READ MORE</a></span>\r\n                         <em></em>  \r\n                    </li> \r\n                    ",1167,1752);
$z[10][4]['orderby']="weight";
$z[10][4]['pagesize']="12";
$z[10][4]['titlelen']="100";
$z[11]=Array("pagelist","",1844,1916);
$z[11][4]['listitem']="index,end,pageno";
$z[11][4]['listsize']="4";
$z[11][4]['sitelang']="en";
$z[12]=Array("include","",2020,2058);
$z[12][4]['filename']="footer.htm";

?>