<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",583,617);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n        <li id=\"[field:id/]\" style=\"background:url([field:pic/]) center top no-repeat;\" class=\"now\"></li>\r\n        ",659,828);
$z[4][4]['name']="news_banner";
$z[4][4]['row']="1";
$z[5]=Array("field","",894,922);
$z[5][4]['name']="position";
$z[6]=Array("type","[field:typename/]",1012,1060);
$z[6][4]['typeid']="";
$z[7]=Array("list","\r\n					<li><span>( [field:pubdate function=\"MyDate('Y-m-d',@me)\"/] )</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                    ",1184,1397);
$z[7][4]['orderby']="weight";
$z[7][4]['pagesize']="10";
$z[7][4]['titlelen']="60";
$z[8]=Array("pagelist","",1516,1595);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[8][4]['sitelang']="cn";
$z[9]=Array("field","",1731,1788);
$z[9][4]['name']="typeid";
$z[9][4]['function']="GetTopInfo(@me,0,2)";
$z[10]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",1855,1974);
$z[10][4]['type']="son";
$z[11]=Array("include","",2043,2079);
$z[11][4]['filename']="footer.htm";

?>