<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",171,194);
$z[2][4]['name']="typepic2";
$z[3]=Array("field","",203,226);
$z[3][4]['name']="typename";
$z[4]=Array("field","",233,256);
$z[4][4]['name']="typename";
$z[5]=Array("field","",290,312);
$z[5][4]['name']="typepic";
$z[6]=Array("field","",455,506);
$z[6][4]['name']="position";
$z[6][4]['function']="position_preg(@me)";
$z[7]=Array("field","",654,677);
$z[7][4]['name']="typename";
$z[8]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",700,786);
$z[8][4]['typeid']="46";
$z[9]=Array("channelartlist","\r\n                 <h3><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h3>\r\n                 ",857,1021);
$z[9][4]['typeid']="46";
$z[10]=Array("list","\r\n                      <tr>\r\n                           <td><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"150\" height=\"104\" /></a></td>\r\n                           <td>[field:shorttitle/]</td>\r\n                           <td>[field:ac_ups/]</td>\r\n                           <td>[field:dc_ups/]</td>\r\n                           <td>[field:battery_ups/]</td>\r\n                           <td>[field:solar_panel_ups/]</td>                         \r\n                      </tr>\r\n                      ",1822,2517);
$z[10][4]['orderby']="weight";
$z[10][4]['pagesize']="10";
$z[10][4]['titlelen']="100";
$z[10][4]['addfields']="ac_ups,dc_ups,battery_ups,solar_panel_ups";
$z[10][4]['channelid']="16";
$z[11]=Array("pagelist","",2710,2782);
$z[11][4]['listitem']="index,end,pageno";
$z[11][4]['listsize']="4";
$z[11][4]['sitelang']="en";
$z[12]=Array("include","",3033,3071);
$z[12][4]['filename']="footer.htm";
$z[13]=Array("type","[field:typelink /]",3559,3619);
$z[13][4]['typeid']="0";
$z[13][4]['row']="1";

?>