<?php
$z[0]=Array("channeltitle","",254,306);
$z[0][4]['order']="backward";
$z[0][4]['character']="_";
$z[1]=Array("global","",307,334);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",378,409);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",446,474);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("global","",602,638);
$z[4][4]['name']="realname_authenticat";
$z[5]=Array("include","",1453,1489);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",1532,1583);
$z[6][4]['name']="position";
$z[6][4]['function']="position_preg(@me)";
$z[7]=Array("field","",1687,1717);
$z[7][4]['name']="typename";
$z[8]=Array("arclist","\r\n                <li>\r\n                <a href=\"[field:app_img/]\" rel=\"prettyPhoto[]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" title=\"[field:title/]\"/></a>\r\n                <span>[field:title/]</span>\r\n                </li>\r\n                ",1780,2141);
$z[8][4]['titlelen']="38";
$z[8][4]['row']="20";
$z[8][4]['addfields']="app_img";
$z[8][4]['channelid']="16";
$z[9]=Array("include","",2198,2236);
$z[9][4]['filename']="footer.htm";

?>