<?php
$z[0]=Array("channeltitle","",254,304);
$z[0][4]['order']="backward";
$z[0][4]['character']="_";
$z[1]=Array("global","",305,330);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",374,405);
$z[2][4]['name']="description";
$z[3]=Array("field","",442,470);
$z[3][4]['name']="keywords";
$z[4]=Array("type","<a href=\"[field:typeurl/]\">加盟首页</a>",980,1056);
$z[4][4]['typeid']="26";
$z[5]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1140,1218);
$z[5][4]['typeid']="36";
$z[6]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1232,1310);
$z[6][4]['typeid']="37";
$z[7]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1324,1402);
$z[7][4]['typeid']="35";
$z[8]=Array("type","<a href=\"[field:typeurl/]\">[field:title/]</a>",1416,1494);
$z[8][4]['typeid']="26";
$z[9]=Array("arclist","\r\n            <div class=\"question_q ie6png\">[field:question/]</div>\r\n            <div class=\"question_a\">[field:answer/]</div>\r\n            ",1560,1816);
$z[9][4]['orderby']="weight";
$z[9][4]['pagesize']="9";
$z[9][4]['titlelen']="60";
$z[9][4]['addfields']="question,answer";
$z[9][4]['channelid']="19";
$z[10]=Array("include","",1854,1894);
$z[10][4]['filename']="sub_footer.htm";

?>