<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",65,100);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",201,225);
$z[2][4]['name']="seotitle";
$z[3]=Array("field","",232,256);
$z[3][4]['name']="seotitle";
$z[4]=Array("field","",716,767);
$z[4][4]['name']="position";
$z[4][4]['function']="position_preg(@me)";
$z[5]=Array("type","\r\n                <a href=\"[field:typelink/]\">\r\n                <em class=\"list-01\">&nbsp;</em>\r\n                <span>[field:typename/]</span>\r\n                </a>\r\n                \r\n                ",965,1202);
$z[5][4]['typeid']="6";
$z[6]=Array("type","\r\n                <a href=\"[field:typelink/]\">\r\n                <em class=\"list-04\">&nbsp;</em>\r\n                <span>[field:typename/]</span>\r\n                </a>\r\n                \r\n                ",1265,1502);
$z[6][4]['typeid']="7";
$z[7]=Array("type","\r\n                <a href=\"[field:typelink/]\">\r\n                <em class=\"list-02\">&nbsp;</em>\r\n                <span>[field:typename/]</span>\r\n                </a>\r\n                \r\n                ",1565,1802);
$z[7][4]['typeid']="8";
$z[8]=Array("type","\r\n                <a href=\"[field:typelink/]\">\r\n                <em class=\"list-03\">&nbsp;</em>\r\n                <span>[field:typename/]</span>\r\n                </a>\r\n                \r\n                ",1865,2102);
$z[8][4]['typeid']="9";
$z[9]=Array("type","\r\n                <a href=\"[field:typelink/]\">\r\n                <em class=\"list-05\">&nbsp;</em>\r\n                <span>[field:typename/]</span>\r\n                </a>\r\n                \r\n                ",2165,2403);
$z[9][4]['typeid']="10";
$z[10]=Array("type","\r\n                <a href=\"[field:typelink/]\">\r\n                <em class=\"list-06\">&nbsp;</em>\r\n                <span>[field:typename/]</span>\r\n                </a>\r\n                \r\n                ",2466,2704);
$z[10][4]['typeid']="11";
$z[11]=Array("list","\r\n                <li><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"270\" height=\"270\" alt=\"[field:typename/] - [field:title/]\" title=\"[field:typename/] - [field:title/]\">\r\n                    <span>[field:title/]</span>\r\n                </a></li>\r\n                ",3571,3919);
$z[11][4]['orderby']="weight";
$z[11][4]['titlelen']="100";
$z[11][4]['pagesize']="8";
$z[12]=Array("pagelist","",4020,4092);
$z[12][4]['listitem']="index,end,pageno";
$z[12][4]['listsize']="4";
$z[12][4]['sitelang']="en";
$z[13]=Array("include","",4190,4228);
$z[13][4]['filename']="footer.htm";

?>