<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",359,410);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("list","\r\n	 	 	 	 <li>\r\n	 	 	 	 	 <h2><a href=\"[field:down_url/]\" target=\"_bank\">[field:title/]</a></h2>\r\n	 	 	 	 	 <a href=\"[field:down_url/]\" target=\"_bank\"><img src=\"/images/down-icon.png\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"162\" height=\"182\"/></a>\r\n	 	 	 	 	 <p>[field:description function='cn_substrR(html2text(@me),100)'/]..</p>\r\n	 	 	 	 	 <p>More products let you know</p>\r\n	 	 	 	 	 <div class=\"icon\">\r\n	 	 	 	 	 	<em class=\"e1\"></em>\r\n	 	 	 	 	 	<em class=\"e2\"></em>\r\n	 	 	 	 	 	<a href=\"[field:down_url/]\" target=\"_bank\"></a>\r\n	 	 	 	 	 </div>\r\n	 	 	 	 </li>\r\n	 	 	 	 ",615,1306);
$z[3][4]['orderby']="weight";
$z[3][4]['pagesize']="9";
$z[3][4]['titlelen']="100";
$z[3][4]['addfields']="down_url";
$z[3][4]['channelid']="14";
$z[4]=Array("include","",1468,1506);
$z[4][4]['filename']="footer.htm";

?>