<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",269,320);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("channelartlist","\r\n                   <div class=\"list\">\r\n                      <h3><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h3>\r\n                      {gemel:channel type='onlyson'}\r\n                      <h4><a href=\"[field:typeurl/]\">[field:typename/]</a></h4>\r\n                      {/gemel:channel}\r\n                   </div> \r\n                   ",520,932);
$z[3][4]['typeid']="1";
$z[4]=Array("field","",1132,1155);
$z[4][4]['name']="typename";
$z[5]=Array("field","",1162,1185);
$z[5][4]['name']="typename";
$z[6]=Array("field","",1218,1240);
$z[6][4]['name']="typepic";
$z[7]=Array("field","",1294,1317);
$z[7][4]['name']="typename";
$z[8]=Array("list","\r\n                       <li>\r\n                           <div class=\"img\">\r\n                               <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/] - [field:typename/]\" alt=\"[field:title/] - [field:typename/]\" width=\"160\" height=\"160\" /></a>\r\n                           </div>\r\n                           <h3><a href=\"[field:arcurl/]\" title=\"[field:title/] - [field:typename/]\">[field:title/]</a></h3>\r\n                       </li>\r\n                       ",1421,1983);
$z[8][4]['orderby']="weight";
$z[8][4]['pagesize']="15";
$z[8][4]['titlelen']="100";
$z[9]=Array("pagelist","",2079,2151);
$z[9][4]['listitem']="index,end,pageno";
$z[9][4]['listsize']="4";
$z[9][4]['sitelang']="en";
$z[10]=Array("include","",2257,2295);
$z[10][4]['filename']="footer.htm";

?>