<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",115,150);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("global","",197,225);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("field","",331,382);
$z[3][4]['name']="position";
$z[3][4]['function']="position_preg(@me)";
$z[4]=Array("channelartlist","\r\n            <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}<i>&nbsp;</i></a></li>\r\n            ",645,834);
$z[4][4]['typeid']="5,6,7,8,9,10,11,12,13,14";
$z[5]=Array("channelartlist","\r\n\r\n                    <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                     ",1533,1708);
$z[5][4]['limit']="0,100";
$z[6]=Array("channelartlist","\r\n                    <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}<i>&nbsp;</i></a></li>\r\n                    ",2074,2256);
$z[6][4]['typeid']="2";
$z[7]=Array("include","",2387,2425);
$z[7][4]['filename']="footer.htm";

?>