<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",583,617);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n        <li id=\"[field:id/]\" style=\"background:url([field:pic/]) center top no-repeat;\" class=\"now\"></li>\r\n        ",659,829);
$z[4][4]['name']="about_banner";
$z[4][4]['row']="1";
$z[5]=Array("field","",895,923);
$z[5][4]['name']="position";
$z[6]=Array("type","[field:typename/]",1013,1061);
$z[6][4]['typeid']="";
$z[7]=Array("list","   \r\n					<li><div class=\"pro_list_img\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" /></a></div><a href=\"[field:arcurl/]\" class=\"pro_list_tit\">[field:title/]</a><a href=\"[field:arcurl/]\" class=\"pro_list_details\">DETAILS+</a></li>\r\n                    ",1181,1506);
$z[7][4]['pagesize']="9";
$z[7][4]['orderby']="weight";
$z[7][4]['titlelen']="16";
$z[8]=Array("pagelist","",1624,1703);
$z[8][4]['listitem']="index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[8][4]['sitelang']="cn";
$z[9]=Array("field","",1819,1876);
$z[9][4]['name']="typeid";
$z[9][4]['function']="GetTopInfo(@me,0,2)";
$z[10]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",1943,2062);
$z[10][4]['type']="son";
$z[11]=Array("include","",2131,2167);
$z[11][4]['filename']="footer.htm";

?>