<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",235,257);
$z[2][4]['name']="typepic";
$z[3]=Array("field","",266,289);
$z[3][4]['name']="typename";
$z[4]=Array("field","",296,319);
$z[4][4]['name']="typename";
$z[5]=Array("field","",386,437);
$z[5][4]['name']="position";
$z[5][4]['function']="position_preg(@me)";
$z[6]=Array("field","",500,523);
$z[6][4]['name']="typename";
$z[7]=Array("list","\r\n                  <li>\r\n                       <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"267\" height=\"200\"/></a>\r\n                       <h2><a href=\"[field:arcurl/]\">[field:title/]</a></h2>\r\n                  </li>\r\n                  ",829,1198);
$z[7][4]['orderby']="weight";
$z[7][4]['pagesize']="9";
$z[7][4]['titlelen']="100";
$z[8]=Array("pagelist","",1269,1341);
$z[8][4]['listitem']="index,end,pageno";
$z[8][4]['listsize']="4";
$z[8][4]['sitelang']="en";
$z[9]=Array("include","",1412,1450);
$z[9][4]['filename']="footer.htm";

?>