<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",238,261);
$z[2][4]['name']="typename";
$z[3]=Array("field","",268,291);
$z[3][4]['name']="typename";
$z[4]=Array("field","",396,447);
$z[4][4]['name']="position";
$z[4][4]['function']="position_preg(@me)";
$z[5]=Array("field","",517,540);
$z[5][4]['name']="typename";
$z[6]=Array("list","\r\n                  <li>\r\n                       <img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"505\" height=\"256\"/>\r\n                       <h2><a href=\"[field:arcurl/]\">[field:title/]</a></h2>\r\n                       <div class=\"arrow\">\r\n                             <a href=\"[field:arcurl/]\">&nbsp;</a>\r\n                       </div>                   \r\n                  </li>\r\n                  ",631,1132);
$z[6][4]['orderby']="weight";
$z[6][4]['pagesize']="10";
$z[6][4]['titlelen']="100";
$z[7]=Array("pagelist","",3339,3411);
$z[7][4]['listitem']="index,end,pageno";
$z[7][4]['listsize']="4";
$z[7][4]['sitelang']="en";
$z[8]=Array("include","",3481,3519);
$z[8][4]['filename']="footer.htm";

?>