<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",115,150);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("global","",197,225);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("field","",331,382);
$z[3][4]['name']="position";
$z[3][4]['function']="position_preg(@me)";
$z[4]=Array("channelartlist","\r\n            <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/} <i>&nbsp;</i> </a></li>\r\n            ",643,834);
$z[4][4]['typeid']="5,6,7,8,9,10,11,12,13,14";
$z[5]=Array("list","\r\n                    <li><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"220\" height=\"220\" alt=\"[field:title/] - [field:typename/]\" title=\"[field:title/] - [field:typename/]\"><p>[field:title/]</p></a><p><i><input type=\"checkbox\" name=\"list[]\" value=\"[field:id/]\" class=\"hidden\" /></i><em><a href=\"/search/email.php?flag=true&sendlist=[field:id/]\">&nbsp;</a></em></p></li>\r\n                    ",1566,2042);
$z[5][4]['orderby']="weight";
$z[5][4]['pagesize']="9";
$z[5][4]['titlelen']="100";
$z[6]=Array("pagelist","",2175,2248);
$z[6][4]['listitem']="index,end,pageno";
$z[6][4]['listsize']="4";
$z[6][4]['sitelang']="en";
$z[7]=Array("channelartlist","\r\n                    <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}<i>&nbsp;</i></a></li>\r\n                    ",3186,3368);
$z[7][4]['typeid']="2";
$z[8]=Array("include","",3499,3537);
$z[8][4]['filename']="footer.htm";

?>