<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",177,228);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",295,318);
$z[3][4]['name']="typename";
$z[4]=Array("list","\r\n                <li>\r\n                     <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"240\" height=\"167\" /></a>\r\n                     <h2><a href=\"[field:arcurl/]\">[field:title/]</a></h2>\r\n                     [field:des/]                 \r\n                </li>\r\n                ",980,1391);
$z[4][4]['orderby']="weight";
$z[4][4]['pagesize']="8";
$z[4][4]['titlelen']="60";
$z[5]=Array("pagelist","",1461,1533);
$z[5][4]['listitem']="index,end,pageno";
$z[5][4]['listsize']="4";
$z[5][4]['sitelang']="en";
$z[6]=Array("include","",1608,1646);
$z[6][4]['filename']="footer.htm";

?>