<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",110,145);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("global","",189,217);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("field","",323,374);
$z[3][4]['name']="position";
$z[3][4]['function']="position_preg(@me)";
$z[4]=Array("channelartlist","\r\n                <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}<i>&nbsp;</i></a></li>\r\n                ",635,832);
$z[4][4]['typeid']="5,6,7,8,9,10,11,12,13,14";
$z[5]=Array("channelartlist","\r\n                    <li class=\"hvr-float-shadow\">\r\n                        <a href=\"{gemel:field.typeurl/}\"><img src=\"{gemel:field.typepic2/}\" width=\"130\" height=\"110\" alt=\"\"><span>{gemel:field.typename/}</span><i>&nbsp;</i></a>\r\n                    </li>\r\n                    ",1574,1959);
$z[5][4]['typeid']="5,6,15,16,17,18,19,20,22,23,24,25,27,28,30,31,33,34";
$z[6]=Array("channelartlist","\r\n                    <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}<i>&nbsp;</i></a></li>\r\n                    ",2295,2477);
$z[6][4]['typeid']="2";
$z[7]=Array("include","",2608,2646);
$z[7][4]['filename']="footer.htm";

?>