<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",71,106);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",207,230);
$z[2][4]['name']="typename";
$z[3]=Array("field","",237,260);
$z[3][4]['name']="typename";
$z[4]=Array("field","",294,316);
$z[4][4]['name']="typepic";
$z[5]=Array("field","",464,515);
$z[5][4]['name']="position";
$z[5][4]['function']="position_preg(@me)";
$z[6]=Array("field","",2536,2559);
$z[6][4]['name']="typename";
$z[7]=Array("list","\r\n                    <li>\r\n                        <div class=\"img\">\r\n                            <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:typename/] - [field:title/]\" alt=\"[field:typename/] - [field:title/]\" width=\"245\" height=\"190\"/></a>\r\n                        </div>\r\n                        <div class=\"text\">\r\n                            <h2><a href=\"\" title=\"\">[field:title/]</a></h2>\r\n                            <a href=\"\" title=\"\">view more</a>\r\n                        </div>\r\n                    </li>\r\n                    ",2658,3292);
$z[7][4]['orderby']="weight";
$z[7][4]['pagesize']="12";
$z[7][4]['titlelen']="100";
$z[8]=Array("pagelist","",5568,5640);
$z[8][4]['listitem']="index,end,pageno";
$z[8][4]['listsize']="4";
$z[8][4]['sitelang']="en";
$z[9]=Array("include","",5744,5782);
$z[9][4]['filename']="footer.htm";

?>