<?php
$z[0]=Array("global","",161,188);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",197,224);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",338,423);
$z[2][4]['typeid']="1";
$z[3]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",478,563);
$z[3][4]['typeid']="2";
$z[4]=Array("channelartlist","\r\n                         <li><a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'>{gemel:field name='typename'/}</a></li>\r\n                       ",636,905);
$z[4][4]['typeid']="2";
$z[4][4]['row']="10";
$z[4][4]['type']="son";
$z[4][4]['currentstyle']="select";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",971,1056);
$z[5][4]['typeid']="3";
$z[6]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1079,1164);
$z[6][4]['typeid']="4";
$z[7]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1188,1273);
$z[7][4]['typeid']="5";

?>