<?php
$z[0]=Array("type","\r\n            <li>\r\n                <h3><i></i><a href=\"[field:typelink/]?check=true\">[field:typename/]</a></h3>\r\n            </li>\r\n            ",139,320);
$z[0][4]['typeid']="2";
$z[1]=Array("type","\r\n                <h3><a href=\"[field:typelink/]?check=true\">[field:typename/]</a><span></span></h3>\r\n                ",356,511);
$z[1][4]['typeid']="13";
$z[2]=Array("channelartlist","\r\n                    <div class=\"three-list\">\r\n                        <div class=\"three-add\">\r\n                            <em></em>\r\n                        </div>\r\n                        <h4><a href=\"{gemel:field.typeurl/}?check=true\">{gemel:field.typename/}</a></h4>\r\n                        <div class=\"three-sort\">\r\n                          {gemel:channel type='onlyson'}\r\n                          <p>\r\n                             <i></i><a href=\"[field:typeurl/]?check=true\">[field:typename/]</a>\r\n                          </p>\r\n                          {/gemel:channel}\r\n                        </div>\r\n                    </div>\r\n                ",666,1385);
$z[2][4]['typeid']="13";
$z[3]=Array("type","\r\n            <li>\r\n                <h3><i></i><a href=\"[field:typelink/]?check=true\">[field:typename/]</a></h3>\r\n            </li>\r\n            ",1442,1623);
$z[3][4]['typeid']="4";

?>