<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",89,174);
$z[0][4]['typeid']="7";
$z[1]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",264,349);
$z[1][4]['typeid']="9";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",373,459);
$z[2][4]['typeid']="10";
$z[3]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",526,611);
$z[3][4]['typeid']="8";
$z[4]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",653,738);
$z[4][4]['typeid']="6";

?>