<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",529,614);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                   ",735,843);
$z[1][4]['typeid']="2";
$z[2]=Array("channelartlist","\r\n\r\n                            <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n\r\n                            ",978,1181);
$z[2][4]['typeid']="5,6,7,8,9,10,11";
$z[3]=Array("channelartlist","\r\n\r\n                            <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n\r\n                            ",1297,1502);
$z[3][4]['typeid']="12,13,14,15,16,17";
$z[4]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                    ",1642,1751);
$z[4][4]['typeid']="3";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                    ",1824,1933);
$z[5][4]['typeid']="4";
$z[6]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3549,3634);
$z[6][4]['typeid']="1";
$z[7]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                <i>&nbsp;</i>",3728,3846);
$z[7][4]['typeid']="2";
$z[8]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                <i>&nbsp;</i>",3907,4025);
$z[8][4]['typeid']="3";
$z[9]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                <i>&nbsp;</i>",4086,4204);
$z[9][4]['typeid']="4";

?>