<?php
$z[0]=Array("type","\r\n                               <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                               ",1353,1513);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1600,1685);
$z[1][4]['typeid']="2";
$z[2]=Array("channelartlist","\r\n                                                  <li><a href=\"{gemel:field name='typeurl'/}\">{gemel:field name='typename'/}</a></li>\r\n                                              ",1840,2098);
$z[2][4]['typeid']="2";
$z[2][4]['row']="4";
$z[2][4]['type']="son";
$z[3]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2347,2432);
$z[3][4]['typeid']="3";
$z[4]=Array("channelartlist","\r\n                                                  <li><a href=\"{gemel:field name='typeurl'/}\">{gemel:field name='typename'/}</a></li>\r\n                                              ",2587,2845);
$z[4][4]['typeid']="3";
$z[4][4]['row']="4";
$z[4][4]['type']="son";
$z[5]=Array("type","\r\n                               <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                               ",3040,3200);
$z[5][4]['typeid']="4";
$z[6]=Array("type","\r\n                               <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                               ",3233,3393);
$z[6][4]['typeid']="5";

?>