<?php
$z[0]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n					   ",777,880);
$z[0][4]['typeid']="2";
$z[1]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n					   ",968,1071);
$z[1][4]['typeid']="3";
$z[2]=Array("channelartlist","\r\n                                 <li><a href=\"{gemel:field name='typeurl'/}\">\r\n                                {gemel:field name='typename'/}</a></li>\r\n                                ",1235,1496);
$z[2][4]['typeid']="3";
$z[2][4]['row']="4";
$z[2][4]['type']="top";
$z[3]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n					    ",1654,1758);
$z[3][4]['typeid']="4";
$z[4]=Array("channelartlist","\r\n                                 <li><a href=\"{gemel:field name='typeurl'/}\">\r\n                                {gemel:field name='typename'/}</a></li>\r\n                                ",1923,2184);
$z[4][4]['typeid']="4";
$z[4][4]['row']="7";
$z[4][4]['type']="top";
$z[5]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n					   ",2303,2407);
$z[5][4]['typeid']="17";
$z[6]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n					   ",2458,2561);
$z[6][4]['typeid']="5";
$z[7]=Array("type","\r\n                            <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                           ",3094,3238);
$z[7][4]['typeid']="2";
$z[8]=Array("type","\r\n                            <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                           ",3338,3482);
$z[8][4]['typeid']="3";
$z[9]=Array("channelartlist","\r\n                                     <li><a href=\"{gemel:field name='typeurl'/}\">\r\n                                    {gemel:field name='typename'/}</a></li>\r\n                                    ",3662,3935);
$z[9][4]['typeid']="3";
$z[9][4]['row']="4";
$z[9][4]['type']="top";
$z[10]=Array("type","\r\n                            <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                            ",4113,4258);
$z[10][4]['typeid']="4";
$z[11]=Array("channelartlist","\r\n                                     <li><a href=\"{gemel:field name='typeurl'/}\">\r\n                                    {gemel:field name='typename'/}</a></li>\r\n                                    ",4439,4712);
$z[11][4]['typeid']="4";
$z[11][4]['row']="7";
$z[11][4]['type']="top";
$z[12]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n					   ",4847,4951);
$z[12][4]['typeid']="17";
$z[13]=Array("type","\r\n                            <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                           ",5010,5154);
$z[13][4]['typeid']="5";

?>