<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",512,597);
$z[0][4]['typeid']="1";
$z[1]=Array("channelartlist","\r\n                            <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                        ",733,914);
$z[1][4]['typeid']="1";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <i>&nbsp;</i>",1040,1160);
$z[2][4]['typeid']="2";
$z[3]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <i>&nbsp;</i>",1227,1347);
$z[3][4]['typeid']="3";
$z[4]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <i>&nbsp;</i>",1414,1534);
$z[4][4]['typeid']="4";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <i>&nbsp;</i>",1601,1721);
$z[5][4]['typeid']="5";
$z[6]=Array("rpad","",2296,2328);
$z[6][4]['name']="google_link";
$z[7]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3125,3210);
$z[7][4]['typeid']="1";
$z[8]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <i>&nbsp;</i>",3312,3432);
$z[8][4]['typeid']="2";
$z[9]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <i>&nbsp;</i>",3499,3619);
$z[9][4]['typeid']="3";
$z[10]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <i>&nbsp;</i>",3686,3806);
$z[10][4]['typeid']="4";
$z[11]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    <i>&nbsp;</i>",3873,3993);
$z[11][4]['typeid']="5";

?>