<?php
$z[0]=Array("type","\r\n                      <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                      <div class=\"nav_bg\"><a href=\"[field:typelink/]\">[field:typename/]</a></div>\r\n                      ",2029,2261);
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n                      <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                      <div class=\"nav_bg\"><a href=\"[field:typelink/]\">[field:typename/]</a></div>\r\n                      ",2612,2844);
$z[1][4]['typeid']="2";
$z[2]=Array("type","\r\n                      <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                      <div class=\"nav_bg\"><a href=\"[field:typelink/]\">[field:typename/]</a></div>\r\n                      ",4539,4771);
$z[2][4]['typeid']="7";
$z[3]=Array("type","\r\n                      <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                      <div class=\"nav_bg_01\"><a href=\"[field:typelink/]\">[field:typename/]</a></div>\r\n                      ",4859,5094);
$z[3][4]['typeid']="8";
$z[4]=Array("type","\r\n                      <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                      <div class=\"nav_bg\"><a href=\"[field:typelink/]\">[field:typename/]</a></div>\r\n                      ",5198,5430);
$z[4][4]['typeid']="9";
$z[5]=Array("type","\r\n                      <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                      <div class=\"nav_bg\"><a href=\"[field:typelink/]\">[field:typename/]</a></div>\r\n                      ",5519,5752);
$z[5][4]['typeid']="10";
$z[6]=Array("type","\r\n                      <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                      <div class=\"nav_bg\"><a href=\"[field:typelink/]\">[field:typename/]</a></div>\r\n                      ",5840,6073);
$z[6][4]['typeid']="11";

?>