<?php
$z[0]=Array("global","",350,377);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",386,413);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",652,737);
$z[2][4]['typeid']="1";
$z[3]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",800,885);
$z[3][4]['typeid']="2";
$z[4]=Array("channelartlist","\r\n                         <h3><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h3>\r\n                         ",1013,1192);
$z[4][4]['typeid']="2";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1268,1353);
$z[5][4]['typeid']="3";
$z[6]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1417,1502);
$z[6][4]['typeid']="4";
$z[7]=Array("channelartlist","\r\n                         <h3><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h3>\r\n                         ",1630,1809);
$z[7][4]['typeid']="4";
$z[8]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1885,1970);
$z[8][4]['typeid']="5";

?>