<?php
$z[0]=Array("type"," \r\n                  <li>\r\n                      <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                      <i>&nbsp;</i>\r\n                  </li> \r\n                  ",421,638);
$z[0][4]['typeid']="3";
$z[1]=Array("type","    \r\n                  <li>\r\n                      <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                      <i>&nbsp;</i>\r\n                  </li>\r\n                  ",658,877);
$z[1][4]['typeid']="4";
$z[2]=Array("type"," \r\n                  <li>\r\n                      <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                      <i class=\"i3\">&nbsp;</i>\r\n                  </li> \r\n                  ",897,1125);
$z[2][4]['typeid']="5";
$z[3]=Array("type"," \r\n                  <li>\r\n                      <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                      <i>&nbsp;</i>\r\n                  </li>\r\n                  ",1145,1361);
$z[3][4]['typeid']="6";
$z[4]=Array("channelartlist","\r\n                  <a href=\"{gemel:field name='typeurl'/}\">{gemel:field name='typename'/}</a>\r\n                  ",2413,2602);
$z[4][4]['typeid']="4";
$z[4][4]['row']="4";
$z[4][4]['type']="son";
$z[5]=Array("channelartlist","\r\n                  <a href=\"{gemel:field name='typeurl'/}\">{gemel:field name='typename'/}</a>\r\n                  ",2779,2968);
$z[5][4]['typeid']="6";
$z[5][4]['row']="4";
$z[5][4]['type']="son";

?>