<?php
$z[0]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",427,563);
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",584,720);
$z[1][4]['typeid']="3";
$z[2]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",741,877);
$z[2][4]['typeid']="4";
$z[3]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",898,1034);
$z[3][4]['typeid']="2";

?>