<?php
$z[0]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n						",1237,1338);
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]<i></i></a>\r\n						",1385,1493);
$z[1][4]['typeid']="2";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1618,1703);
$z[2][4]['typeid']="7";
$z[3]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1836,1921);
$z[3][4]['typeid']="9";
$z[4]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1965,2051);
$z[4][4]['typeid']="10";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2178,2263);
$z[5][4]['typeid']="8";
$z[6]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2308,2393);
$z[6][4]['typeid']="6";
$z[7]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n						",2502,2603);
$z[7][4]['typeid']="3";
$z[8]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]<i></i></a>\r\n						",2657,2765);
$z[8][4]['typeid']="4";
$z[9]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2891,2977);
$z[9][4]['typeid']="12";
$z[10]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3022,3108);
$z[10][4]['typeid']="15";
$z[11]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3153,3239);
$z[11][4]['typeid']="16";
$z[12]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3284,3370);
$z[12][4]['typeid']="17";
$z[13]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3415,3501);
$z[13][4]['typeid']="18";
$z[14]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n						",3606,3707);
$z[14][4]['typeid']="5";

?>