<?php
$z[0]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n						",1298,1399);
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]<i></i></a>\r\n						",1446,1554);
$z[1][4]['typeid']="2";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1679,1764);
$z[2][4]['typeid']="7";
$z[3]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1897,1982);
$z[3][4]['typeid']="9";
$z[4]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2026,2112);
$z[4][4]['typeid']="10";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2239,2324);
$z[5][4]['typeid']="8";
$z[6]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2369,2454);
$z[6][4]['typeid']="6";
$z[7]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n						",2563,2664);
$z[7][4]['typeid']="3";
$z[8]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]<i></i></a>\r\n						",2718,2826);
$z[8][4]['typeid']="4";
$z[9]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2952,3038);
$z[9][4]['typeid']="12";
$z[10]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3083,3169);
$z[10][4]['typeid']="15";
$z[11]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3214,3300);
$z[11][4]['typeid']="16";
$z[12]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3345,3431);
$z[12][4]['typeid']="17";
$z[13]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3476,3562);
$z[13][4]['typeid']="18";
$z[14]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n						",3667,3768);
$z[14][4]['typeid']="5";

?>