<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",339,424);
$z[0][4]['typeid']="7";
$z[1]=Array("include","",537,583);
$z[1][4]['filename']="nav_rhinestone.htm";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",682,767);
$z[2][4]['typeid']="1";
$z[3]=Array("channelartlist","\r\n                                <li>\r\n                                     <h3><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h3>\r\n                                     {gemel:channel type='onlyson'}  \r\n                                     <h4><em></em><a href=\"[field:typeurl/]\">[field:typename/]</a></h4>  \r\n                                     {/gemel:channel}\r\n                                </li>\r\n                                ",925,1433);
$z[3][4]['typeid']="1";
$z[4]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1544,1629);
$z[4][4]['typeid']="2";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1657,1742);
$z[5][4]['typeid']="3";
$z[6]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1770,1855);
$z[6][4]['typeid']="4";
$z[7]=Array("channelartlist","\r\n                                <li>\r\n                                     <h3><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h3>\r\n                                </li>\r\n                                ",2012,2287);
$z[7][4]['typeid']="4";
$z[8]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2398,2483);
$z[8][4]['typeid']="5";

?>