<?php
$z[0]=Array("global","",138,165);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",174,201);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",426,511);
$z[2][4]['typeid']="1";
$z[3]=Array("channelartlist","\r\n                          <h3><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h3>\r\n                          ",590,771);
$z[3][4]['typeid']="1";
$z[4]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",848,933);
$z[4][4]['typeid']="2";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",961,1046);
$z[5][4]['typeid']="3";
$z[6]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1074,1159);
$z[6][4]['typeid']="4";
$z[7]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1187,1272);
$z[7][4]['typeid']="5";
$z[8]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1300,1385);
$z[8][4]['typeid']="6";
$z[9]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1413,1498);
$z[9][4]['typeid']="7";

?>