<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1255,1340);
$z[0][4]['typeid']="2";
$z[1]=Array("channelartlist","\r\n                            <li><i>&nbsp;</i> <a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                            ",1524,1734);
$z[1][4]['typeid']="5,6,7,8,9,10";
$z[2]=Array("channelartlist","\r\n                            <li><i>&nbsp;</i> <a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                            ",1842,2057);
$z[2][4]['typeid']="11,12,13,14,15,16";
$z[3]=Array("channelartlist","\r\n                            <li><i>&nbsp;</i> <a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                            ",2165,2380);
$z[3][4]['typeid']="17,18,19,20,22,23";
$z[4]=Array("channelartlist","\r\n                            <li><i>&nbsp;</i> <a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                            ",2489,2704);
$z[4][4]['typeid']="24,25,27,28,30,31";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a> ",2830,2916);
$z[5][4]['typeid']="1";
$z[6]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a> ",2983,3069);
$z[6][4]['typeid']="3";
$z[7]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a> ",3160,3246);
$z[7][4]['typeid']="4";
$z[8]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",4198,4283);
$z[8][4]['typeid']="1";
$z[9]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                <i>&nbsp;</i>",4369,4485);
$z[9][4]['typeid']="2";
$z[10]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                <i>&nbsp;</i>",4540,4656);
$z[10][4]['typeid']="3";
$z[11]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                <i>&nbsp;</i>",4711,4827);
$z[11][4]['typeid']="4";

?>