<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",520,605);
$z[0][4]['typeid']="1";
$z[1]=Array("channelartlist","\r\n\r\n                            <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n\r\n                            ",791,980);
$z[1][4]['typeid']="1";
$z[2]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                   ",1168,1276);
$z[2][4]['typeid']="2";
$z[3]=Array("channelartlist","\r\n\r\n                            <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n\r\n                            ",1456,1654);
$z[3][4]['typeid']="6,7,8,9,10";
$z[4]=Array("channelartlist","\r\n\r\n                            <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n\r\n                            ",1770,1972);
$z[4][4]['typeid']="12,13,14,15,11";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                    ",2112,2221);
$z[5][4]['typeid']="3";
$z[6]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                    ",2294,2403);
$z[6][4]['typeid']="4";
$z[7]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                    ",2475,2584);
$z[7][4]['typeid']="5";
$z[8]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",4200,4285);
$z[8][4]['typeid']="1";
$z[9]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                <i>&nbsp;</i>",4379,4497);
$z[9][4]['typeid']="2";
$z[10]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                <i>&nbsp;</i>",4558,4676);
$z[10][4]['typeid']="3";
$z[11]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                <i>&nbsp;</i>",4737,4855);
$z[11][4]['typeid']="4";
$z[12]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n\r\n                <i>&nbsp;</i>",4914,5032);
$z[12][4]['typeid']="5";

?>