<?php
$z[0]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",387,523);
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",544,680);
$z[1][4]['typeid']="2";
$z[2]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",701,837);
$z[2][4]['typeid']="3";
$z[3]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",858,994);
$z[3][4]['typeid']="4";
$z[4]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",1015,1151);
$z[4][4]['typeid']="5";
$z[5]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",1172,1308);
$z[5][4]['typeid']="6";

?>