<?php
$z[0]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",446,582);
$z[0][4]['typeid']="1";
$z[1]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",654,739);
$z[1][4]['typeid']="2";
$z[2]=Array("channelartlist","\r\n                                    <li><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                                   ",953,1153);
$z[2][4]['typeid']="2";
$z[3]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",1289,1425);
$z[3][4]['typeid']="3";
$z[4]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",1446,1582);
$z[4][4]['typeid']="5";
$z[5]=Array("type","\r\n                   <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                   ",1603,1739);
$z[5][4]['typeid']="4";

?>