<?php
$z[0]=Array("global","",99,126);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",135,162);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("type","<a href=\"[field:typelink/]\"></a>\r\n                <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                <div class=\"show\">\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                </div>\r\n                ",488,772);
$z[2][4]['typeid']="1";
$z[3]=Array("channelartlist","\r\n                        <li>\r\n                            <div class=\"img\">\r\n                                <a href=\"{gemel:field.typeurl/}\"><img src=\"{gemel:field.typepic2/}\" title=\"{gemel:field.typename/}\" alt=\"{gemel:field.typename/}\" width=\"79\" height=\"62\"/></a>\r\n                            </div>\r\n                            <h2><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h2>\r\n                            <div class=\"list\">\r\n                                {gemel:arclist orderby='weight' titlelen='40' row='14'}\r\n                                <p><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\r\n                                {/gemel:arclist}\r\n                            </div>\r\n                        </li>\r\n                        ",902,1750);
$z[3][4]['typeid']="1";
$z[4]=Array("type","\r\n                 <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                 <div class=\"show\">\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                 </div>\r\n                 ",1840,2096);
$z[4][4]['typeid']="7";
$z[5]=Array("type","\r\n                 <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                 <div class=\"show\">\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                 </div>\r\n                 ",2167,2423);
$z[5][4]['typeid']="8";
$z[6]=Array("type","\r\n                 <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                 <div class=\"show\">\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                 </div>\r\n                 ",2493,2749);
$z[6][4]['typeid']="9";
$z[7]=Array("channelartlist","\r\n                        <h2><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h2>\r\n                    ",2841,3014);
$z[7][4]['typeid']="9";
$z[8]=Array("type","\r\n                <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                <div class=\"show\">\r\n                    <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                </div>\r\n                ",3111,3364);
$z[8][4]['typeid']="10";

?>