<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",413,498);
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n                            <li>\r\n                                <a href=\"[field:typelink/]\"><img src=\"[field:typepic/]\" title=\"PCM Protection Board\" alt=\"PCM Protection Board\" width=\"139\" height=\"128\" /></a>\r\n                                <h3><a href=\"[field:typelink/]\">PCM <br/>Protection Board</a></h3>\r\n                            </li>\r\n                            ",660,1072);
$z[1][4]['typeid']="7";
$z[2]=Array("type","\r\n                            <li>\r\n                                <a href=\"[field:typelink/]\"><img src=\"[field:typepic/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"139\" height=\"128\" /></a>\r\n                                <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n                            </li>\r\n                            ",1102,1501);
$z[2][4]['typeid']="46";
$z[3]=Array("type","\r\n                            <li>\r\n                                <a href=\"[field:typelink/]\"><img src=\"[field:typepic/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"139\" height=\"128\" /></a>\r\n                                <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n                            </li>\r\n                            ",1531,1929);
$z[3][4]['typeid']="5";
$z[4]=Array("type","\r\n                            <li>\r\n                                <a href=\"[field:typelink/]\"><img src=\"[field:typepic/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\" width=\"139\" height=\"128\" /></a>\r\n                                <h3><a href=\"[field:typelink/]\">[field:typename/]</a></h3>\r\n                            </li>\r\n                            ",1959,2357);
$z[4][4]['typeid']="6";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2488,2573);
$z[5][4]['typeid']="2";
$z[6]=Array("channelartlist","\r\n                         <h4><a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></h4>\r\n                        ",2657,2835);
$z[6][4]['typeid']="2";
$z[7]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2911,2996);
$z[7][4]['typeid']="3";
$z[8]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",3024,3109);
$z[8][4]['typeid']="4";

?>