<?php
$z[0]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n						",398,499);
$z[0][4]['typeid']="1";
$z[1]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n					    ",550,654);
$z[1][4]['typeid']="2";
$z[2]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a> \r\n						",706,808);
$z[2][4]['typeid']="3";
$z[3]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n						",859,960);
$z[3][4]['typeid']="4";
$z[4]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n						",1476,1577);
$z[4][4]['typeid']="1";
$z[5]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n					    ",1628,1732);
$z[5][4]['typeid']="2";
$z[6]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a> \r\n						",1784,1886);
$z[6][4]['typeid']="3";
$z[7]=Array("type","\r\n						<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n						",1937,2038);
$z[7][4]['typeid']="4";

?>