<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",808,893);
$z[0][4]['typeid']="2";
$z[1]=Array("channelartlist","\r\n                            <li><i>&nbsp;</i> <a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                            ",1074,1284);
$z[1][4]['typeid']="5,6,7,8,9,10";
$z[2]=Array("channelartlist","\r\n                            <li><i>&nbsp;</i> <a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                            ",1392,1607);
$z[2][4]['typeid']="11,12,13,14,15,16";
$z[3]=Array("channelartlist","\r\n                            <li><i>&nbsp;</i> <a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                            ",1715,1930);
$z[3][4]['typeid']="17,18,19,20,22,23";
$z[4]=Array("channelartlist","\r\n                            <li><i>&nbsp;</i> <a href=\"{gemel:field.typeurl/}\">{gemel:field.typename/}</a></li>\r\n                            ",2039,2254);
$z[4][4]['typeid']="24,25,27,28,30,31";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a> ",2380,2466);
$z[5][4]['typeid']="1";
$z[6]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a> ",2533,2619);
$z[6][4]['typeid']="3";
$z[7]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a> ",2710,2796);
$z[7][4]['typeid']="4";
$z[8]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",4223,4308);
$z[8][4]['typeid']="1";
$z[9]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                <i>&nbsp;</i>",4394,4510);
$z[9][4]['typeid']="2";
$z[10]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                <i>&nbsp;</i>",4565,4681);
$z[10][4]['typeid']="3";
$z[11]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                <i>&nbsp;</i>",4736,4852);
$z[11][4]['typeid']="4";

?>