<?php
$z[0]=Array("include","",0,43);
$z[0][4]['filename']="meta_css_js.htm";
$z[1]=Array("include","",53,89);
$z[1][4]['filename']="head.htm";
$z[2]=Array("field","",193,244);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",318,341);
$z[3][4]['name']="typename";
$z[4]=Array("banner","\r\n                        <div class=\"slideshow\"><img src=\"[field:pic/]\" width=\"740\" height=\"321\" alt=\"[field:text/]\" title=\"[field:text/]\"/></div>\r\n                     ",446,671);
$z[4][4]['name']="news_index";
$z[4][4]['row']="4";
$z[5]=Array("list","\r\n                         <li>\r\n                             <div class=\"news_imgage\">\r\n                                <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"200\" height=\"139\" alt=\"[field:title/]\" title=\"[field:title/]\"/></a>\r\n                             </div>\r\n                             <div class=\"news_title\">\r\n                                <h2><a href=\"[field:arcurl/]\">[field:title/]</a></h2>\r\n                                <p class=\"news_profile\">[field:description/]...</p>\r\n                                <p class=\"news_read\"><a href=\"[field:arcurl/]\">Read more...</a></p>\r\n                             </div>\r\n                             <div class=\"clear\"></div>\r\n                         </li>\r\n                         ",835,1652);
$z[5][4]['pagesize']="3";
$z[5][4]['orderby']="id";
$z[6]=Array("include","",1759,1800);
$z[6][4]['filename']="news_side.htm";
$z[7]=Array("pagelist","",1926,2007);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[7][4]['sitelang']="en";
$z[8]=Array("include","",2081,2119);
$z[8][4]['filename']="footer.htm";

?>