<?php
$z[0]=Array("arclist","\r\n                    <div class=\"exhibition_list\">      \r\n                        <div class=\"exhibition_pic\">\r\n                            <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" width=\"51\" height=\"51\" alt=\"[field:title/]\" title=\"[field:title/]\"></a></div>\r\n                        <div class=\"exhibition_content\">\r\n                            <a href=\"[field:arcurl/]\">[field:title/] ...</a></div>\r\n                        <div class=\"clear\"></div>\r\n                    </div>\r\n                   ",123,715);
$z[0][4]['row']="3";
$z[0][4]['orderby']="id";
$z[0][4]['typeid']="23";
$z[0][4]['titlelen']="30";
$z[1]=Array("include","",786,830);
$z[1][4]['filename']="product_side.htm";

?>