<?php
$z[0]=Array("channel","\r\n        <li>\r\n            <div class=\"menulist_img\"><a href=\"[field:typeurl/]\"><img src=\"[field:typepic/]\" title=\"[field:typename/]\" alt=\"[field:typename/]\"/></a></div>\r\n            <div class=\"menulist_right\">\r\n                <a href=\"[field:typeurl/]\" class=\"menulist_text text_overflow\">[field:typename/]</a>\r\n                <p class=\"menulist_des\">[field:description function='cn_substrR(html2text(@me),60)' /]...</p>\r\n            </div>\r\n        </li>\r\n        ",76,607);
$z[0][4]['typeid']="2";
$z[0][4]['row']="5";
$z[0][4]['type']="son";

?>