<?php
$z[0]=Array("channeltitle","",254,304);
$z[0][4]['order']="backward";
$z[0][4]['character']="_";
$z[1]=Array("global","",305,330);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",374,403);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",440,466);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",1453,1487);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n                    <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                    ",1757,1907);
$z[5][4]['type']="son";
$z[5][4]['typeid']="2";
$z[6]=Array("type","<a href=\"[field:typeurl/]\"><img src=\"/templets/style/images/contact.jpg\" /></a>",2000,2112);
$z[6][4]['typeid']="11";
$z[7]=Array("type","<a href=\"[field:typeurl/]\"><img src=\"/templets/style/images/feedback.jpg\" /></a>",2159,2272);
$z[7][4]['typeid']="21";
$z[8]=Array("field","",2382,2410);
$z[8][4]['name']="position";
$z[9]=Array("type","[field:typename/]",2457,2505);
$z[9][4]['typeid']="";
$z[10]=Array("include","",7633,7669);
$z[10][4]['filename']="footer.htm";

?>