<?php
$z[0]=Array("include","",0,43);
$z[0][4]['filename']="meta_css_js.htm";
$z[1]=Array("include","",53,89);
$z[1][4]['filename']="head.htm";
$z[2]=Array("banner","\r\n                <li><a href=\"[field:link/]\"><img src=\"[field:pic/]\" width=\"1600\" height=\"410\" alt=\"[field:text/]\" title=\"[field:text/]\"/></a></li>\r\n           ",166,386);
$z[2][4]['name']="product_banner";
$z[2][4]['row']="4";
$z[3]=Array("field","",567,618);
$z[3][4]['name']="position";
$z[3][4]['function']="position_preg(@me)";
$z[4]=Array("include","",4416,4454);
$z[4][4]['filename']="footer.htm";

?>