<?php
$z[0]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>|",89,175);
$z[0][4]['typeid']="4";
$z[1]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>|",197,283);
$z[1][4]['typeid']="5";
$z[2]=Array("type","<a href=\"[field:typelink/]\" target=\"_blank\">中文</a>",305,396);
$z[2][4]['typeid']="20";
$z[3]=Array("global","",543,570);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",579,606);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",830,915);
$z[5][4]['typeid']="1";
$z[6]=Array("channelartlist","\r\n                         <li><a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'>{gemel:field name='typename'/}</a></li>\r\n                       ",984,1253);
$z[6][4]['typeid']="1";
$z[6][4]['row']="10";
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="select";
$z[7]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",1363,1448);
$z[7][4]['typeid']="2";
$z[8]=Array("channelartlist","\r\n                       <li><a href='{gemel:field name='typeurl'/}' class='{gemel:field.currentstyle/}'><img src=\"{gemel:field name='typepic'/}\" alt=\"{gemel:field name='typename'/}\" title=\"{gemel:field name='typename'/}\" width=\"53\" height=\"53\" /><span>{gemel:field name='typename'/}</span></a></li>\r\n                       ",1515,1936);
$z[8][4]['typeid']="2";
$z[8][4]['row']="7";
$z[8][4]['type']="son";
$z[8][4]['currentstyle']="select";
$z[9]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2001,2086);
$z[9][4]['typeid']="3";
$z[10]=Array("type","<a href=\"[field:typelink/]\">[field:typename/]</a>",2110,2195);
$z[10][4]['typeid']="6";
$z[11]=Array("field","",3112,3135);
$z[11][4]['name']="typename";

?>