<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",65,100);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",147,198);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",231,251);
$z[3][4]['name']="title";
$z[4]=Array("field","",450,470);
$z[4][4]['name']="title";
$z[5]=Array("field","\r\n                  <li><img src=\"[field:imgsrctrue/]\" width=\"990\" height=\"454\" alt=\"[field:title/]\" title=\"[field:title/]\"/></li>\r\n                 ",663,854);
$z[5][4]['name']="imgurls";
$z[6]=Array("field","",1046,1101);
$z[6][4]['name']="id";
$z[6][4]['function']="get_image_list(@me)";
$z[7]=Array("field","",1228,1247);
$z[7][4]['name']="body";
$z[8]=Array("arclist","\r\n                   <li>\r\n                      <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"238\" height=\"158\" /></a>\r\n                      <p><a href=\"[field:arcurl/]\">[field:title/]</a></p>\r\n                   </li>   \r\n                   ",1550,1934);
$z[8][4]['row']="4";
$z[8][4]['titlelen']="40";
$z[8][4]['orderby']="pubdate";
$z[8][4]['idlist']="";
$z[9]=Array("include","",2057,2095);
$z[9][4]['filename']="footer.htm";

?>