<?php
$z[0]=Array("include","",0,50);
$z[0][4]['filename']="meta_css_js_detail.htm";
$z[1]=Array("include","",60,96);
$z[1][4]['filename']="head.htm";
$z[2]=Array("field","",201,252);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",266,286);
$z[3][4]['name']="title";
$z[4]=Array("include","",320,360);
$z[4][4]['filename']="side_nav.htm";
$z[5]=Array("field","\r\n                         <li class=\"roundabout-moveable-item\"><img src=\"[field:imgsrctrue/]\" width=\"270\" height=\"290\" alt=\"[field:title/]\" title=\"[field:title/]\"/><span>[field:title/]</span></li>                    \r\n                    ",471,752);
$z[5][4]['name']="imgurls";
$z[6]=Array("field","",1275,1295);
$z[6][4]['name']="title";
$z[7]=Array("field","",3480,3499);
$z[7][4]['name']="body";
$z[8]=Array("include","",3619,3657);
$z[8][4]['filename']="footer.htm";

?>