<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",65,100);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",230,281);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",412,432);
$z[3][4]['name']="title";
$z[4]=Array("field","\r\n                  <li><img src=\"[field:imgsrctrue/]\" width=\"834\" height=\"372\" alt=\"[field:title/]\" title=\"[field:title/]\"/></li>\r\n                 ",585,776);
$z[4][4]['name']="imgurls";
$z[5]=Array("field","",962,1017);
$z[5][4]['name']="id";
$z[5][4]['function']="get_image_list(@me)";
$z[6]=Array("field","",1144,1163);
$z[6][4]['name']="body";
$z[7]=Array("arclist","                   \r\n             <li>\r\n                   <div class=\"interested_img\">\r\n                         <a href=\"[field:arcurl /]\"><img src=\"[field:litpic/]\" title=\"[field:title /]\" alt=\"[field:title /]\" width=\"210\" height=\"210\"/></a>\r\n                   </div>\r\n                   <p><a href=\"[field:arcurl /]\">[field:title /]</a></p>\r\n             </li>\r\n             ",1388,1854);
$z[7][4]['flag']="c";
$z[7][4]['channelid']="";
$z[7][4]['row']="4";
$z[7][4]['titlelen']="60";
$z[7][4]['orderby']="";
$z[8]=Array("include","",1949,1987);
$z[8][4]['filename']="footer.htm";

?>