<?php
$z[0]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",104,219);
$z[0][4]['typeid']="4";
$z[1]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",340,456);
$z[1][4]['typeid']="12";
$z[2]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",496,612);
$z[2][4]['typeid']="13";
$z[3]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",652,768);
$z[3][4]['typeid']="14";
$z[4]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",808,924);
$z[4][4]['typeid']="15";
$z[5]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",964,1080);
$z[5][4]['typeid']="16";
$z[6]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",1120,1236);
$z[6][4]['typeid']="17";
$z[7]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",1350,1465);
$z[7][4]['typeid']="5";
$z[8]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",1497,1612);
$z[8][4]['typeid']="6";
$z[9]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",1644,1759);
$z[9][4]['typeid']="7";
$z[10]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",1791,1906);
$z[10][4]['typeid']="8";
$z[11]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",1938,2053);
$z[11][4]['typeid']="9";
$z[12]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",2085,2201);
$z[12][4]['typeid']="10";
$z[13]=Array("type","<a href='[field:typelink/]'><span class=\"gt_icon\"><</span>[field:typename/]</a>",2233,2349);
$z[13][4]['typeid']="11";

?>