<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",65,100);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",177,228);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",261,286);
$z[3][4]['name']="shorttitle";
$z[4]=Array("field","\r\n                         <li>\r\n                             <img src=\"[field:imgsrctrue/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"520\" height=\"270\" />\r\n                         </li>\r\n                         ",495,760);
$z[4][4]['name']="imgurls";
$z[5]=Array("field","",897,922);
$z[5][4]['name']="shorttitle";
$z[6]=Array("field","",952,974);
$z[6][4]['name']="outline";
$z[7]=Array("field","",2610,2665);
$z[7][4]['name']="id";
$z[7][4]['function']="get_image_list(@me)";
$z[8]=Array("field","",2969,2988);
$z[8][4]['name']="body";
$z[9]=Array("include","",3095,3133);
$z[9][4]['filename']="footer.htm";

?>