<?php
$z[0]=Array("include","",0,36);
$z[0][4]['filename']="head.htm";
$z[1]=Array("include","",65,100);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",236,287);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",320,345);
$z[3][4]['name']="shorttitle";
$z[4]=Array("field","\r\n                         <li><img src=\"[field:imgsrctrue/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"712\" height=\"352\" /></li>\r\n                      ",547,751);
$z[4][4]['name']="imgurls";
$z[5]=Array("field","",940,995);
$z[5][4]['name']="id";
$z[5][4]['function']="get_image_list(@me)";
$z[6]=Array("field","",1074,1099);
$z[6][4]['name']="shorttitle";
$z[7]=Array("field","",1390,1409);
$z[7][4]['name']="body";
$z[8]=Array("channelartlist","\r\n              <li>\r\n                   <div class=\"h3\">\r\n                       <h3>{gemel:field.typename/}<span class=\"zans\"></span></h3>\r\n                   </div>\r\n                   <ul>\r\n                       {gemel:arclist orderby='weight' titlelen='40'}\r\n                       <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\" >[field:shorttitle/]</a></li>\r\n                       {/gemel:arclist}\r\n                   </ul>\r\n              </li>\r\n              ",1605,2141);
$z[8][4]['typeid']="3,4,5,6";
$z[9]=Array("include","",2269,2307);
$z[9][4]['filename']="footer.htm";

?>