<?php
$z[0]=Array("include","",0,41);
$z[0][4]['filename']="head_list.htm";
$z[1]=Array("include","",70,105);
$z[1][4]['filename']="nav.htm";
$z[2]=Array("field","",199,221);
$z[2][4]['name']="typepic";
$z[3]=Array("field","",230,253);
$z[3][4]['name']="typename";
$z[4]=Array("field","",260,283);
$z[4][4]['name']="typename";
$z[5]=Array("field","",328,351);
$z[5][4]['name']="typename";
$z[6]=Array("field","",450,501);
$z[6][4]['name']="position";
$z[6][4]['function']="position_preg(@me)";
$z[7]=Array("channelartlist","\r\n                 <li><a href=\"{gemel:field name='typeurl'/}\">{gemel:field name='typename'/}</a></li>\r\n                ",652,847);
$z[7][4]['typeid']="2";
$z[7][4]['row']="9";
$z[7][4]['type']="top";
$z[8]=Array("list","\r\n                    <li>\r\n                         <div class=\"product_img\">\r\n                              <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" alt=\"[field:title/]\" width=\"210\" height=\"210\"/></a>\r\n                         </div>\r\n                         <p><a href=\"[field:arcurl/]\">[field:title/]</a></p>\r\n                    </li>\r\n                    ",1017,1483);
$z[8][4]['orderby']="weight";
$z[8][4]['pagesize']="8";
$z[8][4]['titlelen']="50";
$z[9]=Array("pagelist","",1616,1688);
$z[9][4]['listitem']="index,end,pageno";
$z[9][4]['listsize']="4";
$z[9][4]['sitelang']="en";
$z[10]=Array("include","",1785,1823);
$z[10][4]['filename']="footer.htm";

?>