<?php
$z[0]=Array("include","",0,50);
$z[0][4]['filename']="meta_css_js_detail.htm";
$z[1]=Array("include","",60,96);
$z[1][4]['filename']="head.htm";
$z[2]=Array("field","",165,216);
$z[2][4]['name']="position";
$z[2][4]['function']="position_preg(@me)";
$z[3]=Array("field","",271,291);
$z[3][4]['name']="title";
$z[4]=Array("include","",438,484);
$z[4][4]['filename']="side_nav_left2.htm";
$z[5]=Array("include","",494,542);
$z[5][4]['filename']="hot_product_left.htm";
$z[6]=Array("field","",601,621);
$z[6][4]['name']="title";
$z[7]=Array("field","\r\n                    <div class=\"slideshow\"><img src=\"[field:imgsrctrue/]\"/></div>\r\n                 ",702,846);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","",897,916);
$z[8][4]['name']="body";
$z[9]=Array("include","",986,1024);
$z[9][4]['filename']="footer.htm";

?>