<?php
$z[0]=Array("item","",3,86);
$z[0][4]['ico']="images/addnews.gif";
$z[0][4]['link']="content_list.php";
$z[0][4]['title']="文档列表";
$z[1]=Array("item","",88,172);
$z[1][4]['ico']="images/file_dir.gif";
$z[1][4]['link']="catalog_main.php";
$z[1][4]['title']="栏目管理";
$z[2]=Array("item","",174,253);
$z[2][4]['ico']="images/manage1.gif";
$z[2][4]['link']="sys_info.php";
$z[2][4]['title']="修改参数";

?>