<?php
$z[0]=Array("channeltitle","",254,304);
$z[0][4]['order']="backward";
$z[0][4]['character']="_";
$z[1]=Array("global","",305,330);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",374,403);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",440,466);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",1679,1713);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1874,1902);
$z[5][4]['name']="position";
$z[6]=Array("type","[field:typename/]",1939,1987);
$z[6][4]['typeid']="";
$z[7]=Array("type","<a href=\"[field:typeurl/]\" class=\"c_blue\">《用户协议》</a>",5375,5472);
$z[7][4]['typeid']="32";
$z[8]=Array("include","",5855,5891);
$z[8][4]['filename']="footer.htm";

?>