<?php
$z[0]=Array("global","",254,279);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",323,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,415);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",686,720);
$z[3][4]['filename']="head.htm";
$z[4]=Array("banner","\r\n        <li id=\"[field:id/]\" style=\"background:url([field:pic/]) center top no-repeat;\" class=\"now\"></li>\r\n        ",762,932);
$z[4][4]['name']="about_banner";
$z[4][4]['row']="1";
$z[5]=Array("global","",1110,1164);
$z[5][4]['name']="keyword";
$z[5][4]['function']="RemoveXSS(@me)";
$z[6]=Array("list","   \r\n					<li><div class=\"pro_list_img\"><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" /></a></div><a href=\"[field:arcurl/]\" class=\"pro_list_tit\">[field:title/]</a><a href=\"[field:arcurl/]\" class=\"pro_list_details\">DETAILS+</a></li>\r\n                    ",1298,1611);
$z[6][4]['pagesize']="10";
$z[6][4]['orderby']="weight";
$z[7]=Array("pagelist","",1737,1816);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[7][4]['sitelang']="cn";
$z[8]=Array("type","[field:typename/]",1940,1989);
$z[8][4]['typeid']="7";
$z[9]=Array("channel","\r\n				<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n                ",2056,2186);
$z[9][4]['type']="son";
$z[9][4]['typeid']="7";
$z[10]=Array("include","",2255,2291);
$z[10][4]['filename']="footer.htm";

?>